/*

$Revision$
$Author$
$Date$
$Workfile$
$Archive$

Список таблиц, передаваемых через новости

Автор: Уханов Дмитрий Юрьевич
Дата создания: 03/23/96
Author: Dmitry Ukhanov
Creation date: 03/23/96

*/


/* таблицы которые ходят по новостям только в составе 'кустов' */


define variable attach-list as character no-undo initial '~
abc-analysis-attr~
,abc-analysis-doc~
,abc-analysis-gds-obj~
,abc-analysis-gds-obj-attr~
,abc-analysis-goods~
,abc-analysis-goods-attr~
,abc-analysis-grp~
,abc-analysis-obj~
,abc-analysis-period~
,abc-analysis-prod~
,abcxyz-analysis-attr~
,abcxyz-analysis-goods~
,abcxyz-analysis-goods-attr~
,add-line~
,add-trn~
,add-trn-attr~
,arh-trn-doc-contract~
,c-buyer-in-buyer-group~
,c-buyer-group~
,c-pl-gds-obj~
,c-sht-hist~
,cd-doc-line~
,c-cd-doc-line~
,chk-discnt~
,c-chk-discnt~
,chk-doc~
,chk-doc-attr~
,c-chk-doc-attr~
,chk-gds~
,c-chk-gds~
,chk-pay~
,chk-gds-attr~
,chk-pay-attr~
,c-chk-pay~
,contract-line~
,contract-specif-attr~
,c-contract-line~
,db-grp-obj-price~
,c-db-grp-obj-price~
,doc-abc-def-doc~
,doc-abc-def-obj~
,c-doc-attr~
,doc-fbr-gds~
,c-doc-fbr-gds~
,doc-line~
,c-doc-line~
,doc-line-attr~
,c-doc-line-attr~
,doc-line-sum~
,c-doc-line-sum~
,doc-pl~
,c-doc-pl~
,doc-pl-pump~
,c-doc-pl-pump~
,doc-prts~
,c-doc-prts~
,doc-xyz-def-doc~
,doc-xyz-def-obj~
,esys-route-dump~
,factur-connect-line~
,fbr-line~
,c-fbr-line~
,fbr-pln-line~
,c-fbr-pln-line~
,c-fin-code-an-uchet~
,c-fin-code-cel-nazn~
,c-fin-code-cor-acc~
,fin-doc-attr~
,c-fin-doc-attr~
,fin-doc-tax~
,c-fin-doc-tax~
,fin-gds-part~
,c-fin-gds-part~
,fin-ob-attr~
,c-fin-ob-attr~
,fin-ob-tax~
,c-fin-ob-tax~
,fin-ob-tax-before~
,fin-ob-trn~
,fin-statement-attr~
,c-fin-statement-attr~
,fin-statement-line~
,c-fin-statement-line~
,gds-dtl~
,c-gds-dtl~
,c-global-state~
,global-state-attr~
,c-global-state-attr~
,host-grp-obj-price~
,c-host-grp-obj-price~
,icnt-line~
,inkas-pay~
,c-inkas-pay~
,inkas-pay-desk~
,c-inkas-pay-desk~
,inkas-pay-wth~
,c-inkas-pay-wth~
,inv-doc~
,inv-line~
,c-inv-line~
,layout-elem-rule~
,obj-grp-obj-price~
,c-obj-grp-obj-price~
,ord-cons-attr~
,ord-cons-line-attr~
,ord-doc-attr~
,c-ord-doc-attr~
,ord-dtl~
,c-ord-dtl~
,ord-dtl-cons~
,ord-dtl-rcv~
,ord-gds-cons~
,ord-line~
,c-ord-line~
,ord-line-attr~
,c-ord-line-attr~
,ord-line-rcv~
,ord-rcv-attr~
,ord-rcv-line-attr~
,c-parts~
,c-parts-attr~
,parts-root~
,c-parts-root~
,esys-pck-keys~
,c-price-doc-forming~
,price-doc-forming-attr~
,c-price-doc-forming-attr~
,price-doc-forming-gds~
,c-price-doc-forming-gds~
,price-doc-forming-gdsattr~
,c-price-doc-forming-gdsattr~
,price-doc-forming-gds-qnty~
,c-price-doc-forming-gds-qnty~
,price-doc-forming-gds-sum~
,c-price-doc-forming-gds-sum~
,price-doc-forming-gds-tnv~
,c-price-doc-forming-gds-tnv~
,price-list~
,c-price-list~
,price-list-attr~
,c-price-list-attr~
,price-list-type-attr~
,c-price-list-type-attr~
,price-list-type-cash-pay~
,c-price-list-type-cash-pay~
,price-list-type-cassa~
,c-price-list-type-cassa~
,price-list-type-gds-grp~
,c-price-list-type-gds-grp~
,price-list-type-pay-type~
,c-price-list-type-pay-type~
,c-qnty-group~
,qnty-in-qnty-group~
,c-qnty-in-qnty-group~
,rang-abc-def-obj~
,rang-xyz-def-obj~
,rule-i-script~
,rule-script~
,rule-trans-memo~
,rvs-line~
,rvs-line-attr~
,c-rvs-line~
,rvs-line-pump~
,c-rvs-line-pump~
,rvs-pump~
,sale-doc~
,c-sale-doc~
,schet-fact-line~
,c-schet-fact-line~
,shift-cash~
,c-shift-obj~
,shift-staff~
,c-shift-staff~
,shift-attr~
,c-shift-attr~
,stop-list-line~
,c-sum-group~
,sum-in-sum-group~
,c-sum-in-sum-group~
,c-turnover-group~
,tnv-in-turnover-group~
,c-tnv-in-turnover-group~
,trn-doc-sum~
,c-trn-doc-sum~
,c-trn-reason~
,trn-reason-host~
,c-trn-reason-host~
,trn-reason-obj~
,c-trn-reason-obj~
,trn-rsn-attr~
,c-trn-rsn-attr~
,turnover-buyer~
,turnover-buyer-attr~
,turnover-buyer-gds~
,turnover-buyer-gds-attr~
,wi-mode~
,wth-dtl~
,c-wth-dtl~
,wth-line~
,c-wth-line~
,wth-parts~
,c-wth-parts~
,xyz-analysis-attr~
,xyz-analysis-doc~
,xyz-analysis-gds-obj~
,xyz-analysis-gds-obj-attr~
,xyz-analysis-goods~
,xyz-analysis-goods-attr~
,xyz-analysis-obj~
,xyz-analysis-period~
':U .



/* таблицы которые ходят по новостям  */


define variable news-list as character no-undo initial '~
abc-analysis~
,abcxyz-analysis~
,add-doc~
,action-post~
,action-post-host~
,action-post-menu-group~
,action-post-obj~
,action-post-role~
,action-post-user-login~
,action-role~
,c-action-role~
,action-role-item~
,c-action-role-item~
,action-role-item-gds~
,action-role-item-gds-grp~
,alc-sale-lic~
,c-alc-sale-lic~
,alc-sale-lic-attr~
,c-alc-sale-lic-attr~
,alc-sale-lic-type~
,c-alc-sale-lic-type~
,alc-supp-lic~
,c-alc-supp-lic~
,alc-supp-lic-attr~
,c-alc-supp-lic-attr~
,alc-supp-lic-type~
,c-alc-supp-lic-type~
,alc-type~
,c-alc-type~
,alc-type-attr~
,c-alc-type-attr~
,alc-type-gds~
,c-alc-type-gds~
,arh-fin-doc-an~
,arh-fin-doc-an-nal~
,arh-fin-doc-c-schet-tax-nal~
,arh-fin-doc-contr-schet~
,arh-fin-doc-contr-schet-nal~
,arh-fin-doc-contr-schet-tax~
,arh-fin-doc-schet~
,arh-fin-doc-schet-nal~
,arh-fin-doc-schet-tax~
,arh-fin-doc-schet-tax-nal~
,arh-fin-doc-contr-schet-obj~
,arh-fin-doc-contr-s-nal-obj~
,arh-fin-doc-contr-s-tax-obj~
,arh-fin-doc-c-s-tax-nal-obj~
,arh-fin-doc-schet-obj~
,arh-fin-doc-schet-nal-obj~
,arh-fin-ob-contr~
,attr-prop~
,auto-tank~
,c-auto-tank~
,auto-tank-meas~
,auto-tank-attr~
,bar-code~
,c-bar-code~
,bar-code-attr~
,c-bar-code-attr~
,bar-code-obj-attr~
,c-bar-code-obj-attr~
,blob-bind~
,buyer-group~
,buyer-in-buyer-group~
,c-cli-hist~
,c-dc-hist~
,c-fbr-gds-grp-hist~
,c-gds-grp-hist~
,c-gds-hist~
,c-nzl-hist~
,c-plc-hist~
,c-pmp-hist~
,c-recipe-hist~
,c-table-bind~
,c-tax-hist~
,c-usr-hist~
,c-wth-hist~
,cash-desk~
,c-cash-desk~
,cash-desk-attr~
,c-cash-desk-attr~
,cash-pay~
,c-cash-pay~
,cash-pay-attr~
,c-cash-pay-attr~
,cd-clu~
,c-cd-clu~
,cd-dlu~
,c-cd-dlu~
,cd-doc~
,c-cd-doc~
,cd-events~
,cd-events-attr~
,cd-event-log~
,cd-event-log-attr~
,cd-grp~
,c-cd-grp~
,cd-plu~
,c-cd-plu~
,c-chk-doc~
,cd-trans~
,cd-video-link~
,cd-video-link-attr~
,cli-art~
,cli-gds~
,cli-grp~
,c-cli-grp~
,clients~
,c-clients~
,clients-attr~
,c-clients-attr~
,clob-bind~
,code-range~
,condition-keeping~
,c-condition-keeping~
,config~
,c-config~
,contract~
,c-contract~
,contract-specif~
,c-contract-specif~
,country~
,c-country~
,criterion-analysis~
,cshr-month~
,curr-accnt~
,c-curr-accnt~
,curr-bank~
,c-curr-bank~
,curr-shop~
,currency~
,custom-labels~
,datatype-exp~
,datatype-exp-attr~
,datatype-imp~
,datatype-imp-attr~
,datatype-table~
,datatype-table-exp~
,datatype-table-field~
,datatype-table-field-exp~
,datatype-table-field-imp~
,datatype-table-imp~
,db~
,c-db~
,db-attr~
,db-info~
,db-status~
,deliv-type-cond-keep~
,c-deliv-type-cond-keep~
,delivery-subject~
,c-delivery-subject~
,delivery-type~
,c-delivery-type~
,delivery-type-subject~
,c-delivery-type-subject~
,dis-card~
,c-dis-card~
,dis-card-long~
,c-dis-card-long~
,dis-card-mask~
,c-dis-card-mask~
,dis-card-property~
,c-dis-card-property~
,dis-card-type~
,c-dis-card-type~
,dis-card-type-attr~
,c-dis-card-type-attr~
,dis-cfg-rule~
,c-dis-cfg-rule~
,dis-cp-rule~
,c-dis-cp-rule~
,dis-dc-rule~
,c-dis-dc-rule~
,dis-dct-rule~
,c-dis-dct-rule~
,dis-gds-rule~
,c-dis-gds-rule~
,dis-gds-rule-attr~
,dis-grp-rule~
,c-dis-grp-rule~
,dis-host~
,c-dis-host~
,dis-obj~
,c-dis-obj~
,dis-rule~
,c-dis-rule~
,dis-some-rule~
,c-dis-some-rule~
,dis-thbj-rule~
,c-dis-thbj-rule~
,dis-time-rule~
,c-dis-time-rule~
,doc-abc-def~
,doc-attr~
,doc-xyz-def~
,drt-prop~
,c-drt-prop~
,edi-status~
,esys-all-attr~
,esys-datatype-exp~
,c-esys-datatype-exp~
,esys-datatype-imp~
,c-esys-datatype-imp~
,esys-pck-rcvd~
,esys-pck-sent~
,esys-route~
,ex-mark~
,c-ex-mark~
,ext-artic~
,c-ext-artic~
,ext-artic-attr~
,c-ext-artic-attr~
,ext-classif~
,c-ext-classif~
,ext-file~
,ext-file-line~
,ext-file-par~
,ext-system~
,c-ext-system~
,ext-system-attr~
,factur-connect~
,fbr-doc~
,c-fbr-doc~
,fbr-gds-grp~
,c-fbr-gds-grp~
,fbr-gds-grp-attr~
,c-fbr-gds-grp-attr~
,fbr-gds-obj~
,c-fbr-gds-obj~
,fbr-history~
,fbr-pln~
,c-fbr-pln~
,fbr-prn~
,c-fbr-prn~
,fbr-prn-gds~
,c-fbr-prn-gds~
,fbr-prn-grp~
,c-fbr-prn-grp~
,fbr-recipe~
,fbr-recipe-gds~
,fin-bank~
,c-fin-bank~
,fin-code-an-uchet~
,fin-code-cel-nazn~
,fin-code-cor-acc~
,fin-connect~
,fin-doc~
,c-fin-doc~
,fin-ob~
,c-fin-ob~
,fin-ob-before~
,fin-schet~
,c-fin-schet~
,fin-statement~
,c-fin-statement~
,firm~
,c-firm~
,gds-grp~
,c-gds-grp~
,gds-grp-attr~
,c-gds-grp-attr~
,gds-grp-obj~
,c-gds-grp-obj~
,gds-host-attr~
,c-gds-host-attr~
,gds-obj~
,gds-obj-attr~
,c-gds-obj-attr~
,gds-obj-prop~
,c-gds-obj-prop~
,gds-obj-prop-attr~
,assortment-matrix~
,assortment-matrix-attr~
,c-assortment-matrix~
,assortment-matrix-goods~
,c-assortment-matrix-goods~
,gds-prt~
,c-gds-prt~
,gds-season~
,c-gds-season~
,gds-add-charges~
,c-gds-add-charges~
,gds-grp-obj-attr~
,c-gds-obj-ref~
,global-state~
,goods~
,c-goods~
,goods-attr~
,c-goods-attr~
,group-period-validity~
,c-group-period-validity~
,grp-obj-price~
,c-grp-obj-price~
,hist-nws-option~
,c-hist-nws-option~
,icnt-doc~
,inkas~
,c-inkas~
,layout~
,c-layout~
,layout-elem~
,layout-elem-rule~
,c-layout-elem-rule~
,lvl-name~
,menu-user~
,menu-user-call~
,nozzle~
,c-nozzle~
,nozzle-attr~
,c-nozzle-attr~
,nws-doc-hist~
,nws-outline~
,obj-date~
,ord-cons~
,ord-doc~
,c-ord-doc~
,ord-doc-rcv~
,ord-chain~
,parts~
,parts-attr~
,pay-type~
,c-pay-type~
,pck-rcvd~
,pck-sent~
,person~
,c-person~
,pl-gds~
,c-pl-gds~
,pl-gds-attr~
,c-pl-gds-attr~
,pl-gds-pump~
,c-pl-gds-pump~
,pl-level~
,c-pl-level~
,pl-pump~
,c-pl-pump~
,pl-pump-nozzle~
,c-pl-pump-nozzle~
,place~
,c-place~
,place-attr~
,c-place-attr~
,place-io~
,c-place-io~
,point-io~
,c-point-io~
,point-place-rel~
,c-point-place-rel~
,point-point-rel~
,c-point-point-rel~
,price-all~
,price-doc~
,c-price-doc~
,price-doc-forming~
,c-price-doc-forming~
,price-list-type~
,c-price-list-type~
,prod-bc~
,c-prod-bc~
,prod-bc-db~
,profile-by-profile~
,c-profile-by-profile~
,prop-head~
,c-prop-head~
,prop-map~
,prop-ref~
,c-prop-ref~
,prop-ref-call~
,prop-ruleset~
,prop-script~
,prt-obj~
,pscript-ruleset~
,pump~
,c-pump~
,pump-attr~
,c-pump-attr~
,pump-nozzle~
,c-pump-nozzle~
,qnty-group~
,rang-abc-def~
,rang-xyz-def~
,recipe~
,c-recipe~
,recipe-develop~
,c-recipe-develop~
,recipe-gds~
,c-recipe-gds~
,regions~
,c-regions~
,rp-by-call~
,c-rp-by-call~
,rp-rule-param~
,rpt-option~
,rule~
,rule-by-call~
,c-rule-by-call~
,rule-by-profile~
,rule-by-set~
,rule-call-param~
,c-rule-call-param~
,rule-profile~
,rule-process~
,ruledict~
,c-ruledict~
,ruledict-param~
,ruleset~
,rvs-doc~
,c-rvs-doc~
,s-coeff~
,c-s-coeff~
,scales~
,c-scales~
,scales-attr~
,c-scales-attr~
,scales-gds~
,c-scales-gds~
,scales-grp~
,c-scales-grp~
,schedule~
,schedule-attr~
,schet-fact-doc~
,c-schet-fact-doc~
,season~
,c-season~
,sert~
,c-sert~
,sert-join~
,shift-obj~
,c-shift-obj~
,shop~
,c-shop~
,some-lk~
,sr-izmerenia~
,c-sr-izmerenia~
,staff~
,c-staff~
,stop-list~
,store~
,c-store~
,sum-group~
,sum-grp~
,c-sum-grp~
,sum-grp-obj~
,c-sum-grp-obj~
,sysconf~
,c-sysconf~
,tare~
,c-tare~
,tax~
,c-tax~
,tax-rate~
,c-tax-rate~
,tax-rate-gds~
,tax-rate-gds-grp~
,c-tax-rate-gds-grp~
,tax-rate-value~
,tax-units~
,c-tax-units~
,thbj-attr~
,c-thbj-attr~
,trn-doc~
,c-trn-doc~
,trn-reason~
,turnover-buyer-main~
,turnover-group~
,units~
,c-units~
,upgrade~
,user-account~
,c-user-account~
,user-context-history~
,user-host~
,user-login~
,c-user-login~
,user-login-action-item~
,user-login-action-role~
,user-login-attr~
,user-menu-group~
,user-obj~
,user-window-attr~
,var-deliv-gr-per-val~
,c-var-deliv-gr-per-val~
,variant-delivery~
,c-variant-delivery~
,varianty-delivery-gds-obj~
,c-varianty-delivery-gds-obj~
,wealth~
,c-wealth~
,who-lk~
,wth-doc~
,c-wth-doc~
,wth-doc-attr
,wth-gds~
,c-wth-gds~
,wth-ser~
,c-wth-ser~
,wth-par~
,c-wth-par~
,wth-place~
,c-wth-place~
,xyz-analysis~
,c-user-log~
,egais-clients~
,c-egais-clients~
,egais-gds~
,c-egais-gds~
,c-vsd~
,c-gds-mercury
,vsd~
,vsd-attr~
,c-gds-mercury~
,gds-mercury~
,gds-mercury-attr~
,c-promo-schedule~
,c-promo-schedule-week~
,c-PromoAction~
,c-PromoCriterion~
,c-PromoGift~
,c-PromoGoods~
,c-PromoObject~
,promo-schedule~
,promo-schedule-week~
,PromoAction~
,PromoAttr~
,PromoCriterion~
,PromoGift~
,PromoGoods~
,PromoObject~
':U .


define variable oth-list1 as character no-undo &if "{1}" = "check" &then initial '~
action-group~
,action-head~
,action-item~
,aht-doc~
,aht-gds~
,aht-ot-line~
,aht-ot-tot~
,aht-stk~
,aht-stk-line~
,aht-stk-tot~
,aht-time~
,archive-history~
,arh-fin-doc-an-nal-obj~
,arh-fin-doc-an-obj~
,arh-fin-doc-s-tax-nal-obj~
,arh-fin-doc-schet-tax-obj~
,arh-fin-ob-contr-obj~
,arh-wth-cli~
,arh-wth-cli-tot~
,arh-wth-cli-doc~
,arh-wth-tot~
,arh-wth-w-p~
,BatchProcess~
,cbr-bank~
,c-cbr-bank~
,chk-gds-pay~
,c-currency~
,db-filter~
,db-rec-attr~
,db-usr-flt~
,dish-grp~
,doc-fact-num~
,doc-filter~
,doc-filter-head~
,ext-artic-db~
,ext-artic-host~
,ext-artic-obj~
,feature~
,feature-scale~
,filter~
,c-fin-connect~
,fin-doc-cor-acc-lk~
,fin-doc-obj~
,fin-doc-schet-lk~
,fin-ob-cor-acc-lk~
,fin-ob-schet-lk~
,c-gds-obj~
,gds-obj-flag~
,gen-attr~
,h-route~
,h-route-dump~
,hold-attr~
,hold-gds-grp~
,hold-goods~
,hold-purch~
,hold-purch-grp~
,hold-purch-supp~
,hold-purch-supp-gds~
,hold-sale~
,hold-sale-grp~
,hold-time~
,hold-time-attr~
,hold-trn~
,host-lk~
,lang~
,c-layout-elem~
,menu-group~
,menu-head~
,menu-item~
,menu-item-group~
,nws-last-rec~
,ord-blank~
,ot-line~
,ot-supp-line~
,ot-supp-tot~
,ot-tot~
,parts-supp~
,payment~
,pck-keys~
,prod-bc-attr~
,c-prod-bc-attr~
,prog-message~
,prog-message-lang~
,rcs-attr~
,rcs-chkbody~
,rcs-chkhead~
,rcs-city~
,rcs-clients~
,rcs-country~
,rcs-destn~
,rcs-docbody~
,rcs-dochead~
,rcs-mark~
,rcs-pack~
,rcs-place~
,rcs-retail1action~
,rcs-retail1attr~
,rcs-retail1bank~
,rcs-retail1barcode~
,rcs-retail1bill~
,rcs-retail1billitem~
,rcs-retail1convolution~
,rcs-retail1delete~
,rcs-retail1fortuneproduct~
,rcs-retail1price~
,rcs-retail1priceitem~
,rcs-retail1product~
,rcs-retail1subject~
,rcs-shops~
,rename-fld~
,rep~
,rep-line~
,res-lang~
,resource~
,route~
,route-dump~
,route-dump-link~
,stk-line~
,stk-supp-line~
,stk-supp-tot~
,stk-tot~
,c-stop-list~
,c-stop-list-line~
,sys-ctrl~
,tmp-sale~
,tmp-sale-dtl~
,tmp-sale-gds~
,tnved-head~
,tnved-item~
,user-conn~
,usr-flt~
,usr-stko~
,whole-send-news~
,c-wi-mode~
,wth-obj~
,c-wth-obj~
,wth-pobj~
,c-wth-pobj~
,wth-gds-attr~
,c-wth-gds-attr~
,wth-ser-attr~
,c-wth-ser-attr~
,c-add-doc~
,c-add-line~
,c-parts-add~
,parts-add~
,gds-add-charges-attr~
,c-gds-add-charges-attr~
':U &endif .

define variable oth-list2 as character no-undo &if "{1}" = "check" &then initial '~
abc-analysis-doc-attr~
,abc-analysis-grp-attr~
,abc-analysis-obj-attr~
,abc-analysis-period-attr~
,abc-analysis-prod-attr~
,abc-analysis-cli~
,abc-analysis-cli-attr~
,action-group-attr~
,action-head-attr~
,action-item-attr~
,action-post-attr~
,action-post-host-attr~
,action-post-menu-group-attr~
,action-post-obj-attr~
,action-post-role-attr~
,action-post-user-login-attr~
,action-role-attr~
,action-role-item-attr~
,aht-doc-attr~
,aht-gds-attr~
,aht-ot-line-attr~
,aht-ot-tot-attr~
,aht-stk-attr~
,aht-stk-line-attr~
,aht-stk-tot-attr~
,aht-time-attr~
,alc-sale-lic-type-attr~
,alc-supp-lic-type-attr~
,alc-type-gds-attr~
,archive-history-attr~
,arh-fin-doc-an-attr~
,arh-fin-doc-an-nal-attr~
,arh-fin-doc-an-nal-obj-attr~
,arh-fin-doc-an-obj-attr~
,arh-fin-doc-contr-schet-attr~
,arh-fin-doc-schet-attr~
,arh-fin-doc-schet-nal-attr~
,arh-fin-doc-schet-obj-attr~
,arh-fin-doc-schet-tax-attr~
,arh-fin-ob-contr-attr~
,arh-fin-ob-contr-obj-attr~
,arh-trn-doc-contract-attr~
,arh-wth-cli-attr~
,arh-wth-cli-doc-attr~
,arh-wth-cli-tot-attr~
,arh-wth-tot-attr~
,arh-wth-w-p-attr~
,assortment-matrix-goods-attr~
,auto-tank-meas-attr~
,blob-data~
,buyer-group-attr~
,buyer-in-buyer-group-attr~
,c-auto-tank-attr~
,c-auto-tank-meas-attr~
,c-cbr-bank-attr~
,c-cli-grp-attr~
,c-condition-keeping-attr~
,c-country-attr~
,c-currency-attr~
,c-deliv-type-cond-keep-attr~
,c-delivery-subject-attr~
,c-delivery-type-attr~
,c-delivery-type-subject-attr~
,c-dis-card-long-attr~
,c-dis-card-mask-attr~
,c-dis-rule-attr~
,c-fbr-gds-obj-attr~
,c-fin-bank-attr~
,c-fin-schet-attr~
,c-gds-dtl-attr~
,c-gds-prt-attr~
,c-group-period-validity-attr~
,c-hist-nws-option-attr~
,c-layout-attr~
,c-wi-mode-attr~
,c-layout-elem-attr~
,c-parts-obj-attr~
,c-pay-type-attr~
,c-payment-attr~
,c-pl-gds-pump-attr~
,c-pl-level-attr~
,c-pl-pump-attr~
,c-pl-pump-nozzle-attr~
,c-prod-bc-db-attr~
,c-prop-ruleset~
,c-prop-script~
,c-pscript-ruleset~
,c-pump-nozzle-attr~
,c-rp-rule-param~
,c-rule~
,c-ruledict-param~
,c-rule-by-profile~
,c-rule-by-set~
,c-rule-profile~
,c-rule-process~
,c-ruleset~
,cbr-bank-attr~
,cd-clu-attr~
,cd-dlu-attr~
,cd-doc-attr~
,cd-doc-line-attr~
,cd-grp-attr~
,cd-plu-attr~
,cd-trans-attr~
,chk-discnt-attr~
,cli-art-attr~
,cli-gds-attr~
,cli-grp-attr~
,clob-data~
,condition-keeping-attr~
,contract-attr~
,contract-line-attr~
,country-attr~
,criterion-analysis-attr~
,cshr-month-attr~
,curr-accnt-attr~
,curr-bank-attr~
,curr-shop-attr~
,currency-attr~
,db-filter-attr~
,db-grp-obj-price-attr~
,db-status-attr~
,db-usr-flt-attr~
,deliv-type-cond-keep-attr~
,delivery-subject-attr~
,delivery-type-attr~
,delivery-type-subject-attr~
,dis-card-long-attr~
,dis-card-mask-attr~
,dis-cfg-rule-attr~
,dis-cp-rule-attr~
,dis-dc-rule-attr~
,dis-dct-rule-attr~
,dis-grp-rule-attr~
,dis-rule-attr~
,dis-some-rule-attr~
,dis-thbj-rule-attr~
,dis-time-rule-attr~
,dish-grp-attr~
,doc-abc-def-attr~
,doc-abc-def-doc-attr~
,doc-abc-def-obj-attr~
,doc-fact-num-attr~
,doc-fbr-gds-attr~
,doc-filter-attr~
,doc-filter-head-attr~
,doc-pl-attr~
,doc-pl-pump-attr~
,doc-prts-attr~
,doc-xyz-def-attr~
,doc-xyz-def-doc-attr~
,doc-xyz-def-obj-attr~
,ex-mark-attr~
,ext-artic-db-attr~
,ext-artic-host-attr~
,ext-artic-obj-attr~
,ext-classif-attr~
,ext-file-attr~
,ext-file-line-attr~
,ext-file-par-attr~
,factur-connect-attr~
,factur-connect-line-attr~
,fbr-gds-obj-attr~
,fbr-prn-attr~
,fbr-prn-gds-attr~
,fbr-prn-grp-attr~
,feature-attr~
,feature-scale-attr~
,Filter-attr~
,fin-bank-attr~
,fin-code-an-uchet-attr~
,fin-code-cel-nazn-attr~
,fin-code-cor-acc-attr~
,fin-connect-attr~
,fin-doc-cor-acc-lk-attr~
,fin-doc-obj-attr~
,fin-doc-schet-lk-attr~
,fin-doc-tax-attr~
,fin-gds-part-attr~
,fin-ob-cor-acc-lk-attr~
,fin-ob-schet-lk-attr~
,fin-ob-tax-attr~
,fin-ob-trn-attr~
,fin-schet-attr~
,fin-statement-line-attr~
,gds-dtl-attr~
,gds-obj-flag-attr~
,gds-prt-attr~
,gds-season-attr~
,group-period-validity-attr~
,grp-obj-price-attr~
,hist-nws-option-attr~
,hold-gds-grp-attr~
,hold-goods-attr~
,hold-purch-attr~
,hold-purch-grp-attr~
,hold-purch-supp-attr~
,hold-purch-supp-gds-attr~
,hold-sale-attr~
,hold-sale-grp-attr~
,hold-trn-attr~
,host-grp-obj-price-attr~
,host-lk-attr~
,inkas-pay-attr~
,inkas-pay-desk-attr~
,inv-doc-attr~
,inv-line-attr~
,lang-attr~
,layout-attr~
,layout-elem-attr~
,lvl-name-attr~
,layout-elem-rule-attr~
,c-layout-elem-rule-attr~
,menu-group-attr~
,menu-head-attr~
,menu-item-attr~
,menu-item-group-attr~
,menu-user-attr~
,menu-user-call-attr~
,nws-doc-hist-attr~
,nws-last-rec-attr~
,obj-grp-obj-price-attr~
,ord-blank-attr~
,ord-chain-attr~
,ord-dtl-attr~
,ot-line-attr~
,ot-supp-line-attr~
,ot-supp-tot-attr~
,ot-tot-attr~
,parts-add-attr~
,parts-obj-attr~
,parts-root-attr~
,parts-supp-attr~
,pay-type-attr~
,payment-attr~
,pck-rcvd-attr~
,pck-sent-attr~
,pl-gds-pump-attr~
,pl-level-attr~
,pl-pump-attr~
,pl-pump-nozzle-attr~
,place-io-attr~
,point-io-attr~
,price-all-attr~
,price-list-type-cassa-attr~
,price-list-type-gds-grp-attr~
,prod-bc-db-attr~
,prog-message-attr~
,prog-message-lang-attr~
,prop-head-attr~
,prop-map-attr~
,prop-ref-attr~
,prop-ref-call-attr~
,prop-ruleset-attr~
,prop-script-attr~
,prt-obj-attr~
,pscript-ruleset-attr~
,pump-nozzle-attr~
,qnty-group-attr~
,qnty-in-qnty-group-attr~
,rang-abc-def-attr~
,rang-abc-def-obj-attr~
,rang-xyz-def-attr~
,rang-xyz-def-obj-attr~
,regions-attr~
,rename-fld-attr~
,res-lang-attr~
,resource-attr~
,route-attr~
,route-dump-attr~
,rp-by-call-attr~
,rp-rule-param-attr~
,rpt-option-attr~
,rule-attr~
,rule-by-call-attr~
,rule-by-profile-attr~
,rule-by-set-attr~
,rule-call-param-attr~
,rule-i-script-attr~
,rule-profile-attr~
,rule-script-attr~
,rule-trans-memo-attr~
,ruledict-attr~
,ruledict-param-attr~
,ruleset-attr~
,rvs-doc-attr~
,rvs-line-pump-attr~
,rvs-pump-attr~
,s-coeff-attr~
,sale-doc-attr~
,scales-gds-attr~
,scales-grp-attr~
,schet-fact-doc-attr~
,schet-fact-line-attr~
,season-attr~
,sert-attr~
,sert-join-attr~
,shift-cash-attr~
,shift-obj-attr~
,shift-staff-attr~
,some-lk-attr~
,staff-attr~
,stk-line-attr~
,stk-supp-line-attr~
,stk-supp-tot-attr~
,stk-tot-attr~
,stop-list-attr~
,stop-list-line-attr~
,sum-group-attr~
,sum-grp-attr~
,sum-grp-obj-attr~
,sum-in-sum-group-attr~
,sys-ctrl-attr~
,sysconf-attr~
,tax-attr~
,tax-rate-attr~
,tax-rate-gds-attr~
,tax-rate-gds-grp-attr~
,tax-rate-value-attr~
,tax-units-attr~
,tmp-sale-attr~
,tmp-sale-dtl-attr~
,tmp-sale-gds-attr~
,tnv-in-turnover-group-attr~
,tnved-head-attr~
,tnved-item-attr~
,turnover-buyer-main-attr~
,turnover-group-attr~
,units-attr~
,upgrade-attr~
,user-account-attr~
,user-conn-attr~
,user-context-history-attr~
,user-host-attr~
,user-login-action-item-attr~
,user-login-action-role-attr~
,user-obj-attr~
,user-menu-group-attr~
,usr-flt-attr~
,usr-stko-attr~
,var-deliv-gr-per-val-attr~
,variant-delivery-attr~
,wealth-attr~
,who-lk-attr~
,wi-mode-attr~
,wth-dtl-attr~
,wth-line-attr~
,wth-obj-attr~
,wth-par-attr~
,wth-parts-attr~
,wth-place-attr~
,wth-pobj-attr~
,xyz-analysis-cli~
,xyz-analysis-cli-attr~
,xyz-analysis-grp~
,xyz-analysis-grp-attr~
,xyz-analysis-doc-attr~
,xyz-analysis-obj-attr~
,xyz-analysis-period-attr~
,xyz-analysis-prod~
,xyz-analysis-prod-attr~
':U &endif .

&if "{1}" = "check" &then

procedure nws-tabs_get-variable-names :
define output parameter p-variable-names as character no-undo .

  do
  on error undo, return error
  :
   assign
     p-variable-names = '~
attach-list~
,news-list~
,oth-list1~
,oth-list2~
':U
.

  end.

end procedure. /* nws-tabs_get-variable-names */

procedure nws-tabs_get-variable-value :
define input parameter p-variable-name as character no-undo .
define output parameter p-variable-value as character no-undo .

  do
  on error undo, return error
  :

    case p-variable-name:
      when 'attach-list':U then do:
        assign
        p-variable-value = attach-list.
      end.
      when 'news-list':U then do:
        assign
        p-variable-value = news-list.
      end.
      when 'oth-list1':U then do:
        assign
        p-variable-value = oth-list1.
      end.
      when 'oth-list2':U then do:
        assign
        p-variable-value = oth-list2.
      end.

    end case.

  end.

end procedure. /* nws-tabs_get-variable-value */

&endif

/* $Workfile$ e n d */