/*

$Revision$
$Author$
$Date$
$Workfile$
$Archive$

Инклюд для i n - l i n e . w для записи атрибутов строки и вызова c o r - l i n e . p

Автор: Чернова Светлана Александровна
Дата создания: 10/10/06
Author: Svetlana Chernova
Creation date: 10/10/06

create: Суслов Алексей Юрьевич
Дата создания: 09/20/05


*/

&IF "{1}" = "param" or "{1}" = "eq" &THEN
&ELSE
if not t-doc.flag_ then do:
  { str/in-line.i type-inp-vat }
  { str/in-line.i tot-cli      }
end.
run str/cor-line.p
(input        parparentproc,
 input-output line-rec,
&ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER pardoc-code                LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.doc-code                &ELSE &IF "{1}" = "param" &THEN doc-line.doc-code             &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.doc-code                &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = pardoc-code                &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER parprod-type               LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.prod-type               &ELSE &IF "{1}" = "param" &THEN doc-line.prod-type            &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.prod-type               &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = parprod-type               &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER parprod-code               LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.prod-code               &ELSE &IF "{1}" = "param" &THEN doc-line.prod-code            &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.prod-code               &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = parprod-code               &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER parartic                   LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.artic                   &ELSE &IF "{1}" = "param" &THEN doc-line.artic                &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.artic                   &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = parartic                   &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER parcli-qnty                LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.cli-qnty                &ELSE &IF "{1}" = "param" &THEN doc-line.cli-qnty             &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.cli-qnty                &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = parcli-qnty                &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER parcli-base-rate           LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.cli-base-rate           &ELSE &IF "{1}" = "param" &THEN doc-line.cli-base-rate        &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.cli-base-rate           &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = parcli-base-rate           &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER parfact-qnty               LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.fact-qnty               &ELSE &IF "{1}" = "param" &THEN doc-line.fact-qnty            &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.fact-qnty               &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = parfact-qnty               &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER pardoc-qnty                LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.doc-qnty                &ELSE &IF "{1}" = "param" &THEN doc-line.doc-qnty             &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.doc-qnty                &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = pardoc-qnty                &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER parunit-cli                LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.unit-cli                &ELSE &IF "{1}" = "param" &THEN doc-line.unit-cli             &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.unit-cli                &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = parunit-cli                &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER parvat-pc                  LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.vat-pc                  &ELSE &IF "{1}" = "param" &THEN doc-line.vat-pc               &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.vat-pc                  &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = parvat-pc                  &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER parslt-pc                  LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.slt-pc                  &ELSE &IF "{1}" = "param" &THEN doc-line.slt-pc               &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.slt-pc                  &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = parslt-pc                  &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER parprice-cli               LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.price-cli               &ELSE &IF "{1}" = "param" &THEN doc-line.price-cli            &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.price-cli               &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = parprice-cli               &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER parprice-base              LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.price-base              &ELSE &IF "{1}" = "param" &THEN doc-line.price-base           &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.price-base              &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = parprice-base              &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER parprice-rubl              LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.price-rubl              &ELSE &IF "{1}" = "param" &THEN doc-line.price-rubl           &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.price-rubl              &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = parprice-rubl              &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER parnew-price-sale          LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.new-price-sale          &ELSE &IF "{1}" = "param" &THEN doc-line.new-price-sale       &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.new-price-sale          &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = parnew-price-sale          &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER parnum-place               LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.num-place               &ELSE &IF "{1}" = "param" &THEN doc-line.num-place            &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.num-place               &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = parnum-place               &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER parwt-brutto               LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.wt-brutto               &ELSE &IF "{1}" = "param" &THEN doc-line.wt-brutto            &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.wt-brutto               &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = parwt-brutto               &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER parroad-tax                LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.road-tax                &ELSE &IF "{1}" = "param" &THEN doc-line.road-tax             &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.road-tax                &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = parroad-tax                &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER parexcise                  LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.excise                  &ELSE &IF "{1}" = "param" &THEN doc-line.excise               &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.excise                  &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = parexcise                  &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER pardoc-density             LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.doc-density             &ELSE &IF "{1}" = "param" &THEN doc-line.doc-density          &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.doc-density             &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = pardoc-density             &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER partemperature             LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.temperature             &ELSE &IF "{1}" = "param" &THEN doc-line.temperature          &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.temperature             &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = partemperature             &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER parcontract-code           LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.contract-code           &ELSE &IF "{1}" = "param" &THEN parts.contract-code           &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.contract-code           &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = parcontract-code           &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER parlast-date               LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.last-date               &ELSE &IF "{1}" = "param" &THEN parts.last-date               &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.last-date               &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = parlast-date               &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER parfact-qnty-kg            LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.fact-qnty-kg            &ELSE &IF "{1}" = "param" &THEN doc-line.fact-qnty            &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.fact-qnty-kg            &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = parfact-qnty-kg            &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER parfact-density            LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.fact-density            &ELSE &IF "{1}" = "param" &THEN doc-line.fact-density         &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.fact-density            &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = parfact-density            &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER parcst-code                LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.cst-code                &ELSE &IF "{1}" = "param" &THEN parts.cst-code                &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.cst-code                &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = parcst-code                &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER paralc-update              AS   &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.alc-update              &ELSE &IF "{1}" = "param" &THEN logical                       &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.alc-update              &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = paralc-update              &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER paralc-part-code           LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.part-code               &ELSE &IF "{1}" = "param" &THEN parts.part-code               &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.alc-part-code           &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = paralc-part-code           &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER paralc-mark-db-num         LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.alc-mark-db-num         &ELSE &IF "{1}" = "param" &THEN parts.mark-db-num             &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.alc-mark-db-num         &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = paralc-mark-db-num         &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER paralc-mark-code           LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.alc-mark-code           &ELSE &IF "{1}" = "param" &THEN parts.mark-code               &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.alc-mark-code           &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = paralc-mark-code           &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER paralc-bottling-date       LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.alc-bottling-date       &ELSE &IF "{1}" = "param" &THEN parts.alc-bottling-date       &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.alc-bottling-date       &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = paralc-bottling-date       &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER paralc-ref-ab-path         LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.alc-ref-ab-path         &ELSE &IF "{1}" = "param" &THEN parts.alc-ref-ab-path         &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.alc-ref-ab-path         &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = paralc-ref-ab-path         &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER paralc-quality-certif-path LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.alc-quality-certif-path &ELSE &IF "{1}" = "param" &THEN parts.alc-quality-certif-path &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.alc-quality-certif-path &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = paralc-quality-certif-path &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER paralc-imp-type            LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.alc-imp-type            &ELSE &IF "{1}" = "param" &THEN parts.alc-imp-type            &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.alc-imp-type            &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = paralc-imp-type            &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER paralc-imp-code            LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.alc-imp-code            &ELSE &IF "{1}" = "param" &THEN parts.alc-imp-code            &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.alc-imp-code            &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = paralc-imp-code            &ELSE ,           &ENDIF &ENDIF
 &IF "{1}" = "param" &THEN DEFINE INPUT PARAMETER paralc-certif-path         LIKE &ENDIF &IF "{1}" = "eq" &THEN TT-doc-line.alc-certif-path         &ELSE &IF "{1}" = "param" &THEN parts.alc-certif-path         &ENDIF &IF "{1}" = "realy" &THEN tt-fr-doc-line.alc-certif-path         &ENDIF &ENDIF &IF "{1}" = "param" &THEN NO-UNDO. &ELSE &IF "{1}" = "eq" &THEN = paralc-certif-path         &ELSE ) no-error. if error-status:error then do: return error return-value. end. &ENDIF &ENDIF
/* $Workfile$   E n d */