 
 /*------------------------------------------------------------------------
    File        : eventhndlimpsub
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : asmorozov
    Created     : Sat Oct 14 17:38:38 MSK 2017
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.
block-level on error undo, throw.


class ibs.th.bge.1crn.import.eventhndlimpsub: 

end class.