 
/*------------------------------------------------------------------------
 File : ptrlprop
 Purpose : 
 Syntax : 
 Description : 
 Author(s) : asmorozov
 Created : Mon Oct 01 17:18:41 MSK 2018
 Notes : 
 ----------------------------------------------------------------------*/

using Progress.Lang.*.


class ibs.th.gbl.ptrl.par.ptrlprop: 

  define property ptrlprop-denstclc as character no-undo 
    get.
    set.
  define property ptrlprop-inpptrl as character no-undo
    get.
    set.
  define property ptrlprop-expptrl as character no-undo
    get.
    set.
  define property ptrlprop-autopump as logical no-undo
    get.
    set.
  define property ptrlprop-avtinvpm as logical no-undo
    get.
    set.
  define property ptrlprop-rvsnmter as logical no-undo
    get.
    set.
  define property ptrlprop-olddens as logical no-undo
    get.
    set.
  define property ptrlprop-invclipt as integer no-undo
    get.
    set.
  define property ptrlprop-algrvspt as integer no-undo
    get.
    set.
  define property ptrlprop-temp-for-pomi as integer no-undo
    get.
    set.
  define property ptrlprop-algoincome as integer no-undo
    get.
    set.
  define property ptrlprop-mand-choice-autocar as logical no-undo
    get.
    set.
  define property ptrlprop-Delta-mass-horiz as character no-undo
    get.
    set.
  define property ptrlprop-Delta-mass-vert as character no-undo
    get.
    set.

end class.