/*

$Revision: b10ceb95d184, 3329, rls $
$Author: DRuban $
$Date: 2023/05/19 13:37:08 $
$Workfile: assortment-matrix.cls $
$Archive: ibs/th/bge/1crn/subjects/assortment-matrix.cls $

Структура данных assortment-matrix в 1С

Автор: Молотков Сергей Михайлович
Дата создания: 21/11/17
Author: Molotkov Sergey
Creation date: 21/11/17

*/

using Progress.Lang.*.
using ibs.th.bge.1crn.enum-assortment-stg.
using ibs.th.bge.1crn.subjects.subjects from propath.
block-level on error undo, throw.


class ibs.th.bge.1crn.subjects.assortment-matrix inherits ibs.th.bge.1crn.subjects.asubject:
  define override public property vss-revision    as character no-undo init "$Revision:$":U get .
  define override public property vss-author      as character no-undo init "$Author:$":U get.
  define override public property vss-date        as character no-undo init "$Date:$":U get.
  define override public property vss-workfile    as character no-undo init "$Workfile:$":U get.
  define override public property vss-archive     as character no-undo init "$Archive:$":U get.
 
  define property gds-code as character no-undo
    get.
    private set.
  define property stg as enum-assortment-stg no-undo 
    get. 
    private set.

  define override property InitTag as character no-undo init "assortment-matrix"
    get. 


  method override protected void SetPropProtected (inTag as char, inValue as char):
      /* допустимые значения stg перечислены в enum;
         если дано значение вне enum - поле останется пустым,
         если дано пустое значение - поле заполнится типом "archive" (в БД TradeHouse запишется как "Пусто")
       */
    case inTag:
      when "gds-code" then gds-code = if inValue >= "" then inValue else "" .
      when "stg" then do :
        if inValue >= "" then stg = enum-assortment-stg:GetEnum( integer (inValue) ) .
                         else stg = enum-assortment-stg:enarchive .
      end .
    end case.
    catch exProErrors as class Progress.Lang.ProError :
      case exProErrors:GetMessageNum(1):
        when 18207 then undo, throw new Progress.Lang.AppError(
          substitute("Поле <&1> содержит ошибочное значение [&2]", inTag, inValue)
        ) .
        otherwise undo, throw new Progress.Lang.AppError(
          substitute("Ошибка значения для поля <&1>: &2", inTag, exProErrors:GetMessage(1))
        ) .
      end case .
    end catch .
  end method.


  method override protected void CheckData ():
    def var v-str as char no-undo.
    
    assign
      v-str = ",gds-code" when gds-code = ?
      v-str = v-str + ",stg" when stg = ?
    .
    v-str = substring(v-str, 2).
    if v-str > "" then undo, throw new Progress.Lang.AppError(
      substitute("Теги [&1] отсутствуют в сообщении [&2]", v-str, InitTag)
    ) .

  end method.
  
  method override protected void ClearSub():
    assign 
      gds-code = ?
      stg      = ?
    .
  end method.


end class.