/*

$Revision$
$Author$
$Date$
$Workfile$
$Archive$

Структура данных recipe-gd в 1С

Автор: Молотков Сергей Михайлович
Дата создания: 31/10/17
Author: Molotkov Sergey
Creation date: 31/10/17

*/

using Progress.Lang.*.


class ibs.th.bge.1crn.subjects.recipe-gd inherits ibs.th.bge.1crn.subjects.asubject:

  define property gd-code as character no-undo 
    get. 
    private set.
  /* внутри 1С количество товара в рецепте указывается вместе с единицами измерения количества;
     внутри TH товар всегда измеряется в одинаковой единице измерения;
     поле unit-code получаем в импорте, но не пишем в БД */  
  define property unit-code as character no-undo 
    get. 
    private set.
    
  /* нетто есть брутто, очищенный от коэффициента потерь lf */  
  define property qnty-net as decimal no-undo
    get. 
    private set.
  define property qnty-gross as decimal no-undo
    get. 
    private set.
  define property lf as decimal no-undo
    get. 
    private set.
    
  define property gds-recipe-code as character no-undo
    get. 
    private set.

  /* отсутствуют в БД;
     будут исключены из протокола */  
  define property seasonal-losses as decimal no-undo /* Число (10,2)  0-1 Процент сезонных потерь */
    get. 
    private set.
  define property weight-gross    as decimal no-undo /* Число (10,3)  0-1 Вес брутто с учетом сезонных потерь */
    get. 
    private set.

  define override property InitTag as character no-undo init "recipe-gd"
    get. 

  method override protected void SetPropProtected (inTag as char, inValue as char):
    case inTag:
      when "gd-code"    then gd-code    = if inValue >= "" then inValue else "" .
      when "unit-code"  then unit-code  = if inValue >= "" then inValue else "" .
      when "qnty-net"   then qnty-net   = if inValue >= "" then decimal(inValue) else 0.0 .
      when "qnty-gross" then qnty-gross = if inValue >= "" then decimal(inValue) else 0.0 .
      when "lf"         then lf         = if inValue >= "" then decimal(inValue) else 0.0 .
      when "seasonal-losses" then seasonal-losses = if inValue >= "" then decimal(inValue) else 0.0 .
      when "weight-gross"    then weight-gross    = if inValue >= "" then decimal(inValue) else 0.0 .
      when "recipe-code" then gds-recipe-code = if inValue >= "" then inValue else "" .
    end case.
  end method.


  method override protected void CheckData ():
    def var v-str as char no-undo.
    
    assign
      v-str = ",gd-code" when gd-code = ?
      v-str = v-str + ",unit-code" when unit-code = ?
      v-str = v-str + ",qnty-net" when qnty-net = ?
      v-str = v-str + ",qnty-gross" when qnty-gross = ?
    .
    v-str = substring(v-str, 2).
    if v-str > "" then undo, throw new Progress.Lang.AppError(
      substitute("Теги [&1] отсутствуют в сообщении [&2]", v-str, InitTag)
    ) .

  end method.
  
  method override protected void ClearSub():
    assign 
      gd-code         = ?
      unit-code       = ?
      qnty-net        = ?
      qnty-gross      = ?
      lf              = ?
      gds-recipe-code = ?
      seasonal-losses = ?
      weight-gross    = ?
    .
  end method.


end class.