/*

$Revision$
$Author$
$Date$
$Workfile$
$Archive$

Экспорт сообщения с накладаной в 1С ERPRN tank

Автор: Елена Шкляр
Дата создания: 26/09/17
Author: Shklyar Elena
Creation date: 26/09/17

*/

using Progress.Lang.*.
using ibs.th.bge.1crn.subjects.*.
using ibs.th.str.placelib from propath .

class ibs.th.bge.1crn.subjects.tank implements iexpsubject:

  define variable placelib as class placelib no-undo .
  { cmp/str-glbl.i class }
  
&global-define place-type         "place-type"                /*тип резервуара(вертикальный,горизонтальный)*/
&global-define place-SI           "place-SI"                    /*средство измерения*/
&global-define place-diameter     "place-diameter"        /*диаметр резервуара(мм)*/
&global-define dead-balance       "dead-balance"        /*мертвый остаток*/
&global-define water-level        "water-level"        /*Допустимый уровень воды(мм)*/
/*&global-define place-ratio-error  "place-ratio-error"  /*относительная погрешность составления калибровочной таблицы резервуара*/*/
&global-define place-dens-prov    "dens-prov"         /*плотность при поверке резервуара*/
&global-define place-virtual      "place-virtual"     /*виртуальный резервуар*/
&global-define place-twice-code   "place-twice-code" /*Код сдвоенного резервуара*/
&global-define place-sert-urov    "place-sert-urov" /*Сертифицированный уровнемер по массе*/
&global-define place-local        "place-local"     /*Расположение резервуара*/
&global-define place-error-mass   "place-error-mass" /*Погрешность измерения массы*/
&global-define place-asi-sertif   "place-asi-sertif" /*АСИ сертифицированно*/
&global-define place-rvd-dnsty    "place-rvd-dnsty" /*РВД плотности*/
&global-define place-rvd-lvl      "place-rvd-lvl" /*РВД уровня*/
&global-define place-rvd-tmp      "place-rvd-tmp" /*РВД температуры*/
&global-define place-SI-dens      "place-SI-dens"                    /*средство измерения плотности*/
&global-define place-SI-level     "place-SI-level"                    /*средство измерения уровня*/
&global-define place-SI-temp      "place-SI-temp"                    /*средство измерения температуры*/
&global-define place-passp-num    "place-passp-num"                    /*номер по паспорту*/
&global-define place-passp-type   "place-passp-type"                    /*тип по паспорту*/
&global-define place-dead-high    "place-dead-high"                    /*высота мертвой полости*/
&global-define place-temp-coef    "place-temp-coef"                    /*Температурный коэффициент линейного расширения материала стенки резервуара,*/
&global-define disable-water-alarm   "disable-water-alarm" /*Отключить сообщения по воде*/
&global-define disable-level-alarm   "disable-level-alarm" /*Отключить сообщения по уровню*/
&global-define place-ponton        "place-ponton"                    /*наличие понтона*/
&global-define place-ponton-mass   "place-ponton-mass"                    /*масса понтона*/
&global-define place-ponton-height "place-ponton-height"                    /*высота всплытия понтона*/
&global-define place-need-RVD-rvs "place-need-RVD-rvs" /* Необходимо сделать сверку с РВД (в список не добавлять!) */

&global-define list-place-attr    'place-type,place-SI,place-diameter,dead-balance,water-level,dens-prov,place-virtual,place-twice-code,place-sert-urov,place-local,place-error-mass,place-asi-sertif,place-rvd-dnsty,place-rvd-lvl,place-rvd-tmp,place-SI-dens,place-SI-level,place-SI-temp,place-passp-num,place-passp-type,place-dead-high,place-temp-coef,disable-water-alarm,disable-level-alarm,place-ponton,place-ponton-mass,place-ponton-height':u /*список атрибутов резервуара*/

  define buffer buf_place      for ub.place .
  define buffer buf_c-place    for ub.c-place .
  define buffer buf_place-attr for ub.place-attr .
  define buffer buf_pl-level   for ub.pl-level .
  define buffer buf_c-pl-level for ub.c-pl-level .
  define buffer buf_pl-level-attr for ub.pl-level-attr .
  define buffer buf_pl-gds     for ub.pl-gds .
  define temp-table tt-place like ub.c-place 
  field gds-code as integer.
  define temp-table tt-pl-level like ub.c-pl-level 
  field comp-err  as decimal.
  
  define variable ii      as integer   no-undo .
  define variable v-code  as character no-undo .
  define variable v-value as character no-undo .
  define variable v-ok    as logical   no-undo .
  define variable v-del   as logical   no-undo . 
  
   define temp-table tt-place-attr
      field pl-code             like place.pl-code
      field place-type          as character
      field place-Si            as integer
      field place-diameter      as decimal
      field dead-balance        as decimal
      field place-rel-error     as decimal
      field pl-twice-code       like place.loc1
      field place-dens-prov     as decimal
      field place-local         as integer
      field place-asi-sertif    as integer
      field place-error-mass    as decimal
      field place-rvd-dnsty     as integer
      field place-rvd-lvl       as integer
      field place-rvd-tmp       as integer
      field place-dc-height     as integer
      field place-tank-tk       as decimal
      field place-dnst-mi-code  as character
      field place-lvl-mi-code   as character
      field place-tmp-mi-code   as character
      field place-passport-num  as character
      field place-passport-type as character
      field ponton              as logical
      field ponton-mass         as decimal
      field ponton-height       as decimal
      index pi as primary unique
      pl-code
      .
  
  define property Msg as character no-undo
    get.
    private set.

  
  define property pl-code as character no-undo
    get.
    set.

  define variable sw as handle no-undo.
  

  define property InitSecTag as character no-undo init "tanks"
    get.
    private set.
  

  method public void CrContentToSW (insw as handle):
    sw = insw .
    
    placelib = new placelib().
    /*    sw:start-element ("tanks") .*/
    find first buf_place no-lock where buf_place.pl-code = INTEGER (pl-code) no-error .
    if AVAILABLE buf_place then 
    do:
      v-del = no .
      create tt-place .
      BUFFER-COPY buf_place to tt-place .
      find first buf_pl-gds no-lock where buf_pl-gds.pl-code = buf_place.pl-code no-error .
      if AVAILABLE (buf_pl-gds) then do:
        tt-place.gds-code = buf_pl-gds.gds-code .
      end.  
    end.  
    else 
    do:
      find first buf_c-place no-lock where buf_c-place.pl-code = INTEGER (pl-code) no-error .
      if AVAILABLE buf_c-place then 
      do:
        v-del = yes .
        create tt-place .
        BUFFER-COPY buf_c-place to tt-place .
        find first buf_pl-gds no-lock where buf_pl-gds.pl-code = buf_c-place.pl-code no-error .
        if AVAILABLE (buf_pl-gds) then 
        do:
          tt-place.gds-code = buf_pl-gds.gds-code .
        end.  
      end.  
      else 
      do:
        Msg = "Нет складкского места с кодом" + pl-code .
        return error.
      end.  
    end.
    find first buf_pl-level no-lock where buf_pl-level.pl-code = tt-place.pl-code and
      buf_pl-level.obj-code = tt-place.obj-code and
      buf_pl-level.obj-type = tt-place.obj-type no-error .
    if AVAILABLE buf_pl-level then 
    do:
      for each buf_pl-level no-lock where buf_pl-level.pl-code = tt-place.pl-code and
        buf_pl-level.obj-code = tt-place.obj-code and
        buf_pl-level.obj-type = tt-place.obj-type:
        create tt-pl-level .
        buffer-copy buf_pl-level to tt-pl-level .
     find first buf_pl-level-attr no-lock where buf_pl-level-attr.obj-type  = buf_pl-level.obj-type
                                            and buf_pl-level-attr.obj-code  = buf_pl-level.obj-code
                                            and buf_pl-level-attr.pl-code   = buf_pl-level.pl-code
                                            and buf_pl-level-attr.pl-level  = buf_pl-level.pl-level
                                            and buf_pl-level-attr.attr-code = "tarir-delta"
                                            no-error .
     if available buf_pl-level-attr then tt-pl-level.comp-err = decimal (buf_pl-level-attr.attr-value) .
     end .           
    end .
    else 
    do:
      for each buf_c-pl-level no-lock where buf_c-pl-level.pl-code = tt-place.pl-code and
        buf_c-pl-level.obj-code = tt-place.obj-code and
        buf_c-pl-level.obj-type = tt-place.obj-type:
        create tt-pl-level .
        buffer-copy buf_c-pl-level to tt-pl-level .
     find first buf_pl-level-attr no-lock where buf_pl-level-attr.obj-type  = buf_c-pl-level.obj-type
                                            and buf_pl-level-attr.obj-code  = buf_c-pl-level.obj-code
                                            and buf_pl-level-attr.pl-code   = buf_c-pl-level.pl-code
                                            and buf_pl-level-attr.pl-level  = buf_c-pl-level.pl-level
                                            and buf_pl-level-attr.attr-code = "tarir-delta"
                                            no-error .
     if available buf_pl-level-attr then tt-pl-level.comp-err = decimal (buf_pl-level-attr.attr-value) .        
      end.      
    end.        
    
    for each tt-place where tt-place.pl-code = INTEGER (pl-code) no-lock :    
      find first tt-place-attr exclusive-lock where tt-place-attr.pl-code = tt-place.pl-code no-error.
      if not available tt-place-attr then 
      do :
        create tt-place-attr.
        tt-place-attr.pl-code = tt-place.pl-code.
        ii = 0.
        do ii = 1 to num-entries({&list-place-attr}):
          v-code = entry(ii,{&list-place-attr}) .
          placelib:placelib_get-attr (
            input v-code
            ,input tt-place.obj-code
            ,input tt-place.obj-type
            ,input tt-place.pl-code
            ,output v-value
            ,output v-ok      ) no-error.
           case v-code :
              when {&place-type} then 
                 do :
                    if v-ok then 
                    do :
                       if integer(v-value) = 1 then tt-place-attr.place-type = "1"  .
                       if integer(v-value) = 2 then tt-place-attr.place-type = "2"  .
                    end.
                 end.
              when {&place-SI} then 
                 do :
                    if v-ok then tt-place-attr.place-Si = integer(v-value) .
                 end.
              when {&place-diameter} then 
                 do :
                    if v-ok then tt-place-attr.place-diameter = decimal(v-value) .
                 end.
              when {&dead-balance} then 
                 do :
                    if v-ok then tt-place-attr.dead-balance = decimal(v-value) .
                 end.
/*              when {&place-ratio-error} then                                       */
/*                 do :                                                              */
/*                    if v-ok then tt-place-attr.place-rel-error = decimal(v-value) .*/
/*                 end.                                                              */
              when {&place-dens-prov} then 
                 do :
                    if v-ok then tt-place-attr.place-dens-prov = decimal(v-value) .
                 end.
              when {&place-twice-code} then 
                 do:
                    if v-ok then tt-place-attr.pl-twice-code = v-value .
                 end.
              when {&place-error-mass} then 
                 do: 
                    if v-ok then tt-place-attr.place-error-mass = decimal(v-value) .
                 end.
              when {&place-local} then 
                 do: 
                    if v-ok then 
                    do:
                       if v-value = "1" then tt-place-attr.place-local = 0 .
                       else tt-place-attr.place-local = 1 .
                    end.
                 end.
              when {&place-asi-sertif} then 
                 do: 
                    if v-ok then 
                    do:
                       if v-value = "yes" then tt-place-attr.place-asi-sertif = 1 .
                       else tt-place-attr.place-asi-sertif = 0 .
                    end.
                 end.                                        
              when {&place-rvd-dnsty} then 
                 do: 
                    if v-ok then 
                    do:
                       if v-value = "yes" then tt-place-attr.place-rvd-dnsty = 1 .
                       else tt-place-attr.place-rvd-dnsty = 0 .
                    end.
                 end.                                        
              when {&place-rvd-lvl} then 
                 do: 
                    if v-ok then 
                    do:
                       if v-value = "yes" then tt-place-attr.place-rvd-lvl = 1 .
                       else tt-place-attr.place-rvd-lvl = 0 .
                    end.
                 end.                                    
              when {&place-rvd-tmp} then 
                 do: 
                    if v-ok then 
                    do:
                       if v-value = "yes" then tt-place-attr.place-rvd-tmp = 1 .
                       else tt-place-attr.place-rvd-tmp = 0 .
                    end.
                 end.                                                  
              when {&place-dead-high} then 
                 do: 
                    if v-ok then 
                    do:
                       tt-place-attr.place-dc-height = integer(v-value).
                    end.
                 end. 
              when {&place-temp-coef} then 
                 do: 
                    if v-ok then 
                    do:
                       tt-place-attr.place-tank-tk = decimal(v-value).
                    end.
                 end. 
              when {&place-SI-dens} then 
                 do: 
                    if v-ok then 
                    do:
                       tt-place-attr.place-dnst-mi-code = v-value .
                       if tt-place-attr.place-dnst-mi-code = ? then tt-place-attr.place-dnst-mi-code = "0" .
                    end.
                 end. 
              when {&place-SI-level} then 
                 do: 
                    if v-ok then 
                    do:
                       tt-place-attr.place-lvl-mi-code = v-value .
                       if tt-place-attr.place-lvl-mi-code = ? then tt-place-attr.place-lvl-mi-code = "0" .
                    end.
                 end. 
              when {&place-SI-temp} then 
                 do: 
                    if v-ok then 
                    do:
                       tt-place-attr.place-tmp-mi-code = v-value.
                       if tt-place-attr.place-tmp-mi-code = ? then tt-place-attr.place-tmp-mi-code = "0" .
                    end.
                 end. 
              when {&place-passp-num} then 
                 do: 
                    if v-ok then 
                    do:
                       tt-place-attr.place-passport-num = v-value .
                    end.
                 end.      
              when {&place-passp-type} then 
                 do: 
                    if v-ok then 
                    do:
                       tt-place-attr.place-passport-type = v-value .
                    end.
                 end.   
              when {&place-ponton} then do :
                if v-ok then tt-place-attr.ponton = logical(v-value) .
              end.
              when {&place-ponton-mass} then do: 
                if v-ok then tt-place-attr.ponton-mass = decimal(v-value) .
              end.  
              when {&place-ponton-height} then do: 
                if v-ok then tt-place-attr.ponton-height = decimal(v-value) .
              end.                                                                                               
           end case.
        end.
      end.
      
      sw:start-element ("tank") .
      sw:write-data-element ("tank-code", string(tt-place.pl-code)).
      sw:write-data-element ("tank-num", string(tt-place.loc1)).
      sw:write-data-element ("del-l", if tt-place.status_ <> {&deleted-status} then "0" else "1").
      sw:write-data-element ("del-f", if v-del then "1" else "0").
      sw:write-data-element ("name", if tt-place.pl-name = ? then "" else tt-place.pl-name).
      sw:write-data-element ("gs-code", string(tt-place.obj-code)).
      for each tt-place-attr no-lock where tt-place-attr.pl-code = tt-place.pl-code:
        sw:write-data-element ("tank-type", string(tt-place-attr.place-type)).
        sw:write-data-element ("pl-qnty"  , string(tt-place.add-qnty)).
        sw:write-data-element ("max-qnty" , string(tt-place.max-qnty)).
        sw:write-data-element ("d-qnty"   , string(tt-place-attr.dead-balance)).
        sw:write-data-element ("tank-d"   , string(tt-place-attr.place-diameter)).
        sw:write-data-element ("dc-height" , string(tt-place-attr.place-dc-height)).        
        sw:write-data-element ("rel-er"   , if tt-place-attr.place-type = "1" then "0.20" else "0.25").
        sw:write-data-element ("dnsty"    , string-mth (tt-place-attr.place-dens-prov)).
        sw:write-data-element ("main-mi-code"  , string(if tt-place-attr.place-Si = ? then 0 else tt-place-attr.place-Si)).
        sw:write-data-element ("position"  , string(tt-place-attr.place-local)).
        sw:write-data-element ("certified"  , string(tt-place-attr.place-asi-sertif)).
        sw:write-data-element ("pipe-er"  , string-mth(tt-place-attr.place-error-mass)).
        sw:write-data-element ("tank-tk" , string(tt-place-attr.place-tank-tk)).  
        sw:write-data-element ("rvd-dnsty"  , string(tt-place-attr.place-rvd-dnsty)).
        sw:write-data-element ("dnst-mi-code" , string(tt-place-attr.place-dnst-mi-code)).  
        sw:write-data-element ("rvd-lvl"  , string(tt-place-attr.place-rvd-lvl)).
        sw:write-data-element ("lvl-mi-code" , string(tt-place-attr.place-lvl-mi-code)).
        sw:write-data-element ("rvd-tmp"  , string(tt-place-attr.place-rvd-tmp)).
        sw:write-data-element ("tmp-mi-code" , string(tt-place-attr.place-tmp-mi-code)). 
        sw:write-data-element ("passport-num" , string(tt-place-attr.place-passport-num)).  
        sw:write-data-element ("passport-type" , string(tt-place-attr.place-passport-type)). 
        if tt-place-attr.place-type = "1"
        then do :
          if tt-place-attr.ponton
          then do :
            sw:write-data-element ("pontoon", "1").
            sw:write-data-element ("wght-pntn", string(tt-place-attr.ponton-mass)).
            sw:write-data-element ("srfcng-pntn", string(tt-place-attr.ponton-height)).
          end .
          else do :
            sw:write-data-element ("pontoon", "0").
          end .
        end .
      end.
      sw:write-data-element ("gd-code", string(tt-place.gds-code)).
      sw:write-data-element ("izm-pr", if tt-place.is-meas = yes then "1" else "0").
      find first tt-pl-level no-lock where tt-pl-level.pl-code = tt-place.pl-code and
        tt-pl-level.obj-code = tt-place.obj-code and
        tt-pl-level.obj-type = tt-place.obj-type no-error .
      if AVAILABLE (tt-pl-level) then 
      do:      
        sw:start-element ("cal-tbl") .
        for each tt-pl-level no-lock where tt-pl-level.pl-code = tt-place.pl-code and
          tt-pl-level.obj-code = tt-place.obj-code and
          tt-pl-level.obj-type = tt-place.obj-type:
          sw:start-element ("cal-tbl-line") .
          sw:write-data-element ("lvl"  , string(tt-pl-level.pl-level)).
          sw:write-data-element ("amnt" , string(tt-pl-level.pl-qnty)).
          sw:write-data-element ("comp-err" , string(tt-pl-level.comp-err)).
          sw:end-element ("cal-tbl-line")  .
        end.
        sw:end-element ("cal-tbl")  .  
      end.
      sw:END-ELEMENT ("tank") .  
    end.
  end.  
  method private character string-mth (inValue as decimal):
    
    def var v-str as character no-undo.
    
    if inValue = ?
      then v-str = "0".
    
    if string (inValue) begins "."
      then v-str = "0" + string (inValue).
    else v-str = string (inValue).
    return v-str.
    
  end.
end class.