/*

$Revision$
$Author$
$Date$
$Workfile$
$Archive$



Автор: Морозов Александр Сергеевич
Дата создания: 19/01/18
Author: Alexand Morozov
Creation date: 19/01/18

*/


using Progress.Lang.*.
using ibs.th.str.doc.trn.*.


class ibs.th.gbl.thsubject: 




  /*------------------------------------------------------------------------------
   Purpose:
   Notes:
  ------------------------------------------------------------------------------*/

  method public void AddItem ( ):
    
    return.

  end method.

  /*------------------------------------------------------------------------------
   Purpose:
   Notes:
  ------------------------------------------------------------------------------*/

  method public void UpdateItem (  ):
    
    return.

  end method.
  
  /*------------------------------------------------------------------------------
   Purpose:
   Notes:
  ------------------------------------------------------------------------------*/

  method public void DeleteItem (  ):
    
    return.

  end method.


end class.