/*

$Revision$
$Author$
$Date$
$Workfile$
$Archive$

Интерфейс сущностей
Модуль взаимодействия сущностей TH с базой данных

Автор: Морозов Александр Сергеевич
Дата создания: 04/23/18
Author: Morozov Alexandr
Creation date: 04/23/18


*/

using Progress.Lang.*.

interface ibs.th.gbl.storage.ithsub:  
  
  
  
  /*------------------------------------------------------------------------------
   Purpose:
   Notes:
  ------------------------------------------------------------------------------*/

/*  method public void setMsg( arg as character ).*/

  /*------------------------------------------------------------------------------
   Purpose:
   Notes:
  ------------------------------------------------------------------------------*/

/*  method public void setStatusErr( arg as logical ).*/
  

end interface.