/*

$Revision: fd21875b889d, 1394, rls $
$Author: ASMorozov $
$Date: Thu Jun 28 15:24:33 2018 +0300 $
$Workfile: ithsub.cls $
$Archive: ibs/th/gbl/storage/ithsub.cls $

Интерфейс сущностей
Модуль взаимодействия сущностей TH с базой данных

Автор: Морозов Александр Сергеевич
Дата создания: 04/23/18
Author: Morozov Alexandr
Creation date: 04/23/18


*/

using Progress.Lang.*.
block-level on error undo, throw.
interface ibs.th.gbl.storage.ithsub:  
  
  
  
  /*------------------------------------------------------------------------------
   Purpose:
   Notes:
  ------------------------------------------------------------------------------*/

/*  method public void setMsg( arg as character ).*/

  /*------------------------------------------------------------------------------
   Purpose:
   Notes:
  ------------------------------------------------------------------------------*/

/*  method public void setStatusErr( arg as logical ).*/
  

end interface.