/*

$Revision$
$Author$
$Date$
$Workfile$
$Archive$

номера температурных коэффициентов линейного расширения материала средства измерения уровня, согласно протоколу взаимодействия с 1С

Автор: Молотков Сергей
Дата создания: 04/12/17
Author: Molotkov Sergey
Creation date: 04/12/17

*/

enum ibs.th.bge.1crn.enum-ms-tk-type:
  define enum
    ensteel  = 1 /* сталь */
    enalumin = 2 /* алюминий */
  .
end enum .
