/*

$Revision: $
$Author: $
$Date: $
$Workfile: $
$Archive: $

Глобальные определения имен таблиц

Автор: Перваков Михаил Сергеевич
Дата создания: 04/05/06
Author: Mikhail Pervakov
Creation date: 04/05/06

Файл автоматически создается процедурой utl/gen-tbln.p

*/

&glob table_abc-analysis 'abc-analysis':U
&glob table_abc-analysis-attr 'abc-analysis-attr':U
&glob table_abc-analysis-cli 'abc-analysis-cli':U
&glob table_abc-analysis-cli-attr 'abc-analysis-cli-attr':U
&glob table_abc-analysis-doc 'abc-analysis-doc':U
&glob table_abc-analysis-doc-attr 'abc-analysis-doc-attr':U
&glob table_abc-analysis-gds-obj 'abc-analysis-gds-obj':U
&glob table_abc-analysis-gds-obj-attr 'abc-analysis-gds-obj-attr':U
&glob table_abc-analysis-goods 'abc-analysis-goods':U
&glob table_abc-analysis-goods-attr 'abc-analysis-goods-attr':U
&glob table_abc-analysis-grp 'abc-analysis-grp':U
&glob table_abc-analysis-grp-attr 'abc-analysis-grp-attr':U
&glob table_abc-analysis-obj 'abc-analysis-obj':U
&glob table_abc-analysis-obj-attr 'abc-analysis-obj-attr':U
&glob table_abc-analysis-period 'abc-analysis-period':U
&glob table_abc-analysis-period-attr 'abc-analysis-period-attr':U
&glob table_abc-analysis-prod 'abc-analysis-prod':U
&glob table_abc-analysis-prod-attr 'abc-analysis-prod-attr':U
&glob table_abcxyz-analysis 'abcxyz-analysis':U
&glob table_abcxyz-analysis-attr 'abcxyz-analysis-attr':U
&glob table_abcxyz-analysis-goods 'abcxyz-analysis-goods':U
&glob table_abcxyz-analysis-goods-attr 'abcxyz-analysis-goods-attr':U
&glob table_action-group 'action-group':U
&glob table_action-group-attr 'action-group-attr':U
&glob table_action-head 'action-head':U
&glob table_action-head-attr 'action-head-attr':U
&glob table_action-item 'action-item':U
&glob table_action-item-attr 'action-item-attr':U
&glob table_action-post 'action-post':U
&glob table_action-post-attr 'action-post-attr':U
&glob table_action-post-host 'action-post-host':U
&glob table_action-post-host-attr 'action-post-host-attr':U
&glob table_action-post-menu-group 'action-post-menu-group':U
&glob table_action-post-menu-group-attr 'action-post-menu-group-attr':U
&glob table_action-post-obj 'action-post-obj':U
&glob table_action-post-obj-attr 'action-post-obj-attr':U
&glob table_action-post-role 'action-post-role':U
&glob table_action-post-role-attr 'action-post-role-attr':U
&glob table_action-post-user-login 'action-post-user-login':U
&glob table_action-post-user-login-attr 'action-post-user-login-attr':U
&glob table_action-role 'action-role':U
&glob table_action-role-attr 'action-role-attr':U
&glob table_action-role-item 'action-role-item':U
&glob table_action-role-item-attr 'action-role-item-attr':U
&glob table_action-role-item-gds 'action-role-item-gds':U
&glob table_action-role-item-gds-grp 'action-role-item-gds-grp':U
&glob table_add-doc 'add-doc':U
&glob table_add-line 'add-line':U
&glob table_add-trn 'add-trn':U
&glob table_add-trn-attr 'add-trn-attr':U
&glob table_aht-doc 'aht-doc':U
&glob table_aht-doc-attr 'aht-doc-attr':U
&glob table_aht-gds 'aht-gds':U
&glob table_aht-gds-attr 'aht-gds-attr':U
&glob table_aht-ot-line 'aht-ot-line':U
&glob table_aht-ot-line-attr 'aht-ot-line-attr':U
&glob table_aht-ot-tot 'aht-ot-tot':U
&glob table_aht-ot-tot-attr 'aht-ot-tot-attr':U
&glob table_aht-stk 'aht-stk':U
&glob table_aht-stk-attr 'aht-stk-attr':U
&glob table_aht-stk-line 'aht-stk-line':U
&glob table_aht-stk-line-attr 'aht-stk-line-attr':U
&glob table_aht-stk-tot 'aht-stk-tot':U
&glob table_aht-stk-tot-attr 'aht-stk-tot-attr':U
&glob table_aht-time 'aht-time':U
&glob table_aht-time-attr 'aht-time-attr':U
&glob table_alc-sale-lic 'alc-sale-lic':U
&glob table_alc-sale-lic-attr 'alc-sale-lic-attr':U
&glob table_alc-sale-lic-type 'alc-sale-lic-type':U
&glob table_alc-sale-lic-type-attr 'alc-sale-lic-type-attr':U
&glob table_alc-supp-lic 'alc-supp-lic':U
&glob table_alc-supp-lic-attr 'alc-supp-lic-attr':U
&glob table_alc-supp-lic-type 'alc-supp-lic-type':U
&glob table_alc-supp-lic-type-attr 'alc-supp-lic-type-attr':U
&glob table_alc-type 'alc-type':U
&glob table_alc-type-attr 'alc-type-attr':U
&glob table_alc-type-gds 'alc-type-gds':U
&glob table_alc-type-gds-attr 'alc-type-gds-attr':U
&glob table_archive-history 'archive-history':U
&glob table_archive-history-attr 'archive-history-attr':U
&glob table_arh-fin-doc-an 'arh-fin-doc-an':U
&glob table_arh-fin-doc-an-attr 'arh-fin-doc-an-attr':U
&glob table_arh-fin-doc-an-nal 'arh-fin-doc-an-nal':U
&glob table_arh-fin-doc-an-nal-attr 'arh-fin-doc-an-nal-attr':U
&glob table_arh-fin-doc-an-nal-obj 'arh-fin-doc-an-nal-obj':U
&glob table_arh-fin-doc-an-nal-obj-attr 'arh-fin-doc-an-nal-obj-attr':U
&glob table_arh-fin-doc-an-obj 'arh-fin-doc-an-obj':U
&glob table_arh-fin-doc-an-obj-attr 'arh-fin-doc-an-obj-attr':U
&glob table_arh-fin-doc-c-s-tax-nal-obj 'arh-fin-doc-c-s-tax-nal-obj':U
&glob table_arh-fin-doc-c-schet-tax-nal 'arh-fin-doc-c-schet-tax-nal':U
&glob table_arh-fin-doc-contr-s-nal-obj 'arh-fin-doc-contr-s-nal-obj':U
&glob table_arh-fin-doc-contr-s-tax-obj 'arh-fin-doc-contr-s-tax-obj':U
&glob table_arh-fin-doc-contr-schet 'arh-fin-doc-contr-schet':U
&glob table_arh-fin-doc-contr-schet-attr 'arh-fin-doc-contr-schet-attr':U
&glob table_arh-fin-doc-contr-schet-nal 'arh-fin-doc-contr-schet-nal':U
&glob table_arh-fin-doc-contr-schet-obj 'arh-fin-doc-contr-schet-obj':U
&glob table_arh-fin-doc-contr-schet-tax 'arh-fin-doc-contr-schet-tax':U
&glob table_arh-fin-doc-s-tax-nal-obj 'arh-fin-doc-s-tax-nal-obj':U
&glob table_arh-fin-doc-schet 'arh-fin-doc-schet':U
&glob table_arh-fin-doc-schet-attr 'arh-fin-doc-schet-attr':U
&glob table_arh-fin-doc-schet-nal 'arh-fin-doc-schet-nal':U
&glob table_arh-fin-doc-schet-nal-attr 'arh-fin-doc-schet-nal-attr':U
&glob table_arh-fin-doc-schet-nal-obj 'arh-fin-doc-schet-nal-obj':U
&glob table_arh-fin-doc-schet-obj 'arh-fin-doc-schet-obj':U
&glob table_arh-fin-doc-schet-obj-attr 'arh-fin-doc-schet-obj-attr':U
&glob table_arh-fin-doc-schet-tax 'arh-fin-doc-schet-tax':U
&glob table_arh-fin-doc-schet-tax-attr 'arh-fin-doc-schet-tax-attr':U
&glob table_arh-fin-doc-schet-tax-nal 'arh-fin-doc-schet-tax-nal':U
&glob table_arh-fin-doc-schet-tax-obj 'arh-fin-doc-schet-tax-obj':U
&glob table_arh-fin-ob-contr 'arh-fin-ob-contr':U
&glob table_arh-fin-ob-contr-attr 'arh-fin-ob-contr-attr':U
&glob table_arh-fin-ob-contr-obj 'arh-fin-ob-contr-obj':U
&glob table_arh-fin-ob-contr-obj-attr 'arh-fin-ob-contr-obj-attr':U
&glob table_arh-trn-doc-contract 'arh-trn-doc-contract':U
&glob table_arh-trn-doc-contract-attr 'arh-trn-doc-contract-attr':U
&glob table_arh-wth-cli 'arh-wth-cli':U
&glob table_arh-wth-cli-attr 'arh-wth-cli-attr':U
&glob table_arh-wth-cli-doc 'arh-wth-cli-doc':U
&glob table_arh-wth-cli-doc-attr 'arh-wth-cli-doc-attr':U
&glob table_arh-wth-cli-tot 'arh-wth-cli-tot':U
&glob table_arh-wth-cli-tot-attr 'arh-wth-cli-tot-attr':U
&glob table_arh-wth-tot 'arh-wth-tot':U
&glob table_arh-wth-tot-attr 'arh-wth-tot-attr':U
&glob table_arh-wth-w-p 'arh-wth-w-p':U
&glob table_arh-wth-w-p-attr 'arh-wth-w-p-attr':U
&glob table_assortment-matrix 'assortment-matrix':U
&glob table_assortment-matrix-attr 'assortment-matrix-attr':U
&glob table_assortment-matrix-goods 'assortment-matrix-goods':U
&glob table_assortment-matrix-goods-attr 'assortment-matrix-goods-attr':U
&glob table_attr-prop 'attr-prop':U
&glob table_auto-section 'auto-section':U
&glob table_auto-section-attr 'auto-section-attr':U
&glob table_auto-section-table 'auto-section-table':U
&glob table_auto-tank 'auto-tank':U
&glob table_auto-tank-attr 'auto-tank-attr':U
&glob table_auto-tank-meas 'auto-tank-meas':U
&glob table_auto-tank-meas-attr 'auto-tank-meas-attr':U
&glob table_bar-code 'bar-code':U
&glob table_bar-code-attr 'bar-code-attr':U
&glob table_bar-code-obj-attr 'bar-code-obj-attr':U
&glob table_BatchProcess 'BatchProcess':U
&glob table_blob-bind 'blob-bind':U
&glob table_blob-data 'blob-data':U
&glob table_buyer-group 'buyer-group':U
&glob table_buyer-group-attr 'buyer-group-attr':U
&glob table_buyer-in-buyer-group 'buyer-in-buyer-group':U
&glob table_buyer-in-buyer-group-attr 'buyer-in-buyer-group-attr':U
&glob table_c-action-role 'c-action-role':U
&glob table_c-action-role-item 'c-action-role-item':U
&glob table_c-add-doc 'c-add-doc':U
&glob table_c-add-line 'c-add-line':U
&glob table_c-alc-sale-lic 'c-alc-sale-lic':U
&glob table_c-alc-sale-lic-attr 'c-alc-sale-lic-attr':U
&glob table_c-alc-sale-lic-type 'c-alc-sale-lic-type':U
&glob table_c-alc-supp-lic 'c-alc-supp-lic':U
&glob table_c-alc-supp-lic-attr 'c-alc-supp-lic-attr':U
&glob table_c-alc-supp-lic-type 'c-alc-supp-lic-type':U
&glob table_c-alc-type 'c-alc-type':U
&glob table_c-alc-type-attr 'c-alc-type-attr':U
&glob table_c-alc-type-gds 'c-alc-type-gds':U
&glob table_c-assortment-matrix 'c-assortment-matrix':U
&glob table_c-assortment-matrix-goods 'c-assortment-matrix-goods':U
&glob table_c-auto-section 'c-auto-section':U
&glob table_c-auto-section-attr 'c-auto-section-attr':U
&glob table_c-auto-section-table 'c-auto-section-table':U
&glob table_c-auto-tank 'c-auto-tank':U
&glob table_c-auto-tank-attr 'c-auto-tank-attr':U
&glob table_c-auto-tank-meas-attr 'c-auto-tank-meas-attr':U
&glob table_c-bar-code 'c-bar-code':U
&glob table_c-bar-code-attr 'c-bar-code-attr':U
&glob table_c-bar-code-obj-attr 'c-bar-code-obj-attr':U
&glob table_c-buyer-group 'c-buyer-group':U
&glob table_c-buyer-in-buyer-group 'c-buyer-in-buyer-group':U
&glob table_c-cash-desk 'c-cash-desk':U
&glob table_c-cash-desk-attr 'c-cash-desk-attr':U
&glob table_c-cash-pay 'c-cash-pay':U
&glob table_c-cash-pay-attr 'c-cash-pay-attr':U
&glob table_c-CashBook 'c-CashBook':U
&glob table_c-cashbook-head 'c-cashbook-head':U
&glob table_c-CashBookAttr 'c-CashBookAttr':U
&glob table_c-CashBookRule 'c-CashBookRule':U
&glob table_c-CashBookRuleAttr 'c-CashBookRuleAttr':U
&glob table_c-cbr-bank 'c-cbr-bank':U
&glob table_c-cbr-bank-attr 'c-cbr-bank-attr':U
&glob table_c-cd-clu 'c-cd-clu':U
&glob table_c-cd-dlu 'c-cd-dlu':U
&glob table_c-cd-doc 'c-cd-doc':U
&glob table_c-cd-doc-line 'c-cd-doc-line':U
&glob table_c-cd-grp 'c-cd-grp':U
&glob table_c-cd-plu 'c-cd-plu':U
&glob table_c-chk-discnt 'c-chk-discnt':U
&glob table_c-chk-doc 'c-chk-doc':U
&glob table_c-chk-doc-attr 'c-chk-doc-attr':U
&glob table_c-chk-gds 'c-chk-gds':U
&glob table_c-chk-pay 'c-chk-pay':U
&glob table_c-cli-grp 'c-cli-grp':U
&glob table_c-cli-grp-attr 'c-cli-grp-attr':U
&glob table_c-cli-hist 'c-cli-hist':U
&glob table_c-clients 'c-clients':U
&glob table_c-clients-attr 'c-clients-attr':U
&glob table_c-Code 'c-Code':U
&glob table_c-condition-keeping 'c-condition-keeping':U
&glob table_c-condition-keeping-attr 'c-condition-keeping-attr':U
&glob table_c-config 'c-config':U
&glob table_c-contract 'c-contract':U
&glob table_c-contract-line 'c-contract-line':U
&glob table_c-contract-specif 'c-contract-specif':U
&glob table_c-contract-specif-attr 'c-contract-specif-attr':U
&glob table_c-counter 'c-counter':U
&glob table_c-country 'c-country':U
&glob table_c-country-attr 'c-country-attr':U
&glob table_c-curr-accnt 'c-curr-accnt':U
&glob table_c-curr-bank 'c-curr-bank':U
&glob table_c-currency 'c-currency':U
&glob table_c-currency-attr 'c-currency-attr':U
&glob table_c-db 'c-db':U
&glob table_c-db-grp-obj-price 'c-db-grp-obj-price':U
&glob table_c-dc-hist 'c-dc-hist':U
&glob table_c-deliv-type-cond-keep 'c-deliv-type-cond-keep':U
&glob table_c-deliv-type-cond-keep-attr 'c-deliv-type-cond-keep-attr':U
&glob table_c-delivery-subject 'c-delivery-subject':U
&glob table_c-delivery-subject-attr 'c-delivery-subject-attr':U
&glob table_c-delivery-type 'c-delivery-type':U
&glob table_c-delivery-type-attr 'c-delivery-type-attr':U
&glob table_c-delivery-type-subject 'c-delivery-type-subject':U
&glob table_c-delivery-type-subject-attr 'c-delivery-type-subject-attr':U
&glob table_c-dis-card 'c-dis-card':U
&glob table_c-dis-card-long 'c-dis-card-long':U
&glob table_c-dis-card-long-attr 'c-dis-card-long-attr':U
&glob table_c-dis-card-mask 'c-dis-card-mask':U
&glob table_c-dis-card-mask-attr 'c-dis-card-mask-attr':U
&glob table_c-dis-card-property 'c-dis-card-property':U
&glob table_c-dis-card-type 'c-dis-card-type':U
&glob table_c-dis-card-type-attr 'c-dis-card-type-attr':U
&glob table_c-dis-cfg-rule 'c-dis-cfg-rule':U
&glob table_c-dis-cp-rule 'c-dis-cp-rule':U
&glob table_c-dis-dc-rule 'c-dis-dc-rule':U
&glob table_c-dis-dct-rule 'c-dis-dct-rule':U
&glob table_c-dis-gds-rule 'c-dis-gds-rule':U
&glob table_c-dis-grp-rule 'c-dis-grp-rule':U
&glob table_c-dis-host 'c-dis-host':U
&glob table_c-dis-obj 'c-dis-obj':U
&glob table_c-dis-rule 'c-dis-rule':U
&glob table_c-dis-rule-attr 'c-dis-rule-attr':U
&glob table_c-dis-some-rule 'c-dis-some-rule':U
&glob table_c-dis-thbj-rule 'c-dis-thbj-rule':U
&glob table_c-dis-time-rule 'c-dis-time-rule':U
&glob table_c-doc-attr 'c-doc-attr':U
&glob table_c-doc-fbr-gds 'c-doc-fbr-gds':U
&glob table_c-doc-line 'c-doc-line':U
&glob table_c-doc-line-attr 'c-doc-line-attr':U
&glob table_c-doc-line-sum 'c-doc-line-sum':U
&glob table_c-doc-pl 'c-doc-pl':U
&glob table_c-doc-pl-pump 'c-doc-pl-pump':U
&glob table_c-doc-prts 'c-doc-prts':U
&glob table_c-drt-prop 'c-drt-prop':U
&glob table_c-egais-clients 'c-egais-clients':U
&glob table_c-egais-gds 'c-egais-gds':U
&glob table_c-esys-datatype-exp 'c-esys-datatype-exp':U
&glob table_c-esys-datatype-imp 'c-esys-datatype-imp':U
&glob table_c-ex-mark 'c-ex-mark':U
&glob table_c-ext-artic 'c-ext-artic':U
&glob table_c-ext-artic-attr 'c-ext-artic-attr':U
&glob table_c-ext-classif 'c-ext-classif':U
&glob table_c-ext-system 'c-ext-system':U
&glob table_c-fbr-doc 'c-fbr-doc':U
&glob table_c-fbr-gds-grp 'c-fbr-gds-grp':U
&glob table_c-fbr-gds-grp-attr 'c-fbr-gds-grp-attr':U
&glob table_c-fbr-gds-grp-hist 'c-fbr-gds-grp-hist':U
&glob table_c-fbr-gds-obj 'c-fbr-gds-obj':U
&glob table_c-fbr-gds-obj-attr 'c-fbr-gds-obj-attr':U
&glob table_c-fbr-line 'c-fbr-line':U
&glob table_c-fbr-pln 'c-fbr-pln':U
&glob table_c-fbr-pln-line 'c-fbr-pln-line':U
&glob table_c-fbr-prn 'c-fbr-prn':U
&glob table_c-fbr-prn-gds 'c-fbr-prn-gds':U
&glob table_c-fbr-prn-grp 'c-fbr-prn-grp':U
&glob table_c-fin-bank 'c-fin-bank':U
&glob table_c-fin-bank-attr 'c-fin-bank-attr':U
&glob table_c-fin-code-an-uchet 'c-fin-code-an-uchet':U
&glob table_c-fin-code-cel-nazn 'c-fin-code-cel-nazn':U
&glob table_c-fin-code-cor-acc 'c-fin-code-cor-acc':U
&glob table_c-fin-connect 'c-fin-connect':U
&glob table_c-fin-doc 'c-fin-doc':U
&glob table_c-fin-doc-attr 'c-fin-doc-attr':U
&glob table_c-fin-doc-tax 'c-fin-doc-tax':U
&glob table_c-fin-gds-part 'c-fin-gds-part':U
&glob table_c-fin-ob 'c-fin-ob':U
&glob table_c-fin-ob-attr 'c-fin-ob-attr':U
&glob table_c-fin-ob-tax 'c-fin-ob-tax':U
&glob table_c-fin-schet 'c-fin-schet':U
&glob table_c-fin-schet-attr 'c-fin-schet-attr':U
&glob table_c-fin-statement 'c-fin-statement':U
&glob table_c-fin-statement-attr 'c-fin-statement-attr':U
&glob table_c-fin-statement-line 'c-fin-statement-line':U
&glob table_c-firm 'c-firm':U
&glob table_c-gds-add-charges 'c-gds-add-charges':U
&glob table_c-gds-add-charges-attr 'c-gds-add-charges-attr':U
&glob table_c-gds-dtl 'c-gds-dtl':U
&glob table_c-gds-dtl-attr 'c-gds-dtl-attr':U
&glob table_c-gds-grp 'c-gds-grp':U
&glob table_c-gds-grp-attr 'c-gds-grp-attr':U
&glob table_c-gds-grp-hist 'c-gds-grp-hist':U
&glob table_c-gds-grp-obj 'c-gds-grp-obj':U
&glob table_c-gds-hist 'c-gds-hist':U
&glob table_c-gds-host-attr 'c-gds-host-attr':U
&glob table_c-gds-mercury 'c-gds-mercury':U
&glob table_c-gds-obj 'c-gds-obj':U
&glob table_c-gds-obj-attr 'c-gds-obj-attr':U
&glob table_c-gds-obj-prop 'c-gds-obj-prop':U
&glob table_c-gds-obj-ref 'c-gds-obj-ref':U
&glob table_c-gds-prt 'c-gds-prt':U
&glob table_c-gds-prt-attr 'c-gds-prt-attr':U
&glob table_c-gds-season 'c-gds-season':U
&glob table_c-global-state 'c-global-state':U
&glob table_c-global-state-attr 'c-global-state-attr':U
&glob table_c-goods 'c-goods':U
&glob table_c-goods-attr 'c-goods-attr':U
&glob table_c-goods-attr-any 'c-goods-attr-any':U
&glob table_c-group-period-validity 'c-group-period-validity':U
&glob table_c-group-period-validity-attr 'c-group-period-validity-attr':U
&glob table_c-grp-obj-price 'c-grp-obj-price':U
&glob table_c-hist-nws-option 'c-hist-nws-option':U
&glob table_c-hist-nws-option-attr 'c-hist-nws-option-attr':U
&glob table_c-host-grp-obj-price 'c-host-grp-obj-price':U
&glob table_c-inkas 'c-inkas':U
&glob table_c-inkas-pay 'c-inkas-pay':U
&glob table_c-inkas-pay-desk 'c-inkas-pay-desk':U
&glob table_c-inkas-pay-wth 'c-inkas-pay-wth':U
&glob table_c-inv-line 'c-inv-line':U
&glob table_c-layout 'c-layout':U
&glob table_c-layout-attr 'c-layout-attr':U
&glob table_c-layout-elem 'c-layout-elem':U
&glob table_c-layout-elem-attr 'c-layout-elem-attr':U
&glob table_c-layout-elem-rule 'c-layout-elem-rule':U
&glob table_c-layout-elem-rule-attr 'c-layout-elem-rule-attr':U
&glob table_c-norm-loss 'c-norm-loss':U
&glob table_c-nozzle 'c-nozzle':U
&glob table_c-nozzle-attr 'c-nozzle-attr':U
&glob table_c-nzl-hist 'c-nzl-hist':U
&glob table_c-obj-grp-obj-price 'c-obj-grp-obj-price':U
&glob table_c-OperServ 'c-OperServ':U
&glob table_c-operServAttr 'c-operServAttr':U
&glob table_c-ord-doc 'c-ord-doc':U
&glob table_c-ord-doc-attr 'c-ord-doc-attr':U
&glob table_c-ord-dtl 'c-ord-dtl':U
&glob table_c-ord-line 'c-ord-line':U
&glob table_c-ord-line-attr 'c-ord-line-attr':U
&glob table_c-parts 'c-parts':U
&glob table_c-parts-add 'c-parts-add':U
&glob table_c-parts-attr 'c-parts-attr':U
&glob table_c-parts-obj-attr 'c-parts-obj-attr':U
&glob table_c-parts-root 'c-parts-root':U
&glob table_c-pay-type 'c-pay-type':U
&glob table_c-pay-type-attr 'c-pay-type-attr':U
&glob table_c-payment-attr 'c-payment-attr':U
&glob table_c-person 'c-person':U
&glob table_c-pl-gds 'c-pl-gds':U
&glob table_c-pl-gds-attr 'c-pl-gds-attr':U
&glob table_c-pl-gds-obj 'c-pl-gds-obj':U
&glob table_c-pl-gds-pump 'c-pl-gds-pump':U
&glob table_c-pl-gds-pump-attr 'c-pl-gds-pump-attr':U
&glob table_c-pl-level 'c-pl-level':U
&glob table_c-pl-level-attr 'c-pl-level-attr':U
&glob table_c-pl-pump 'c-pl-pump':U
&glob table_c-pl-pump-attr 'c-pl-pump-attr':U
&glob table_c-pl-pump-nozzle 'c-pl-pump-nozzle':U
&glob table_c-pl-pump-nozzle-attr 'c-pl-pump-nozzle-attr':U
&glob table_c-place 'c-place':U
&glob table_c-place-attr 'c-place-attr':U
&glob table_c-place-io 'c-place-io':U
&glob table_c-plc-hist 'c-plc-hist':U
&glob table_c-pmp-hist 'c-pmp-hist':U
&glob table_c-point-io 'c-point-io':U
&glob table_c-point-place-rel 'c-point-place-rel':U
&glob table_c-point-point-rel 'c-point-point-rel':U
&glob table_c-price-doc 'c-price-doc':U
&glob table_c-price-doc-forming 'c-price-doc-forming':U
&glob table_c-price-doc-forming-attr 'c-price-doc-forming-attr':U
&glob table_c-price-doc-forming-gds 'c-price-doc-forming-gds':U
&glob table_c-price-doc-forming-gds-qnty 'c-price-doc-forming-gds-qnty':U
&glob table_c-price-doc-forming-gds-sum 'c-price-doc-forming-gds-sum':U
&glob table_c-price-doc-forming-gds-tnv 'c-price-doc-forming-gds-tnv':U
&glob table_c-price-doc-forming-gdsattr 'c-price-doc-forming-gdsattr':U
&glob table_c-price-list 'c-price-list':U
&glob table_c-price-list-attr 'c-price-list-attr':U
&glob table_c-price-list-type 'c-price-list-type':U
&glob table_c-price-list-type-attr 'c-price-list-type-attr':U
&glob table_c-price-list-type-cash-pay 'c-price-list-type-cash-pay':U
&glob table_c-price-list-type-cassa 'c-price-list-type-cassa':U
&glob table_c-price-list-type-gds-grp 'c-price-list-type-gds-grp':U
&glob table_c-price-list-type-pay-type 'c-price-list-type-pay-type':U
&glob table_c-prod-bc 'c-prod-bc':U
&glob table_c-prod-bc-attr 'c-prod-bc-attr':U
&glob table_c-prod-bc-db-attr 'c-prod-bc-db-attr':U
&glob table_c-profile-by-profile 'c-profile-by-profile':U
&glob table_c-promo-head 'c-promo-head':U
&glob table_c-promo-schedule 'c-promo-schedule':U
&glob table_c-promo-schedule-week 'c-promo-schedule-week':U
&glob table_c-PromoAction 'c-PromoAction':U
&glob table_c-PromoAttr 'c-PromoAttr':U
&glob table_c-PromoCriterion 'c-PromoCriterion':U
&glob table_c-PromoGift 'c-PromoGift':U
&glob table_c-PromoGoods 'c-PromoGoods':U
&glob table_c-PromoObject 'c-PromoObject':U
&glob table_c-prop-head 'c-prop-head':U
&glob table_c-prop-ref 'c-prop-ref':U
&glob table_c-prop-ruleset 'c-prop-ruleset':U
&glob table_c-prop-script 'c-prop-script':U
&glob table_c-pscript-ruleset 'c-pscript-ruleset':U
&glob table_c-pump 'c-pump':U
&glob table_c-pump-attr 'c-pump-attr':U
&glob table_c-pump-nozzle 'c-pump-nozzle':U
&glob table_c-pump-nozzle-attr 'c-pump-nozzle-attr':U
&glob table_c-qnty-group 'c-qnty-group':U
&glob table_c-qnty-in-qnty-group 'c-qnty-in-qnty-group':U
&glob table_c-recipe 'c-recipe':U
&glob table_c-recipe-develop 'c-recipe-develop':U
&glob table_c-recipe-gds 'c-recipe-gds':U
&glob table_c-recipe-hist 'c-recipe-hist':U
&glob table_c-regions 'c-regions':U
&glob table_c-rp-by-call 'c-rp-by-call':U
&glob table_c-rp-rule-param 'c-rp-rule-param':U
&glob table_c-rule 'c-rule':U
&glob table_c-rule-by-call 'c-rule-by-call':U
&glob table_c-rule-by-profile 'c-rule-by-profile':U
&glob table_c-rule-by-set 'c-rule-by-set':U
&glob table_c-rule-call-param 'c-rule-call-param':U
&glob table_c-rule-process 'c-rule-process':U
&glob table_c-rule-profile 'c-rule-profile':U
&glob table_c-ruledict 'c-ruledict':U
&glob table_c-ruledict-param 'c-ruledict-param':U
&glob table_c-ruleset 'c-ruleset':U
&glob table_c-rvs-doc 'c-rvs-doc':U
&glob table_c-rvs-line 'c-rvs-line':U
&glob table_c-rvs-line-pump 'c-rvs-line-pump':U
&glob table_c-s-coeff 'c-s-coeff':U
&glob table_c-sale-doc 'c-sale-doc':U
&glob table_c-scales 'c-scales':U
&glob table_c-scales-attr 'c-scales-attr':U
&glob table_c-scales-gds 'c-scales-gds':U
&glob table_c-scales-grp 'c-scales-grp':U
&glob table_c-schet-fact-doc 'c-schet-fact-doc':U
&glob table_c-schet-fact-line 'c-schet-fact-line':U
&glob table_c-season 'c-season':U
&glob table_c-sert 'c-sert':U
&glob table_c-shift-attr 'c-shift-attr':U
&glob table_c-shift-obj 'c-shift-obj':U
&glob table_c-shift-staff 'c-shift-staff':U
&glob table_c-shop 'c-shop':U
&glob table_c-sht-hist 'c-sht-hist':U
&glob table_c-sr-izmerenia 'c-sr-izmerenia':U
&glob table_c-sr-izmerenia-attr 'c-sr-izmerenia-attr':U
&glob table_c-staff 'c-staff':U
&glob table_c-stop-list 'c-stop-list':U
&glob table_c-stop-list-line 'c-stop-list-line':U
&glob table_c-store 'c-store':U
&glob table_c-sum-group 'c-sum-group':U
&glob table_c-sum-grp 'c-sum-grp':U
&glob table_c-sum-grp-obj 'c-sum-grp-obj':U
&glob table_c-sum-in-sum-group 'c-sum-in-sum-group':U
&glob table_c-sysconf 'c-sysconf':U
&glob table_c-table-bind 'c-table-bind':U
&glob table_c-tare 'c-tare':U
&glob table_c-tax 'c-tax':U
&glob table_c-tax-hist 'c-tax-hist':U
&glob table_c-tax-rate 'c-tax-rate':U
&glob table_c-tax-rate-gds-grp 'c-tax-rate-gds-grp':U
&glob table_c-tax-units 'c-tax-units':U
&glob table_c-tech-prol-pwd 'c-tech-prol-pwd':U
&glob table_c-thbj-attr 'c-thbj-attr':U
&glob table_c-tnv-in-turnover-group 'c-tnv-in-turnover-group':U
&glob table_c-trn-doc 'c-trn-doc':U
&glob table_c-trn-doc-sum 'c-trn-doc-sum':U
&glob table_c-trn-reason 'c-trn-reason':U
&glob table_c-trn-reason-host 'c-trn-reason-host':U
&glob table_c-trn-reason-obj 'c-trn-reason-obj':U
&glob table_c-trn-rsn-attr 'c-trn-rsn-attr':U
&glob table_c-turnover-group 'c-turnover-group':U
&glob table_c-units 'c-units':U
&glob table_c-user-account 'c-user-account':U
&glob table_c-user-log 'c-user-log':U
&glob table_c-user-login 'c-user-login':U
&glob table_c-usr-hist 'c-usr-hist':U
&glob table_c-utd 'c-utd':U
&glob table_c-utd-attr 'c-utd-attr':U
&glob table_c-utd-err 'c-utd-err':U
&glob table_c-utd-err-attr 'c-utd-err-attr':U
&glob table_c-utd-head 'c-utd-head':U
&glob table_c-utd-lines 'c-utd-lines':U
&glob table_c-utd-lines-attr 'c-utd-lines-attr':U
&glob table_c-utd-marking-lines 'c-utd-marking-lines':U
&glob table_c-utd-marking-lines-attr 'c-utd-marking-lines-attr':U
&glob table_c-var-deliv-gr-per-val 'c-var-deliv-gr-per-val':U
&glob table_c-variant-delivery 'c-variant-delivery':U
&glob table_c-varianty-delivery-gds-obj 'c-varianty-delivery-gds-obj':U
&glob table_c-vsd 'c-vsd':U
&glob table_c-wealth 'c-wealth':U
&glob table_c-wi-mode 'c-wi-mode':U
&glob table_c-wi-mode-attr 'c-wi-mode-attr':U
&glob table_c-wth-doc 'c-wth-doc':U
&glob table_c-wth-dtl 'c-wth-dtl':U
&glob table_c-wth-gds 'c-wth-gds':U
&glob table_c-wth-gds-attr 'c-wth-gds-attr':U
&glob table_c-wth-hist 'c-wth-hist':U
&glob table_c-wth-line 'c-wth-line':U
&glob table_c-wth-obj 'c-wth-obj':U
&glob table_c-wth-par 'c-wth-par':U
&glob table_c-wth-parts 'c-wth-parts':U
&glob table_c-wth-place 'c-wth-place':U
&glob table_c-wth-pobj 'c-wth-pobj':U
&glob table_c-wth-ser 'c-wth-ser':U
&glob table_c-wth-ser-attr 'c-wth-ser-attr':U
&glob table_cash-desk 'cash-desk':U
&glob table_cash-desk-attr 'cash-desk-attr':U
&glob table_Cash-param-hist 'Cash-param-hist':U
&glob table_cash-pay 'cash-pay':U
&glob table_cash-pay-attr 'cash-pay-attr':U
&glob table_CashBook 'CashBook':U
&glob table_CashBookAttr 'CashBookAttr':U
&glob table_CashBookRule 'CashBookRule':U
&glob table_CashBookRuleAttr 'CashBookRuleAttr':U
&glob table_cbr-bank 'cbr-bank':U
&glob table_cbr-bank-attr 'cbr-bank-attr':U
&glob table_cd-clu 'cd-clu':U
&glob table_cd-clu-attr 'cd-clu-attr':U
&glob table_cd-dlu 'cd-dlu':U
&glob table_cd-dlu-attr 'cd-dlu-attr':U
&glob table_cd-doc 'cd-doc':U
&glob table_cd-doc-attr 'cd-doc-attr':U
&glob table_cd-doc-line 'cd-doc-line':U
&glob table_cd-doc-line-attr 'cd-doc-line-attr':U
&glob table_cd-event-log 'cd-event-log':U
&glob table_cd-event-log-attr 'cd-event-log-attr':U
&glob table_cd-events 'cd-events':U
&glob table_cd-events-attr 'cd-events-attr':U
&glob table_cd-grp 'cd-grp':U
&glob table_cd-grp-attr 'cd-grp-attr':U
&glob table_cd-plu 'cd-plu':U
&glob table_cd-plu-attr 'cd-plu-attr':U
&glob table_cd-trans 'cd-trans':U
&glob table_cd-trans-attr 'cd-trans-attr':U
&glob table_cd-video-link 'cd-video-link':U
&glob table_cd-video-link-attr 'cd-video-link-attr':U
&glob table_chk-discnt 'chk-discnt':U
&glob table_chk-discnt-attr 'chk-discnt-attr':U
&glob table_chk-doc 'chk-doc':U
&glob table_chk-doc-attr 'chk-doc-attr':U
&glob table_chk-gds 'chk-gds':U
&glob table_chk-gds-attr 'chk-gds-attr':U
&glob table_chk-gds-pay 'chk-gds-pay':U
&glob table_chk-pay 'chk-pay':U
&glob table_chk-pay-attr 'chk-pay-attr':U
&glob table_chk-slip-head 'chk-slip-head':U
&glob table_chk-slip-string 'chk-slip-string':U
&glob table_cli-art 'cli-art':U
&glob table_cli-art-attr 'cli-art-attr':U
&glob table_cli-gds 'cli-gds':U
&glob table_cli-gds-attr 'cli-gds-attr':U
&glob table_cli-grp 'cli-grp':U
&glob table_cli-grp-attr 'cli-grp-attr':U
&glob table_clients 'clients':U
&glob table_clients-attr 'clients-attr':U
&glob table_clob-bind 'clob-bind':U
&glob table_clob-data 'clob-data':U
&glob table_Code 'Code':U
&glob table_code-range 'code-range':U
&glob table_condition-keeping 'condition-keeping':U
&glob table_condition-keeping-attr 'condition-keeping-attr':U
&glob table_config 'config':U
&glob table_contract 'contract':U
&glob table_contract-attr 'contract-attr':U
&glob table_contract-line 'contract-line':U
&glob table_contract-line-attr 'contract-line-attr':U
&glob table_contract-specif 'contract-specif':U
&glob table_contract-specif-attr 'contract-specif-attr':U
&glob table_counter 'counter':U
&glob table_country 'country':U
&glob table_country-attr 'country-attr':U
&glob table_criterion-analysis 'criterion-analysis':U
&glob table_criterion-analysis-attr 'criterion-analysis-attr':U
&glob table_cshr-month 'cshr-month':U
&glob table_cshr-month-attr 'cshr-month-attr':U
&glob table_curr-accnt 'curr-accnt':U
&glob table_curr-accnt-attr 'curr-accnt-attr':U
&glob table_curr-bank 'curr-bank':U
&glob table_curr-bank-attr 'curr-bank-attr':U
&glob table_curr-shop 'curr-shop':U
&glob table_curr-shop-attr 'curr-shop-attr':U
&glob table_currency 'currency':U
&glob table_currency-attr 'currency-attr':U
&glob table_custom-labels 'custom-labels':U
&glob table_datatype-exp 'datatype-exp':U
&glob table_datatype-exp-attr 'datatype-exp-attr':U
&glob table_datatype-imp 'datatype-imp':U
&glob table_datatype-imp-attr 'datatype-imp-attr':U
&glob table_datatype-table 'datatype-table':U
&glob table_datatype-table-exp 'datatype-table-exp':U
&glob table_datatype-table-field 'datatype-table-field':U
&glob table_datatype-table-field-exp 'datatype-table-field-exp':U
&glob table_datatype-table-field-imp 'datatype-table-field-imp':U
&glob table_datatype-table-imp 'datatype-table-imp':U
&glob table_db 'db':U
&glob table_db-attr 'db-attr':U
&glob table_db-filter 'db-filter':U
&glob table_db-filter-attr 'db-filter-attr':U
&glob table_db-grp-obj-price 'db-grp-obj-price':U
&glob table_db-grp-obj-price-attr 'db-grp-obj-price-attr':U
&glob table_db-info 'db-info':U
&glob table_db-rec-attr 'db-rec-attr':U
&glob table_db-status 'db-status':U
&glob table_db-status-attr 'db-status-attr':U
&glob table_db-usr-flt 'db-usr-flt':U
&glob table_db-usr-flt-attr 'db-usr-flt-attr':U
&glob table_deliv-type-cond-keep 'deliv-type-cond-keep':U
&glob table_deliv-type-cond-keep-attr 'deliv-type-cond-keep-attr':U
&glob table_delivery-subject 'delivery-subject':U
&glob table_delivery-subject-attr 'delivery-subject-attr':U
&glob table_delivery-type 'delivery-type':U
&glob table_delivery-type-attr 'delivery-type-attr':U
&glob table_delivery-type-subject 'delivery-type-subject':U
&glob table_delivery-type-subject-attr 'delivery-type-subject-attr':U
&glob table_devisPC 'devisPC':U
&glob table_devisPC-attr 'devisPC-attr':U
&glob table_dis-card 'dis-card':U
&glob table_dis-card-long 'dis-card-long':U
&glob table_dis-card-long-attr 'dis-card-long-attr':U
&glob table_dis-card-mask 'dis-card-mask':U
&glob table_dis-card-mask-attr 'dis-card-mask-attr':U
&glob table_dis-card-property 'dis-card-property':U
&glob table_dis-card-type 'dis-card-type':U
&glob table_dis-card-type-attr 'dis-card-type-attr':U
&glob table_dis-cfg-rule 'dis-cfg-rule':U
&glob table_dis-cfg-rule-attr 'dis-cfg-rule-attr':U
&glob table_dis-cp-rule 'dis-cp-rule':U
&glob table_dis-cp-rule-attr 'dis-cp-rule-attr':U
&glob table_dis-dc-rule 'dis-dc-rule':U
&glob table_dis-dc-rule-attr 'dis-dc-rule-attr':U
&glob table_dis-dct-rule 'dis-dct-rule':U
&glob table_dis-dct-rule-attr 'dis-dct-rule-attr':U
&glob table_dis-gds-rule 'dis-gds-rule':U
&glob table_dis-gds-rule-attr 'dis-gds-rule-attr':U
&glob table_dis-grp-rule 'dis-grp-rule':U
&glob table_dis-grp-rule-attr 'dis-grp-rule-attr':U
&glob table_dis-host 'dis-host':U
&glob table_dis-obj 'dis-obj':U
&glob table_dis-rule 'dis-rule':U
&glob table_dis-rule-attr 'dis-rule-attr':U
&glob table_dis-some-rule 'dis-some-rule':U
&glob table_dis-some-rule-attr 'dis-some-rule-attr':U
&glob table_dis-thbj-rule 'dis-thbj-rule':U
&glob table_dis-thbj-rule-attr 'dis-thbj-rule-attr':U
&glob table_dis-time-rule 'dis-time-rule':U
&glob table_dis-time-rule-attr 'dis-time-rule-attr':U
&glob table_dish-grp 'dish-grp':U
&glob table_dish-grp-attr 'dish-grp-attr':U
&glob table_doc-abc-def 'doc-abc-def':U
&glob table_doc-abc-def-attr 'doc-abc-def-attr':U
&glob table_doc-abc-def-doc 'doc-abc-def-doc':U
&glob table_doc-abc-def-doc-attr 'doc-abc-def-doc-attr':U
&glob table_doc-abc-def-obj 'doc-abc-def-obj':U
&glob table_doc-abc-def-obj-attr 'doc-abc-def-obj-attr':U
&glob table_doc-attr 'doc-attr':U
&glob table_doc-fact-num 'doc-fact-num':U
&glob table_doc-fact-num-attr 'doc-fact-num-attr':U
&glob table_doc-fbr-gds 'doc-fbr-gds':U
&glob table_doc-fbr-gds-attr 'doc-fbr-gds-attr':U
&glob table_doc-filter 'doc-filter':U
&glob table_doc-filter-attr 'doc-filter-attr':U
&glob table_doc-filter-head 'doc-filter-head':U
&glob table_doc-filter-head-attr 'doc-filter-head-attr':U
&glob table_doc-line 'doc-line':U
&glob table_doc-line-attr 'doc-line-attr':U
&glob table_doc-line-sum 'doc-line-sum':U
&glob table_doc-pl 'doc-pl':U
&glob table_doc-pl-attr 'doc-pl-attr':U
&glob table_doc-pl-pump 'doc-pl-pump':U
&glob table_doc-pl-pump-attr 'doc-pl-pump-attr':U
&glob table_doc-prts 'doc-prts':U
&glob table_doc-prts-attr 'doc-prts-attr':U
&glob table_doc-xyz-def 'doc-xyz-def':U
&glob table_doc-xyz-def-attr 'doc-xyz-def-attr':U
&glob table_doc-xyz-def-doc 'doc-xyz-def-doc':U
&glob table_doc-xyz-def-doc-attr 'doc-xyz-def-doc-attr':U
&glob table_doc-xyz-def-obj 'doc-xyz-def-obj':U
&glob table_doc-xyz-def-obj-attr 'doc-xyz-def-obj-attr':U
&glob table_drt-prop 'drt-prop':U
&glob table_edi-status 'edi-status':U
&glob table_egais-clients 'egais-clients':U
&glob table_egais-gds 'egais-gds':U
&glob table_esys-all-attr 'esys-all-attr':U
&glob table_esys-datatype-exp 'esys-datatype-exp':U
&glob table_esys-datatype-imp 'esys-datatype-imp':U
&glob table_esys-pck-keys 'esys-pck-keys':U
&glob table_esys-pck-rcvd 'esys-pck-rcvd':U
&glob table_esys-pck-sent 'esys-pck-sent':U
&glob table_esys-route 'esys-route':U
&glob table_esys-route-dump 'esys-route-dump':U
&glob table_ex-mark 'ex-mark':U
&glob table_ex-mark-attr 'ex-mark-attr':U
&glob table_ext-artic 'ext-artic':U
&glob table_ext-artic-attr 'ext-artic-attr':U
&glob table_ext-artic-db 'ext-artic-db':U
&glob table_ext-artic-db-attr 'ext-artic-db-attr':U
&glob table_ext-artic-host 'ext-artic-host':U
&glob table_ext-artic-host-attr 'ext-artic-host-attr':U
&glob table_ext-artic-obj 'ext-artic-obj':U
&glob table_ext-artic-obj-attr 'ext-artic-obj-attr':U
&glob table_ext-classif 'ext-classif':U
&glob table_ext-classif-attr 'ext-classif-attr':U
&glob table_ext-file 'ext-file':U
&glob table_ext-file-attr 'ext-file-attr':U
&glob table_ext-file-line 'ext-file-line':U
&glob table_ext-file-line-attr 'ext-file-line-attr':U
&glob table_ext-file-par 'ext-file-par':U
&glob table_ext-file-par-attr 'ext-file-par-attr':U
&glob table_ext-system 'ext-system':U
&glob table_ext-system-attr 'ext-system-attr':U
&glob table_factur-connect 'factur-connect':U
&glob table_factur-connect-attr 'factur-connect-attr':U
&glob table_factur-connect-line 'factur-connect-line':U
&glob table_factur-connect-line-attr 'factur-connect-line-attr':U
&glob table_fbr-doc 'fbr-doc':U
&glob table_fbr-gds-grp 'fbr-gds-grp':U
&glob table_fbr-gds-grp-attr 'fbr-gds-grp-attr':U
&glob table_fbr-gds-obj 'fbr-gds-obj':U
&glob table_fbr-gds-obj-attr 'fbr-gds-obj-attr':U
&glob table_fbr-history 'fbr-history':U
&glob table_fbr-line 'fbr-line':U
&glob table_fbr-pln 'fbr-pln':U
&glob table_fbr-pln-line 'fbr-pln-line':U
&glob table_fbr-prn 'fbr-prn':U
&glob table_fbr-prn-attr 'fbr-prn-attr':U
&glob table_fbr-prn-gds 'fbr-prn-gds':U
&glob table_fbr-prn-gds-attr 'fbr-prn-gds-attr':U
&glob table_fbr-prn-grp 'fbr-prn-grp':U
&glob table_fbr-prn-grp-attr 'fbr-prn-grp-attr':U
&glob table_fbr-recipe 'fbr-recipe':U
&glob table_fbr-recipe-gds 'fbr-recipe-gds':U
&glob table_feature 'feature':U
&glob table_feature-attr 'feature-attr':U
&glob table_feature-scale 'feature-scale':U
&glob table_feature-scale-attr 'feature-scale-attr':U
&glob table_Filter 'Filter':U
&glob table_Filter-attr 'Filter-attr':U
&glob table_fin-bank 'fin-bank':U
&glob table_fin-bank-attr 'fin-bank-attr':U
&glob table_fin-code-an-uchet 'fin-code-an-uchet':U
&glob table_fin-code-an-uchet-attr 'fin-code-an-uchet-attr':U
&glob table_fin-code-cel-nazn 'fin-code-cel-nazn':U
&glob table_fin-code-cel-nazn-attr 'fin-code-cel-nazn-attr':U
&glob table_fin-code-cor-acc 'fin-code-cor-acc':U
&glob table_fin-code-cor-acc-attr 'fin-code-cor-acc-attr':U
&glob table_fin-connect 'fin-connect':U
&glob table_fin-connect-attr 'fin-connect-attr':U
&glob table_fin-doc 'fin-doc':U
&glob table_fin-doc-attr 'fin-doc-attr':U
&glob table_fin-doc-cor-acc-lk 'fin-doc-cor-acc-lk':U
&glob table_fin-doc-cor-acc-lk-attr 'fin-doc-cor-acc-lk-attr':U
&glob table_fin-doc-obj 'fin-doc-obj':U
&glob table_fin-doc-obj-attr 'fin-doc-obj-attr':U
&glob table_fin-doc-schet-lk 'fin-doc-schet-lk':U
&glob table_fin-doc-schet-lk-attr 'fin-doc-schet-lk-attr':U
&glob table_fin-doc-tax 'fin-doc-tax':U
&glob table_fin-doc-tax-attr 'fin-doc-tax-attr':U
&glob table_fin-gds-part 'fin-gds-part':U
&glob table_fin-gds-part-attr 'fin-gds-part-attr':U
&glob table_fin-ob 'fin-ob':U
&glob table_fin-ob-attr 'fin-ob-attr':U
&glob table_fin-ob-before 'fin-ob-before':U
&glob table_fin-ob-cor-acc-lk 'fin-ob-cor-acc-lk':U
&glob table_fin-ob-cor-acc-lk-attr 'fin-ob-cor-acc-lk-attr':U
&glob table_fin-ob-schet-lk 'fin-ob-schet-lk':U
&glob table_fin-ob-schet-lk-attr 'fin-ob-schet-lk-attr':U
&glob table_fin-ob-tax 'fin-ob-tax':U
&glob table_fin-ob-tax-attr 'fin-ob-tax-attr':U
&glob table_fin-ob-tax-before 'fin-ob-tax-before':U
&glob table_fin-ob-trn 'fin-ob-trn':U
&glob table_fin-ob-trn-attr 'fin-ob-trn-attr':U
&glob table_fin-schet 'fin-schet':U
&glob table_fin-schet-attr 'fin-schet-attr':U
&glob table_fin-statement 'fin-statement':U
&glob table_fin-statement-attr 'fin-statement-attr':U
&glob table_fin-statement-line 'fin-statement-line':U
&glob table_fin-statement-line-attr 'fin-statement-line-attr':U
&glob table_firm 'firm':U
&glob table_gds-add-charges 'gds-add-charges':U
&glob table_gds-add-charges-attr 'gds-add-charges-attr':U
&glob table_gds-dtl 'gds-dtl':U
&glob table_gds-dtl-attr 'gds-dtl-attr':U
&glob table_gds-grp 'gds-grp':U
&glob table_gds-grp-attr 'gds-grp-attr':U
&glob table_gds-grp-obj 'gds-grp-obj':U
&glob table_gds-grp-obj-attr 'gds-grp-obj-attr':U
&glob table_gds-host-attr 'gds-host-attr':U
&glob table_gds-mercury 'gds-mercury':U
&glob table_gds-mercury-attr 'gds-mercury-attr':U
&glob table_gds-obj 'gds-obj':U
&glob table_gds-obj-attr 'gds-obj-attr':U
&glob table_gds-obj-flag 'gds-obj-flag':U
&glob table_gds-obj-flag-attr 'gds-obj-flag-attr':U
&glob table_gds-obj-prop 'gds-obj-prop':U
&glob table_gds-obj-prop-attr 'gds-obj-prop-attr':U
&glob table_gds-prt 'gds-prt':U
&glob table_gds-prt-attr 'gds-prt-attr':U
&glob table_gds-season 'gds-season':U
&glob table_gds-season-attr 'gds-season-attr':U
&glob table_gen-attr 'gen-attr':U
&glob table_global-state 'global-state':U
&glob table_global-state-attr 'global-state-attr':U
&glob table_goods 'goods':U
&glob table_goods-attr 'goods-attr':U
&glob table_group-period-validity 'group-period-validity':U
&glob table_group-period-validity-attr 'group-period-validity-attr':U
&glob table_grp-obj-price 'grp-obj-price':U
&glob table_grp-obj-price-attr 'grp-obj-price-attr':U
&glob table_h-route 'h-route':U
&glob table_h-route-dump 'h-route-dump':U
&glob table_hist-nws-option 'hist-nws-option':U
&glob table_hist-nws-option-attr 'hist-nws-option-attr':U
&glob table_hold-attr 'hold-attr':U
&glob table_hold-gds-grp 'hold-gds-grp':U
&glob table_hold-gds-grp-attr 'hold-gds-grp-attr':U
&glob table_hold-goods 'hold-goods':U
&glob table_hold-goods-attr 'hold-goods-attr':U
&glob table_hold-purch 'hold-purch':U
&glob table_hold-purch-attr 'hold-purch-attr':U
&glob table_hold-purch-grp 'hold-purch-grp':U
&glob table_hold-purch-grp-attr 'hold-purch-grp-attr':U
&glob table_hold-purch-supp 'hold-purch-supp':U
&glob table_hold-purch-supp-attr 'hold-purch-supp-attr':U
&glob table_hold-purch-supp-gds 'hold-purch-supp-gds':U
&glob table_hold-purch-supp-gds-attr 'hold-purch-supp-gds-attr':U
&glob table_hold-sale 'hold-sale':U
&glob table_hold-sale-attr 'hold-sale-attr':U
&glob table_hold-sale-grp 'hold-sale-grp':U
&glob table_hold-sale-grp-attr 'hold-sale-grp-attr':U
&glob table_hold-time 'hold-time':U
&glob table_hold-time-attr 'hold-time-attr':U
&glob table_hold-trn 'hold-trn':U
&glob table_hold-trn-attr 'hold-trn-attr':U
&glob table_host-grp-obj-price 'host-grp-obj-price':U
&glob table_host-grp-obj-price-attr 'host-grp-obj-price-attr':U
&glob table_host-lk 'host-lk':U
&glob table_host-lk-attr 'host-lk-attr':U
&glob table_icnt-doc 'icnt-doc':U
&glob table_icnt-line 'icnt-line':U
&glob table_inkas 'inkas':U
&glob table_inkas-pay 'inkas-pay':U
&glob table_inkas-pay-attr 'inkas-pay-attr':U
&glob table_inkas-pay-desk 'inkas-pay-desk':U
&glob table_inkas-pay-desk-attr 'inkas-pay-desk-attr':U
&glob table_inkas-pay-wth 'inkas-pay-wth':U
&glob table_inv-doc 'inv-doc':U
&glob table_inv-doc-attr 'inv-doc-attr':U
&glob table_inv-line 'inv-line':U
&glob table_inv-line-attr 'inv-line-attr':U
&glob table_lang 'lang':U
&glob table_lang-attr 'lang-attr':U
&glob table_layout 'layout':U
&glob table_layout-attr 'layout-attr':U
&glob table_layout-elem 'layout-elem':U
&glob table_layout-elem-attr 'layout-elem-attr':U
&glob table_layout-elem-rule 'layout-elem-rule':U
&glob table_layout-elem-rule-attr 'layout-elem-rule-attr':U
&glob table_lvl-name 'lvl-name':U
&glob table_lvl-name-attr 'lvl-name-attr':U
&glob table_marking 'marking':U
&glob table_marking-attr 'marking-attr':U
&glob table_marking-chk 'marking-chk':U
&glob table_marking-lines 'marking-lines':U
&glob table_menu-group 'menu-group':U
&glob table_menu-group-attr 'menu-group-attr':U
&glob table_menu-head 'menu-head':U
&glob table_menu-head-attr 'menu-head-attr':U
&glob table_menu-item 'menu-item':U
&glob table_menu-item-attr 'menu-item-attr':U
&glob table_menu-item-group 'menu-item-group':U
&glob table_menu-item-group-attr 'menu-item-group-attr':U
&glob table_menu-user 'menu-user':U
&glob table_menu-user-attr 'menu-user-attr':U
&glob table_menu-user-call 'menu-user-call':U
&glob table_menu-user-call-attr 'menu-user-call-attr':U
&glob table_norm-loss 'norm-loss':U
&glob table_nozzle 'nozzle':U
&glob table_nozzle-attr 'nozzle-attr':U
&glob table_nws-doc-hist 'nws-doc-hist':U
&glob table_nws-doc-hist-attr 'nws-doc-hist-attr':U
&glob table_nws-last-rec 'nws-last-rec':U
&glob table_nws-last-rec-attr 'nws-last-rec-attr':U
&glob table_nws-outline 'nws-outline':U
&glob table_obj-date 'obj-date':U
&glob table_obj-grp-obj-price 'obj-grp-obj-price':U
&glob table_obj-grp-obj-price-attr 'obj-grp-obj-price-attr':U
&glob table_OperServ 'OperServ':U
&glob table_OperServAttr 'OperServAttr':U
&glob table_ord-blank 'ord-blank':U
&glob table_ord-blank-attr 'ord-blank-attr':U
&glob table_ord-chain 'ord-chain':U
&glob table_ord-chain-attr 'ord-chain-attr':U
&glob table_ord-cons 'ord-cons':U
&glob table_ord-cons-attr 'ord-cons-attr':U
&glob table_ord-cons-line-attr 'ord-cons-line-attr':U
&glob table_ord-doc 'ord-doc':U
&glob table_ord-doc-attr 'ord-doc-attr':U
&glob table_ord-doc-rcv 'ord-doc-rcv':U
&glob table_ord-dtl 'ord-dtl':U
&glob table_ord-dtl-attr 'ord-dtl-attr':U
&glob table_ord-dtl-cons 'ord-dtl-cons':U
&glob table_ord-dtl-rcv 'ord-dtl-rcv':U
&glob table_ord-gds-cons 'ord-gds-cons':U
&glob table_ord-line 'ord-line':U
&glob table_ord-line-attr 'ord-line-attr':U
&glob table_ord-line-rcv 'ord-line-rcv':U
&glob table_ord-rcv-attr 'ord-rcv-attr':U
&glob table_ord-rcv-line-attr 'ord-rcv-line-attr':U
&glob table_ot-line 'ot-line':U
&glob table_ot-line-attr 'ot-line-attr':U
&glob table_ot-supp-line 'ot-supp-line':U
&glob table_ot-supp-line-attr 'ot-supp-line-attr':U
&glob table_ot-supp-tot 'ot-supp-tot':U
&glob table_ot-supp-tot-attr 'ot-supp-tot-attr':U
&glob table_ot-tot 'ot-tot':U
&glob table_ot-tot-attr 'ot-tot-attr':U
&glob table_parts 'parts':U
&glob table_parts-add 'parts-add':U
&glob table_parts-add-attr 'parts-add-attr':U
&glob table_parts-attr 'parts-attr':U
&glob table_parts-obj-attr 'parts-obj-attr':U
&glob table_parts-root 'parts-root':U
&glob table_parts-root-attr 'parts-root-attr':U
&glob table_parts-supp 'parts-supp':U
&glob table_parts-supp-attr 'parts-supp-attr':U
&glob table_pay-type 'pay-type':U
&glob table_pay-type-attr 'pay-type-attr':U
&glob table_payment 'payment':U
&glob table_payment-attr 'payment-attr':U
&glob table_pck-keys 'pck-keys':U
&glob table_pck-rcvd 'pck-rcvd':U
&glob table_pck-rcvd-attr 'pck-rcvd-attr':U
&glob table_pck-sent 'pck-sent':U
&glob table_pck-sent-attr 'pck-sent-attr':U
&glob table_person 'person':U
&glob table_pl-gds 'pl-gds':U
&glob table_pl-gds-attr 'pl-gds-attr':U
&glob table_pl-gds-pump 'pl-gds-pump':U
&glob table_pl-gds-pump-attr 'pl-gds-pump-attr':U
&glob table_pl-level 'pl-level':U
&glob table_pl-level-attr 'pl-level-attr':U
&glob table_pl-pump 'pl-pump':U
&glob table_pl-pump-attr 'pl-pump-attr':U
&glob table_pl-pump-nozzle 'pl-pump-nozzle':U
&glob table_pl-pump-nozzle-attr 'pl-pump-nozzle-attr':U
&glob table_place 'place':U
&glob table_place-attr 'place-attr':U
&glob table_place-io 'place-io':U
&glob table_place-io-attr 'place-io-attr':U
&glob table_point-io 'point-io':U
&glob table_point-io-attr 'point-io-attr':U
&glob table_point-place-rel 'point-place-rel':U
&glob table_point-point-rel 'point-point-rel':U
&glob table_price-all 'price-all':U
&glob table_price-all-attr 'price-all-attr':U
&glob table_price-doc 'price-doc':U
&glob table_price-doc-forming 'price-doc-forming':U
&glob table_price-doc-forming-attr 'price-doc-forming-attr':U
&glob table_price-doc-forming-gds 'price-doc-forming-gds':U
&glob table_price-doc-forming-gds-qnty 'price-doc-forming-gds-qnty':U
&glob table_price-doc-forming-gds-sum 'price-doc-forming-gds-sum':U
&glob table_price-doc-forming-gds-tnv 'price-doc-forming-gds-tnv':U
&glob table_price-doc-forming-gdsattr 'price-doc-forming-gdsattr':U
&glob table_price-list 'price-list':U
&glob table_price-list-attr 'price-list-attr':U
&glob table_price-list-type 'price-list-type':U
&glob table_price-list-type-attr 'price-list-type-attr':U
&glob table_price-list-type-cash-pay 'price-list-type-cash-pay':U
&glob table_price-list-type-cassa 'price-list-type-cassa':U
&glob table_price-list-type-cassa-attr 'price-list-type-cassa-attr':U
&glob table_price-list-type-gds-grp 'price-list-type-gds-grp':U
&glob table_price-list-type-gds-grp-attr 'price-list-type-gds-grp-attr':U
&glob table_price-list-type-pay-type 'price-list-type-pay-type':U
&glob table_prod-bc 'prod-bc':U
&glob table_prod-bc-attr 'prod-bc-attr':U
&glob table_prod-bc-db 'prod-bc-db':U
&glob table_prod-bc-db-attr 'prod-bc-db-attr':U
&glob table_profile-by-profile 'profile-by-profile':U
&glob table_prog-message 'prog-message':U
&glob table_prog-message-attr 'prog-message-attr':U
&glob table_prog-message-lang 'prog-message-lang':U
&glob table_prog-message-lang-attr 'prog-message-lang-attr':U
&glob table_promo-schedule 'promo-schedule':U
&glob table_promo-schedule-week 'promo-schedule-week':U
&glob table_PromoAction 'PromoAction':U
&glob table_PromoAttr 'PromoAttr':U
&glob table_PromoCriterion 'PromoCriterion':U
&glob table_PromoGift 'PromoGift':U
&glob table_PromoGoods 'PromoGoods':U
&glob table_PromoObject 'PromoObject':U
&glob table_prop-head 'prop-head':U
&glob table_prop-head-attr 'prop-head-attr':U
&glob table_prop-map 'prop-map':U
&glob table_prop-map-attr 'prop-map-attr':U
&glob table_prop-ref 'prop-ref':U
&glob table_prop-ref-attr 'prop-ref-attr':U
&glob table_prop-ref-call 'prop-ref-call':U
&glob table_prop-ref-call-attr 'prop-ref-call-attr':U
&glob table_prop-ruleset 'prop-ruleset':U
&glob table_prop-ruleset-attr 'prop-ruleset-attr':U
&glob table_prop-script 'prop-script':U
&glob table_prop-script-attr 'prop-script-attr':U
&glob table_prt-obj 'prt-obj':U
&glob table_prt-obj-attr 'prt-obj-attr':U
&glob table_pscript-ruleset 'pscript-ruleset':U
&glob table_pscript-ruleset-attr 'pscript-ruleset-attr':U
&glob table_pump 'pump':U
&glob table_pump-attr 'pump-attr':U
&glob table_pump-nozzle 'pump-nozzle':U
&glob table_pump-nozzle-attr 'pump-nozzle-attr':U
&glob table_qnty-group 'qnty-group':U
&glob table_qnty-group-attr 'qnty-group-attr':U
&glob table_qnty-in-qnty-group 'qnty-in-qnty-group':U
&glob table_qnty-in-qnty-group-attr 'qnty-in-qnty-group-attr':U
&glob table_rang-abc-def 'rang-abc-def':U
&glob table_rang-abc-def-attr 'rang-abc-def-attr':U
&glob table_rang-abc-def-obj 'rang-abc-def-obj':U
&glob table_rang-abc-def-obj-attr 'rang-abc-def-obj-attr':U
&glob table_rang-xyz-def 'rang-xyz-def':U
&glob table_rang-xyz-def-attr 'rang-xyz-def-attr':U
&glob table_rang-xyz-def-obj 'rang-xyz-def-obj':U
&glob table_rang-xyz-def-obj-attr 'rang-xyz-def-obj-attr':U
&glob table_rcs-attr 'rcs-attr':U
&glob table_rcs-chkbody 'rcs-chkbody':U
&glob table_rcs-chkhead 'rcs-chkhead':U
&glob table_rcs-city 'rcs-city':U
&glob table_rcs-clients 'rcs-clients':U
&glob table_rcs-country 'rcs-country':U
&glob table_rcs-destn 'rcs-destn':U
&glob table_rcs-docbody 'rcs-docbody':U
&glob table_rcs-dochead 'rcs-dochead':U
&glob table_rcs-mark 'rcs-mark':U
&glob table_rcs-pack 'rcs-pack':U
&glob table_rcs-place 'rcs-place':U
&glob table_rcs-retail1action 'rcs-retail1action':U
&glob table_rcs-retail1attr 'rcs-retail1attr':U
&glob table_rcs-retail1bank 'rcs-retail1bank':U
&glob table_rcs-retail1barcode 'rcs-retail1barcode':U
&glob table_rcs-retail1bill 'rcs-retail1bill':U
&glob table_rcs-retail1billitem 'rcs-retail1billitem':U
&glob table_rcs-retail1convolution 'rcs-retail1convolution':U
&glob table_rcs-retail1delete 'rcs-retail1delete':U
&glob table_rcs-retail1fortuneproduct 'rcs-retail1fortuneproduct':U
&glob table_rcs-retail1price 'rcs-retail1price':U
&glob table_rcs-retail1priceitem 'rcs-retail1priceitem':U
&glob table_rcs-retail1product 'rcs-retail1product':U
&glob table_rcs-retail1subject 'rcs-retail1subject':U
&glob table_rcs-shops 'rcs-shops':U
&glob table_recipe 'recipe':U
&glob table_recipe-develop 'recipe-develop':U
&glob table_recipe-gds 'recipe-gds':U
&glob table_regions 'regions':U
&glob table_regions-attr 'regions-attr':U
&glob table_rename-fld 'rename-fld':U
&glob table_rename-fld-attr 'rename-fld-attr':U
&glob table_rep 'rep':U
&glob table_rep-line 'rep-line':U
&glob table_res-lang 'res-lang':U
&glob table_res-lang-attr 'res-lang-attr':U
&glob table_resource 'resource':U
&glob table_resource-attr 'resource-attr':U
&glob table_route 'route':U
&glob table_route-attr 'route-attr':U
&glob table_route-dump 'route-dump':U
&glob table_route-dump-attr 'route-dump-attr':U
&glob table_route-dump-link 'route-dump-link':U
&glob table_rp-by-call 'rp-by-call':U
&glob table_rp-by-call-attr 'rp-by-call-attr':U
&glob table_rp-rule-param 'rp-rule-param':U
&glob table_rp-rule-param-attr 'rp-rule-param-attr':U
&glob table_rpt-option 'rpt-option':U
&glob table_rpt-option-attr 'rpt-option-attr':U
&glob table_rule 'rule':U
&glob table_rule-attr 'rule-attr':U
&glob table_rule-by-call 'rule-by-call':U
&glob table_rule-by-call-attr 'rule-by-call-attr':U
&glob table_rule-by-profile 'rule-by-profile':U
&glob table_rule-by-profile-attr 'rule-by-profile-attr':U
&glob table_rule-by-set 'rule-by-set':U
&glob table_rule-by-set-attr 'rule-by-set-attr':U
&glob table_rule-call-param 'rule-call-param':U
&glob table_rule-call-param-attr 'rule-call-param-attr':U
&glob table_rule-i-script 'rule-i-script':U
&glob table_rule-i-script-attr 'rule-i-script-attr':U
&glob table_rule-process 'rule-process':U
&glob table_rule-profile 'rule-profile':U
&glob table_rule-profile-attr 'rule-profile-attr':U
&glob table_rule-script 'rule-script':U
&glob table_rule-script-attr 'rule-script-attr':U
&glob table_rule-trans-memo 'rule-trans-memo':U
&glob table_rule-trans-memo-attr 'rule-trans-memo-attr':U
&glob table_ruledict 'ruledict':U
&glob table_ruledict-attr 'ruledict-attr':U
&glob table_ruledict-param 'ruledict-param':U
&glob table_ruledict-param-attr 'ruledict-param-attr':U
&glob table_ruleset 'ruleset':U
&glob table_ruleset-attr 'ruleset-attr':U
&glob table_rvs-doc 'rvs-doc':U
&glob table_rvs-doc-attr 'rvs-doc-attr':U
&glob table_rvs-line 'rvs-line':U
&glob table_rvs-line-attr 'rvs-line-attr':U
&glob table_rvs-line-pump 'rvs-line-pump':U
&glob table_rvs-line-pump-attr 'rvs-line-pump-attr':U
&glob table_rvs-pump 'rvs-pump':U
&glob table_rvs-pump-attr 'rvs-pump-attr':U
&glob table_s-coeff 's-coeff':U
&glob table_s-coeff-attr 's-coeff-attr':U
&glob table_sale-doc 'sale-doc':U
&glob table_sale-doc-attr 'sale-doc-attr':U
&glob table_scales 'scales':U
&glob table_scales-attr 'scales-attr':U
&glob table_scales-gds 'scales-gds':U
&glob table_scales-gds-attr 'scales-gds-attr':U
&glob table_scales-grp 'scales-grp':U
&glob table_scales-grp-attr 'scales-grp-attr':U
&glob table_schedule 'schedule':U
&glob table_schedule-attr 'schedule-attr':U
&glob table_schet-fact-doc 'schet-fact-doc':U
&glob table_schet-fact-doc-attr 'schet-fact-doc-attr':U
&glob table_schet-fact-line 'schet-fact-line':U
&glob table_schet-fact-line-attr 'schet-fact-line-attr':U
&glob table_season 'season':U
&glob table_season-attr 'season-attr':U
&glob table_sert 'sert':U
&glob table_sert-attr 'sert-attr':U
&glob table_sert-join 'sert-join':U
&glob table_sert-join-attr 'sert-join-attr':U
&glob table_shift-attr 'shift-attr':U
&glob table_shift-cash 'shift-cash':U
&glob table_shift-cash-attr 'shift-cash-attr':U
&glob table_shift-obj 'shift-obj':U
&glob table_shift-obj-attr 'shift-obj-attr':U
&glob table_shift-staff 'shift-staff':U
&glob table_shift-staff-attr 'shift-staff-attr':U
&glob table_shop 'shop':U
&glob table_some-lk 'some-lk':U
&glob table_some-lk-attr 'some-lk-attr':U
&glob table_sr-izmerenia 'sr-izmerenia':U
&glob table_sr-izmerenia-attr 'sr-izmerenia-attr':U
&glob table_staff 'staff':U
&glob table_staff-attr 'staff-attr':U
&glob table_stk-line 'stk-line':U
&glob table_stk-line-attr 'stk-line-attr':U
&glob table_stk-supp-line 'stk-supp-line':U
&glob table_stk-supp-line-attr 'stk-supp-line-attr':U
&glob table_stk-supp-tot 'stk-supp-tot':U
&glob table_stk-supp-tot-attr 'stk-supp-tot-attr':U
&glob table_stk-tot 'stk-tot':U
&glob table_stk-tot-attr 'stk-tot-attr':U
&glob table_stop-list 'stop-list':U
&glob table_stop-list-attr 'stop-list-attr':U
&glob table_stop-list-line 'stop-list-line':U
&glob table_stop-list-line-attr 'stop-list-line-attr':U
&glob table_store 'store':U
&glob table_sum-group 'sum-group':U
&glob table_sum-group-attr 'sum-group-attr':U
&glob table_sum-grp 'sum-grp':U
&glob table_sum-grp-attr 'sum-grp-attr':U
&glob table_sum-grp-obj 'sum-grp-obj':U
&glob table_sum-grp-obj-attr 'sum-grp-obj-attr':U
&glob table_sum-in-sum-group 'sum-in-sum-group':U
&glob table_sum-in-sum-group-attr 'sum-in-sum-group-attr':U
&glob table_sys-ctrl 'sys-ctrl':U
&glob table_sys-ctrl-attr 'sys-ctrl-attr':U
&glob table_sysconf 'sysconf':U
&glob table_sysconf-attr 'sysconf-attr':U
&glob table_tare 'tare':U
&glob table_tax 'tax':U
&glob table_tax-attr 'tax-attr':U
&glob table_tax-rate 'tax-rate':U
&glob table_tax-rate-attr 'tax-rate-attr':U
&glob table_tax-rate-gds 'tax-rate-gds':U
&glob table_tax-rate-gds-attr 'tax-rate-gds-attr':U
&glob table_tax-rate-gds-grp 'tax-rate-gds-grp':U
&glob table_tax-rate-gds-grp-attr 'tax-rate-gds-grp-attr':U
&glob table_tax-rate-value 'tax-rate-value':U
&glob table_tax-rate-value-attr 'tax-rate-value-attr':U
&glob table_tax-units 'tax-units':U
&glob table_tax-units-attr 'tax-units-attr':U
&glob table_tech-prol-pwd 'tech-prol-pwd':U
&glob table_thbj-attr 'thbj-attr':U
&glob table_tmp-sale 'tmp-sale':U
&glob table_tmp-sale-attr 'tmp-sale-attr':U
&glob table_tmp-sale-dtl 'tmp-sale-dtl':U
&glob table_tmp-sale-dtl-attr 'tmp-sale-dtl-attr':U
&glob table_tmp-sale-gds 'tmp-sale-gds':U
&glob table_tmp-sale-gds-attr 'tmp-sale-gds-attr':U
&glob table_tnv-in-turnover-group 'tnv-in-turnover-group':U
&glob table_tnv-in-turnover-group-attr 'tnv-in-turnover-group-attr':U
&glob table_tnved-head 'tnved-head':U
&glob table_tnved-head-attr 'tnved-head-attr':U
&glob table_tnved-item 'tnved-item':U
&glob table_tnved-item-attr 'tnved-item-attr':U
&glob table_tran-fuel 'tran-fuel':U
&glob table_trn-doc 'trn-doc':U
&glob table_trn-doc-sum 'trn-doc-sum':U
&glob table_trn-reason 'trn-reason':U
&glob table_trn-reason-host 'trn-reason-host':U
&glob table_trn-reason-obj 'trn-reason-obj':U
&glob table_trn-rsn-attr 'trn-rsn-attr':U
&glob table_turnover-buyer 'turnover-buyer':U
&glob table_turnover-buyer-attr 'turnover-buyer-attr':U
&glob table_turnover-buyer-gds 'turnover-buyer-gds':U
&glob table_turnover-buyer-gds-attr 'turnover-buyer-gds-attr':U
&glob table_turnover-buyer-main 'turnover-buyer-main':U
&glob table_turnover-buyer-main-attr 'turnover-buyer-main-attr':U
&glob table_turnover-group 'turnover-group':U
&glob table_turnover-group-attr 'turnover-group-attr':U
&glob table_units 'units':U
&glob table_units-attr 'units-attr':U
&glob table_upgrade 'upgrade':U
&glob table_upgrade-attr 'upgrade-attr':U
&glob table_user-account 'user-account':U
&glob table_user-account-attr 'user-account-attr':U
&glob table_user-conn 'user-conn':U
&glob table_user-conn-attr 'user-conn-attr':U
&glob table_user-context-history 'user-context-history':U
&glob table_user-context-history-attr 'user-context-history-attr':U
&glob table_user-host 'user-host':U
&glob table_user-host-attr 'user-host-attr':U
&glob table_user-login 'user-login':U
&glob table_user-login-action-item 'user-login-action-item':U
&glob table_user-login-action-item-attr 'user-login-action-item-attr':U
&glob table_user-login-action-role 'user-login-action-role':U
&glob table_user-login-action-role-attr 'user-login-action-role-attr':U
&glob table_user-login-attr 'user-login-attr':U
&glob table_user-menu-group 'user-menu-group':U
&glob table_user-menu-group-attr 'user-menu-group-attr':U
&glob table_user-obj 'user-obj':U
&glob table_user-obj-attr 'user-obj-attr':U
&glob table_user-window-attr 'user-window-attr':U
&glob table_usr-flt 'usr-flt':U
&glob table_usr-flt-attr 'usr-flt-attr':U
&glob table_usr-stko 'usr-stko':U
&glob table_usr-stko-attr 'usr-stko-attr':U
&glob table_utd 'utd':U
&glob table_utd-attr 'utd-attr':U
&glob table_utd-err 'utd-err':U
&glob table_utd-err-attr 'utd-err-attr':U
&glob table_utd-lines 'utd-lines':U
&glob table_utd-lines-attr 'utd-lines-attr':U
&glob table_utd-marking-lines 'utd-marking-lines':U
&glob table_utd-marking-lines-attr 'utd-marking-lines-attr':U
&glob table_var-deliv-gr-per-val 'var-deliv-gr-per-val':U
&glob table_var-deliv-gr-per-val-attr 'var-deliv-gr-per-val-attr':U
&glob table_variant-delivery 'variant-delivery':U
&glob table_variant-delivery-attr 'variant-delivery-attr':U
&glob table_varianty-delivery-gds-obj 'varianty-delivery-gds-obj':U
&glob table_vsd 'vsd':U
&glob table_vsd-attr 'vsd-attr':U
&glob table_wealth 'wealth':U
&glob table_wealth-attr 'wealth-attr':U
&glob table_who-lk 'who-lk':U
&glob table_who-lk-attr 'who-lk-attr':U
&glob table_whole-send-news 'whole-send-news':U
&glob table_wi-mode 'wi-mode':U
&glob table_wi-mode-attr 'wi-mode-attr':U
&glob table_wth-doc 'wth-doc':U
&glob table_wth-doc-attr 'wth-doc-attr':U
&glob table_wth-dtl 'wth-dtl':U
&glob table_wth-dtl-attr 'wth-dtl-attr':U
&glob table_wth-gds 'wth-gds':U
&glob table_wth-gds-attr 'wth-gds-attr':U
&glob table_wth-line 'wth-line':U
&glob table_wth-line-attr 'wth-line-attr':U
&glob table_wth-obj 'wth-obj':U
&glob table_wth-obj-attr 'wth-obj-attr':U
&glob table_wth-par 'wth-par':U
&glob table_wth-par-attr 'wth-par-attr':U
&glob table_wth-parts 'wth-parts':U
&glob table_wth-parts-attr 'wth-parts-attr':U
&glob table_wth-place 'wth-place':U
&glob table_wth-place-attr 'wth-place-attr':U
&glob table_wth-pobj 'wth-pobj':U
&glob table_wth-pobj-attr 'wth-pobj-attr':U
&glob table_wth-ser 'wth-ser':U
&glob table_wth-ser-attr 'wth-ser-attr':U
&glob table_Xattr 'Xattr':U
&glob table_xGroupObj 'xGroupObj':U
&glob table_xstatus 'xstatus':U
&glob table_xyz-analysis 'xyz-analysis':U
&glob table_xyz-analysis-attr 'xyz-analysis-attr':U
&glob table_xyz-analysis-cli 'xyz-analysis-cli':U
&glob table_xyz-analysis-cli-attr 'xyz-analysis-cli-attr':U
&glob table_xyz-analysis-doc 'xyz-analysis-doc':U
&glob table_xyz-analysis-doc-attr 'xyz-analysis-doc-attr':U
&glob table_xyz-analysis-gds-obj 'xyz-analysis-gds-obj':U
&glob table_xyz-analysis-gds-obj-attr 'xyz-analysis-gds-obj-attr':U
&glob table_xyz-analysis-goods 'xyz-analysis-goods':U
&glob table_xyz-analysis-goods-attr 'xyz-analysis-goods-attr':U
&glob table_xyz-analysis-grp 'xyz-analysis-grp':U
&glob table_xyz-analysis-grp-attr 'xyz-analysis-grp-attr':U
&glob table_xyz-analysis-obj 'xyz-analysis-obj':U
&glob table_xyz-analysis-obj-attr 'xyz-analysis-obj-attr':U
&glob table_xyz-analysis-period 'xyz-analysis-period':U
&glob table_xyz-analysis-period-attr 'xyz-analysis-period-attr':U
&glob table_xyz-analysis-prod 'xyz-analysis-prod':U
&glob table_xyz-analysis-prod-attr 'xyz-analysis-prod-attr':U
/* $Workfile: $ e n d */

