/*

$Revision: $
$Author: $
$Date: $
$Workfile: $
$Archive: $

Глобальные определения имен таблиц

Автор: Бахтадзе Наталья Викторовна
Дата создания: 01/29/07
Author: Bakhtadze Natalya
Creation date: 01/29/07

Файл автоматически создается процедурой utl/gen-tbln.p

*/

&glob bef-table_abc-analysis abc-analysis
&glob bef-table_abc-analysis-attr abc-analysis-attr
&glob bef-table_abc-analysis-cli abc-analysis-cli
&glob bef-table_abc-analysis-cli-attr abc-analysis-cli-attr
&glob bef-table_abc-analysis-doc abc-analysis-doc
&glob bef-table_abc-analysis-doc-attr abc-analysis-doc-attr
&glob bef-table_abc-analysis-gds-obj abc-analysis-gds-obj
&glob bef-table_abc-analysis-gds-obj-attr abc-analysis-gds-obj-attr
&glob bef-table_abc-analysis-goods abc-analysis-goods
&glob bef-table_abc-analysis-goods-attr abc-analysis-goods-attr
&glob bef-table_abc-analysis-grp abc-analysis-grp
&glob bef-table_abc-analysis-grp-attr abc-analysis-grp-attr
&glob bef-table_abc-analysis-obj abc-analysis-obj
&glob bef-table_abc-analysis-obj-attr abc-analysis-obj-attr
&glob bef-table_abc-analysis-period abc-analysis-period
&glob bef-table_abc-analysis-period-attr abc-analysis-period-attr
&glob bef-table_abc-analysis-prod abc-analysis-prod
&glob bef-table_abc-analysis-prod-attr abc-analysis-prod-attr
&glob bef-table_abcxyz-analysis abcxyz-analysis
&glob bef-table_abcxyz-analysis-attr abcxyz-analysis-attr
&glob bef-table_abcxyz-analysis-goods abcxyz-analysis-goods
&glob bef-table_abcxyz-analysis-goods-attr abcxyz-analysis-goods-attr
&glob bef-table_action-group action-group
&glob bef-table_action-group-attr action-group-attr
&glob bef-table_action-head action-head
&glob bef-table_action-head-attr action-head-attr
&glob bef-table_action-item action-item
&glob bef-table_action-item-attr action-item-attr
&glob bef-table_action-post action-post
&glob bef-table_action-post-attr action-post-attr
&glob bef-table_action-post-host action-post-host
&glob bef-table_action-post-host-attr action-post-host-attr
&glob bef-table_action-post-menu-group action-post-menu-group
&glob bef-table_action-post-menu-group-attr action-post-menu-group-attr
&glob bef-table_action-post-obj action-post-obj
&glob bef-table_action-post-obj-attr action-post-obj-attr
&glob bef-table_action-post-role action-post-role
&glob bef-table_action-post-role-attr action-post-role-attr
&glob bef-table_action-post-user-login action-post-user-login
&glob bef-table_action-post-user-login-attr action-post-user-login-attr
&glob bef-table_action-role action-role
&glob bef-table_action-role-attr action-role-attr
&glob bef-table_action-role-item action-role-item
&glob bef-table_action-role-item-attr action-role-item-attr
&glob bef-table_action-role-item-gds action-role-item-gds
&glob bef-table_action-role-item-gds-grp action-role-item-gds-grp
&glob bef-table_add-doc add-doc
&glob bef-table_add-line add-line
&glob bef-table_add-trn add-trn
&glob bef-table_add-trn-attr add-trn-attr
&glob bef-table_aht-doc aht-doc
&glob bef-table_aht-doc-attr aht-doc-attr
&glob bef-table_aht-gds aht-gds
&glob bef-table_aht-gds-attr aht-gds-attr
&glob bef-table_aht-ot-line aht-ot-line
&glob bef-table_aht-ot-line-attr aht-ot-line-attr
&glob bef-table_aht-ot-tot aht-ot-tot
&glob bef-table_aht-ot-tot-attr aht-ot-tot-attr
&glob bef-table_aht-stk aht-stk
&glob bef-table_aht-stk-attr aht-stk-attr
&glob bef-table_aht-stk-line aht-stk-line
&glob bef-table_aht-stk-line-attr aht-stk-line-attr
&glob bef-table_aht-stk-tot aht-stk-tot
&glob bef-table_aht-stk-tot-attr aht-stk-tot-attr
&glob bef-table_aht-time aht-time
&glob bef-table_aht-time-attr aht-time-attr
&glob bef-table_alc-sale-lic alc-sale-lic
&glob bef-table_alc-sale-lic-attr alc-sale-lic-attr
&glob bef-table_alc-sale-lic-type alc-sale-lic-type
&glob bef-table_alc-sale-lic-type-attr alc-sale-lic-type-attr
&glob bef-table_alc-supp-lic alc-supp-lic
&glob bef-table_alc-supp-lic-attr alc-supp-lic-attr
&glob bef-table_alc-supp-lic-type alc-supp-lic-type
&glob bef-table_alc-supp-lic-type-attr alc-supp-lic-type-attr
&glob bef-table_alc-type alc-type
&glob bef-table_alc-type-attr alc-type-attr
&glob bef-table_alc-type-gds alc-type-gds
&glob bef-table_alc-type-gds-attr alc-type-gds-attr
&glob bef-table_archive-history archive-history
&glob bef-table_archive-history-attr archive-history-attr
&glob bef-table_arh-fin-doc-an arh-fin-doc-an
&glob bef-table_arh-fin-doc-an-attr arh-fin-doc-an-attr
&glob bef-table_arh-fin-doc-an-nal arh-fin-doc-an-nal
&glob bef-table_arh-fin-doc-an-nal-attr arh-fin-doc-an-nal-attr
&glob bef-table_arh-fin-doc-an-nal-obj arh-fin-doc-an-nal-obj
&glob bef-table_arh-fin-doc-an-nal-obj-attr arh-fin-doc-an-nal-obj-attr
&glob bef-table_arh-fin-doc-an-obj arh-fin-doc-an-obj
&glob bef-table_arh-fin-doc-an-obj-attr arh-fin-doc-an-obj-attr
&glob bef-table_arh-fin-doc-c-s-tax-nal-obj arh-fin-doc-c-s-tax-nal-obj
&glob bef-table_arh-fin-doc-c-schet-tax-nal arh-fin-doc-c-schet-tax-nal
&glob bef-table_arh-fin-doc-contr-s-nal-obj arh-fin-doc-contr-s-nal-obj
&glob bef-table_arh-fin-doc-contr-s-tax-obj arh-fin-doc-contr-s-tax-obj
&glob bef-table_arh-fin-doc-contr-schet arh-fin-doc-contr-schet
&glob bef-table_arh-fin-doc-contr-schet-attr arh-fin-doc-contr-schet-attr
&glob bef-table_arh-fin-doc-contr-schet-nal arh-fin-doc-contr-schet-nal
&glob bef-table_arh-fin-doc-contr-schet-obj arh-fin-doc-contr-schet-obj
&glob bef-table_arh-fin-doc-contr-schet-tax arh-fin-doc-contr-schet-tax
&glob bef-table_arh-fin-doc-s-tax-nal-obj arh-fin-doc-s-tax-nal-obj
&glob bef-table_arh-fin-doc-schet arh-fin-doc-schet
&glob bef-table_arh-fin-doc-schet-attr arh-fin-doc-schet-attr
&glob bef-table_arh-fin-doc-schet-nal arh-fin-doc-schet-nal
&glob bef-table_arh-fin-doc-schet-nal-attr arh-fin-doc-schet-nal-attr
&glob bef-table_arh-fin-doc-schet-nal-obj arh-fin-doc-schet-nal-obj
&glob bef-table_arh-fin-doc-schet-obj arh-fin-doc-schet-obj
&glob bef-table_arh-fin-doc-schet-obj-attr arh-fin-doc-schet-obj-attr
&glob bef-table_arh-fin-doc-schet-tax arh-fin-doc-schet-tax
&glob bef-table_arh-fin-doc-schet-tax-attr arh-fin-doc-schet-tax-attr
&glob bef-table_arh-fin-doc-schet-tax-nal arh-fin-doc-schet-tax-nal
&glob bef-table_arh-fin-doc-schet-tax-obj arh-fin-doc-schet-tax-obj
&glob bef-table_arh-fin-ob-contr arh-fin-ob-contr
&glob bef-table_arh-fin-ob-contr-attr arh-fin-ob-contr-attr
&glob bef-table_arh-fin-ob-contr-obj arh-fin-ob-contr-obj
&glob bef-table_arh-fin-ob-contr-obj-attr arh-fin-ob-contr-obj-attr
&glob bef-table_arh-trn-doc-contract arh-trn-doc-contract
&glob bef-table_arh-trn-doc-contract-attr arh-trn-doc-contract-attr
&glob bef-table_arh-wth-cli arh-wth-cli
&glob bef-table_arh-wth-cli-attr arh-wth-cli-attr
&glob bef-table_arh-wth-cli-doc arh-wth-cli-doc
&glob bef-table_arh-wth-cli-doc-attr arh-wth-cli-doc-attr
&glob bef-table_arh-wth-cli-tot arh-wth-cli-tot
&glob bef-table_arh-wth-cli-tot-attr arh-wth-cli-tot-attr
&glob bef-table_arh-wth-tot arh-wth-tot
&glob bef-table_arh-wth-tot-attr arh-wth-tot-attr
&glob bef-table_arh-wth-w-p arh-wth-w-p
&glob bef-table_arh-wth-w-p-attr arh-wth-w-p-attr
&glob bef-table_assortment-matrix assortment-matrix
&glob bef-table_assortment-matrix-attr assortment-matrix-attr
&glob bef-table_assortment-matrix-goods assortment-matrix-goods
&glob bef-table_assortment-matrix-goods-attr assortment-matrix-goods-attr
&glob bef-table_attr-prop attr-prop
&glob bef-table_auto-section auto-section
&glob bef-table_auto-section-attr auto-section-attr
&glob bef-table_auto-section-table auto-section-table
&glob bef-table_auto-tank auto-tank
&glob bef-table_auto-tank-attr auto-tank-attr
&glob bef-table_auto-tank-meas auto-tank-meas
&glob bef-table_auto-tank-meas-attr auto-tank-meas-attr
&glob bef-table_bar-code bar-code
&glob bef-table_bar-code-attr bar-code-attr
&glob bef-table_bar-code-obj-attr bar-code-obj-attr
&glob bef-table_BatchProcess BatchProcess
&glob bef-table_blob-bind blob-bind
&glob bef-table_blob-data blob-data
&glob bef-table_buyer-group buyer-group
&glob bef-table_buyer-group-attr buyer-group-attr
&glob bef-table_buyer-in-buyer-group buyer-in-buyer-group
&glob bef-table_buyer-in-buyer-group-attr buyer-in-buyer-group-attr
&glob bef-table_c-action-role c-action-role
&glob bef-table_c-action-role-item c-action-role-item
&glob bef-table_c-add-doc c-add-doc
&glob bef-table_c-add-line c-add-line
&glob bef-table_c-alc-sale-lic c-alc-sale-lic
&glob bef-table_c-alc-sale-lic-attr c-alc-sale-lic-attr
&glob bef-table_c-alc-sale-lic-type c-alc-sale-lic-type
&glob bef-table_c-alc-supp-lic c-alc-supp-lic
&glob bef-table_c-alc-supp-lic-attr c-alc-supp-lic-attr
&glob bef-table_c-alc-supp-lic-type c-alc-supp-lic-type
&glob bef-table_c-alc-type c-alc-type
&glob bef-table_c-alc-type-attr c-alc-type-attr
&glob bef-table_c-alc-type-gds c-alc-type-gds
&glob bef-table_c-assortment-matrix c-assortment-matrix
&glob bef-table_c-assortment-matrix-goods c-assortment-matrix-goods
&glob bef-table_c-auto-section c-auto-section
&glob bef-table_c-auto-section-attr c-auto-section-attr
&glob bef-table_c-auto-section-table c-auto-section-table
&glob bef-table_c-auto-tank c-auto-tank
&glob bef-table_c-auto-tank-attr c-auto-tank-attr
&glob bef-table_c-auto-tank-meas-attr c-auto-tank-meas-attr
&glob bef-table_c-bar-code c-bar-code
&glob bef-table_c-bar-code-attr c-bar-code-attr
&glob bef-table_c-bar-code-obj-attr c-bar-code-obj-attr
&glob bef-table_c-buyer-group c-buyer-group
&glob bef-table_c-buyer-in-buyer-group c-buyer-in-buyer-group
&glob bef-table_c-cash-desk c-cash-desk
&glob bef-table_c-cash-desk-attr c-cash-desk-attr
&glob bef-table_c-cash-pay c-cash-pay
&glob bef-table_c-cash-pay-attr c-cash-pay-attr
&glob bef-table_c-CashBook c-CashBook
&glob bef-table_c-cashbook-head c-cashbook-head
&glob bef-table_c-CashBookAttr c-CashBookAttr
&glob bef-table_c-CashBookRule c-CashBookRule
&glob bef-table_c-CashBookRuleAttr c-CashBookRuleAttr
&glob bef-table_c-cbr-bank c-cbr-bank
&glob bef-table_c-cbr-bank-attr c-cbr-bank-attr
&glob bef-table_c-cd-clu c-cd-clu
&glob bef-table_c-cd-dlu c-cd-dlu
&glob bef-table_c-cd-doc c-cd-doc
&glob bef-table_c-cd-doc-line c-cd-doc-line
&glob bef-table_c-cd-grp c-cd-grp
&glob bef-table_c-cd-plu c-cd-plu
&glob bef-table_c-chk-discnt c-chk-discnt
&glob bef-table_c-chk-doc c-chk-doc
&glob bef-table_c-chk-doc-attr c-chk-doc-attr
&glob bef-table_c-chk-gds c-chk-gds
&glob bef-table_c-chk-pay c-chk-pay
&glob bef-table_c-cli-grp c-cli-grp
&glob bef-table_c-cli-grp-attr c-cli-grp-attr
&glob bef-table_c-cli-hist c-cli-hist
&glob bef-table_c-clients c-clients
&glob bef-table_c-clients-attr c-clients-attr
&glob bef-table_c-condition-keeping c-condition-keeping
&glob bef-table_c-condition-keeping-attr c-condition-keeping-attr
&glob bef-table_c-config c-config
&glob bef-table_c-contract c-contract
&glob bef-table_c-contract-line c-contract-line
&glob bef-table_c-contract-specif c-contract-specif
&glob bef-table_c-contract-specif-attr c-contract-specif-attr
&glob bef-table_c-counter c-counter
&glob bef-table_c-country c-country
&glob bef-table_c-country-attr c-country-attr
&glob bef-table_c-curr-accnt c-curr-accnt
&glob bef-table_c-curr-bank c-curr-bank
&glob bef-table_c-currency c-currency
&glob bef-table_c-currency-attr c-currency-attr
&glob bef-table_c-db c-db
&glob bef-table_c-db-grp-obj-price c-db-grp-obj-price
&glob bef-table_c-dc-hist c-dc-hist
&glob bef-table_c-deliv-type-cond-keep c-deliv-type-cond-keep
&glob bef-table_c-deliv-type-cond-keep-attr c-deliv-type-cond-keep-attr
&glob bef-table_c-delivery-subject c-delivery-subject
&glob bef-table_c-delivery-subject-attr c-delivery-subject-attr
&glob bef-table_c-delivery-type c-delivery-type
&glob bef-table_c-delivery-type-attr c-delivery-type-attr
&glob bef-table_c-delivery-type-subject c-delivery-type-subject
&glob bef-table_c-delivery-type-subject-attr c-delivery-type-subject-attr
&glob bef-table_c-dis-card c-dis-card
&glob bef-table_c-dis-card-long c-dis-card-long
&glob bef-table_c-dis-card-long-attr c-dis-card-long-attr
&glob bef-table_c-dis-card-mask c-dis-card-mask
&glob bef-table_c-dis-card-mask-attr c-dis-card-mask-attr
&glob bef-table_c-dis-card-property c-dis-card-property
&glob bef-table_c-dis-card-type c-dis-card-type
&glob bef-table_c-dis-card-type-attr c-dis-card-type-attr
&glob bef-table_c-dis-cfg-rule c-dis-cfg-rule
&glob bef-table_c-dis-cp-rule c-dis-cp-rule
&glob bef-table_c-dis-dc-rule c-dis-dc-rule
&glob bef-table_c-dis-dct-rule c-dis-dct-rule
&glob bef-table_c-dis-gds-rule c-dis-gds-rule
&glob bef-table_c-dis-grp-rule c-dis-grp-rule
&glob bef-table_c-dis-host c-dis-host
&glob bef-table_c-dis-obj c-dis-obj
&glob bef-table_c-dis-rule c-dis-rule
&glob bef-table_c-dis-rule-attr c-dis-rule-attr
&glob bef-table_c-dis-some-rule c-dis-some-rule
&glob bef-table_c-dis-thbj-rule c-dis-thbj-rule
&glob bef-table_c-dis-time-rule c-dis-time-rule
&glob bef-table_c-doc-attr c-doc-attr
&glob bef-table_c-doc-fbr-gds c-doc-fbr-gds
&glob bef-table_c-doc-line c-doc-line
&glob bef-table_c-doc-line-attr c-doc-line-attr
&glob bef-table_c-doc-line-sum c-doc-line-sum
&glob bef-table_c-doc-pl c-doc-pl
&glob bef-table_c-doc-pl-pump c-doc-pl-pump
&glob bef-table_c-doc-prts c-doc-prts
&glob bef-table_c-drt-prop c-drt-prop
&glob bef-table_c-egais-clients c-egais-clients
&glob bef-table_c-egais-gds c-egais-gds
&glob bef-table_c-esys-datatype-exp c-esys-datatype-exp
&glob bef-table_c-esys-datatype-imp c-esys-datatype-imp
&glob bef-table_c-ex-mark c-ex-mark
&glob bef-table_c-ext-artic c-ext-artic
&glob bef-table_c-ext-artic-attr c-ext-artic-attr
&glob bef-table_c-ext-classif c-ext-classif
&glob bef-table_c-ext-system c-ext-system
&glob bef-table_c-fbr-doc c-fbr-doc
&glob bef-table_c-fbr-gds-grp c-fbr-gds-grp
&glob bef-table_c-fbr-gds-grp-attr c-fbr-gds-grp-attr
&glob bef-table_c-fbr-gds-grp-hist c-fbr-gds-grp-hist
&glob bef-table_c-fbr-gds-obj c-fbr-gds-obj
&glob bef-table_c-fbr-gds-obj-attr c-fbr-gds-obj-attr
&glob bef-table_c-fbr-line c-fbr-line
&glob bef-table_c-fbr-pln c-fbr-pln
&glob bef-table_c-fbr-pln-line c-fbr-pln-line
&glob bef-table_c-fbr-prn c-fbr-prn
&glob bef-table_c-fbr-prn-gds c-fbr-prn-gds
&glob bef-table_c-fbr-prn-grp c-fbr-prn-grp
&glob bef-table_c-fin-bank c-fin-bank
&glob bef-table_c-fin-bank-attr c-fin-bank-attr
&glob bef-table_c-fin-code-an-uchet c-fin-code-an-uchet
&glob bef-table_c-fin-code-cel-nazn c-fin-code-cel-nazn
&glob bef-table_c-fin-code-cor-acc c-fin-code-cor-acc
&glob bef-table_c-fin-connect c-fin-connect
&glob bef-table_c-fin-doc c-fin-doc
&glob bef-table_c-fin-doc-attr c-fin-doc-attr
&glob bef-table_c-fin-doc-tax c-fin-doc-tax
&glob bef-table_c-fin-gds-part c-fin-gds-part
&glob bef-table_c-fin-ob c-fin-ob
&glob bef-table_c-fin-ob-attr c-fin-ob-attr
&glob bef-table_c-fin-ob-tax c-fin-ob-tax
&glob bef-table_c-fin-schet c-fin-schet
&glob bef-table_c-fin-schet-attr c-fin-schet-attr
&glob bef-table_c-fin-statement c-fin-statement
&glob bef-table_c-fin-statement-attr c-fin-statement-attr
&glob bef-table_c-fin-statement-line c-fin-statement-line
&glob bef-table_c-firm c-firm
&glob bef-table_c-gds-add-charges c-gds-add-charges
&glob bef-table_c-gds-add-charges-attr c-gds-add-charges-attr
&glob bef-table_c-gds-dtl c-gds-dtl
&glob bef-table_c-gds-dtl-attr c-gds-dtl-attr
&glob bef-table_c-gds-grp c-gds-grp
&glob bef-table_c-gds-grp-attr c-gds-grp-attr
&glob bef-table_c-gds-grp-hist c-gds-grp-hist
&glob bef-table_c-gds-grp-obj c-gds-grp-obj
&glob bef-table_c-gds-hist c-gds-hist
&glob bef-table_c-gds-host-attr c-gds-host-attr
&glob bef-table_c-gds-mercury c-gds-mercury
&glob bef-table_c-gds-obj c-gds-obj
&glob bef-table_c-gds-obj-attr c-gds-obj-attr
&glob bef-table_c-gds-obj-prop c-gds-obj-prop
&glob bef-table_c-gds-obj-ref c-gds-obj-ref
&glob bef-table_c-gds-prt c-gds-prt
&glob bef-table_c-gds-prt-attr c-gds-prt-attr
&glob bef-table_c-gds-season c-gds-season
&glob bef-table_c-global-state c-global-state
&glob bef-table_c-global-state-attr c-global-state-attr
&glob bef-table_c-goods c-goods
&glob bef-table_c-goods-attr c-goods-attr
&glob bef-table_c-goods-attr-any c-goods-attr-any
&glob bef-table_c-group-period-validity c-group-period-validity
&glob bef-table_c-group-period-validity-attr c-group-period-validity-attr
&glob bef-table_c-grp-obj-price c-grp-obj-price
&glob bef-table_c-hist-nws-option c-hist-nws-option
&glob bef-table_c-hist-nws-option-attr c-hist-nws-option-attr
&glob bef-table_c-host-grp-obj-price c-host-grp-obj-price
&glob bef-table_c-inkas c-inkas
&glob bef-table_c-inkas-pay c-inkas-pay
&glob bef-table_c-inkas-pay-desk c-inkas-pay-desk
&glob bef-table_c-inkas-pay-wth c-inkas-pay-wth
&glob bef-table_c-inv-line c-inv-line
&glob bef-table_c-layout c-layout
&glob bef-table_c-layout-attr c-layout-attr
&glob bef-table_c-layout-elem c-layout-elem
&glob bef-table_c-layout-elem-attr c-layout-elem-attr
&glob bef-table_c-layout-elem-rule c-layout-elem-rule
&glob bef-table_c-layout-elem-rule-attr c-layout-elem-rule-attr
&glob bef-table_c-norm-loss c-norm-loss
&glob bef-table_c-nozzle c-nozzle
&glob bef-table_c-nozzle-attr c-nozzle-attr
&glob bef-table_c-nzl-hist c-nzl-hist
&glob bef-table_c-obj-grp-obj-price c-obj-grp-obj-price
&glob bef-table_c-OperServ c-OperServ
&glob bef-table_c-operServAttr c-operServAttr
&glob bef-table_c-ord-doc c-ord-doc
&glob bef-table_c-ord-doc-attr c-ord-doc-attr
&glob bef-table_c-ord-dtl c-ord-dtl
&glob bef-table_c-ord-line c-ord-line
&glob bef-table_c-ord-line-attr c-ord-line-attr
&glob bef-table_c-parts c-parts
&glob bef-table_c-parts-add c-parts-add
&glob bef-table_c-parts-attr c-parts-attr
&glob bef-table_c-parts-obj-attr c-parts-obj-attr
&glob bef-table_c-parts-root c-parts-root
&glob bef-table_c-pay-type c-pay-type
&glob bef-table_c-pay-type-attr c-pay-type-attr
&glob bef-table_c-payment-attr c-payment-attr
&glob bef-table_c-person c-person
&glob bef-table_c-pl-gds c-pl-gds
&glob bef-table_c-pl-gds-attr c-pl-gds-attr
&glob bef-table_c-pl-gds-obj c-pl-gds-obj
&glob bef-table_c-pl-gds-pump c-pl-gds-pump
&glob bef-table_c-pl-gds-pump-attr c-pl-gds-pump-attr
&glob bef-table_c-pl-level c-pl-level
&glob bef-table_c-pl-level-attr c-pl-level-attr
&glob bef-table_c-pl-pump c-pl-pump
&glob bef-table_c-pl-pump-attr c-pl-pump-attr
&glob bef-table_c-pl-pump-nozzle c-pl-pump-nozzle
&glob bef-table_c-pl-pump-nozzle-attr c-pl-pump-nozzle-attr
&glob bef-table_c-place c-place
&glob bef-table_c-place-attr c-place-attr
&glob bef-table_c-place-io c-place-io
&glob bef-table_c-plc-hist c-plc-hist
&glob bef-table_c-pmp-hist c-pmp-hist
&glob bef-table_c-point-io c-point-io
&glob bef-table_c-point-place-rel c-point-place-rel
&glob bef-table_c-point-point-rel c-point-point-rel
&glob bef-table_c-price-doc c-price-doc
&glob bef-table_c-price-doc-forming c-price-doc-forming
&glob bef-table_c-price-doc-forming-attr c-price-doc-forming-attr
&glob bef-table_c-price-doc-forming-gds c-price-doc-forming-gds
&glob bef-table_c-price-doc-forming-gds-qnty c-price-doc-forming-gds-qnty
&glob bef-table_c-price-doc-forming-gds-sum c-price-doc-forming-gds-sum
&glob bef-table_c-price-doc-forming-gds-tnv c-price-doc-forming-gds-tnv
&glob bef-table_c-price-doc-forming-gdsattr c-price-doc-forming-gdsattr
&glob bef-table_c-price-list c-price-list
&glob bef-table_c-price-list-attr c-price-list-attr
&glob bef-table_c-price-list-type c-price-list-type
&glob bef-table_c-price-list-type-attr c-price-list-type-attr
&glob bef-table_c-price-list-type-cash-pay c-price-list-type-cash-pay
&glob bef-table_c-price-list-type-cassa c-price-list-type-cassa
&glob bef-table_c-price-list-type-gds-grp c-price-list-type-gds-grp
&glob bef-table_c-price-list-type-pay-type c-price-list-type-pay-type
&glob bef-table_c-prod-bc c-prod-bc
&glob bef-table_c-prod-bc-attr c-prod-bc-attr
&glob bef-table_c-prod-bc-db-attr c-prod-bc-db-attr
&glob bef-table_c-profile-by-profile c-profile-by-profile
&glob bef-table_c-promo-head c-promo-head
&glob bef-table_c-promo-schedule c-promo-schedule
&glob bef-table_c-promo-schedule-week c-promo-schedule-week
&glob bef-table_c-PromoAction c-PromoAction
&glob bef-table_c-PromoAttr c-PromoAttr
&glob bef-table_c-PromoCriterion c-PromoCriterion
&glob bef-table_c-PromoGift c-PromoGift
&glob bef-table_c-PromoGoods c-PromoGoods
&glob bef-table_c-PromoObject c-PromoObject
&glob bef-table_c-prop-head c-prop-head
&glob bef-table_c-prop-ref c-prop-ref
&glob bef-table_c-prop-ruleset c-prop-ruleset
&glob bef-table_c-prop-script c-prop-script
&glob bef-table_c-pscript-ruleset c-pscript-ruleset
&glob bef-table_c-pump c-pump
&glob bef-table_c-pump-attr c-pump-attr
&glob bef-table_c-pump-nozzle c-pump-nozzle
&glob bef-table_c-pump-nozzle-attr c-pump-nozzle-attr
&glob bef-table_c-qnty-group c-qnty-group
&glob bef-table_c-qnty-in-qnty-group c-qnty-in-qnty-group
&glob bef-table_c-recipe c-recipe
&glob bef-table_c-recipe-develop c-recipe-develop
&glob bef-table_c-recipe-gds c-recipe-gds
&glob bef-table_c-recipe-hist c-recipe-hist
&glob bef-table_c-regions c-regions
&glob bef-table_c-rp-by-call c-rp-by-call
&glob bef-table_c-rp-rule-param c-rp-rule-param
&glob bef-table_c-rule c-rule
&glob bef-table_c-rule-by-call c-rule-by-call
&glob bef-table_c-rule-by-profile c-rule-by-profile
&glob bef-table_c-rule-by-set c-rule-by-set
&glob bef-table_c-rule-call-param c-rule-call-param
&glob bef-table_c-rule-process c-rule-process
&glob bef-table_c-rule-profile c-rule-profile
&glob bef-table_c-ruledict c-ruledict
&glob bef-table_c-ruledict-param c-ruledict-param
&glob bef-table_c-ruleset c-ruleset
&glob bef-table_c-rvs-doc c-rvs-doc
&glob bef-table_c-rvs-line c-rvs-line
&glob bef-table_c-rvs-line-pump c-rvs-line-pump
&glob bef-table_c-s-coeff c-s-coeff
&glob bef-table_c-sale-doc c-sale-doc
&glob bef-table_c-scales c-scales
&glob bef-table_c-scales-attr c-scales-attr
&glob bef-table_c-scales-gds c-scales-gds
&glob bef-table_c-scales-grp c-scales-grp
&glob bef-table_c-schet-fact-doc c-schet-fact-doc
&glob bef-table_c-schet-fact-line c-schet-fact-line
&glob bef-table_c-season c-season
&glob bef-table_c-sert c-sert
&glob bef-table_c-shift-attr c-shift-attr
&glob bef-table_c-shift-obj c-shift-obj
&glob bef-table_c-shift-staff c-shift-staff
&glob bef-table_c-shop c-shop
&glob bef-table_c-sht-hist c-sht-hist
&glob bef-table_c-sr-izmerenia c-sr-izmerenia
&glob bef-table_c-sr-izmerenia-attr c-sr-izmerenia-attr
&glob bef-table_c-staff c-staff
&glob bef-table_c-stop-list c-stop-list
&glob bef-table_c-stop-list-line c-stop-list-line
&glob bef-table_c-store c-store
&glob bef-table_c-sum-group c-sum-group
&glob bef-table_c-sum-grp c-sum-grp
&glob bef-table_c-sum-grp-obj c-sum-grp-obj
&glob bef-table_c-sum-in-sum-group c-sum-in-sum-group
&glob bef-table_c-sysconf c-sysconf
&glob bef-table_c-table-bind c-table-bind
&glob bef-table_c-tare c-tare
&glob bef-table_c-tax c-tax
&glob bef-table_c-tax-hist c-tax-hist
&glob bef-table_c-tax-rate c-tax-rate
&glob bef-table_c-tax-rate-gds-grp c-tax-rate-gds-grp
&glob bef-table_c-tax-units c-tax-units
&glob bef-table_c-tech-prol-pwd c-tech-prol-pwd
&glob bef-table_c-thbj-attr c-thbj-attr
&glob bef-table_c-tnv-in-turnover-group c-tnv-in-turnover-group
&glob bef-table_c-trn-doc c-trn-doc
&glob bef-table_c-trn-doc-sum c-trn-doc-sum
&glob bef-table_c-trn-reason c-trn-reason
&glob bef-table_c-trn-reason-host c-trn-reason-host
&glob bef-table_c-trn-reason-obj c-trn-reason-obj
&glob bef-table_c-trn-rsn-attr c-trn-rsn-attr
&glob bef-table_c-turnover-group c-turnover-group
&glob bef-table_c-units c-units
&glob bef-table_c-user-account c-user-account
&glob bef-table_c-user-log c-user-log
&glob bef-table_c-user-login c-user-login
&glob bef-table_c-usr-hist c-usr-hist
&glob bef-table_c-utd c-utd
&glob bef-table_c-utd-attr c-utd-attr
&glob bef-table_c-utd-err c-utd-err
&glob bef-table_c-utd-err-attr c-utd-err-attr
&glob bef-table_c-utd-head c-utd-head
&glob bef-table_c-utd-lines c-utd-lines
&glob bef-table_c-utd-lines-attr c-utd-lines-attr
&glob bef-table_c-utd-marking-lines c-utd-marking-lines
&glob bef-table_c-utd-marking-lines-attr c-utd-marking-lines-attr
&glob bef-table_c-var-deliv-gr-per-val c-var-deliv-gr-per-val
&glob bef-table_c-variant-delivery c-variant-delivery
&glob bef-table_c-varianty-delivery-gds-obj c-varianty-delivery-gds-obj
&glob bef-table_c-vsd c-vsd
&glob bef-table_c-wealth c-wealth
&glob bef-table_c-wi-mode c-wi-mode
&glob bef-table_c-wi-mode-attr c-wi-mode-attr
&glob bef-table_c-wth-doc c-wth-doc
&glob bef-table_c-wth-dtl c-wth-dtl
&glob bef-table_c-wth-gds c-wth-gds
&glob bef-table_c-wth-gds-attr c-wth-gds-attr
&glob bef-table_c-wth-hist c-wth-hist
&glob bef-table_c-wth-line c-wth-line
&glob bef-table_c-wth-obj c-wth-obj
&glob bef-table_c-wth-par c-wth-par
&glob bef-table_c-wth-parts c-wth-parts
&glob bef-table_c-wth-place c-wth-place
&glob bef-table_c-wth-pobj c-wth-pobj
&glob bef-table_c-wth-ser c-wth-ser
&glob bef-table_c-wth-ser-attr c-wth-ser-attr
&glob bef-table_cash-desk cash-desk
&glob bef-table_cash-desk-attr cash-desk-attr
&glob bef-table_cash-pay cash-pay
&glob bef-table_cash-pay-attr cash-pay-attr
&glob bef-table_CashBook CashBook
&glob bef-table_CashBookAttr CashBookAttr
&glob bef-table_CashBookRule CashBookRule
&glob bef-table_CashBookRuleAttr CashBookRuleAttr
&glob bef-table_cbr-bank cbr-bank
&glob bef-table_cbr-bank-attr cbr-bank-attr
&glob bef-table_cd-clu cd-clu
&glob bef-table_cd-clu-attr cd-clu-attr
&glob bef-table_cd-dlu cd-dlu
&glob bef-table_cd-dlu-attr cd-dlu-attr
&glob bef-table_cd-doc cd-doc
&glob bef-table_cd-doc-attr cd-doc-attr
&glob bef-table_cd-doc-line cd-doc-line
&glob bef-table_cd-doc-line-attr cd-doc-line-attr
&glob bef-table_cd-event-log cd-event-log
&glob bef-table_cd-event-log-attr cd-event-log-attr
&glob bef-table_cd-events cd-events
&glob bef-table_cd-events-attr cd-events-attr
&glob bef-table_cd-grp cd-grp
&glob bef-table_cd-grp-attr cd-grp-attr
&glob bef-table_cd-plu cd-plu
&glob bef-table_cd-plu-attr cd-plu-attr
&glob bef-table_cd-trans cd-trans
&glob bef-table_cd-trans-attr cd-trans-attr
&glob bef-table_cd-video-link cd-video-link
&glob bef-table_cd-video-link-attr cd-video-link-attr
&glob bef-table_chk-discnt chk-discnt
&glob bef-table_chk-discnt-attr chk-discnt-attr
&glob bef-table_chk-doc chk-doc
&glob bef-table_chk-doc-attr chk-doc-attr
&glob bef-table_chk-gds chk-gds
&glob bef-table_chk-gds-attr chk-gds-attr
&glob bef-table_chk-gds-pay chk-gds-pay
&glob bef-table_chk-pay chk-pay
&glob bef-table_chk-pay-attr chk-pay-attr
&glob bef-table_chk-slip-head chk-slip-head
&glob bef-table_chk-slip-string chk-slip-string
&glob bef-table_cli-art cli-art
&glob bef-table_cli-art-attr cli-art-attr
&glob bef-table_cli-gds cli-gds
&glob bef-table_cli-gds-attr cli-gds-attr
&glob bef-table_cli-grp cli-grp
&glob bef-table_cli-grp-attr cli-grp-attr
&glob bef-table_clients clients
&glob bef-table_clients-attr clients-attr
&glob bef-table_clob-bind clob-bind
&glob bef-table_clob-data clob-data
&glob bef-table_Code Code
&glob bef-table_code-range code-range
&glob bef-table_condition-keeping condition-keeping
&glob bef-table_condition-keeping-attr condition-keeping-attr
&glob bef-table_config config
&glob bef-table_contract contract
&glob bef-table_contract-attr contract-attr
&glob bef-table_contract-line contract-line
&glob bef-table_contract-line-attr contract-line-attr
&glob bef-table_contract-specif contract-specif
&glob bef-table_contract-specif-attr contract-specif-attr
&glob bef-table_counter counter
&glob bef-table_country country
&glob bef-table_country-attr country-attr
&glob bef-table_criterion-analysis criterion-analysis
&glob bef-table_criterion-analysis-attr criterion-analysis-attr
&glob bef-table_cshr-month cshr-month
&glob bef-table_cshr-month-attr cshr-month-attr
&glob bef-table_curr-accnt curr-accnt
&glob bef-table_curr-accnt-attr curr-accnt-attr
&glob bef-table_curr-bank curr-bank
&glob bef-table_curr-bank-attr curr-bank-attr
&glob bef-table_curr-shop curr-shop
&glob bef-table_curr-shop-attr curr-shop-attr
&glob bef-table_currency currency
&glob bef-table_currency-attr currency-attr
&glob bef-table_custom-labels custom-labels
&glob bef-table_datatype-exp datatype-exp
&glob bef-table_datatype-exp-attr datatype-exp-attr
&glob bef-table_datatype-imp datatype-imp
&glob bef-table_datatype-imp-attr datatype-imp-attr
&glob bef-table_datatype-table datatype-table
&glob bef-table_datatype-table-exp datatype-table-exp
&glob bef-table_datatype-table-field datatype-table-field
&glob bef-table_datatype-table-field-exp datatype-table-field-exp
&glob bef-table_datatype-table-field-imp datatype-table-field-imp
&glob bef-table_datatype-table-imp datatype-table-imp
&glob bef-table_db db
&glob bef-table_db-attr db-attr
&glob bef-table_db-filter db-filter
&glob bef-table_db-filter-attr db-filter-attr
&glob bef-table_db-grp-obj-price db-grp-obj-price
&glob bef-table_db-grp-obj-price-attr db-grp-obj-price-attr
&glob bef-table_db-info db-info
&glob bef-table_db-rec-attr db-rec-attr
&glob bef-table_db-status db-status
&glob bef-table_db-status-attr db-status-attr
&glob bef-table_db-usr-flt db-usr-flt
&glob bef-table_db-usr-flt-attr db-usr-flt-attr
&glob bef-table_deliv-type-cond-keep deliv-type-cond-keep
&glob bef-table_deliv-type-cond-keep-attr deliv-type-cond-keep-attr
&glob bef-table_delivery-subject delivery-subject
&glob bef-table_delivery-subject-attr delivery-subject-attr
&glob bef-table_delivery-type delivery-type
&glob bef-table_delivery-type-attr delivery-type-attr
&glob bef-table_delivery-type-subject delivery-type-subject
&glob bef-table_delivery-type-subject-attr delivery-type-subject-attr
&glob bef-table_devisPC devisPC
&glob bef-table_devisPC-attr devisPC-attr
&glob bef-table_dis-card dis-card
&glob bef-table_dis-card-long dis-card-long
&glob bef-table_dis-card-long-attr dis-card-long-attr
&glob bef-table_dis-card-mask dis-card-mask
&glob bef-table_dis-card-mask-attr dis-card-mask-attr
&glob bef-table_dis-card-property dis-card-property
&glob bef-table_dis-card-type dis-card-type
&glob bef-table_dis-card-type-attr dis-card-type-attr
&glob bef-table_dis-cfg-rule dis-cfg-rule
&glob bef-table_dis-cfg-rule-attr dis-cfg-rule-attr
&glob bef-table_dis-cp-rule dis-cp-rule
&glob bef-table_dis-cp-rule-attr dis-cp-rule-attr
&glob bef-table_dis-dc-rule dis-dc-rule
&glob bef-table_dis-dc-rule-attr dis-dc-rule-attr
&glob bef-table_dis-dct-rule dis-dct-rule
&glob bef-table_dis-dct-rule-attr dis-dct-rule-attr
&glob bef-table_dis-gds-rule dis-gds-rule
&glob bef-table_dis-gds-rule-attr dis-gds-rule-attr
&glob bef-table_dis-grp-rule dis-grp-rule
&glob bef-table_dis-grp-rule-attr dis-grp-rule-attr
&glob bef-table_dis-host dis-host
&glob bef-table_dis-obj dis-obj
&glob bef-table_dis-rule dis-rule
&glob bef-table_dis-rule-attr dis-rule-attr
&glob bef-table_dis-some-rule dis-some-rule
&glob bef-table_dis-some-rule-attr dis-some-rule-attr
&glob bef-table_dis-thbj-rule dis-thbj-rule
&glob bef-table_dis-thbj-rule-attr dis-thbj-rule-attr
&glob bef-table_dis-time-rule dis-time-rule
&glob bef-table_dis-time-rule-attr dis-time-rule-attr
&glob bef-table_dish-grp dish-grp
&glob bef-table_dish-grp-attr dish-grp-attr
&glob bef-table_doc-abc-def doc-abc-def
&glob bef-table_doc-abc-def-attr doc-abc-def-attr
&glob bef-table_doc-abc-def-doc doc-abc-def-doc
&glob bef-table_doc-abc-def-doc-attr doc-abc-def-doc-attr
&glob bef-table_doc-abc-def-obj doc-abc-def-obj
&glob bef-table_doc-abc-def-obj-attr doc-abc-def-obj-attr
&glob bef-table_doc-attr doc-attr
&glob bef-table_doc-fact-num doc-fact-num
&glob bef-table_doc-fact-num-attr doc-fact-num-attr
&glob bef-table_doc-fbr-gds doc-fbr-gds
&glob bef-table_doc-fbr-gds-attr doc-fbr-gds-attr
&glob bef-table_doc-filter doc-filter
&glob bef-table_doc-filter-attr doc-filter-attr
&glob bef-table_doc-filter-head doc-filter-head
&glob bef-table_doc-filter-head-attr doc-filter-head-attr
&glob bef-table_doc-line doc-line
&glob bef-table_doc-line-attr doc-line-attr
&glob bef-table_doc-line-sum doc-line-sum
&glob bef-table_doc-pl doc-pl
&glob bef-table_doc-pl-attr doc-pl-attr
&glob bef-table_doc-pl-pump doc-pl-pump
&glob bef-table_doc-pl-pump-attr doc-pl-pump-attr
&glob bef-table_doc-prts doc-prts
&glob bef-table_doc-prts-attr doc-prts-attr
&glob bef-table_doc-xyz-def doc-xyz-def
&glob bef-table_doc-xyz-def-attr doc-xyz-def-attr
&glob bef-table_doc-xyz-def-doc doc-xyz-def-doc
&glob bef-table_doc-xyz-def-doc-attr doc-xyz-def-doc-attr
&glob bef-table_doc-xyz-def-obj doc-xyz-def-obj
&glob bef-table_doc-xyz-def-obj-attr doc-xyz-def-obj-attr
&glob bef-table_drt-prop drt-prop
&glob bef-table_edi-status edi-status
&glob bef-table_egais-clients egais-clients
&glob bef-table_egais-gds egais-gds
&glob bef-table_esys-all-attr esys-all-attr
&glob bef-table_esys-datatype-exp esys-datatype-exp
&glob bef-table_esys-datatype-imp esys-datatype-imp
&glob bef-table_esys-pck-keys esys-pck-keys
&glob bef-table_esys-pck-rcvd esys-pck-rcvd
&glob bef-table_esys-pck-sent esys-pck-sent
&glob bef-table_esys-route esys-route
&glob bef-table_esys-route-dump esys-route-dump
&glob bef-table_ex-mark ex-mark
&glob bef-table_ex-mark-attr ex-mark-attr
&glob bef-table_ext-artic ext-artic
&glob bef-table_ext-artic-attr ext-artic-attr
&glob bef-table_ext-artic-db ext-artic-db
&glob bef-table_ext-artic-db-attr ext-artic-db-attr
&glob bef-table_ext-artic-host ext-artic-host
&glob bef-table_ext-artic-host-attr ext-artic-host-attr
&glob bef-table_ext-artic-obj ext-artic-obj
&glob bef-table_ext-artic-obj-attr ext-artic-obj-attr
&glob bef-table_ext-classif ext-classif
&glob bef-table_ext-classif-attr ext-classif-attr
&glob bef-table_ext-file ext-file
&glob bef-table_ext-file-attr ext-file-attr
&glob bef-table_ext-file-line ext-file-line
&glob bef-table_ext-file-line-attr ext-file-line-attr
&glob bef-table_ext-file-par ext-file-par
&glob bef-table_ext-file-par-attr ext-file-par-attr
&glob bef-table_ext-system ext-system
&glob bef-table_ext-system-attr ext-system-attr
&glob bef-table_factur-connect factur-connect
&glob bef-table_factur-connect-attr factur-connect-attr
&glob bef-table_factur-connect-line factur-connect-line
&glob bef-table_factur-connect-line-attr factur-connect-line-attr
&glob bef-table_fbr-doc fbr-doc
&glob bef-table_fbr-gds-grp fbr-gds-grp
&glob bef-table_fbr-gds-grp-attr fbr-gds-grp-attr
&glob bef-table_fbr-gds-obj fbr-gds-obj
&glob bef-table_fbr-gds-obj-attr fbr-gds-obj-attr
&glob bef-table_fbr-history fbr-history
&glob bef-table_fbr-line fbr-line
&glob bef-table_fbr-pln fbr-pln
&glob bef-table_fbr-pln-line fbr-pln-line
&glob bef-table_fbr-prn fbr-prn
&glob bef-table_fbr-prn-attr fbr-prn-attr
&glob bef-table_fbr-prn-gds fbr-prn-gds
&glob bef-table_fbr-prn-gds-attr fbr-prn-gds-attr
&glob bef-table_fbr-prn-grp fbr-prn-grp
&glob bef-table_fbr-prn-grp-attr fbr-prn-grp-attr
&glob bef-table_fbr-recipe fbr-recipe
&glob bef-table_fbr-recipe-gds fbr-recipe-gds
&glob bef-table_feature feature
&glob bef-table_feature-attr feature-attr
&glob bef-table_feature-scale feature-scale
&glob bef-table_feature-scale-attr feature-scale-attr
&glob bef-table_Filter Filter
&glob bef-table_Filter-attr Filter-attr
&glob bef-table_fin-bank fin-bank
&glob bef-table_fin-bank-attr fin-bank-attr
&glob bef-table_fin-code-an-uchet fin-code-an-uchet
&glob bef-table_fin-code-an-uchet-attr fin-code-an-uchet-attr
&glob bef-table_fin-code-cel-nazn fin-code-cel-nazn
&glob bef-table_fin-code-cel-nazn-attr fin-code-cel-nazn-attr
&glob bef-table_fin-code-cor-acc fin-code-cor-acc
&glob bef-table_fin-code-cor-acc-attr fin-code-cor-acc-attr
&glob bef-table_fin-connect fin-connect
&glob bef-table_fin-connect-attr fin-connect-attr
&glob bef-table_fin-doc fin-doc
&glob bef-table_fin-doc-attr fin-doc-attr
&glob bef-table_fin-doc-cor-acc-lk fin-doc-cor-acc-lk
&glob bef-table_fin-doc-cor-acc-lk-attr fin-doc-cor-acc-lk-attr
&glob bef-table_fin-doc-obj fin-doc-obj
&glob bef-table_fin-doc-obj-attr fin-doc-obj-attr
&glob bef-table_fin-doc-schet-lk fin-doc-schet-lk
&glob bef-table_fin-doc-schet-lk-attr fin-doc-schet-lk-attr
&glob bef-table_fin-doc-tax fin-doc-tax
&glob bef-table_fin-doc-tax-attr fin-doc-tax-attr
&glob bef-table_fin-gds-part fin-gds-part
&glob bef-table_fin-gds-part-attr fin-gds-part-attr
&glob bef-table_fin-ob fin-ob
&glob bef-table_fin-ob-attr fin-ob-attr
&glob bef-table_fin-ob-before fin-ob-before
&glob bef-table_fin-ob-cor-acc-lk fin-ob-cor-acc-lk
&glob bef-table_fin-ob-cor-acc-lk-attr fin-ob-cor-acc-lk-attr
&glob bef-table_fin-ob-schet-lk fin-ob-schet-lk
&glob bef-table_fin-ob-schet-lk-attr fin-ob-schet-lk-attr
&glob bef-table_fin-ob-tax fin-ob-tax
&glob bef-table_fin-ob-tax-attr fin-ob-tax-attr
&glob bef-table_fin-ob-tax-before fin-ob-tax-before
&glob bef-table_fin-ob-trn fin-ob-trn
&glob bef-table_fin-ob-trn-attr fin-ob-trn-attr
&glob bef-table_fin-schet fin-schet
&glob bef-table_fin-schet-attr fin-schet-attr
&glob bef-table_fin-statement fin-statement
&glob bef-table_fin-statement-attr fin-statement-attr
&glob bef-table_fin-statement-line fin-statement-line
&glob bef-table_fin-statement-line-attr fin-statement-line-attr
&glob bef-table_firm firm
&glob bef-table_gds-add-charges gds-add-charges
&glob bef-table_gds-add-charges-attr gds-add-charges-attr
&glob bef-table_gds-dtl gds-dtl
&glob bef-table_gds-dtl-attr gds-dtl-attr
&glob bef-table_gds-grp gds-grp
&glob bef-table_gds-grp-attr gds-grp-attr
&glob bef-table_gds-grp-obj gds-grp-obj
&glob bef-table_gds-grp-obj-attr gds-grp-obj-attr
&glob bef-table_gds-host-attr gds-host-attr
&glob bef-table_gds-mercury gds-mercury
&glob bef-table_gds-mercury-attr gds-mercury-attr
&glob bef-table_gds-obj gds-obj
&glob bef-table_gds-obj-attr gds-obj-attr
&glob bef-table_gds-obj-flag gds-obj-flag
&glob bef-table_gds-obj-flag-attr gds-obj-flag-attr
&glob bef-table_gds-obj-prop gds-obj-prop
&glob bef-table_gds-obj-prop-attr gds-obj-prop-attr
&glob bef-table_gds-prt gds-prt
&glob bef-table_gds-prt-attr gds-prt-attr
&glob bef-table_gds-season gds-season
&glob bef-table_gds-season-attr gds-season-attr
&glob bef-table_gen-attr gen-attr
&glob bef-table_global-state global-state
&glob bef-table_global-state-attr global-state-attr
&glob bef-table_goods goods
&glob bef-table_goods-attr goods-attr
&glob bef-table_group-period-validity group-period-validity
&glob bef-table_group-period-validity-attr group-period-validity-attr
&glob bef-table_grp-obj-price grp-obj-price
&glob bef-table_grp-obj-price-attr grp-obj-price-attr
&glob bef-table_h-route h-route
&glob bef-table_h-route-dump h-route-dump
&glob bef-table_hist-nws-option hist-nws-option
&glob bef-table_hist-nws-option-attr hist-nws-option-attr
&glob bef-table_hold-attr hold-attr
&glob bef-table_hold-gds-grp hold-gds-grp
&glob bef-table_hold-gds-grp-attr hold-gds-grp-attr
&glob bef-table_hold-goods hold-goods
&glob bef-table_hold-goods-attr hold-goods-attr
&glob bef-table_hold-purch hold-purch
&glob bef-table_hold-purch-attr hold-purch-attr
&glob bef-table_hold-purch-grp hold-purch-grp
&glob bef-table_hold-purch-grp-attr hold-purch-grp-attr
&glob bef-table_hold-purch-supp hold-purch-supp
&glob bef-table_hold-purch-supp-attr hold-purch-supp-attr
&glob bef-table_hold-purch-supp-gds hold-purch-supp-gds
&glob bef-table_hold-purch-supp-gds-attr hold-purch-supp-gds-attr
&glob bef-table_hold-sale hold-sale
&glob bef-table_hold-sale-attr hold-sale-attr
&glob bef-table_hold-sale-grp hold-sale-grp
&glob bef-table_hold-sale-grp-attr hold-sale-grp-attr
&glob bef-table_hold-time hold-time
&glob bef-table_hold-time-attr hold-time-attr
&glob bef-table_hold-trn hold-trn
&glob bef-table_hold-trn-attr hold-trn-attr
&glob bef-table_host-grp-obj-price host-grp-obj-price
&glob bef-table_host-grp-obj-price-attr host-grp-obj-price-attr
&glob bef-table_host-lk host-lk
&glob bef-table_host-lk-attr host-lk-attr
&glob bef-table_icnt-doc icnt-doc
&glob bef-table_icnt-line icnt-line
&glob bef-table_inkas inkas
&glob bef-table_inkas-pay inkas-pay
&glob bef-table_inkas-pay-attr inkas-pay-attr
&glob bef-table_inkas-pay-desk inkas-pay-desk
&glob bef-table_inkas-pay-desk-attr inkas-pay-desk-attr
&glob bef-table_inkas-pay-wth inkas-pay-wth
&glob bef-table_inv-doc inv-doc
&glob bef-table_inv-doc-attr inv-doc-attr
&glob bef-table_inv-line inv-line
&glob bef-table_inv-line-attr inv-line-attr
&glob bef-table_lang lang
&glob bef-table_lang-attr lang-attr
&glob bef-table_layout layout
&glob bef-table_layout-attr layout-attr
&glob bef-table_layout-elem layout-elem
&glob bef-table_layout-elem-attr layout-elem-attr
&glob bef-table_layout-elem-rule layout-elem-rule
&glob bef-table_layout-elem-rule-attr layout-elem-rule-attr
&glob bef-table_lvl-name lvl-name
&glob bef-table_lvl-name-attr lvl-name-attr
&glob bef-table_marking marking
&glob bef-table_marking-attr marking-attr
&glob bef-table_marking-chk marking-chk
&glob bef-table_marking-lines marking-lines
&glob bef-table_menu-group menu-group
&glob bef-table_menu-group-attr menu-group-attr
&glob bef-table_menu-head menu-head
&glob bef-table_menu-head-attr menu-head-attr
&glob bef-table_menu-item menu-item
&glob bef-table_menu-item-attr menu-item-attr
&glob bef-table_menu-item-group menu-item-group
&glob bef-table_menu-item-group-attr menu-item-group-attr
&glob bef-table_menu-user menu-user
&glob bef-table_menu-user-attr menu-user-attr
&glob bef-table_menu-user-call menu-user-call
&glob bef-table_menu-user-call-attr menu-user-call-attr
&glob bef-table_norm-loss norm-loss
&glob bef-table_nozzle nozzle
&glob bef-table_nozzle-attr nozzle-attr
&glob bef-table_nws-doc-hist nws-doc-hist
&glob bef-table_nws-doc-hist-attr nws-doc-hist-attr
&glob bef-table_nws-last-rec nws-last-rec
&glob bef-table_nws-last-rec-attr nws-last-rec-attr
&glob bef-table_nws-outline nws-outline
&glob bef-table_obj-date obj-date
&glob bef-table_obj-grp-obj-price obj-grp-obj-price
&glob bef-table_obj-grp-obj-price-attr obj-grp-obj-price-attr
&glob bef-table_OperServ OperServ
&glob bef-table_OperServAttr OperServAttr
&glob bef-table_ord-blank ord-blank
&glob bef-table_ord-blank-attr ord-blank-attr
&glob bef-table_ord-chain ord-chain
&glob bef-table_ord-chain-attr ord-chain-attr
&glob bef-table_ord-cons ord-cons
&glob bef-table_ord-cons-attr ord-cons-attr
&glob bef-table_ord-cons-line-attr ord-cons-line-attr
&glob bef-table_ord-doc ord-doc
&glob bef-table_ord-doc-attr ord-doc-attr
&glob bef-table_ord-doc-rcv ord-doc-rcv
&glob bef-table_ord-dtl ord-dtl
&glob bef-table_ord-dtl-attr ord-dtl-attr
&glob bef-table_ord-dtl-cons ord-dtl-cons
&glob bef-table_ord-dtl-rcv ord-dtl-rcv
&glob bef-table_ord-gds-cons ord-gds-cons
&glob bef-table_ord-line ord-line
&glob bef-table_ord-line-attr ord-line-attr
&glob bef-table_ord-line-rcv ord-line-rcv
&glob bef-table_ord-rcv-attr ord-rcv-attr
&glob bef-table_ord-rcv-line-attr ord-rcv-line-attr
&glob bef-table_ot-line ot-line
&glob bef-table_ot-line-attr ot-line-attr
&glob bef-table_ot-supp-line ot-supp-line
&glob bef-table_ot-supp-line-attr ot-supp-line-attr
&glob bef-table_ot-supp-tot ot-supp-tot
&glob bef-table_ot-supp-tot-attr ot-supp-tot-attr
&glob bef-table_ot-tot ot-tot
&glob bef-table_ot-tot-attr ot-tot-attr
&glob bef-table_parts parts
&glob bef-table_parts-add parts-add
&glob bef-table_parts-add-attr parts-add-attr
&glob bef-table_parts-attr parts-attr
&glob bef-table_parts-obj-attr parts-obj-attr
&glob bef-table_parts-root parts-root
&glob bef-table_parts-root-attr parts-root-attr
&glob bef-table_parts-supp parts-supp
&glob bef-table_parts-supp-attr parts-supp-attr
&glob bef-table_pay-type pay-type
&glob bef-table_pay-type-attr pay-type-attr
&glob bef-table_payment payment
&glob bef-table_payment-attr payment-attr
&glob bef-table_pck-keys pck-keys
&glob bef-table_pck-rcvd pck-rcvd
&glob bef-table_pck-rcvd-attr pck-rcvd-attr
&glob bef-table_pck-sent pck-sent
&glob bef-table_pck-sent-attr pck-sent-attr
&glob bef-table_person person
&glob bef-table_pl-gds pl-gds
&glob bef-table_pl-gds-attr pl-gds-attr
&glob bef-table_pl-gds-pump pl-gds-pump
&glob bef-table_pl-gds-pump-attr pl-gds-pump-attr
&glob bef-table_pl-level pl-level
&glob bef-table_pl-level-attr pl-level-attr
&glob bef-table_pl-pump pl-pump
&glob bef-table_pl-pump-attr pl-pump-attr
&glob bef-table_pl-pump-nozzle pl-pump-nozzle
&glob bef-table_pl-pump-nozzle-attr pl-pump-nozzle-attr
&glob bef-table_place place
&glob bef-table_place-attr place-attr
&glob bef-table_place-io place-io
&glob bef-table_place-io-attr place-io-attr
&glob bef-table_point-io point-io
&glob bef-table_point-io-attr point-io-attr
&glob bef-table_point-place-rel point-place-rel
&glob bef-table_point-point-rel point-point-rel
&glob bef-table_price-all price-all
&glob bef-table_price-all-attr price-all-attr
&glob bef-table_price-doc price-doc
&glob bef-table_price-doc-forming price-doc-forming
&glob bef-table_price-doc-forming-attr price-doc-forming-attr
&glob bef-table_price-doc-forming-gds price-doc-forming-gds
&glob bef-table_price-doc-forming-gds-qnty price-doc-forming-gds-qnty
&glob bef-table_price-doc-forming-gds-sum price-doc-forming-gds-sum
&glob bef-table_price-doc-forming-gds-tnv price-doc-forming-gds-tnv
&glob bef-table_price-doc-forming-gdsattr price-doc-forming-gdsattr
&glob bef-table_price-list price-list
&glob bef-table_price-list-attr price-list-attr
&glob bef-table_price-list-type price-list-type
&glob bef-table_price-list-type-attr price-list-type-attr
&glob bef-table_price-list-type-cash-pay price-list-type-cash-pay
&glob bef-table_price-list-type-cassa price-list-type-cassa
&glob bef-table_price-list-type-cassa-attr price-list-type-cassa-attr
&glob bef-table_price-list-type-gds-grp price-list-type-gds-grp
&glob bef-table_price-list-type-gds-grp-attr price-list-type-gds-grp-attr
&glob bef-table_price-list-type-pay-type price-list-type-pay-type
&glob bef-table_prod-bc prod-bc
&glob bef-table_prod-bc-attr prod-bc-attr
&glob bef-table_prod-bc-db prod-bc-db
&glob bef-table_prod-bc-db-attr prod-bc-db-attr
&glob bef-table_profile-by-profile profile-by-profile
&glob bef-table_prog-message prog-message
&glob bef-table_prog-message-attr prog-message-attr
&glob bef-table_prog-message-lang prog-message-lang
&glob bef-table_prog-message-lang-attr prog-message-lang-attr
&glob bef-table_promo-schedule promo-schedule
&glob bef-table_promo-schedule-week promo-schedule-week
&glob bef-table_PromoAction PromoAction
&glob bef-table_PromoAttr PromoAttr
&glob bef-table_PromoCriterion PromoCriterion
&glob bef-table_PromoGift PromoGift
&glob bef-table_PromoGoods PromoGoods
&glob bef-table_PromoObject PromoObject
&glob bef-table_prop-head prop-head
&glob bef-table_prop-head-attr prop-head-attr
&glob bef-table_prop-map prop-map
&glob bef-table_prop-map-attr prop-map-attr
&glob bef-table_prop-ref prop-ref
&glob bef-table_prop-ref-attr prop-ref-attr
&glob bef-table_prop-ref-call prop-ref-call
&glob bef-table_prop-ref-call-attr prop-ref-call-attr
&glob bef-table_prop-ruleset prop-ruleset
&glob bef-table_prop-ruleset-attr prop-ruleset-attr
&glob bef-table_prop-script prop-script
&glob bef-table_prop-script-attr prop-script-attr
&glob bef-table_prt-obj prt-obj
&glob bef-table_prt-obj-attr prt-obj-attr
&glob bef-table_pscript-ruleset pscript-ruleset
&glob bef-table_pscript-ruleset-attr pscript-ruleset-attr
&glob bef-table_pump pump
&glob bef-table_pump-attr pump-attr
&glob bef-table_pump-nozzle pump-nozzle
&glob bef-table_pump-nozzle-attr pump-nozzle-attr
&glob bef-table_qnty-group qnty-group
&glob bef-table_qnty-group-attr qnty-group-attr
&glob bef-table_qnty-in-qnty-group qnty-in-qnty-group
&glob bef-table_qnty-in-qnty-group-attr qnty-in-qnty-group-attr
&glob bef-table_rang-abc-def rang-abc-def
&glob bef-table_rang-abc-def-attr rang-abc-def-attr
&glob bef-table_rang-abc-def-obj rang-abc-def-obj
&glob bef-table_rang-abc-def-obj-attr rang-abc-def-obj-attr
&glob bef-table_rang-xyz-def rang-xyz-def
&glob bef-table_rang-xyz-def-attr rang-xyz-def-attr
&glob bef-table_rang-xyz-def-obj rang-xyz-def-obj
&glob bef-table_rang-xyz-def-obj-attr rang-xyz-def-obj-attr
&glob bef-table_rcs-attr rcs-attr
&glob bef-table_rcs-chkbody rcs-chkbody
&glob bef-table_rcs-chkhead rcs-chkhead
&glob bef-table_rcs-city rcs-city
&glob bef-table_rcs-clients rcs-clients
&glob bef-table_rcs-country rcs-country
&glob bef-table_rcs-destn rcs-destn
&glob bef-table_rcs-docbody rcs-docbody
&glob bef-table_rcs-dochead rcs-dochead
&glob bef-table_rcs-mark rcs-mark
&glob bef-table_rcs-pack rcs-pack
&glob bef-table_rcs-place rcs-place
&glob bef-table_rcs-retail1action rcs-retail1action
&glob bef-table_rcs-retail1attr rcs-retail1attr
&glob bef-table_rcs-retail1bank rcs-retail1bank
&glob bef-table_rcs-retail1barcode rcs-retail1barcode
&glob bef-table_rcs-retail1bill rcs-retail1bill
&glob bef-table_rcs-retail1billitem rcs-retail1billitem
&glob bef-table_rcs-retail1convolution rcs-retail1convolution
&glob bef-table_rcs-retail1delete rcs-retail1delete
&glob bef-table_rcs-retail1fortuneproduct rcs-retail1fortuneproduct
&glob bef-table_rcs-retail1price rcs-retail1price
&glob bef-table_rcs-retail1priceitem rcs-retail1priceitem
&glob bef-table_rcs-retail1product rcs-retail1product
&glob bef-table_rcs-retail1subject rcs-retail1subject
&glob bef-table_rcs-shops rcs-shops
&glob bef-table_recipe recipe
&glob bef-table_recipe-develop recipe-develop
&glob bef-table_recipe-gds recipe-gds
&glob bef-table_regions regions
&glob bef-table_regions-attr regions-attr
&glob bef-table_rename-fld rename-fld
&glob bef-table_rename-fld-attr rename-fld-attr
&glob bef-table_rep rep
&glob bef-table_rep-line rep-line
&glob bef-table_res-lang res-lang
&glob bef-table_res-lang-attr res-lang-attr
&glob bef-table_resource resource
&glob bef-table_resource-attr resource-attr
&glob bef-table_route route
&glob bef-table_route-attr route-attr
&glob bef-table_route-dump route-dump
&glob bef-table_route-dump-attr route-dump-attr
&glob bef-table_route-dump-link route-dump-link
&glob bef-table_rp-by-call rp-by-call
&glob bef-table_rp-by-call-attr rp-by-call-attr
&glob bef-table_rp-rule-param rp-rule-param
&glob bef-table_rp-rule-param-attr rp-rule-param-attr
&glob bef-table_rpt-option rpt-option
&glob bef-table_rpt-option-attr rpt-option-attr
&glob bef-table_rule rule
&glob bef-table_rule-attr rule-attr
&glob bef-table_rule-by-call rule-by-call
&glob bef-table_rule-by-call-attr rule-by-call-attr
&glob bef-table_rule-by-profile rule-by-profile
&glob bef-table_rule-by-profile-attr rule-by-profile-attr
&glob bef-table_rule-by-set rule-by-set
&glob bef-table_rule-by-set-attr rule-by-set-attr
&glob bef-table_rule-call-param rule-call-param
&glob bef-table_rule-call-param-attr rule-call-param-attr
&glob bef-table_rule-i-script rule-i-script
&glob bef-table_rule-i-script-attr rule-i-script-attr
&glob bef-table_rule-process rule-process
&glob bef-table_rule-profile rule-profile
&glob bef-table_rule-profile-attr rule-profile-attr
&glob bef-table_rule-script rule-script
&glob bef-table_rule-script-attr rule-script-attr
&glob bef-table_rule-trans-memo rule-trans-memo
&glob bef-table_rule-trans-memo-attr rule-trans-memo-attr
&glob bef-table_ruledict ruledict
&glob bef-table_ruledict-attr ruledict-attr
&glob bef-table_ruledict-param ruledict-param
&glob bef-table_ruledict-param-attr ruledict-param-attr
&glob bef-table_ruleset ruleset
&glob bef-table_ruleset-attr ruleset-attr
&glob bef-table_rvs-doc rvs-doc
&glob bef-table_rvs-doc-attr rvs-doc-attr
&glob bef-table_rvs-line rvs-line
&glob bef-table_rvs-line-attr rvs-line-attr
&glob bef-table_rvs-line-pump rvs-line-pump
&glob bef-table_rvs-line-pump-attr rvs-line-pump-attr
&glob bef-table_rvs-pump rvs-pump
&glob bef-table_rvs-pump-attr rvs-pump-attr
&glob bef-table_s-coeff s-coeff
&glob bef-table_s-coeff-attr s-coeff-attr
&glob bef-table_sale-doc sale-doc
&glob bef-table_sale-doc-attr sale-doc-attr
&glob bef-table_scales scales
&glob bef-table_scales-attr scales-attr
&glob bef-table_scales-gds scales-gds
&glob bef-table_scales-gds-attr scales-gds-attr
&glob bef-table_scales-grp scales-grp
&glob bef-table_scales-grp-attr scales-grp-attr
&glob bef-table_schedule schedule
&glob bef-table_schedule-attr schedule-attr
&glob bef-table_schet-fact-doc schet-fact-doc
&glob bef-table_schet-fact-doc-attr schet-fact-doc-attr
&glob bef-table_schet-fact-line schet-fact-line
&glob bef-table_schet-fact-line-attr schet-fact-line-attr
&glob bef-table_season season
&glob bef-table_season-attr season-attr
&glob bef-table_sert sert
&glob bef-table_sert-attr sert-attr
&glob bef-table_sert-join sert-join
&glob bef-table_sert-join-attr sert-join-attr
&glob bef-table_shift-attr shift-attr
&glob bef-table_shift-cash shift-cash
&glob bef-table_shift-cash-attr shift-cash-attr
&glob bef-table_shift-obj shift-obj
&glob bef-table_shift-obj-attr shift-obj-attr
&glob bef-table_shift-staff shift-staff
&glob bef-table_shift-staff-attr shift-staff-attr
&glob bef-table_shop shop
&glob bef-table_some-lk some-lk
&glob bef-table_some-lk-attr some-lk-attr
&glob bef-table_sr-izmerenia sr-izmerenia
&glob bef-table_sr-izmerenia-attr sr-izmerenia-attr
&glob bef-table_staff staff
&glob bef-table_staff-attr staff-attr
&glob bef-table_stk-line stk-line
&glob bef-table_stk-line-attr stk-line-attr
&glob bef-table_stk-supp-line stk-supp-line
&glob bef-table_stk-supp-line-attr stk-supp-line-attr
&glob bef-table_stk-supp-tot stk-supp-tot
&glob bef-table_stk-supp-tot-attr stk-supp-tot-attr
&glob bef-table_stk-tot stk-tot
&glob bef-table_stk-tot-attr stk-tot-attr
&glob bef-table_stop-list stop-list
&glob bef-table_stop-list-attr stop-list-attr
&glob bef-table_stop-list-line stop-list-line
&glob bef-table_stop-list-line-attr stop-list-line-attr
&glob bef-table_store store
&glob bef-table_sum-group sum-group
&glob bef-table_sum-group-attr sum-group-attr
&glob bef-table_sum-grp sum-grp
&glob bef-table_sum-grp-attr sum-grp-attr
&glob bef-table_sum-grp-obj sum-grp-obj
&glob bef-table_sum-grp-obj-attr sum-grp-obj-attr
&glob bef-table_sum-in-sum-group sum-in-sum-group
&glob bef-table_sum-in-sum-group-attr sum-in-sum-group-attr
&glob bef-table_sys-ctrl sys-ctrl
&glob bef-table_sys-ctrl-attr sys-ctrl-attr
&glob bef-table_sysconf sysconf
&glob bef-table_sysconf-attr sysconf-attr
&glob bef-table_tare tare
&glob bef-table_tax tax
&glob bef-table_tax-attr tax-attr
&glob bef-table_tax-rate tax-rate
&glob bef-table_tax-rate-attr tax-rate-attr
&glob bef-table_tax-rate-gds tax-rate-gds
&glob bef-table_tax-rate-gds-attr tax-rate-gds-attr
&glob bef-table_tax-rate-gds-grp tax-rate-gds-grp
&glob bef-table_tax-rate-gds-grp-attr tax-rate-gds-grp-attr
&glob bef-table_tax-rate-value tax-rate-value
&glob bef-table_tax-rate-value-attr tax-rate-value-attr
&glob bef-table_tax-units tax-units
&glob bef-table_tax-units-attr tax-units-attr
&glob bef-table_tech-prol-pwd tech-prol-pwd
&glob bef-table_thbj-attr thbj-attr
&glob bef-table_tmp-sale tmp-sale
&glob bef-table_tmp-sale-attr tmp-sale-attr
&glob bef-table_tmp-sale-dtl tmp-sale-dtl
&glob bef-table_tmp-sale-dtl-attr tmp-sale-dtl-attr
&glob bef-table_tmp-sale-gds tmp-sale-gds
&glob bef-table_tmp-sale-gds-attr tmp-sale-gds-attr
&glob bef-table_tnv-in-turnover-group tnv-in-turnover-group
&glob bef-table_tnv-in-turnover-group-attr tnv-in-turnover-group-attr
&glob bef-table_tnved-head tnved-head
&glob bef-table_tnved-head-attr tnved-head-attr
&glob bef-table_tnved-item tnved-item
&glob bef-table_tnved-item-attr tnved-item-attr
&glob bef-table_tran-fuel tran-fuel
&glob bef-table_trn-doc trn-doc
&glob bef-table_trn-doc-sum trn-doc-sum
&glob bef-table_trn-reason trn-reason
&glob bef-table_trn-reason-host trn-reason-host
&glob bef-table_trn-reason-obj trn-reason-obj
&glob bef-table_trn-rsn-attr trn-rsn-attr
&glob bef-table_turnover-buyer turnover-buyer
&glob bef-table_turnover-buyer-attr turnover-buyer-attr
&glob bef-table_turnover-buyer-gds turnover-buyer-gds
&glob bef-table_turnover-buyer-gds-attr turnover-buyer-gds-attr
&glob bef-table_turnover-buyer-main turnover-buyer-main
&glob bef-table_turnover-buyer-main-attr turnover-buyer-main-attr
&glob bef-table_turnover-group turnover-group
&glob bef-table_turnover-group-attr turnover-group-attr
&glob bef-table_units units
&glob bef-table_units-attr units-attr
&glob bef-table_upgrade upgrade
&glob bef-table_upgrade-attr upgrade-attr
&glob bef-table_user-account user-account
&glob bef-table_user-account-attr user-account-attr
&glob bef-table_user-conn user-conn
&glob bef-table_user-conn-attr user-conn-attr
&glob bef-table_user-context-history user-context-history
&glob bef-table_user-context-history-attr user-context-history-attr
&glob bef-table_user-host user-host
&glob bef-table_user-host-attr user-host-attr
&glob bef-table_user-login user-login
&glob bef-table_user-login-action-item user-login-action-item
&glob bef-table_user-login-action-item-attr user-login-action-item-attr
&glob bef-table_user-login-action-role user-login-action-role
&glob bef-table_user-login-action-role-attr user-login-action-role-attr
&glob bef-table_user-login-attr user-login-attr
&glob bef-table_user-menu-group user-menu-group
&glob bef-table_user-menu-group-attr user-menu-group-attr
&glob bef-table_user-obj user-obj
&glob bef-table_user-obj-attr user-obj-attr
&glob bef-table_user-window-attr user-window-attr
&glob bef-table_usr-flt usr-flt
&glob bef-table_usr-flt-attr usr-flt-attr
&glob bef-table_usr-stko usr-stko
&glob bef-table_usr-stko-attr usr-stko-attr
&glob bef-table_utd utd
&glob bef-table_utd-attr utd-attr
&glob bef-table_utd-err utd-err
&glob bef-table_utd-err-attr utd-err-attr
&glob bef-table_utd-lines utd-lines
&glob bef-table_utd-lines-attr utd-lines-attr
&glob bef-table_utd-marking-lines utd-marking-lines
&glob bef-table_utd-marking-lines-attr utd-marking-lines-attr
&glob bef-table_var-deliv-gr-per-val var-deliv-gr-per-val
&glob bef-table_var-deliv-gr-per-val-attr var-deliv-gr-per-val-attr
&glob bef-table_variant-delivery variant-delivery
&glob bef-table_variant-delivery-attr variant-delivery-attr
&glob bef-table_varianty-delivery-gds-obj varianty-delivery-gds-obj
&glob bef-table_vsd vsd
&glob bef-table_vsd-attr vsd-attr
&glob bef-table_wealth wealth
&glob bef-table_wealth-attr wealth-attr
&glob bef-table_who-lk who-lk
&glob bef-table_who-lk-attr who-lk-attr
&glob bef-table_whole-send-news whole-send-news
&glob bef-table_wi-mode wi-mode
&glob bef-table_wi-mode-attr wi-mode-attr
&glob bef-table_wth-doc wth-doc
&glob bef-table_wth-doc-attr wth-doc-attr
&glob bef-table_wth-dtl wth-dtl
&glob bef-table_wth-dtl-attr wth-dtl-attr
&glob bef-table_wth-gds wth-gds
&glob bef-table_wth-gds-attr wth-gds-attr
&glob bef-table_wth-line wth-line
&glob bef-table_wth-line-attr wth-line-attr
&glob bef-table_wth-obj wth-obj
&glob bef-table_wth-obj-attr wth-obj-attr
&glob bef-table_wth-par wth-par
&glob bef-table_wth-par-attr wth-par-attr
&glob bef-table_wth-parts wth-parts
&glob bef-table_wth-parts-attr wth-parts-attr
&glob bef-table_wth-place wth-place
&glob bef-table_wth-place-attr wth-place-attr
&glob bef-table_wth-pobj wth-pobj
&glob bef-table_wth-pobj-attr wth-pobj-attr
&glob bef-table_wth-ser wth-ser
&glob bef-table_wth-ser-attr wth-ser-attr
&glob bef-table_Xattr Xattr
&glob bef-table_xGroupObj xGroupObj
&glob bef-table_xstatus xstatus
&glob bef-table_xyz-analysis xyz-analysis
&glob bef-table_xyz-analysis-attr xyz-analysis-attr
&glob bef-table_xyz-analysis-cli xyz-analysis-cli
&glob bef-table_xyz-analysis-cli-attr xyz-analysis-cli-attr
&glob bef-table_xyz-analysis-doc xyz-analysis-doc
&glob bef-table_xyz-analysis-doc-attr xyz-analysis-doc-attr
&glob bef-table_xyz-analysis-gds-obj xyz-analysis-gds-obj
&glob bef-table_xyz-analysis-gds-obj-attr xyz-analysis-gds-obj-attr
&glob bef-table_xyz-analysis-goods xyz-analysis-goods
&glob bef-table_xyz-analysis-goods-attr xyz-analysis-goods-attr
&glob bef-table_xyz-analysis-grp xyz-analysis-grp
&glob bef-table_xyz-analysis-grp-attr xyz-analysis-grp-attr
&glob bef-table_xyz-analysis-obj xyz-analysis-obj
&glob bef-table_xyz-analysis-obj-attr xyz-analysis-obj-attr
&glob bef-table_xyz-analysis-period xyz-analysis-period
&glob bef-table_xyz-analysis-period-attr xyz-analysis-period-attr
&glob bef-table_xyz-analysis-prod xyz-analysis-prod
&glob bef-table_xyz-analysis-prod-attr xyz-analysis-prod-attr
/* $Workfile: $ e n d */

