block-level on error undo, throw.

/*
$Revision$
$Author$
$Date$
$Workfile$
$Archive$

Автор: Сгенерировано автоматически методом crTriggerFile ibs.th.adm.upd.analisdf
Дата создания: 16/05/2025
Author: automatically generated by crTriggerFile ibs.th.adm.upd.analisdf
Created: 16/05/2025
*/

&glob main-tbl c-order-line-attr
trigger procedure for delete of ub.{&main-tbl}.

define variable vss-revision    as character no-undo initial "$Revision$":U.
define variable vss-author      as character no-undo initial "$Author$":U.
define variable vss-date        as character no-undo initial "$Date$":U.
define variable vss-workfile    as character no-undo initial "$Workfile$":U.
define variable vss-archive     as character no-undo initial "$Archive$":U.
define variable vss-description as character no-undo init "Триггер на delete c-order-line-attr".
