block-level on error undo, throw.

/*
$Revision$
$Author$
$Date$
$Workfile$
$Archive$

Автор: Сгенерировано автоматически методом crTriggerFile ibs.th.adm.upd.analisdf
Дата создания: 16/05/2025
Author: automatically generated by crTriggerFile ibs.th.adm.upd.analisdf
Created: 16/05/2025
*/

&glob main-tbl order-line-attr
trigger procedure for write of ub.{&main-tbl} 
  new buffer new-{&main-tbl}
  old buffer old-{&main-tbl}
.

define variable vss-revision    as character no-undo initial "$Revision$":U.
define variable vss-author      as character no-undo initial "$Author$":U.
define variable vss-date        as character no-undo initial "$Date$":U.
define variable vss-workfile    as character no-undo initial "$Workfile$":U.
define variable vss-archive     as character no-undo initial "$Archive$":U.
define variable vss-description as character no-undo init "Триггер на write order-line-attr".

{ trg/trghistnws.i 
  &hist = yes 
  &seqnamehist = "s-c-order-chip-num"
  &histheadtbl = "c-order-head"
  &fieldmainheadtab  = "db-num doc-code" 
} 
