&global-define flt-eq "равно"
&global-define flt-ne "не равно"
&global-define flt-lt "меньше"
&global-define flt-le "меньше или равно"
&global-define flt-gt "больше"
&global-define flt-ge "больше или равно"
&global-define flt-begins "начинается с"
&global-define flt-between "между"
&global-define flt-list "список"
&global-define flt-contrains "содержит"