<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:element name="bge-client-01" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="firm" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="referenceNo" type="xsd:string" nillable="false"/>
              <xsd:element name="name" type="xsd:string" nillable="false"/>
              <xsd:element name="orgtype" type="xsd:string" nillable="false"/>
              <xsd:element name="selfHost" type="xsd:boolean" nillable="false"/>
              <xsd:element name="stts" type="xsd:int" nillable="false"/>
              <xsd:element name="comment" type="xsd:string" nillable="true"/>
              <xsd:element name="inn" type="xsd:string" nillable="false"/>
              <xsd:element name="kpp" type="xsd:string" nillable="false"/>
              <xsd:element name="okonh" type="xsd:string" nillable="false"/>
              <xsd:element name="okpo" type="xsd:string" nillable="false"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//firm"/>
      <xsd:field xpath="referenceNo"/>
    </xsd:unique>
  </xsd:element>
</xsd:schema>
