<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:element name="cli-grp-export-01-ds" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="cli-grp-01" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="node-code" type="xsd:int" nillable="false"/>
              <xsd:element name="upper-code" type="xsd:int" nillable="false"/>
              <xsd:element name="node-name" type="xsd:string" nillable="false"/>
              <xsd:element name="full-name" type="xsd:string" nillable="false"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//cli-grp-01"/>
      <xsd:field xpath="node-code"/>
    </xsd:unique>
  </xsd:element>
</xsd:schema>
