<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:element name="clients-export-01-ds" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="clients-01" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="obj-type" type="xsd:string" nillable="false"/>
              <xsd:element name="obj-code" type="xsd:int" nillable="false"/>
              <xsd:element name="grp-code" type="xsd:int" nillable="false"/>
              <xsd:element name="grp-name" type="xsd:string" nillable="false"/>
              <xsd:element name="obj-name" type="xsd:string" nillable="false"/>
              <xsd:element name="PS" type="xsd:string" nillable="true"/>
              <xsd:element name="reg-code" type="xsd:int" nillable="true"/>
              <xsd:element name="attr-cli-alc-producer" type="xsd:string" nillable="true"/>
              <xsd:element name="attr-foreign-producer" type="xsd:string" nillable="true"/>
              <xsd:element name="firm-01" minOccurs="0" maxOccurs="1">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="firm-code" type="xsd:int" nillable="false"/>
                    <xsd:element name="addres1" type="xsd:string" nillable="false"/>
                    <xsd:element name="addres2" type="xsd:string" nillable="false"/>
                    <xsd:element name="city" type="xsd:string" nillable="false"/>
                    <xsd:element name="contact-psn" type="xsd:string" nillable="true"/>
                    <xsd:element name="director" type="xsd:string" nillable="true"/>
                    <xsd:element name="e-mail" type="xsd:string" nillable="true"/>
                    <xsd:element name="engl-name" type="xsd:string" nillable="false"/>
                    <xsd:element name="fax" type="xsd:string" nillable="true"/>
                    <xsd:element name="gen-acct" type="xsd:string" nillable="true"/>
                    <xsd:element name="given-by" type="xsd:string" nillable="true"/>
                    <xsd:element name="head-position" type="xsd:string" nillable="true"/>
                    <xsd:element name="ind" type="xsd:string" nillable="true"/>
                    <xsd:element name="inn" type="xsd:string" nillable="true"/>
                    <xsd:element name="is-pboul" type="xsd:boolean" nillable="false"/>
                    <xsd:element name="kpp" type="xsd:string" nillable="true"/>
                    <xsd:element name="okonh" type="xsd:string" nillable="true"/>
                    <xsd:element name="okpo" type="xsd:string" nillable="true"/>
                    <xsd:element name="passp-num" type="xsd:string" nillable="true"/>
                    <xsd:element name="passp-ser" type="xsd:string" nillable="true"/>
                    <xsd:element name="phone1-note" type="xsd:string" nillable="true"/>
                    <xsd:element name="phone" type="xsd:string" nillable="true"/>
                    <xsd:element name="post-addr1" type="xsd:string" nillable="true"/>
                    <xsd:element name="post-addr2" type="xsd:string" nillable="true"/>
                    <xsd:element name="post-city" type="xsd:string" nillable="false"/>
                    <xsd:element name="post-ind" type="xsd:string" nillable="true"/>
                    <xsd:element name="telex" type="xsd:string" nillable="true"/>
                    <xsd:element name="tobj-code" type="xsd:int" nillable="true"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="person-01" minOccurs="0" maxOccurs="1">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="psn-code" type="xsd:int" nillable="false"/>
                    <xsd:element name="address" type="xsd:string" nillable="true"/>
                    <xsd:element name="city" type="xsd:string" nillable="true"/>
                    <xsd:element name="date-birth" type="xsd:date" nillable="true"/>
                    <xsd:element name="e-mail" type="xsd:string" nillable="true"/>
                    <xsd:element name="fax" type="xsd:string" nillable="true"/>
                    <xsd:element name="firm-code" type="xsd:int" nillable="true"/>
                    <xsd:element name="firm-name" type="xsd:string" nillable="true"/>
                    <xsd:element name="gender" type="xsd:boolean" nillable="true"/>
                    <xsd:element name="given-by" type="xsd:string" nillable="true"/>
                    <xsd:element name="ind" type="xsd:string" nillable="true"/>
                    <xsd:element name="inn" type="xsd:string" nillable="true"/>
                    <xsd:element name="is-pboul" type="xsd:boolean" nillable="false"/>
                    <xsd:element name="kpp" type="xsd:string" nillable="true"/>
                    <xsd:element name="name1" type="xsd:string" nillable="true"/>
                    <xsd:element name="name2" type="xsd:string" nillable="true"/>
                    <xsd:element name="okonh" type="xsd:string" nillable="true"/>
                    <xsd:element name="okpo" type="xsd:string" nillable="true"/>
                    <xsd:element name="passp-num" type="xsd:string" nillable="true"/>
                    <xsd:element name="passp-ser" type="xsd:string" nillable="true"/>
                    <xsd:element name="phone1-note" type="xsd:string" nillable="true"/>
                    <xsd:element name="phone1" type="xsd:string" nillable="true"/>
                    <xsd:element name="position" type="xsd:string" nillable="true"/>
                    <xsd:element name="post-box" type="xsd:string" nillable="true"/>
                    <xsd:element name="post-address" type="xsd:string" nillable="true"/>
                    <xsd:element name="post-city" type="xsd:string" nillable="true"/>
                    <xsd:element name="post-ind" type="xsd:string" nillable="true"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//clients-01"/>
      <xsd:field xpath="obj-type"/>
      <xsd:field xpath="obj-code"/>
    </xsd:unique>
    <xsd:unique name="firm-01_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//firm-01"/>
      <xsd:field xpath="firm-code"/>
    </xsd:unique>
    <xsd:unique name="person-01_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//person-01"/>
      <xsd:field xpath="psn-code"/>
    </xsd:unique>
  </xsd:element>
 <xsd:annotation>
    <xsd:appinfo>
      <prodata:relation name="firm" prodata:nested="true" prodata:parent="clients-01" prodata:child="firm-01" prodata:relationFields="obj-code,firm-code"/>
      <prodata:relation name="person" prodata:nested="true" prodata:parent="clients-01" prodata:child="person-01" prodata:relationFields="obj-code,psn-code"/>
    </xsd:appinfo>
  </xsd:annotation>
</xsd:schema>