<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsd="undefined" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xs:include schemaLocation="exitetypes_0-02.xsd"/>
  <xs:element name="DESADV_">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="DESADV">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="NUMBER" type="numbertype"/>
              <xs:element name="DATE" type="xs:date" minOccurs="0"/>
              <xs:element name="DELIVERYDATE" type="xs:date" minOccurs="0"/>
              <xs:element name="EARLIESTDELIVERY" type="xs:date" minOccurs="0"/>
              <xs:element name="LATESTDELIVERY" type="xs:date" minOccurs="0"/>
              <xs:element name="DELIVERYTIME" type="timetype" minOccurs="0"/>
              <xs:element name="ORDERNUMBER" type="numbertype"/>
              <xs:element name="ORDERDATE" type="xs:date" minOccurs="0"/>
              <xs:element name="DELIVERYNOTENUMBER" type="numbertype" minOccurs="0"/>
              <xs:element name="DELIVERYNOTEDATE" type="xs:date" minOccurs="0"/>
              <xs:element name="SUPPLIERORDERNUMBER" type="numbertype" minOccurs="0"/>
              <xs:element name="SUPPLIERORDERDATE" type="xs:date" minOccurs="0"/>
              <xs:element name="TRANSPORTATIONTYPES" type="transport-type" minOccurs="0"/>
              <xs:element name="TRANSPORTATIONMEANS" type="transport-condition" minOccurs="0"/>
              <xs:element name="GROSSWEIGHT" type="amount" minOccurs="0"/>
              <xs:element name="GROSSVOLUME" type="amount" minOccurs="0"/>
              <xs:element ref="HEAD"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    <xs:unique name="pi" prodata:primaryIndex="true">
      <xs:selector xpath=".//DESADV"/>
      <xs:field xpath="NUMBER"/>
    </xs:unique>
    <xs:unique name="HEAD_pi" prodata:primaryIndex="true">
      <xs:selector xpath=".//HEAD"/>
      <xs:field xpath="NUMBER"/>
    </xs:unique>
    <xs:unique name="POSITION_pi" prodata:primaryIndex="true">
      <xs:selector xpath=".//POSITION"/>
      <xs:field xpath="NUMBER"/>
      <xs:field xpath="POSITIONNUMBER"/>
    </xs:unique>
    <xs:keyref name="r1" refer="pi" prodata:nested="true">
      <xs:selector xpath=".//HEAD"/>
      <xs:field xpath="NUMBER"/>
    </xs:keyref>
    <xs:keyref name="r2" refer="HEAD_pi" prodata:nested="true">
      <xs:selector xpath=".//POSITION"/>
      <xs:field xpath="NUMBER"/>
    </xs:keyref>
  </xs:element>
  <xs:element name="HEAD">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="NUMBER" type="numbertype"/>
        <xs:element name="SUPPLIER" type="gln"/>
        <xs:element name="BUYER" type="gln"/>
        <xs:element name="DELIVERYPLACE" type="gln"/>
        <xs:element name="FINALRECIPIENT" type="gln" minOccurs="0"/>
        <xs:element name="ORDERPARTNER" type="gln" minOccurs="0"/>
        <xs:element name="LOGISTICPARTNER" type="gln" minOccurs="0"/>
        <xs:element name="SENDER" type="mailbox"/>
        <xs:element name="RECIPIENT" type="mailbox"/>
        <xs:element name="EDIINTERCHANGEID" type="edi-interchange-id"/>
        <xs:element name="EDIMESSAGE" type="xs:string" minOccurs="0"/>
        <xs:element ref="POSITION" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="POSITION">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="NUMBER" type="numbertype"/>
        <xs:element name="POSITIONNUMBER" type="positionnumbertype"/>
        <xs:element name="PRODUCT" type="gln"/>
        <xs:element name="PRODUCTIDSUPPLIER" type="numbertype"/>
        <xs:element name="PRODUCTIDBUYER" type="numbertype"/>
        <xs:element name="DELIVEREDQUANTITY" type="amount"/>
        <xs:element name="DELIVEREDUNIT" type="measurement-unit"/>
        <xs:element name="ORDEREDQUANTITY" type="amount"/>
        <xs:element name="ORDERUNIT" type="measurement-unit"/>
        <xs:element name="PRICEQUANT" type="price" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>