<?xml version="1.0" encoding="windows-1251"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:include schemaLocation="DTKheader.xsd"/>
  <xsd:element name="THDK" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="countries" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Rec_ID" type="Rec_IDType" nillable="false"/>
              <xsd:element name="ID" type="CountryIDType" nillable="false"/>
              <xsd:element name="Action" type="ActionType" nillable="false"/>
              <xsd:element name="Name" type="CountryNameType" nillable="true"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="countries_pi" prodata:primaryIndex="true">
      <xsd:annotation>
        <xsd:documentation>Первичный ключ для справочника стран</xsd:documentation>
      </xsd:annotation>
      <xsd:selector xpath=".//countries"/>
      <xsd:field xpath="Rec_ID"/>
      <xsd:field xpath="ID"/>
    </xsd:unique>
  </xsd:element>
</xsd:schema> 