<?xml version="1.0" encoding="windows-1251"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:include schemaLocation="DTKheader.xsd"/>
  <xsd:element name="THDK" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="goods" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Rec_ID" type="Rec_IDType" nillable="false"/>
              <xsd:element name="ID" type="GoodsIDType" nillable="false"/>
              <xsd:element name="Action" type="ActionType" nillable="false"/>
              <xsd:element name="Name" type="xsd:string" nillable="true"/>
              <xsd:element name="Baseunit" type="UnitType" nillable="true"/>
              <xsd:element name="Baseprice" type="PriceType" nillable="true"/>
              <xsd:element name="CountryID" type="CountryIDType" nillable="true"/>
              <xsd:element name="Producer" type="ClientsNameType" nillable="true"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="barcodes" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Rec_ID" type="Rec_IDType" nillable="false"/>
              <xsd:element name="BC" type="BCIDType" nillable="false"/>
              <xsd:element name="Action" type="ActionType" nillable="false"/>
              <xsd:element name="GoodsID" type="GoodsIDType" nillable="false"/>
              <xsd:element name="Price" type="PriceType" nillable="true"/>
              <xsd:element name="Unit" type="UnitType" nillable="true"/>
              <xsd:element name="CUnit" type="CUnitType" nillable="true"/>
              <xsd:element name="NodeName" type="xsd:string" nillable="true"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="smprices" type="SmpricesType" minOccurs="0" maxOccurs="unbounded">
        </xsd:element>
        <xsd:element name="counts" type="CountsType" minOccurs="0" maxOccurs="unbounded">
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:annotation>
        <xsd:documentation>Первичный ключ для справочника товаров</xsd:documentation>
      </xsd:annotation>
      <xsd:selector xpath=".//goods"/>
      <xsd:field xpath="Rec_ID"/>
      <xsd:field xpath="ID"/>
    </xsd:unique>
    <xsd:unique name="barcodes_pi" prodata:primaryIndex="true">
	  <xsd:annotation>
	  	<xsd:documentation>Первичный ключ для справочника штрих-кодов</xsd:documentation>
	  </xsd:annotation>
	  <xsd:selector xpath=".//barcodes"/>
      <xsd:field xpath="Rec_ID"/>
      <xsd:field xpath="BC"/>
    </xsd:unique>
    <xsd:unique name="smprices_pi" prodata:primaryIndex="true">
	  <xsd:annotation>
	  	<xsd:documentation>Первичный ключи для прайс-листов</xsd:documentation>
	  </xsd:annotation>
	  <xsd:selector xpath=".//smprices"/>
      <xsd:field xpath="Rec_ID"/>
      <xsd:field xpath="GoodsID"/>
      <xsd:field xpath="BC"/>
      <xsd:field xpath="PriceID"/>
    </xsd:unique>
    <xsd:unique name="counts_pi" prodata:primaryIndex="true">
	  <xsd:annotation>
      <xsd:documentation>Первичный ключ для остатков</xsd:documentation>
	  </xsd:annotation>
     <xsd:selector xpath=".//counts"/>
      <xsd:field xpath="Rec_ID"/>
      <xsd:field xpath="GoodsID"/>
      <xsd:field xpath="StoreID"/>
    </xsd:unique>
  </xsd:element>
</xsd:schema>