<?xml version="1.0" encoding="windows-1251"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:include schemaLocation="DTKheader.xsd"/>
  <xsd:element name="THDK" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="smprices" type="SmpricesType" minOccurs="0" maxOccurs="unbounded">
        </xsd:element>
        <xsd:element name="doc_header" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Rec_ID" type="Rec_IDType" nillable="false"/>
              <xsd:element name="ID" type="DocIDType" nillable="false"/>
              <xsd:element name="Action" type="ActionType" nillable="false"/>
              <xsd:element name="ExtNum" type="THDocCode" nillable="true"/>
              <xsd:element name="Type" type="DocTypeType" nillable="true"/>
              <xsd:element name="AgentID" type="ClientsIDType" nillable="true"/>
              <xsd:element name="FromStoreID" type="StoresIDType" nillable="true"/>
              <xsd:element name="ToStoreID" type="StoresIDType" nillable="true"/>
              <xsd:element name="User_ID" type="USERIDType" nillable="true"/>
              <xsd:element name="PPrice" type="PriceType" nillable="true"/>
              <xsd:element name="FPrice" type="PriceType" nillable="true"/>
              <xsd:element name="PDate" type="DocDateType" nillable="true"/>
              <xsd:element name="StartDate" type="DocDateType" nillable="true"/>
              <xsd:element name="FinishDate" type="DocDateType" nillable="true"/>
              <xsd:element name="doc_line" minOccurs="1" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="Rec_ID" type="Rec_IDType" nillable="false"/>
                    <xsd:element name="DocID" type="DocIDType" nillable="false"/>
                    <xsd:element name="Pos" type="DocLinePosType" nillable="false"/>
                    <xsd:element name="Action" type="ActionType" nillable="false"/>
                    <xsd:element name="GoodsID" type="GoodsIDType" nillable="false"/>
                    <xsd:element name="StoreID" type="StoresIDType" nillable="true"/>
                    <xsd:element name="BC" type="BCIDType" nillable="true"/>
                    <xsd:element name="SN" type="DocLineSNType" nillable="true"/>
                    <xsd:element name="Name" type="DocLineNameType" nillable="true"/>
                    <xsd:element name="PCount" type="QntyType" nillable="true"/>
                    <xsd:element name="FCount" type="QntyType" nillable="true"/>
                    <xsd:element name="PPrice" type="PriceType" nillable="true"/>
                    <xsd:element name="FPrice" type="PriceType" nillable="true"/>
                    <xsd:element name="ExtArtic" type="xsd:string" nillable="true"/>
                    <xsd:element name="Comment" type="DocLineCommentType" nillable="true"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="smprices_pi" prodata:primaryIndex="true">
      <xsd:annotation>
        <xsd:documentation>Первичный ключ для прайс-листов</xsd:documentation>
      </xsd:annotation>
      <xsd:selector xpath=".//smprices"/>
      <xsd:field xpath="Rec_ID"/>
      <xsd:field xpath="GoodsID"/>
      <xsd:field xpath="BC"/>
      <xsd:field xpath="PriceID"/>
    </xsd:unique>
    <xsd:unique name="pi_doc-header" prodata:primaryIndex="true">
      <xsd:annotation>
        <xsd:documentation>Первичный ключ для шапки документа</xsd:documentation>
      </xsd:annotation>
      <xsd:selector xpath=".//doc_header"/>
      <xsd:field xpath="Rec_ID"/>
      <xsd:field xpath="ID"/>
    </xsd:unique>
    <xsd:unique name="pi_doc-line" prodata:primaryIndex="true">
      <xsd:annotation>
        <xsd:documentation>Первичный ключ для строки документа</xsd:documentation>
      </xsd:annotation>
      <xsd:selector xpath=".//doc_line"/>
      <xsd:field xpath="Rec_ID"/>
      <xsd:field xpath="DocID"/>
      <xsd:field xpath="Pos"/>
      <xsd:field xpath="GoodsID"/>
      <xsd:field xpath="BC"/>
    </xsd:unique>
  </xsd:element>
  <xsd:annotation>
    <xsd:appinfo>
      <prodata:index name="doc_header_pi">
        <prodata:table name="doc_header"/>
        <prodata:field name="ID"/>
      </prodata:index>
      <prodata:index name="doc_line_pi">
        <prodata:table name="doc_line"/>
        <prodata:field name="DocID"/>
        <prodata:field name="Pos"/>
        <prodata:field name="GoodsID"/>
        <prodata:field name="BC"/>
      </prodata:index>
      <prodata:relation name="RELATION_DOC_DOC_LINE" prodata:nested="true" prodata:parent="doc_header" prodata:child="doc_line" prodata:relationFields="ID,DocID">
        <xsd:annotation>
          <xsd:documentation>Привязка строк документа к документу</xsd:documentation>
        </xsd:annotation>
      </prodata:relation>
    </xsd:appinfo>
  </xsd:annotation>
</xsd:schema> 