<?xml version="1.0" encoding="windows-1251"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:simpleType name="Rec_IDType">
		<xsd:annotation>
			<xsd:documentation>Уникальный код записи</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ActionType">
		<xsd:annotation>
			<xsd:documentation>Тип действия: u - добавление или изменение, d - удаление.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="u|d"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="GoodsIDType">
		<xsd:annotation>
			<xsd:documentation>Уникальный код товара</xsd:documentation>
		</xsd:annotation>
      <xsd:restriction base="xsd:int">
			<xsd:minInclusive value="0"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="UnitType">
		<xsd:annotation>
			<xsd:documentation>Код единицы измерения</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:normalizedString">
  			<xsd:maxLength value="3"/>
  		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="PriceType">
		<xsd:annotation>
			<xsd:documentation>Цена</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:decimal">
			<xsd:minInclusive value="0"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="CountryIDType">
		<xsd:annotation>
			<xsd:documentation>Код страны</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:normalizedString">
			<xsd:maxLength value="2"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="BCIDType">
		<xsd:annotation>
			<xsd:documentation>Штрих-код товара</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>
	<xsd:simpleType name="CUnitType">
		<xsd:annotation>
			<xsd:documentation>Коэфф. пересчета из базовой единицы измерения</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:decimal">
			<xsd:minInclusive value="0"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ClientsIDType">
		<xsd:annotation>
			<xsd:documentation>Код клиента</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:normalizedString">
			<xsd:maxLength value="15"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ClientsNameType">
		<xsd:annotation>
			<xsd:documentation>Наименование клиента</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:normalizedString">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="StoresIDType">
		<xsd:annotation>
			<xsd:documentation>Наименование клиента</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:normalizedString">
			<xsd:maxLength value="15"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="StoresNameType">
		<xsd:annotation>
			<xsd:documentation>Наименование хранилища(склада, объекта)</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:normalizedString">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="QntyType">
		<xsd:annotation>
			<xsd:documentation>Количество товара</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:decimal"/>
	</xsd:simpleType>
	<xsd:simpleType name="PriceIDType">
		<xsd:annotation>
			<xsd:documentation>Код прайс-листа</xsd:documentation>
		</xsd:annotation>
      <xsd:restriction base="xsd:int"/>
	</xsd:simpleType>
	<xsd:simpleType name="CountryNameType">
		<xsd:annotation>
			<xsd:documentation>Название страны</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:normalizedString">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DocIDType">
		<xsd:annotation>
			<xsd:documentation>Код документа в DKLink</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:int">
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="THDocCode">
		<xsd:annotation>
	  		<xsd:documentation>Номер документа IBS TH</xsd:documentation>
	  	</xsd:annotation>
	 	<xsd:restriction base="xsd:string">
	  	</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DocTypeType">
 		<xsd:annotation>
	  		<xsd:documentation>Тип документа в DK: 0: приход 1: отгрузка 2: инвентаризация 3: внутренний приход 4: внутренняя отгрузка 5: заказ (мягкий чек) 6: возврат 7: комплектация</xsd:documentation>
	  	</xsd:annotation>
			<xsd:restriction base="xsd:int">
  				<xsd:enumeration value="0"/>
  				<xsd:enumeration value="1"/>
  				<xsd:enumeration value="2"/>
				<xsd:enumeration value="3"/>
				<xsd:enumeration value="4"/>
				<xsd:enumeration value="7"/>
			</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="USERIDType">
 		<xsd:annotation>
	  		<xsd:documentation>User ID пользователя в ДК или в TH</xsd:documentation>
	  	</xsd:annotation>
			<xsd:restriction base="xsd:normalizedString">
				<xsd:maxLength value="15"/>
			</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DocDateType">
 		<xsd:annotation>
	  		<xsd:documentation>Текстовое представление даты и времени</xsd:documentation>
	  	</xsd:annotation>
 		<xsd:restriction base="xsd:dateTime">
  		</xsd:restriction>
  	</xsd:simpleType>
	<xsd:simpleType name="IntTimeType">
 		<xsd:annotation>
	  		<xsd:documentation>Числовое представление времени в количестве секунд от полуночи</xsd:documentation>
	  	</xsd:annotation>
			<xsd:restriction base="xsd:int">
				<xsd:maxInclusive value="86399"/>
				<xsd:minInclusive value="0"/>
			</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DocLinePosType">
 		<xsd:annotation>
	  		<xsd:documentation>Номер строки документа</xsd:documentation>
	  	</xsd:annotation>
			<xsd:restriction base="xsd:int">
				<xsd:minInclusive value="1"/>
			</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DocLineSNType">
 		<xsd:annotation>
	  		<xsd:documentation>Номер строки документа</xsd:documentation>
	  	</xsd:annotation>
			<xsd:restriction base="xsd:normalizedString">
				<xsd:maxLength value="30"/>
			</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DocLineNameType">
 		<xsd:annotation>
	  		<xsd:documentation>Наименование товара</xsd:documentation>
	  	</xsd:annotation>
			<xsd:restriction base="xsd:normalizedString">
				<xsd:maxLength value="100"/>
			</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DocLineCommentType">
 		<xsd:annotation>
	  		<xsd:documentation>Коментарий к строке документа</xsd:documentation>
	  	</xsd:annotation>
			<xsd:restriction base="xsd:normalizedString">
				<xsd:maxLength value="100"/>
			</xsd:restriction>
	</xsd:simpleType>
  <xsd:complexType name="SmpricesType">
    <xsd:sequence>
      <xsd:element name="Rec_ID" type="Rec_IDType" nillable="false"/>
      <xsd:element name="GoodsID" type="GoodsIDType" nillable="false"/>
      <xsd:element name="BC" type="BCIDType" nillable="false"/>
      <xsd:element name="PriceID" type="PriceIDType" nillable="false"/>
      <xsd:element name="Action" type="ActionType" nillable="false"/>
      <xsd:element name="Price" type="PriceType" nillable="true"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="CountsType">
    <xsd:sequence>
      <xsd:element name="Rec_ID" type="Rec_IDType" nillable="false"/>
      <xsd:element name="GoodsID" type="GoodsIDType" nillable="false"/>
      <xsd:element name="StoreID" type="StoresIDType" nillable="false"/>
      <xsd:element name="Action" type="ActionType" nillable="false"/>
      <xsd:element name="Counts" type="QntyType" nillable="true"/>
      <xsd:element name="Reserve" type="QntyType" nillable="true"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>