<?xml version="1.0" encoding="windows-1251"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:include schemaLocation="ESHOPHEADER.xsd"/>
  <xsd:element name="ExpenseExternal" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Header_" type="HEADERType">
          <xsd:annotation>
            <xsd:documentation>Ссылка на файл, содержащий стандартные определения типов IBS TH</xsd:documentation>
          </xsd:annotation>
        </xsd:element>
        <xsd:element name="trn-doc" maxOccurs="unbounded">
          <xsd:annotation>
            <xsd:documentation>Один документа вынешнего расхода</xsd:documentation>
          </xsd:annotation>
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="line-num" type="Line-numType" nillable="false">
                <xsd:annotation>
                  <xsd:documentation>Порядковый номер текущего документа в текущем файле</xsd:documentation>
                </xsd:annotation>
              </xsd:element>
              <xsd:element name="doc-date" type="xsd:date" nillable="false">
                <xsd:annotation>
                  <xsd:documentation>Дата документа (заказа)</xsd:documentation>
                </xsd:annotation>
              </xsd:element>
              <xsd:element name="cli-code" type="CliCode" nillable="false">
                <xsd:annotation>
                  <xsd:documentation>Код контрагента документа в системе IBS TH</xsd:documentation>
                </xsd:annotation>
              </xsd:element>
              <xsd:element name="cli-type" type="CliType" nillable="false">
                <xsd:annotation>
                  <xsd:documentation>Тип контрагента документа в системе IBS TH</xsd:documentation>
                </xsd:annotation>
              </xsd:element>
              <xsd:element name="obj-type" type="ObjType" nillable="false">
                <xsd:annotation>
                  <xsd:documentation>Тип объекта документа в системе IBS TH</xsd:documentation>
                </xsd:annotation>
              </xsd:element>
              <xsd:element name="obj-code" type="ObjCode" nillable="false">
                <xsd:annotation>
                  <xsd:documentation>Код объекта документа в системе IBS TH</xsd:documentation>
                </xsd:annotation>
              </xsd:element>
              <xsd:element name="ext-doc-code" type="xsd:string" nillable="false">
                <xsd:annotation>
                  <xsd:documentation>№ документа в системе-экспортере</xsd:documentation>
                </xsd:annotation>
              </xsd:element>
              <xsd:element name="ps" type="xsd:string" minOccurs="0">
                <xsd:annotation>
                  <xsd:documentation>Примечание к документу</xsd:documentation>
                </xsd:annotation>
              </xsd:element>
              <xsd:element name="doc-line" maxOccurs="unbounded">
                <xsd:annotation>
                  <xsd:documentation>Строка документа</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="line-num" type="Line-numType" nillable="false">
                      <xsd:annotation>
                        <xsd:documentation>Порядковый номер текущего документа в текущем файле 
                = ВСЕГДА равен значению данного тэга для записи trn-doc</xsd:documentation>
                      </xsd:annotation>
                    </xsd:element>
                    <xsd:element name="fact-qnty" nillable="false">
                      <xsd:annotation>
                        <xsd:documentation>Факт кол-во товара по строке документа</xsd:documentation>
                      </xsd:annotation>
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:decimal">
                          <xsd:minInclusive value="0"/>
                          <xsd:fractionDigits value="3"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="price-rubl" type="PriceType" nillable="false">
                      <xsd:annotation>
                        <xsd:documentation>Цена товара по строке документа</xsd:documentation>
                      </xsd:annotation>
                    </xsd:element>
                    <xsd:element name="gds-code" type="BarCodeType" nillable="false">
                      <xsd:annotation>
                        <xsd:documentation>Код товара строки документа в систем IBS TH</xsd:documentation>
                      </xsd:annotation>
                    </xsd:element>
                    <xsd:element name="ext-doc-code" type="xsd:string" nillable="false">
                      <xsd:annotation>
                        <xsd:documentation>№ документа в системе-экспортере                 
              = ВСЕГДА равен значению данного тэга для записи trn-doc</xsd:documentation>
                      </xsd:annotation>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//trn-doc"/>
      <xsd:field xpath="line-num"/>
    </xsd:unique>
    <xsd:unique name="doc-line_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//doc-line"/>
      <xsd:field xpath="line-num"/>
      <xsd:field xpath="doc-code"/>
      <xsd:field xpath="gds-code"/>
    </xsd:unique>
  </xsd:element>
  <xsd:annotation>
    <xsd:appinfo>
      <prodata:index name="iline">
        <prodata:table name="doc-line"/>
        <prodata:field name="ext-doc-code"/>
        <prodata:field name="gds-code"/>
      </prodata:index>
      <prodata:relation name="ext-doc-code" prodata:nested="true" prodata:parent="trn-doc" prodata:child="doc-line" prodata:relationFields="line-num,line-num,doc-code,doc-code"/>
    </xsd:appinfo>
  </xsd:annotation>
</xsd:schema>