<?xml version="1.0" encoding="windows-1251"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
<!--ВНИМАНИЕ!!! при изменении надо переименовать ФАЙЛ - и добавить новый в VSS - перименовать все ссылки на него в XSD схемах!!-->
  <xs:simpleType name="numbertype">
    <xs:restriction base="xs:string">
      <xs:maxLength value="16"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="amount">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0"/>
      <xs:totalDigits value="10"/>
      <xs:fractionDigits value="3"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="gln">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{8}([0-9]{3}([0-9]{0,3}))?"/>
      <!-- das sind entweder 8, 11, 12, 13 oder 14 Ziffern -->
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="time">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{2}:[0-9]{2}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="percentage">
    <xs:restriction base="xs:decimal">
      <xs:totalDigits value="4"/>
      <xs:fractionDigits value="2"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="measurement-unit">
    <xs:restriction base="xs:string">
      <xs:maxLength value="3"/>
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="mailbox">
    <xs:restriction base="xs:string">
      <xs:maxLength value="13"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="order-type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="220"/>
      <xs:enumeration value="224"/>
      <xs:enumeration value="22E"/>
      <xs:enumeration value="402"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="delivery-condition">
    <xs:restriction base="xs:string">
      <xs:enumeration value="01E"/>
      <!-- Vor Lieferung Lieferanschrift verst&#xE4;ndigen (EAN-Code) -->
      <xs:enumeration value="02E"/>
      <!-- Dringliche Auslieferung (EAN-Code) -->
      <xs:enumeration value="03E"/>
      <!-- Spezielle Lieferbedingungen (EAN-Code) -->
      <xs:enumeration value="04E"/>
      <!-- Lieferung per Nachnahme (EAN-Code) -->
      <xs:enumeration value="CFR"/>
      <!-- Kosten und Fracht -->
      <xs:enumeration value="CIF"/>
      <!-- Kosten, Versicherung und Fracht -->
      <xs:enumeration value="CIP"/>
      <!-- Frachtfrei, versichert -->
      <xs:enumeration value="CPT"/>
      <!-- Frachtfrei -->
      <xs:enumeration value="DAF"/>
      <!-- Geliefert frei Grenze -->
      <xs:enumeration value="DDP"/>
      <!-- Geliefert Bestimmungsort, verzollt -->
      <xs:enumeration value="DDU"/>
      <!-- Geliefert Bestimmungsort, unverzollt -->
      <xs:enumeration value="DEQ"/>
      <!-- Geliefert ab Kai -->
      <xs:enumeration value="DES"/>
      <!-- Geliefert ab Schiff -->
      <xs:enumeration value="EXW"/>
      <!-- Ab Werk -->
      <xs:enumeration value="FAS"/>
      <!-- Frei L&#xE4;ngsseite Seeschiff -->
      <xs:enumeration value="FCA"/>
      <!-- Frei Frachtf&#xFC;hrer -->
      <xs:enumeration value="FOA"/>
      <!-- FOB Airport - Named airport of departure -->
      <xs:enumeration value="FOB"/>
      <!-- Frei an Bord -->
      <xs:enumeration value="FOR"/>
      <!-- Free on Rail - Named departure point -->
      <xs:enumeration value="RDN"/>
      <!-- Unterschriebenen Lieferschein zur&#xFC;cksenden (EAN-Code) -->
      <xs:enumeration value="RPD"/>
      <!-- Abliefernachweisnummer des Warenempf&#xE4;ngers zur&#xFC;ckmelden (EAN-Code) -->
      <xs:enumeration value="SD"/>
      <!-- Sendung ist auf mehr als ein Transportmittel aufgeteilt (EAN-Code) -->
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="transport-condition">
    <xs:restriction base="xs:string">
      <xs:enumeration value="1"/>
      <!-- Chemikalientanker/Lastkahn -->
      <xs:enumeration value="101"/>
      <!-- Kurierdienst -->
      <xs:enumeration value="10E"/>
      <!-- Tautliner 25t -->
      <xs:enumeration value="11E"/>
      <!-- Tautliner 25t mit abnehmbarem Dach -->
      <xs:enumeration value="12"/>
      <!-- Tankschiff -->
      <xs:enumeration value="12E"/>
      <!-- Sattelzug mit Pritsche 25 t -->
      <xs:enumeration value="13E"/>
      <!-- Sattelzug 24 t mit Pritsche und Kran 10m -->
      <xs:enumeration value="14E"/>
      <!-- Sattelzug 24 t mit Pritsche und Kran 15m -->
      <xs:enumeration value="15E"/>
      <!-- Sattelzug 24 t mit Pritsche und Kran 18m -->
      <xs:enumeration value="16E"/>
      <!-- Sattelzug mit Pritsche 10 t -->
      <xs:enumeration value="17E"/>
      <!-- Tautliner 25t mit Anhaenger 90m3 -->
      <xs:enumeration value="18E"/>
      <!-- Tautliner 25t mit Anhaenger 120m3 -->
      <xs:enumeration value="19E"/>
      <!-- LKW mit Pritsche, Anhaenger + Krank 10m -->
      <xs:enumeration value="20E"/>
      <!-- Sattelzug mit Tankaufbau -->
      <xs:enumeration value="21"/>
      <!-- Tankwaggon -->
      <xs:enumeration value="21E"/>
      <!-- LKW mit Pritsche 15t -->
      <xs:enumeration value="22E"/>
      <!-- LKW mit Pritsche und Kran 15t -->
      <xs:enumeration value="23"/>
      <!-- Schuettgutwaggon -->
      <xs:enumeration value="23E"/>
      <!-- LKW/Anhaenger mit Kippvorrichtung -->
      <xs:enumeration value="24E"/>
      <!-- Tiefkuehl-LKW -->
      <xs:enumeration value="25"/>
      <!-- Bahnexpress -->
      <xs:enumeration value="25E"/>
      <!-- LKW mit isoliertem Kofferaufbau -->
      <xs:enumeration value="26E"/>
      <!-- Kuehl-LKW -->
      <xs:enumeration value="27E"/>
      <!-- Anhaenger mit isoliertem Kofferaufbau -->
      <xs:enumeration value="28E"/>
      <!-- Kuehlanhaenger -->
      <xs:enumeration value="29E"/>
      <!-- Tiefkuehl-Lieferwagen -->
      <xs:enumeration value="30E"/>
      <!-- Lieferwagen mit isoliertem Aufbau -->
      <xs:enumeration value="31"/>
      <!-- LKW -->
      <xs:enumeration value="31E"/>
      <!-- Kuehl-Lieferwagen -->
      <xs:enumeration value="32"/>
      <!-- Tankwagen -->
      <xs:enumeration value="32E"/>
      <!-- Anhaenger -->
      <xs:enumeration value="33E"/>
      <!-- Anhaenger mit Tankaufbau -->
      <xs:enumeration value="34"/>
      <!-- Strassen-Paketexpress -->
      <xs:enumeration value="34E"/>
      <!-- Anhaenger fuer Schuettgut -->
      <xs:enumeration value="35"/>
      <!-- LKW/Anhaenger mit Kippvorrichtung -->
      <xs:enumeration value="35E"/>
      <!-- LKW fuer Schuettgut -->
      <xs:enumeration value="36E"/>
      <!-- Lieferwagen -->
      <xs:enumeration value="37E"/>
      <!-- Anhaenger ausziehbar -->
      <xs:enumeration value="38E"/>
      <!-- Dolly-Anhaenger -->
      <xs:enumeration value="39E"/>
      <!-- Tiefkuehl-Anhaenger -->
      <xs:enumeration value="41"/>
      <!-- Luftfracht -->
      <xs:enumeration value="42"/>
      <!-- Isolierter LKW -->
      <xs:enumeration value="43"/>
      <!-- Kuehl-LKW -->
      <xs:enumeration value="51"/>
      <!-- Paketdienst der Post -->
      <xs:enumeration value="52"/>
      <!-- Exppressdienst der Post -->
      <xs:enumeration value="53"/>
      <!-- Normaler Postversand -->
      <xs:enumeration value="54"/>
      <!-- Beschleunigter normaler Postversand -->
      <xs:enumeration value="55"/>
      <!-- Luftpost -->
      <xs:enumeration value="56"/>
      <!-- Drucksache -->
      <xs:enumeration value="97E"/>
      <!-- LKW mit Anhaenger -->
      <xs:enumeration value="98E"/>
      <!-- LKW mit Kran ebenerdig ohne Anhaenger -->
      <xs:enumeration value="99E"/>
      <!-- LKW mit Kran ebenerdig mit Anhaenger -->
      <xs:enumeration value="X01"/>
      <!-- LKW mit Kran Hochtr. ohne Anhaenger -->
      <xs:enumeration value="X02"/>
      <!-- LKW m. Kran Hochtransp. m. Anhaenger -->
      <xs:enumeration value="X14"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="transport-type">
    <xs:restriction base="xs:positiveInteger">
      <xs:enumeration value="10"/>
      <!-- Seetransport -->
      <xs:enumeration value="20"/>
      <!-- Bahntransport -->
      <xs:enumeration value="30"/>
      <!-- Stra&#xDF;entransport -->
      <xs:enumeration value="40"/>
      <!-- Lufttransport -->
      <xs:enumeration value="50"/>
      <!-- Post -->
      <xs:enumeration value="60"/>
      <!-- Multimodaler Transp. / komb. Verkehr  -->
      <xs:enumeration value="70"/>
      <!-- Fixe Transportinstallationen -->
      <xs:enumeration value="80"/>
      <!-- Transport auf Binnengew&#xE4;ssern -->
      <xs:enumeration value="100"/>
      <!-- Botendienst -->
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="currency">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ATS"/>
      <xs:enumeration value="CHF"/>
      <xs:enumeration value="DEM"/>
      <xs:enumeration value="EUR"/>
      <xs:enumeration value="ITL"/>
      <xs:enumeration value="UAH"/>
      <xs:enumeration value="RUB"/>
      <xs:enumeration value="USD"/>
      <xs:enumeration value="BYR"/>
      <xs:enumeration value="MDL"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="edi-interchange-id">
    <xs:restriction base="xs:string">
      <xs:maxLength value="14"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="transport-means">
    <xs:restriction base="xs:string">
      <xs:enumeration value="1"/>
      <!-- Chemikalientanker/Lastkahn -->
      <xs:enumeration value="101"/>
      <!-- Kurierdienst -->
      <xs:enumeration value="10E"/>
      <!-- Tautliner 25t -->
      <xs:enumeration value="11E"/>
      <!-- Tautliner 25t mit abnehmbarem Dach -->
      <xs:enumeration value="12"/>
      <!-- Tankschiff -->
      <xs:enumeration value="12E"/>
      <!-- Sattelzug mit Pritsche 25 t -->
      <xs:enumeration value="13E"/>
      <!-- Sattelzug 24 t mit Pritsche und Kran 10m -->
      <xs:enumeration value="14E"/>
      <!-- Sattelzug 24 t mit Pritsche und Kran 15m -->
      <xs:enumeration value="15E"/>
      <!-- Sattelzug 24 t mit Pritsche und Kran 18m -->
      <xs:enumeration value="16E"/>
      <!-- Sattelzug mit Pritsche 10 t -->
      <xs:enumeration value="17E"/>
      <!-- Tautliner 25t mit Anhaenger 90m3 -->
      <xs:enumeration value="18E"/>
      <!-- Tautliner 25t mit Anhaenger 120m3 -->
      <xs:enumeration value="19E"/>
      <!-- LKW mit Pritsche, Anhaenger + Krank 10m -->
      <xs:enumeration value="20E"/>
      <!-- Sattelzug mit Tankaufbau -->
      <xs:enumeration value="21"/>
      <!-- Tankwaggon -->
      <xs:enumeration value="21E"/>
      <!-- LKW mit Pritsche 15t -->
      <xs:enumeration value="22E"/>
      <!-- LKW mit Pritsche und Kran 15t -->
      <xs:enumeration value="23"/>
      <!-- Schuettgutwaggon -->
      <xs:enumeration value="23E"/>
      <!-- LKW/Anhaenger mit Kippvorrichtung -->
      <xs:enumeration value="24E"/>
      <!-- Tiefkuehl-LKW -->
      <xs:enumeration value="25"/>
      <!-- Bahnexpress -->
      <xs:enumeration value="25E"/>
      <!-- LKW mit isoliertem Kofferaufbau -->
      <xs:enumeration value="26E"/>
      <!-- Kuehl-LKW -->
      <xs:enumeration value="27E"/>
      <!-- Anhaenger mit isoliertem Kofferaufbau -->
      <xs:enumeration value="28E"/>
      <!-- Kuehlanhaenger -->
      <xs:enumeration value="29E"/>
      <!-- Tiefkuehl-Lieferwagen -->
      <xs:enumeration value="30E"/>
      <!-- Lieferwagen mit isoliertem Aufbau -->
      <xs:enumeration value="31"/>
      <!-- LKW -->
      <xs:enumeration value="31E"/>
      <!-- Kuehl-Lieferwagen -->
      <xs:enumeration value="32"/>
      <!-- Tankwagen -->
      <xs:enumeration value="32E"/>
      <!-- Anhaenger -->
      <xs:enumeration value="33E"/>
      <!-- Anhaenger mit Tankaufbau -->
      <xs:enumeration value="34"/>
      <!-- Strassen-Paketexpress -->
      <xs:enumeration value="34E"/>
      <!-- Anhaenger fuer Schuettgut -->
      <xs:enumeration value="35"/>
      <!-- LKW/Anhaenger mit Kippvorrichtung -->
      <xs:enumeration value="35E"/>
      <!-- LKW fuer Schuettgut -->
      <xs:enumeration value="36E"/>
      <!-- Lieferwagen -->
      <xs:enumeration value="37E"/>
      <!-- Anhaenger ausziehbar -->
      <xs:enumeration value="38E"/>
      <!-- Dolly-Anhaenger -->
      <xs:enumeration value="39E"/>
      <!-- Tiefkuehl-Anhaenger -->
      <xs:enumeration value="41"/>
      <!-- Luftfracht -->
      <xs:enumeration value="42"/>
      <!-- Isolierter LKW -->
      <xs:enumeration value="43"/>
      <!-- Kuehl-LKW -->
      <xs:enumeration value="51"/>
      <!-- Paketdienst der Post -->
      <xs:enumeration value="52"/>
      <!-- Exppressdienst der Post -->
      <xs:enumeration value="53"/>
      <!-- Normaler Postversand -->
      <xs:enumeration value="54"/>
      <!-- Beschleunigter normaler Postversand -->
      <xs:enumeration value="55"/>
      <!-- Luftpost -->
      <xs:enumeration value="56"/>
      <!-- Drucksache -->
      <xs:enumeration value="97E"/>
      <!-- LKW mit Anhaenger -->
      <xs:enumeration value="98E"/>
      <!-- LKW mit Kran ebenerdig ohne Anhaenger -->
      <xs:enumeration value="99E"/>
      <!-- LKW mit Kran ebenerdig mit Anhaenger -->
      <xs:enumeration value="X01"/>
      <!-- LKW mit Kran Hochtr. ohne Anhaenger -->
      <xs:enumeration value="X02"/>
      <!-- LKW m. Kran Hochtransp. m. Anhaenger -->
      <xs:enumeration value="X09"/>
      <xs:enumeration value="X13"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="timetype">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{2}:[0-9]{2}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="positionnumbertype">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="1"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="statustype">
    <xs:restriction base="xs:int">
      <xs:enumeration value="0"/>
      <xs:enumeration value="1"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="doctype">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ORDERS"/>
      <xs:enumeration value="ORDRSP"/>
      <xs:enumeration value="DESADV"/>
      <xs:enumeration value="RECADV"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- Тип продукта -->
  <xs:simpleType name="producttypetype">
    <xs:restriction base="xs:int">
      <xs:enumeration value="1"/>
      <!-- Продукт будет поставлен -->
      <xs:enumeration value="2"/>
      <!-- Продукт будет поставлен с изменением количества поставки -->
      <xs:enumeration value="3"/>
      <!-- Продукт не будет поставлен -->
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="actiontype">
    <xs:restriction base="xs:int">
      <xs:enumeration value="5"/>
      <xs:enumeration value="27"/>
      <xs:enumeration value="29"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>