<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:element name="goods-export-01-ds" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="goods-01" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="gds-code" type="xsd:int" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Уникальный код товара</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="mode" type="xsd:string" nillable="false">
                 <xsd:annotation>
                    <xsd:documentation>Режим для импорта: 'add' - добавление товара, 'upd' - изменение товара</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="artic" type="xsd:string" nillable="false">
                 <xsd:annotation>
                    <xsd:documentation>Артикула товара - уникальный в пределах данного производителя</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="prod-type" type="xsd:string" nillable="false">
                 <xsd:annotation>
                    <xsd:documentation>Перечислимый тип производителя: организация, физ. лицо и т.д.</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="prod-code" type="xsd:int" nillable="false">
                 <xsd:annotation>
                    <xsd:documentation>Код производителя - уникальный внутри конкретного справочника</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="prod-name" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Наименование производителя</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="alpha1" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Код страны</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="attrib" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Характеристики</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="calc-method" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Способ расчета цен в текущем сеансе формирования прайс-листа (авто)</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="chk-name" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Название для чека</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="cond-keep-code" type="xsd:int" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Код условия хранения</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="cli-base-rate" type="xsd:decimal" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Коэффициент к единице измерения поставщика</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="cst-base-rate" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Коэффициент пересчета из таможенной в основную единуцу измерения</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="deadline" type="xsd:int" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Срок хранения (дней)</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="destin" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Назначение</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="engl-name" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Название на английском</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="fbr-grp-code" type="xsd:int" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Код глобальной группы для ресторана</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="fbr-grp-name" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Название глобальной группы для ресторана</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="gds-name" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Название товара, соответствующее артикулу</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="gds-type" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Тип: "т" - товар, "у" - услуги</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="grp-code" type="xsd:int" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Ссылка на группу товаров - внутренний номер узла дерева</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="grp-name" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Полное название группы (за искл. корневого узла), к которой относится товар</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="increase-pc" type="xsd:decimal" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Процент наценки</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="label-name" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Название на ценнике</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="max-rate" type="xsd:decimal" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Макс кол-во дробного в штуке (max вес ювелирного изделия)</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="min-rate" type="xsd:decimal" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Мин кол-во дробного в штуке (min вес ювелирного изделия)</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="ms-base" type="xsd:decimal" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Объем штуки</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="ms-cart" type="xsd:decimal" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Объем упаковки</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="negative-Rest" type="xsd:boolean" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Разрешение отрицательных остатков</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="normal-wastage" type="xsd:decimal" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Норма естественной убыли</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="normal-waste" type="xsd:decimal" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Норма отходов</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="okdp" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>ОКДП</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="proof" type="xsd:decimal" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Содержание безводного спирта (%)</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="prt-root" type="xsd:int" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Ссылка на внутренний код корневого узла дерева признаков для данного товара</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="prt-root-name" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Название корневого узла дерева признаков для данного товара</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="PS" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Примечание</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="qnty-cart" type="xsd:decimal" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Количество товара в упаковке в базовых единицах измерения</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="sert" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Сертификация</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="sort" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Сорт</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="struct" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Состав</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="tnved" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Код ТНВЭД</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="unit-base" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Базовая (учетная) единица измерения</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="unit-cli" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Единица измерения поставщика</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="unit-cst" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Таможенная единица измерения</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="user-rule" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Правила эксплутации</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="wt-base" type="xsd:decimal" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Вес штуки</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="wt-cart" type="xsd:decimal" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Вес упаковки</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="vat-pc" type="xsd:decimal" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Ставка НДС (%)</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="attr-alcohol-prod" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Алкогольная продукция</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="attr-fasovka" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Товар фасуется</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="attr-15x80" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Текст поля СОСТАВ 15x80 (DIGI-SM)</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="attr-8x50" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Текст поля СОСТАВ 8x50 (CAS_LP-16x)</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="attr-6x50" type="xsd:string" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Текст поля СОСТАВ 6x50 (CAS_CL5000 CAS_CL5000J)</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="alc-type-code" type="xsd:int" nillable="true">
                 <xsd:annotation>
                    <xsd:documentation>Внутренний код вида алкогольной продукции</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="bar-code-01" minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                   <xsd:documentation>Список бар-кодов по признакам, общий для фирмы</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="b-code" type="xsd:int" nillable="false">
                       <xsd:annotation>
                          <xsd:documentation>Бар-код</xsd:documentation>
                       </xsd:annotation>
                    </xsd:element>
                    <xsd:element name="gds-code" type="xsd:int" nillable="false">
                       <xsd:annotation>
                          <xsd:documentation>Уникальный код товара</xsd:documentation>
                       </xsd:annotation>
                    </xsd:element>
                    <xsd:element name="cli-base-rate" type="xsd:decimal" nillable="false">
                       <xsd:annotation>
                          <xsd:documentation>Коэффициент пересчета из ед. изм. поставщика в базовую (колич. в баз. = колич. в ед. изм. пост. * коэффициент)</xsd:documentation>
                       </xsd:annotation>
                    </xsd:element>
                    <xsd:element name="node-code" type="xsd:int" nillable="false">
                       <xsd:annotation>
                          <xsd:documentation>Внутренний номер узла дерева - ПК</xsd:documentation>
                       </xsd:annotation>
                    </xsd:element>
                    <xsd:element name="node-name" type="xsd:string" nillable="true">
                       <xsd:annotation>
                          <xsd:documentation>Название внутреннего номера узла дерева</xsd:documentation>
                       </xsd:annotation>
                    </xsd:element>
                    <xsd:element name="unit-cli" type="xsd:string" nillable="false">
                       <xsd:annotation>
                          <xsd:documentation>Единица измерения поставщика / покупателя</xsd:documentation>
                       </xsd:annotation>
                    </xsd:element>
                    <xsd:element name="prod-bc-01" minOccurs="0" maxOccurs="unbounded">
                      <xsd:annotation>
                         <xsd:documentation>Дополнительные бар-коды производителя / поставщика</xsd:documentation>
                      </xsd:annotation>
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="b-str" type="xsd:string" nillable="false">
                             <xsd:annotation>
                                <xsd:documentation>Дополнительный бар-код на признак (мб на упаковке)</xsd:documentation>
                             </xsd:annotation>
                          </xsd:element>
                          <xsd:element name="b-code" type="xsd:int" nillable="false">
                             <xsd:annotation>
                                <xsd:documentation>Собственный код с любой единицей измерения на товар, партию, признак</xsd:documentation>
                             </xsd:annotation>
                          </xsd:element>
                          <xsd:element name="bc-on" type="xsd:boolean" nillable="false">
                             <xsd:annotation>
                                <xsd:documentation>Отметка для одинаковых кодов, что именно этот отправляется на кассу, мб yes только для одного</xsd:documentation>
                             </xsd:annotation>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="gds-obj-prop" minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                   <xsd:documentation>Свойства товара на объекте</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="gds-code" type="xsd:int" nillable="false">
                             <xsd:annotation>
                                <xsd:documentation>Уникальный код товара</xsd:documentation>
                             </xsd:annotation>
                          </xsd:element>
                          <xsd:element name="obj-type" type="xsd:string" nillable="false">
                             <xsd:annotation>
                                <xsd:documentation>Перечислимый тип объекта учета товара: склад, магазин, физ. лицо и т.д.</xsd:documentation>
                             </xsd:annotation>
                          </xsd:element>
                          <xsd:element name="obj-code" type="xsd:int" nillable="false">
                             <xsd:annotation>
                                <xsd:documentation>Код объекта - уникальный внутри конкретного справочника</xsd:documentation>
                             </xsd:annotation>
                          </xsd:element>
                          <xsd:element name="grop-level-always-presence" type="xsd:decimal" nillable="true">
                             <xsd:annotation>
                                <xsd:documentation>Уровень постоянного присутстви </xsd:documentation>
                             </xsd:annotation>
                          </xsd:element>
                          <xsd:element name="grop-max-stock" type="xsd:decimal" nillable="true">
                             <xsd:annotation>
                                <xsd:documentation>Максимальный остаток</xsd:documentation>
                             </xsd:annotation>
                          </xsd:element>
                          <xsd:element name="grop-min-order" type="xsd:decimal" nillable="true">
                             <xsd:annotation>
                                <xsd:documentation>Минимальный заказ</xsd:documentation>
                             </xsd:annotation>
                          </xsd:element>
                          <xsd:element name="gdop-igt" type="xsd:string" nillable="true">
                             <xsd:annotation>
                                <xsd:documentation>Индикатор жизнедеятельности товара</xsd:documentation>
                             </xsd:annotation>
                          </xsd:element>
                          <xsd:element name="gdop-min-stock" type="xsd:decimal" nillable="true">
                             <xsd:annotation>
                                <xsd:documentation>Минимальный остаток</xsd:documentation>
                             </xsd:annotation>
                          </xsd:element>
                          <xsd:element name="gdop-assort-min" type="xsd:boolean" nillable="true">
                             <xsd:annotation>
                                <xsd:documentation>Ассортиментный минимум</xsd:documentation>
                             </xsd:annotation>
                          </xsd:element>
                        </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//goods-01"/>
      <xsd:field xpath="gds-code"/>
    </xsd:unique>
    <xsd:unique name="bar-code-01_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//bar-code-01"/>
      <xsd:field xpath="b-code"/>
    </xsd:unique>
    <xsd:unique name="prod-bc-01_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//prod-bc-01"/>
      <xsd:field xpath="b-code"/>
      <xsd:field xpath="b-str"/>
    </xsd:unique>
    <xsd:keyref name="gds-code" refer="pi" prodata:nested="true">
      <xsd:selector xpath=".//bar-code-01"/>
      <xsd:field xpath="gds-code"/>
    </xsd:keyref>
    <xsd:keyref name="b-code" refer="bar-code-01_pi" prodata:nested="true">
      <xsd:selector xpath=".//prod-bc-01"/>
      <xsd:field xpath="b-code"/>
    </xsd:keyref>
  </xsd:element>
</xsd:schema>