<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:include schemaLocation="HEADER.xsd" />
  <xsd:element name="Oracle_Retail" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Header_" type="HEADERType" />
        <xsd:element name="pay-type" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="line-num" type="Line-numType" nillable="false"/>
              <xsd:element name="obj-code" nillable="false">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:positiveInteger">
                    <xsd:totalDigits value="5"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="obj-name" nillable="false">
                <xsd:simpleType>
                   <xsd:restriction base="xsd:normalizedString">
                   <xsd:maxLength value="40"/>
                   </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//pay-type"/>
      <xsd:field xpath="line-num"/>
    </xsd:unique>
  </xsd:element>
  <xsd:annotation>
    <xsd:appinfo>
      <prodata:index name="ipay-type">
        <prodata:table name="pay-type"/>
        <prodata:field name="obj-code"/>
      </prodata:index>
    </xsd:appinfo>
  </xsd:annotation>
</xsd:schema>
