<?xml version="1.0" encoding="windows-1251"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:include schemaLocation="HEADER.xsd" />
  <xsd:element name="Oracle_Retail" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Header_" type="HEADERType" />
        <xsd:element name="tax-rate" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="line-num" type="Line-numType" nillable="false"/>
              <xsd:element name="rate-code" nillable="false">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:positiveInteger">
                    <xsd:totalDigits value="3"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="rate-name" minOccurs="0" nillable="false">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:normalizedString">
                    <xsd:maxLength value="40"/>
                    <xsd:minLength value="1"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="status_" type="StatusType" nillable="false"/>
              <xsd:element name="tax-rate-value" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="line-num" type="Line-numType" nillable="false"/>
                    <xsd:element name="rate-code" nillable="false">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:positiveInteger">
                          <xsd:totalDigits value="3"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="fact-date" type="xsd:date" nillable="false"/>
                    <xsd:element name="rate-value" nillable="false">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:decimal">
                          <xsd:minInclusive value="0"/>
                          <xsd:maxExclusive value="100"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="status_" type="StatusType" nillable="false"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//tax-rate"/>
      <xsd:field xpath="line-num"/>
    </xsd:unique>
    <xsd:unique name="tax-rate-value_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//tax-rate-value"/>
      <xsd:field xpath="line-num"/>
      <xsd:field xpath="fact-date"/>
    </xsd:unique>
    <xsd:keyref name="line" refer="pi" prodata:nested="true">
      <xsd:selector xpath=".//tax-rate-value"/>
      <xsd:field xpath="line-num"/>
    </xsd:keyref>
  </xsd:element>
  <xsd:annotation>
    <xsd:appinfo>
      <prodata:index name="irate">
        <prodata:table name="tax-rate"/>
        <prodata:field name="rate-code"/>
      </prodata:index>
      <prodata:index name="pi2">
        <prodata:table name="tax-rate-value"/>
        <prodata:field name="line-num"/>
        <prodata:field name="rate-code"/>
        <prodata:field name="fact-date"/>
      </prodata:index>
    </xsd:appinfo>
  </xsd:annotation>
</xsd:schema>