<?xml version="1.0" encoding="windows-1251"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:include schemaLocation="HEADER.xsd" />
  <xsd:element name="Oracle_Retail" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Header_" type="HEADERType" />
        <xsd:element name="dis-card" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="line-num" type="Line-numType" nillable="false"/>
              <xsd:element name="cli-type" type="CliType" nillable="false"/>
              <xsd:element name="cli-code" type="CliCode" nillable="false"/>
              <xsd:element name="d-card" nillable="false">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                    <xsd:pattern value="[1-9]([0-9]{0,18})"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="type"  nillable="false">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:normalizedString">
                    <xsd:maxLength value="8"/>
                    <xsd:minLength value="1"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="issue-date" type="xsd:date" nillable="false"/>
              <xsd:element name="valid-date" type="xsd:date" nillable="true"/>
              <xsd:element name="category"  nillable="false">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:nonNegativeInteger">
                    <xsd:maxInclusive value="9999"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="status_" type="StatusType" nillable="false"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//dis-card"/>
      <xsd:field xpath="line-num"/>
    </xsd:unique>
  </xsd:element>
  <xsd:annotation>
    <xsd:appinfo>
      <prodata:index name="icard">
        <prodata:table name="dis-card"/>
        <prodata:field name="d-card"/>
      </prodata:index>
    </xsd:appinfo>
  </xsd:annotation>
</xsd:schema>
