<?xml version="1.0" encoding="windows-1251"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:include schemaLocation="HEADER.xsd" />
  <xsd:element name="Oracle_Retail" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Header_" type="HEADERType" />
        <xsd:element maxOccurs="unbounded" name="clients">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="line-num" type="Line-numType" nillable="false"/>
              <xsd:element name="obj-type" type="CliType" nillable="false"/>
              <xsd:element name="obj-code" type="CliCode" nillable="false"/>
              <xsd:element name="obj-name" nillable="false">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:normalizedString">
                    <xsd:minLength value="1"/>
                    <xsd:maxLength value="130"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="stts" nillable="false">
                <xsd:simpleType>
                  <xsd:annotation>
                    <xsd:documentation>
                      0- статус текущий (активный) 1- логически удаленный
                    </xsd:documentation>
                  </xsd:annotation>
                  <xsd:restriction base="xsd:int">
                    <xsd:enumeration value="0"/>
                    <xsd:enumeration value="1"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="vetoManDoc" nillable="false" minOccurs="0">
                <xsd:simpleType>
                  <xsd:annotation>
                    <xsd:documentation>
                      запрет на создание оператором документов на данного контрагента (если значение не равно ПУСТО)
                      типы запрещенных документов могут (в будущем) зависеть от значения атрибута
                      в настоящий момент поддерживается только одно непустое значение = ALL
                    </xsd:documentation>
                  </xsd:annotation>
                  <xsd:restriction base="xsd:string">
                    <xsd:enumeration value=""/>
                    <xsd:enumeration value="ALL"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element minOccurs="0" name="ps" type="xsd:string" />
              <xsd:element name="fin-schet" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="line-num" type="Line-numType" nillable="false"/>
                    <xsd:element name="cli-type" type="CliType" nillable="false"/>
                    <xsd:element name="cli-code" type="CliCode" nillable="false"/>
                    <xsd:element name="code-bank" type="posint9" nillable="false"/>
                    <xsd:element name="curr-code" type="CurrCode" nillable="false"/>
                    <xsd:element name="r-schet" nillable="false">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:minLength value="9"/>
                          <xsd:maxLength value="20"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="firm" minOccurs="0" maxOccurs="1">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="line-num" type="Line-numType" nillable="false"/>
                    <xsd:element name="firm-code" type="CliCode" nillable="false"/>
                    <xsd:element minOccurs="0" name="engl-name">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:normalizedString">
                          <xsd:minLength value="1" />
                          <xsd:maxLength value="40" />
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="city">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:normalizedString">
                          <xsd:maxLength value="40"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="ind">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:int">
                          <xsd:minInclusive value="0"/>
                          <xsd:maxInclusive value="999999"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                     </xsd:element>
                    <xsd:element minOccurs="0" name="addres1" type="xsd:normalizedString" />
                    <xsd:element minOccurs="0" name="addres2" type="xsd:normalizedString" />
                    <xsd:element minOccurs="0" name="post-addr1" type="xsd:normalizedString" />
                    <xsd:element minOccurs="0" name="post-addr2" type="xsd:normalizedString" />
                    <xsd:element minOccurs="0" name="inn" >
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:pattern value="[0-9]{0,12}"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="nds-serries" >
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:int">
                          <xsd:minInclusive value="0"/>
                          <xsd:maxInclusive value="99999"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="nds-number"  >
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:int">
                          <xsd:minInclusive value="0"/>
                          <xsd:maxInclusive value="9999999"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="nds-date" type="xsd:date" />
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="person" minOccurs="0" maxOccurs="1">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="line-num" type="Line-numType" nillable="false"/>
                    <xsd:element name="psn-code" type="CliCode" nillable="false"/>
                    <xsd:element name="name1" type="xsd:normalizedString" />
                    <xsd:element name="name2" type="xsd:normalizedString" />
                    <xsd:element minOccurs="0" name="address" type="xsd:normalizedString" />
                    <xsd:element minOccurs="0" name="passp-ser" type="xsd:normalizedString" />
                    <xsd:element minOccurs="0" name="passp-num" type="xsd:normalizedString" />
                    <xsd:element minOccurs="0" name="given-by" type="xsd:normalizedString" />
                    <xsd:element minOccurs="0" name="city" type="xsd:normalizedString" />
                    <xsd:element minOccurs="0" name="ind">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:int">
                          <xsd:minInclusive value="0"/>
                          <xsd:maxInclusive value="999999"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                     </xsd:element>
                    <xsd:element minOccurs="0" name="inn">
                      <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                          <xsd:pattern value="[0-9]{0,12}"/>
                        </xsd:restriction>
                      </xsd:simpleType>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="gender" type="xsd:boolean">
                      <xsd:annotation>
                        <xsd:documentation>
                          мужской - false, женский - true, неизвестно nill
                        </xsd:documentation>
                      </xsd:annotation>
                    </xsd:element>
                    <xsd:element minOccurs="0" name="date-birth" type="xsd:date" />
                    <xsd:element minOccurs="0" name="position" type="xsd:normalizedString" />
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//clients"/>
      <xsd:field xpath="line-num"/>
    </xsd:unique>
    <xsd:unique name="fin-schet_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//fin-schet"/>
      <xsd:field xpath="line-num"/>
      <xsd:field xpath="code-bank"/>
      <xsd:field xpath="r-schet"/>
    </xsd:unique>
    <xsd:unique name="firm_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//firm"/>
      <xsd:field xpath="line-num"/>
    </xsd:unique>
    <xsd:unique name="person_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//person"/>
      <xsd:field xpath="line-num"/>
    </xsd:unique>
  </xsd:element>
  <xsd:annotation>
    <xsd:appinfo>
      <prodata:index name="icli">
        <prodata:table name="clients"/>
        <prodata:field name="obj-type"/>
        <prodata:field name="obj-code"/>
        <prodata:field name="line-num"/>
      </prodata:index>
      <prodata:index name="ischet">
        <prodata:table name="fin-schet"/>
        <prodata:field name="cli-type"/>
        <prodata:field name="cli-code"/>
        <prodata:field name="code-bank"/>
        <prodata:field name="r-schet"/>
        <prodata:field name="line-num"/>
      </prodata:index>
      <prodata:index name="ifirm">
        <prodata:table name="firm"/>
        <prodata:field name="firm-code"/>
        <prodata:field name="line-num"/>
      </prodata:index>
      <prodata:index name="ipsn">
        <prodata:table name="person"/>
        <prodata:field name="psn-code"/>
        <prodata:field name="line-num"/>
      </prodata:index>
      <prodata:relation name="schet-r" prodata:nested="true" prodata:parent="clients" prodata:child="fin-schet" prodata:relationFields="obj-type,cli-type,obj-code,cli-code"/>
      <prodata:relation name="firm-r" prodata:nested="true" prodata:parent="clients" prodata:child="firm" prodata:relationFields="obj-code,firm-code"/>
      <prodata:relation name="person-r" prodata:nested="true" prodata:parent="clients" prodata:child="person" prodata:relationFields="obj-code,psn-code"/>
    </xsd:appinfo>
  </xsd:annotation>
</xsd:schema>