<?xml version="1.0" encoding="windows-1251"?>
<xsd:schema xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:include schemaLocation="HEADER.xsd" />
  <xsd:element prodata:proDataSet="true" name="Oracle_Retail">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Header_" type="HEADERType" />
        <xsd:element minOccurs="1" maxOccurs="unbounded" name="Category">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="line-num" type="Line-numType"/>
              <xsd:element name="CATEGORY_ID" type="posint9"/>
              <xsd:element name="CATEGORY_NAME" minOccurs="0">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:normalizedString">
                    <xsd:minLength value="1" />
                    <xsd:maxLength value="160" />
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="status_" type="StatusType"/>
              <xsd:element name="discnt-type" nillable="false">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:normalizedString">
                    <xsd:enumeration value="temp-disc"/>
                    <xsd:enumeration value="pcnt-tot-kateg"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="Cat-dtl" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="line-num" type="Line-numType" />
                    <xsd:element name="CATEGORY_ID" type="posint9" />
                    <xsd:element name="dtl_id" type="xsd:int" nillable="false"/>
                    <xsd:element name="Discount" type="xsd:decimal" />
                    <xsd:element name="Threshold" type="xsd:decimal" minOccurs="0"  />
                    <xsd:element name="status_" type="StatusType" />
                    <xsd:element name="Cat-item" minOccurs="0" maxOccurs="unbounded">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="line-num" type="Line-numType" />
                          <xsd:element name="CATEGORY_ID" type="posint9" />
                          <xsd:element name="dtl_id" type="xsd:int" nillable="false"/>
                          <xsd:element name="b-code" type="posint9" />
                          <xsd:element name="status_" type="StatusType" />
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//Category"/>
      <xsd:field xpath="line-num"/>
    </xsd:unique>
    <xsd:unique name="Cat-dtl_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//Cat-dtl"/>
      <xsd:field xpath="line-num"/>
      <xsd:field xpath="CATEGORY_ID"/>
      <xsd:field xpath="dtl_id"/>
    </xsd:unique>
    <xsd:unique name="Cat-item_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//Cat-item"/>
      <xsd:field xpath="line-num"/>
      <xsd:field xpath="dtl_id"/>
      <xsd:field xpath="b-code"/>
    </xsd:unique>
  </xsd:element>
  <xsd:annotation>
    <xsd:appinfo>
      <prodata:index name="icat">
        <prodata:table name="Category"/>
        <prodata:field name="CATEGORY_ID"/>
      </prodata:index>
      <prodata:index name="ibcode">
        <prodata:table name="Cat-item"/>
        <prodata:field name="b-code"/>
      </prodata:index>
      <prodata:relation name="cat1" prodata:nested="true" prodata:parent="Category" prodata:child="Cat-dtl" prodata:relationFields="line-num,line-num,CATEGORY_ID,CATEGORY_ID"/>
      <prodata:relation name="cat2" prodata:nested="true" prodata:parent="Cat-dtl" prodata:child="Cat-item" prodata:relationFields="line-num,line-num,dtl_id,dtl_id"/>
    </xsd:appinfo>
  </xsd:annotation>
</xsd:schema>