<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:include schemaLocation="HEADER.xsd"/>
  <xsd:element name="Oracle_Retail" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Header_" type="HEADERType"/>
        <xsd:element name="goods" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="line-num" type="Line-numType" nillable="false"/>
              <xsd:element name="status_" type="StatusType" nillable="false"/>
              <xsd:element name="gds-code" type="BarCodeType" nillable="false"/>
              <xsd:element name="artic" type="THArtic" nillable="false"/>
              <xsd:element name="prod-type" type="CliType" nillable="false"/>
              <xsd:element name="prod-code" type="CliCode" nillable="false"/>
              <xsd:element name="gds-name" nillable="false">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:normalizedString">
                    <xsd:maxLength value="48"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="engl-name" minOccurs="0">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:normalizedString">
                    <xsd:maxLength value="40"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="label-name" nillable="false">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:normalizedString">
                    <xsd:maxLength value="80"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="chk-name" nillable="false">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:normalizedString">
                    <xsd:maxLength value="25"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="depart-code" type="posint9" nillable="false"/>
              <xsd:element name="class-code" type="posint9" nillable="false"/>
              <xsd:element name="subclass-code" type="posint9" nillable="false"/>
              <xsd:element name="unit-base" type="Unit" nillable="false"/>
              <xsd:element name="wt-base" minOccurs="0">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:decimal">
                    <xsd:minExclusive value="0"/>
                    <xsd:fractionDigits value="3"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="ms-base" minOccurs="0">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:decimal">
                    <xsd:minExclusive value="0"/>
                    <xsd:fractionDigits value="3"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="unit-cli" type="Unit" minOccurs="0"/>
              <xsd:element name="cli-base-rate" type="THCliBaseRate" minOccurs="0"/>
              <xsd:element name="qnty-cart" minOccurs="0">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:decimal">
                    <xsd:minExclusive value="0"/>
                    <xsd:fractionDigits value="3"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="wt-cart" minOccurs="0">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:decimal">
                    <xsd:minExclusive value="0"/>
                    <xsd:fractionDigits value="3"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="ms-cart" minOccurs="0">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:decimal">
                    <xsd:minExclusive value="0"/>
                    <xsd:fractionDigits value="3"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="gds-type" type="THGoodsType" nillable="false"/>
              <xsd:element name="PS" type="xsd:string" minOccurs="0"/>
              <xsd:element name="okdp" minOccurs="0">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:normalizedString">
                    <xsd:maxLength value="9"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="negative-rest" type="xsd:boolean" nillable="false"/>
              <xsd:element name="min-stock" type="xsd:decimal" minOccurs="0"/>
              <xsd:element name="alpha1" nillable="false">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                    <xsd:pattern value="[A-Z]{2}"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="rate-code" nillable="false">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:positiveInteger">
                    <xsd:totalDigits value="3"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="bar-code" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="line-num" type="Line-numType" nillable="false"/>
                    <xsd:element name="status_" type="StatusType" nillable="false"/>
                    <xsd:element name="b-code" type="BarCodeType" nillable="false"/>
                    <xsd:element name="gds-code" type="BarCodeType" nillable="false"/>
                    <xsd:element name="unit-cli" type="Unit" nillable="false"/>
                    <xsd:element name="cli-base-rate" type="THCliBaseRate" nillable="false"/>
                    <xsd:element name="prod-bc" minOccurs="0" maxOccurs="unbounded">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="line-num" type="Line-numType" nillable="false"/>
                          <xsd:element name="gds-code" type="BarCodeType" nillable="false"/>
                          <xsd:element name="b-code" type="BarCodeType" nillable="false"/>
                          <xsd:element name="b-str" nillable="false">
                            <xsd:simpleType>
                              <xsd:restriction base="xsd:string">
                                <xsd:pattern value="\d{6,16}"/>
                              </xsd:restriction>
                            </xsd:simpleType>
                          </xsd:element>
                          <xsd:element name="bc-on" type="xsd:boolean" nillable="false"/>
                          <xsd:element name="status_" type="StatusType" nillable="false">
                            <xsd:annotation>
                              <xsd:documentation>
                              Физическое удаление
                              </xsd:documentation>
                            </xsd:annotation>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//goods"/>
      <xsd:field xpath="line-num"/>
    </xsd:unique>
    <xsd:unique name="bar-code_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//bar-code"/>
      <xsd:field xpath="line-num"/>
      <xsd:field xpath="b-code"/>
    </xsd:unique>
    <xsd:unique name="prod-bc_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//prod-bc"/>
      <xsd:field xpath="line-num"/>
      <xsd:field xpath="b-code"/>
      <xsd:field xpath="b-str"/>
    </xsd:unique>
    <xsd:keyref name="b-code2" refer="bar-code_pi" prodata:nested="true">
      <xsd:selector xpath=".//prod-bc"/>
      <xsd:field xpath="line-num"/>
      <xsd:field xpath="b-code"/>
    </xsd:keyref>
  </xsd:element>
  <xsd:annotation>
    <xsd:appinfo>
      <prodata:index name="pi2">
        <prodata:table name="goods"/>
        <prodata:field name="gds-code"/>
      </prodata:index>
      <prodata:index name="iartic">
        <prodata:table name="goods"/>
        <prodata:field name="artic"/>
        <prodata:field name="prod-type"/>
        <prodata:field name="prod-code"/>
      </prodata:index>
      <prodata:index name="pi2">
        <prodata:table name="bar-code"/>
        <prodata:field name="b-code"/>
      </prodata:index>
      <prodata:index name="igds">
        <prodata:table name="bar-code"/>
        <prodata:field name="gds-code"/>
      </prodata:index>
      <prodata:index name="pi2">
        <prodata:table name="prod-bc"/>
        <prodata:field name="b-code"/>
        <prodata:field name="b-str"/>
      </prodata:index>
      <prodata:relation name="b-code1" prodata:nested="true" prodata:parent="goods" prodata:child="bar-code" prodata:relationFields="line-num,line-num,gds-code,gds-code"/>
    </xsd:appinfo>
  </xsd:annotation>
</xsd:schema>