<?xml version="1.0" encoding="windows-1251"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:include schemaLocation="HEADER.xsd" />
  <xsd:element name="Oracle_Retail" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Header_" type="HEADERType" />
        <xsd:element name="rpm-gds-grp" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="line-num" type="Line-numType" nillable="false"/>
              <xsd:element name="status_" type="StatusType" nillable="false"/>
              <xsd:element name="group-code" type="posint9" nillable="false"/>
              <xsd:element name="depart-code" type="xsd:nonNegativeInteger" nillable="false">
                <xsd:annotation>
                  <xsd:documentation>
                    если 0, то предполагаю, что это группа
                  </xsd:documentation>
                </xsd:annotation>
              </xsd:element> 
              <xsd:element name="class-code" type="xsd:nonNegativeInteger" nillable="false">
                <xsd:annotation>
                  <xsd:documentation>
                    если 0, то предполагаю, что это отдел
                  </xsd:documentation>
                </xsd:annotation>
              </xsd:element>
              <xsd:element name="subclass-code" type="xsd:nonNegativeInteger" nillable="false">
                <xsd:annotation>
                  <xsd:documentation>
                    если 0, то предполагаю, что это класс
                  </xsd:documentation>
                </xsd:annotation>
              </xsd:element>
              <xsd:element name="rpm-grp-name" nillable="false">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:normalizedString">
                    <xsd:minLength value="1"/>
                    <xsd:maxLength value="40"/>
                    </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//rpm-gds-grp"/>
      <xsd:field xpath="line-num"/>
    </xsd:unique>
  </xsd:element>
  <xsd:annotation>
    <xsd:appinfo>
      <prodata:index name="igrp">
        <prodata:table name="rpm-gds-grp"/>
        <prodata:field name="group-code"/>
        <prodata:field name="depart-code"/>
        <prodata:field name="class-code"/>
        <prodata:field name="subclass-code"/>
      </prodata:index>
    </xsd:appinfo>
  </xsd:annotation>
</xsd:schema>
