<?xml version="1.0" encoding="windows-1251"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:include schemaLocation="HEADER.xsd" />
  <xsd:element name="Oracle_Retail" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
       <xsd:element name="Header_" type="HEADERType" />
        <xsd:element name="price-doc" minOccurs="1" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="line-num" type="Line-numType" nillable="false"/>
              <xsd:element name="doc-num" type="xsd:positiveInteger" nillable="false"/>
              <xsd:element name="obj-type" type="ObjType" nillable="false"/>
              <xsd:element name="obj-code" type="ObjCode" nillable="false"/>
              <xsd:element name="doc-date" type="xsd:date" nillable="false"/>
              <xsd:element name="price-list" minOccurs="1" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                     <xsd:element name="line-num" type="Line-numType" nillable="false"/>
                    <xsd:element name="doc-num" type="xsd:positiveInteger" nillable="false"/>
                    <xsd:element name="bar-code" type="BarCodeType" nillable="false"/>
                    <xsd:element name="price-sale" type="PriceType" nillable="false"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//price-doc"/>
      <xsd:field xpath="line-num"/>
    </xsd:unique>
    <xsd:unique name="price-list_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//price-list"/>
      <xsd:field xpath="line-num"/>
      <xsd:field xpath="doc-num"/>
      <xsd:field xpath="bar-code"/>
    </xsd:unique>
  </xsd:element>
  <xsd:annotation>
    <xsd:appinfo>
      <prodata:index name="idoc">
        <prodata:table name="price-doc"/>
        <prodata:field name="doc-num"/>
      </prodata:index>
      <prodata:relation name="doc-num" prodata:nested="true" prodata:parent="price-doc" prodata:child="price-list" prodata:relationFields="line-num,line-num,doc-num,doc-num"/>
    </xsd:appinfo>
  </xsd:annotation>

</xsd:schema>