<?xml version="1.0" encoding="windows-1251"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
<xsd:include schemaLocation="HEADER.xsd" />
  <xsd:element name="Oracle_Retail" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Header_" type="HEADERType" />
        <xsd:element name="contract-specif" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="line-num" type="Line-numType" nillable="false"/>
              <xsd:element name="contract-code" type="posint9" nillable="false">
                 <xsd:annotation>
                    <xsd:documentation>Значение contract-code всегда совпадает с кодом поставщика</xsd:documentation>
                 </xsd:annotation>
              </xsd:element>
              <xsd:element name="status_" type="StatusType" nillable="false"/>
              <xsd:element name="gds-code" type="BarCodeType" nillable="false"/>
              <xsd:element name="price-cli" type="PriceType" nillable="false"/>
              <xsd:element name="exch-code" type="CurrCode" nillable="false"/>
              <xsd:element name="exch-rate" type="THExchRate" nillable="false"/>
              <xsd:element name="exch-scale" type="THExchScale" nillable="false"/>
              <xsd:element name="prc" type="xsd:decimal" nillable="false"/>
              <xsd:element name="vat-pc" type="VatType" nillable="false"/>
              <xsd:element name="payer-vat" nillable="false">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="в т. ч."/>
                    <xsd:enumeration value="нет"/>
                    <xsd:enumeration value="без"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//contract-specif"/>
      <xsd:field xpath="line-num"/>
      <xsd:field xpath="contract-code"/>
      <xsd:field xpath="gds-code"/>
    </xsd:unique>
  </xsd:element>
</xsd:schema>
