<?xml version="1.0" encoding="windows-1251"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:include schemaLocation="HEADER.xsd" />
  <xsd:element name="Oracle_Retail" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Header_" type="HEADERType" />
        <xsd:element name="inv-doc" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="line-num" type="Line-numType" nillable="false"/>
              <xsd:element name="doc-date" type="xsd:date" nillable="false"/>
              <xsd:element name="obj-type" type="ObjType" nillable="false"/>
              <xsd:element name="obj-code" type="ObjCode" nillable="false"/>
              <xsd:element name="doc-code" type="xsd:string" nillable="false"/>
              <xsd:element name="ps" type="xsd:string" minOccurs="0"/>
              <xsd:element name="ext-doc-type" type="THExtentedDocType" nillable="false"/>
              <xsd:element name="gds-line" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="line-num" type="Line-numType" nillable="false"/>
                    <xsd:element name="gds-code" type="BarCodeType" nillable="false"/>
                    <xsd:element name="doc-code" type="xsd:string" nillable="false"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="grp-line" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="line-num" type="Line-numType" nillable="false"/>
                    <xsd:element name="depart-code" type="posint9" nillable="false"/>
                    <xsd:element name="class-code" type="xsd:nonNegativeInteger" nillable="false"/>
                    <xsd:element name="subclass-code" type="xsd:nonNegativeInteger" nillable="false"/>
                    <xsd:element name="doc-code" type="xsd:string" nillable="false"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//inv-doc"/>
      <xsd:field xpath="line-num"/>
    </xsd:unique>
    <xsd:unique name="gds-line_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//gds-line"/>
      <xsd:field xpath="line-num"/>
      <xsd:field xpath="doc-code"/>
      <xsd:field xpath="gds-code"/>
    </xsd:unique>
    <xsd:unique name="grp-line_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//grp-line"/>
      <xsd:field xpath="line-num"/>
      <xsd:field xpath="doc-code"/>
      <xsd:field xpath="depart-code"/>
      <xsd:field xpath="class-code"/>
      <xsd:field xpath="subclass-code"/>
    </xsd:unique>
  </xsd:element>
  <xsd:annotation>
    <xsd:appinfo>
      <prodata:index name="igdsline">
        <prodata:table name="gds-line"/>
        <prodata:field name="doc-code"/>
        <prodata:field name="gds-code"/>
      </prodata:index>
      <prodata:index name="igrpline">
        <prodata:table name="grp-line"/>
        <prodata:field name="doc-code"/>
        <prodata:field name="depart-code"/>
        <prodata:field name="class-code"/>
        <prodata:field name="subclass-code"/>
      </prodata:index>
      <prodata:relation name="doc-code1" prodata:nested="true" prodata:parent="inv-doc" prodata:child="gds-line" prodata:relationFields="line-num,line-num,doc-code,doc-code"/>
      <prodata:relation name="doc-code2" prodata:nested="true" prodata:parent="inv-doc" prodata:child="grp-line" prodata:relationFields="line-num,line-num,doc-code,doc-code"/>
    </xsd:appinfo>
  </xsd:annotation>
</xsd:schema>