<?xml version="1.0" encoding="windows-1251"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:include schemaLocation="HEADER.xsd" />
  <xsd:element name="Oracle_Retail" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Header_" type="HEADERType" />
        <xsd:element name="fin-bank" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="line-num" type="Line-numType" nillable="false"/>
              <xsd:element name="code-bank" type="posint9" nillable="false"/>
              <xsd:element name="bank-name" nillable="false">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:normalizedString">
                    <xsd:maxLength value="100"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="bik" nillable="false">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                    <xsd:minLength value="8"/>
                    <xsd:maxLength value="11"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="addres" nillable="false">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:normalizedString">
                    <xsd:maxLength value="100"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="short-name" nillable="false">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:normalizedString">
                    <xsd:maxLength value="25"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="bank-city" nillable="false">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:normalizedString">
                    <xsd:maxLength value="25"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="PS" type="xsd:string" minOccurs="0"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//fin-bank"/>
      <xsd:field xpath="line-num"/>
    </xsd:unique>
  </xsd:element>
  <xsd:annotation>
    <xsd:appinfo>
      <prodata:index name="pi2">
        <prodata:table name="fin-bank"/>
        <prodata:field name="code-bank"/>
      </prodata:index>
    </xsd:appinfo>
  </xsd:annotation>
</xsd:schema>
