<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:element name="lantab-export-ds" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="lantab-export-trn" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="d-card" type="xsd:string" nillable="true"/>
              <xsd:element name="obj-code" type="xsd:int" nillable="true"/>
              <xsd:element name="gds-dis-r-b" type="xsd:decimal" nillable="true"/>
              <xsd:element name="gds-tot-r-b" type="xsd:decimal" nillable="true"/>
              <xsd:element name="sale-doc" type="xsd:string" nillable="true"/>
              <xsd:element name="doc-date" type="xsd:date" nillable="true"/>
              <xsd:element name="action" type="xsd:int" nillable="true"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="lantab-export-chk" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="d-card" type="xsd:string" nillable="true"/>
              <xsd:element name="obj-code" type="xsd:int" nillable="true"/>
              <xsd:element name="netto" type="xsd:decimal" nillable="true"/>
              <xsd:element name="discnt" type="xsd:decimal" nillable="true"/>
              <xsd:element name="doc-code" type="xsd:string" nillable="true"/>
              <xsd:element name="out-code" type="xsd:string" nillable="true"/>
              <xsd:element name="chk-date" type="xsd:date" nillable="true"/>
              <xsd:element name="action" type="xsd:int" nillable="true"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//lantab-export-trn"/>
      <xsd:field xpath="d-card"/>
      <xsd:field xpath="sale-doc"/>
      <xsd:field xpath="action"/>
    </xsd:unique>
    <xsd:unique name="lantab-export-chk_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//lantab-export-chk"/>
      <xsd:field xpath="d-card"/>
      <xsd:field xpath="doc-code"/>
      <xsd:field xpath="out-code"/>
      <xsd:field xpath="action"/>
    </xsd:unique>
  </xsd:element>
</xsd:schema>
