<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
	<xsd:element name="IBS_Trade_House" prodata:proDataSet="true">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="receipt" minOccurs="1" maxOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="exch_file_name" type="xsd:string" nillable="false"/>
							<xsd:element name="exch_file_date" type="xsd:string" nillable="false"/>
							<xsd:element name="file_proc_date" type="xsd:string" nillable="false"/>
							<xsd:element name="error" nillable="false">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:enumeration value="RANGE"/>
										<xsd:enumeration value="SYNCHRONIZATION"/>
										<xsd:enumeration value="NULL"/>
										<xsd:enumeration value="PROCESSING"/>
										<xsd:enumeration value="STRUCTURE"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="prot_file_name" type="xsd:string" nillable="false"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
		<xsd:unique name="pi" prodata:primaryIndex="true">
			<xsd:selector xpath=".//receipt"/>
			<xsd:field xpath="exch_file_name"/>
		</xsd:unique>
	</xsd:element>
</xsd:schema>