<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:element name="order-line-export-01-ds" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="order-line-01" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="cliart" type="xsd:string" nillable="false"/>
              <xsd:element name="artth" type="xsd:string" nillable="false"/>
              <xsd:element name="nameth" type="xsd:string" nillable="flase"/>
              <xsd:element name="quantityquant" type="xsd:decimal" nillable="false"/>
              <xsd:element name="pricequant" type="xsd:decimal" nillable="false"/>
              <xsd:element name="status_" type="xsd:int" nillable="false"/>
              <xsd:element name="desstatus" type="xsd:string" nillable="false"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//order-line-01"/>
      <xsd:field xpath="cliart"/>
    </xsd:unique>
  </xsd:element>
</xsd:schema>
