<?xml version="1.0" encoding="windows-1251"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsd="undefined" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xs:include schemaLocation="exitetypes_0-01.xsd"/>
  <xs:element name="ORDRSP_">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ORDRSP">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="NUMBER" type="numbertype"/>
              <!-- Номер документа -->
              <xs:element name="DATE" type="xs:date"/>
              <!-- Дата документа -->
              <xs:element name="TIME_" type="timetype" minOccurs="0">
              </xs:element>
              <xs:element name="ORDERNUMBER" type="numbertype"/>
              <!-- Номер заказа -->
              <xs:element name="ORDERDATE" type="xs:date"/>
              <!-- Дата заказа -->
              <xs:element name="DELIVERYDATE" type="xs:date" minOccurs="0"/>
              <!-- Дата доставки -->
              <xs:element name="CURRENCY" type="currency" minOccurs="0"/>
              <!-- Валюта -->
              <xs:element name="ACTION" type="actiontype"/>
              <xs:element ref="HEAD"/>
              <!--  -->
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    <xs:unique name="pi" prodata:primaryIndex="true">
      <xs:selector xpath=".//ORDRSP"/>
      <xs:field xpath="NUMBER"/>
    </xs:unique>
    <xs:unique name="HEAD_pi" prodata:primaryIndex="true">
      <xs:selector xpath=".//HEAD"/>
      <xs:field xpath="NUMBER"/>
    </xs:unique>
    <xs:unique name="POSITION_pi" prodata:primaryIndex="true">
      <xs:selector xpath=".//POSITION"/>
      <xs:field xpath="NUMBER"/>
      <xs:field xpath="POSITIONNUMBER"/>
    </xs:unique>
    <xs:keyref name="r1" refer="pi" prodata:nested="true">
      <xs:selector xpath=".//HEAD"/>
      <xs:field xpath="NUMBER"/>
    </xs:keyref>
    <xs:keyref name="r2" refer="HEAD_pi" prodata:nested="true">
      <xs:selector xpath=".//POSITION"/>
      <xs:field xpath="NUMBER"/>
    </xs:keyref>
  </xs:element>

  <xs:element name="HEAD">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="NUMBER" type="numbertype"/>
        <!-- Номер документа -->
        <xs:element name="BUYER" type="gln"/>
        <!-- GLN покупателя -->
        <xs:element name="SUPPLIER" type="gln"/>
        <!-- GLN поставщика -->
        <xs:element name="DELIVERYPLACE" type="gln"/>
        <!-- GLN места доставки -->
        <xs:element name="INVOICEPARTNER" type="gln" minOccurs="0"/>
        <!-- GLN плательщика -->
        <xs:element name="SENDER" type="mailbox"/>
        <!-- GLN отправителя сообщения -->
        <xs:element name="RECIPIENT" type="mailbox"/>
        <!-- GLN получателя сообщения -->
        <xs:element name="EDIINTERCHANGEID" type="edi-interchange-id">
          <!-- Номер транзакции -->
        </xs:element>
        <xs:element name="EDIMESSAGE" type="ordrspdoctype" minOccurs="0"/>
        <!-- ... -->

        <xs:element ref="POSITION" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="POSITION">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="NUMBER" type="numbertype"/>
        <xs:element name="POSITIONNUMBER" type="positionnumbertype"/>
        <!-- Номер позиции в заказе -->
        <xs:element name="PRODUCT" type="gln"/>
        <!-- GTIN(Штрих-код) продукта-->
        <xs:element name="PRODUCTIDBUYER" type="numbertype"/>
        <!-- Номер продукта по БД покупателя -->
        <xs:element name="PRODUCTIDSUPPLIER" type="numbertype"/>
        <!-- Номер продукта по БД поставщика -->
        <xs:element name="DESCRIPTION" type="xs:string" minOccurs="0"/>
        <!-- Описание позиции -->
        <xs:element name="PRICE" type="amount"/>
        <!-- Цена -->
        <xs:element name="VAT" type="percentage"/>
        <xs:element name="PRODUCTTYPE" type="producttypetype"/>
        <!-- Тип продукта -->
        <xs:element name="ORDEREDQUANTITY" type="amount"/>
        <!-- Заказанное количество -->
        <xs:element name="ACCEPTEDQUANTITY" type="amount"/>
        <!-- Имеющееся количество -->
        <xs:element name="INFO" type="xs:string" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="ordrspdoctype">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ORDERSP"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>