<?xml version="1.0" encoding="windows-1251"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:include schemaLocation="reporttypes.xsd"/>
  <xsd:element name="report-ptdysa-ds" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="report-header" type="reportheaderType"/>
        <xsd:element name="obj-dyn-sal" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="obj-type" type="xsd:string" nillable="false"/>
              <xsd:element name="obj-code" type="xsd:int" nillable="false"/>
              <xsd:element name="obj-name" type="xsd:string" nillable="false"/>
              <xsd:element name="obj-address" type="xsd:string"/>
              <xsd:element name="obj-phone" type="xsd:string"/>
              <xsd:element name="db-num" type="xsd:int" nillable="false"/>
              <xsd:element name="shift-date" type="xsd:date" nillable="false"/>
              <xsd:element name="shift-num" type="xsd:int" nillable="false"/>
              <xsd:element name="shift-name" type="xsd:string" nillable="false"/>
              <xsd:element name="report-num" type="xsd:int" nillable="false"/>
              <xsd:element name="current-datetime" type="xsd:dateTime" nillable="false" prodata:dataType="prodata:dateTime"/>
              <xsd:element name="cd-dyn-sal" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="obj-type" type="xsd:string" nillable="false"/>
                    <xsd:element name="obj-code" type="xsd:int" nillable="false"/>
                    <xsd:element name="shift-date" type="xsd:date" nillable="false"/>
                    <xsd:element name="shift-num" type="xsd:int" nillable="false"/>
                    <xsd:element name="cash-num" type="xsd:int" nillable="false"/>
                    <xsd:element name="start-date" type="xsd:date" nillable="false"/>
                    <xsd:element name="start-time" type="xsd:int" nillable="false"/>
                    <xsd:element name="end-date" type="xsd:date" nillable="false"/>
                    <xsd:element name="end-time" type="xsd:int" nillable="false"/>
                    <xsd:element name="report-num" type="xsd:int" nillable="false"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="grp-dyn-sal" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="node-code" type="xsd:int" nillable="false"/>
                    <xsd:element name="full-name" type="xsd:string" nillable="false"/>
                    <xsd:element name="obj-type" type="xsd:string" nillable="false"/>
                    <xsd:element name="obj-code" type="xsd:int" nillable="false"/>
                    <xsd:element name="shift-date" type="xsd:date" nillable="false"/>
                    <xsd:element name="shift-num" type="xsd:int" nillable="false"/>
                    <xsd:element name="fact-qnty" type="xsd:decimal" nillable="false"/>
                    <xsd:element name="fact-sum" type="xsd:decimal" nillable="false"/>
                    <xsd:element name="gds-dyn-sal" minOccurs="0" maxOccurs="unbounded">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="gds-code" type="xsd:int" nillable="false"/>
                          <xsd:element name="node-code" type="xsd:int" nillable="false"/>
                          <xsd:element name="obj-type" type="xsd:string" nillable="false"/>
                          <xsd:element name="obj-code" type="xsd:int" nillable="false"/>
                          <xsd:element name="shift-date" type="xsd:date" nillable="false"/>
                          <xsd:element name="shift-num" type="xsd:int" nillable="false"/>
                          <xsd:element name="unit-base" type="xsd:string" nillable="false"/>
                          <xsd:element name="gds-name" type="xsd:string" nillable="false"/>
                          <xsd:element name="fact-qnty" type="xsd:decimal" nillable="false"/>
                          <xsd:element name="fact-sum" type="xsd:decimal" nillable="false"/>
                          <xsd:element name="is-petrol" type="xsd:boolean" nillable="false"/>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//obj-dyn-sal"/>
      <xsd:field xpath="obj-type"/>
      <xsd:field xpath="obj-code"/>
    </xsd:unique>
    <xsd:unique name="cd-dyn-sal_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//cd-dyn-sal"/>
      <xsd:field xpath="obj-type"/>
      <xsd:field xpath="obj-code"/>
      <xsd:field xpath="shift-date"/>
      <xsd:field xpath="shift-num"/>
      <xsd:field xpath="cash-num"/>
    </xsd:unique>
    <xsd:unique name="grp-dyn-sal_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//grp-dyn-sal"/>
      <xsd:field xpath="obj-type"/>
      <xsd:field xpath="obj-code"/>
      <xsd:field xpath="shift-date"/>
      <xsd:field xpath="shift-num"/>
      <xsd:field xpath="node-code"/>
    </xsd:unique>
    <xsd:unique name="gds-dyn-sal_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//gds-dyn-sal"/>
      <xsd:field xpath="obj-type"/>
      <xsd:field xpath="obj-code"/>
      <xsd:field xpath="shift-date"/>
      <xsd:field xpath="shift-num"/>
      <xsd:field xpath="gds-code"/>
    </xsd:unique>
    <xsd:keyref name="r2" refer="grp-dyn-sal_pi" prodata:nested="true">
      <xsd:selector xpath=".//gds-dyn-sal"/>
      <xsd:field xpath="obj-type"/>
      <xsd:field xpath="obj-code"/>
      <xsd:field xpath="shift-date"/>
      <xsd:field xpath="shift-num"/>
      <xsd:field xpath="node-code"/>
    </xsd:keyref>
    <xsd:unique name="report-header_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//report-header"/>
      <xsd:field xpath="report-id"/>
    </xsd:unique>
    <xsd:unique name="report-parameters_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//report-parameters"/>
      <xsd:field xpath="report-id"/>
      <xsd:field xpath="parameter-name"/>
      <xsd:field xpath="parameter-index"/>
    </xsd:unique>
    <xsd:unique name="report-errors_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//report-errors"/>
      <xsd:field xpath="report-id"/>
      <xsd:field xpath="ErrNum"/>
    </xsd:unique>
    <xsd:unique name="report-destination_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//report-destination"/>
      <xsd:field xpath="report-id"/>
      <xsd:field xpath="destination-id"/>
    </xsd:unique>
    <xsd:keyref name="rh1" refer="report-header_pi" prodata:nested="true">
      <xsd:selector xpath=".//report-parameters"/>
      <xsd:field xpath="report-id"/>
    </xsd:keyref>
    <xsd:keyref name="rh2" refer="report-header_pi" prodata:nested="true">
      <xsd:selector xpath=".//report-errors"/>
      <xsd:field xpath="report-id"/>
    </xsd:keyref>
    <xsd:keyref name="rh3" refer="report-header_pi" prodata:nested="true">
      <xsd:selector xpath=".//report-destination"/>
      <xsd:field xpath="report-id"/>
    </xsd:keyref>
  </xsd:element>
  <xsd:annotation>
    <xsd:appinfo>
      <prodata:index name="igrp">
        <prodata:table name="gds-dyn-sal"/>
        <prodata:field name="obj-type"/>
        <prodata:field name="obj-code"/>
        <prodata:field name="shift-date"/>
        <prodata:field name="shift-num"/>
        <prodata:field name="node-code"/>
      </prodata:index>
      <prodata:relation name="r1" prodata:nested="true" prodata:parent="obj-dyn-sal" prodata:child="grp-dyn-sal" prodata:relationFields="obj-type,obj-type,obj-code,obj-code,shift-date,shift-date,shift-num,shift-num"/>
      <prodata:relation name="r3" prodata:nested="true" prodata:parent="obj-dyn-sal" prodata:child="cd-dyn-sal" prodata:relationFields="obj-type,obj-type,obj-code,obj-code,shift-date,shift-date,shift-num,shift-num"/>
    </xsd:appinfo>
  </xsd:annotation>
</xsd:schema>