<?xml version="1.0" encoding="windows-1251"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"        xmlns=""        xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:element name="Recipe-imp-01" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="recipe" minOccurs="1" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
            <xsd:element name="gds-code"            type="xsd:integer" nillable="false"/>
            <xsd:element name="recipe-code"         type="xsd:string" nillable="false"/>
            <xsd:element name="brutto-qnty"         type="xsd:decimal" nillable="false"/>
            <xsd:element name="host-code"           type="xsd:integer" nillable="false"/>
            <xsd:element name="is-default"          type="xsd:boolean" nillable="false"/>
            <xsd:element name="obj-code"            type="xsd:integer" nillable="false"/>
            <xsd:element name="obj-type"            type="xsd:string" nillable="false"/>
            <xsd:element name="portion-qnty"        type="xsd:integer" nillable="false"/>
            <xsd:element name="portion-weight"      type="xsd:decimal" nillable="false"/>
            <xsd:element name="qnty"                type="xsd:decimal" nillable="false"/>
            <xsd:element name="recipe-design"       type="xsd:string" nillable="false"/>
            <xsd:element name="recipe-name"         type="xsd:string" nillable="false"/>
            <xsd:element name="recipe-quality"      type="xsd:string" nillable="false"/>
            <xsd:element name="recipe-ref-num"      type="xsd:string" nillable="false"/>
            <xsd:element name="recipe-technique"    type="xsd:string" nillable="false"/>
            <xsd:element name="recipe-type"         type="xsd:string" nillable="false"/>
	        <xsd:element name="recipe-gds" minOccurs="0" maxOccurs="unbounded">
	           <xsd:complexType>
	              <xsd:sequence>
                 <xsd:element name="gds-code"    type="xsd:integer" nillable="false"/>
                 <xsd:element name="recipe-code" type="xsd:string" nillable="false"/>
                 <xsd:element name="rcp-gds-code" type="xsd:integer" nillable="false"/>
	              <xsd:element name="brutto-qnty" type="xsd:decimal" nillable="false"/>
	              <xsd:element name="calc-method" type="xsd:integer" nillable="false"/>
	              <xsd:element name="coeff-waste" type="xsd:decimal" nillable="false"/>
	              <xsd:element name="is-waste"    type="xsd:boolean" nillable="false"/>
	              <xsd:element name="proc-number" type="xsd:integer" nillable="false"/>
                 <xsd:element name="qnty"        type="xsd:decimal" nillable="false"/>
	              </xsd:sequence>
	           </xsd:complexType>
	        </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi-recipe" prodata:primaryIndex="true">
      <xsd:selector xpath=".//recipe"/>
      <xsd:field xpath="recipe-code"/>
    </xsd:unique>
    <xsd:unique name="pi-recipe-gds" prodata:primaryIndex="true">
      <xsd:selector xpath=".//recipe-gds"/>
      <xsd:field xpath="recipe-code"/>
      <xsd:field xpath="rcp-gds-code"/>
    </xsd:unique>
    <xsd:keyref name="recipe-code" refer="pi-recipe" prodata:nested="true">
      <xsd:selector xpath=".//recipe-gds"/>
      <xsd:field xpath="recipe-code"/>
    </xsd:keyref>
  </xsd:element>
</xsd:schema>