<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:element name="RETANN_" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="RETANN" minOccurs="0" maxOccurs="unbounded" prodata:tableName="tt-RETANN">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="NUMBER" type="xsd:string" nillable="true"/>
              <xsd:element name="DATE" type="xsd:string" nillable="true"/>
              <xsd:element name="INFO" type="xsd:string" nillable="true"/>
              <xsd:element name="HEAD" minOccurs="0" maxOccurs="unbounded" prodata:tableName="tt-HEAD">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="NUMBER" type="xsd:string" nillable="true"/>
                    <xsd:element name="SUPPLIER" type="xsd:string" nillable="true"/>
                    <xsd:element name="BUYER" type="xsd:string" nillable="true"/>
                    <xsd:element name="DELIVERYPLACE" type="xsd:string" nillable="true"/>
                    <xsd:element name="SENDER" type="xsd:string" nillable="true"/>
                    <xsd:element name="RECIPIENT" type="xsd:string" nillable="true"/>
                    <xsd:element name="POSITION" minOccurs="0" maxOccurs="unbounded" prodata:tableName="tt-POSITION">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="NUMBER" type="xsd:string" nillable="true"/>
                          <xsd:element name="POSITIONNUMBER" type="xsd:int" nillable="true"/>
                          <xsd:element name="PRODUCT" type="xsd:string" nillable="true"/>
                          <xsd:element name="PRODUCTIDSUPPLIER" type="xsd:string" nillable="true"/>
                          <xsd:element name="PRODUCTIDBUYER" type="xsd:string" nillable="true"/>
                          <xsd:element name="RETURNQUANTITY" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="RETURNQUANTITYUNIT" type="xsd:string" nillable="true"/>
                          <xsd:element name="PRICE" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="AMOUNT" type="xsd:decimal" nillable="true"/>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//RETANN"/>
      <xsd:field xpath="NUMBER"/>
    </xsd:unique>
    <xsd:unique name="HEAD_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//HEAD"/>
      <xsd:field xpath="NUMBER"/>
    </xsd:unique>
    <xsd:unique name="POSITION_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//POSITION"/>
      <xsd:field xpath="NUMBER"/>
      <xsd:field xpath="POSITIONNUMBER"/>
    </xsd:unique>
    <xsd:keyref name="r1" refer="pi" prodata:nested="true">
      <xsd:selector xpath=".//HEAD"/>
      <xsd:field xpath="NUMBER"/>
    </xsd:keyref>
    <xsd:keyref name="r2" refer="HEAD_pi" prodata:nested="true">
      <xsd:selector xpath=".//POSITION"/>
      <xsd:field xpath="NUMBER"/>
    </xsd:keyref>
  </xsd:element>
</xsd:schema>
