<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:element name="sale-card-doc-ds" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="sale-card-doc" minOccurs="1" maxOccurs="1">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="obj-type" type="xsd:string" nillable="false"/>
              <xsd:element name="obj-code" type="xsd:int" nillable="false"/>
              <xsd:element name="sale-doc" type="xsd:string" nillable="false"/>
              <xsd:element name="sale-type" type="xsd:string" nillable="false"/>
              <xsd:element name="sale-date" type="xsd:date" nillable="false"/>
              <xsd:element name="action" type="xsd:int" nillable="false"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="sale-card-line" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="sale-doc" type="xsd:string" nillable="false"/>
              <xsd:element name="d-card" type="xsd:string" nillable="false"/>
              <xsd:element name="obj-type" type="xsd:string" nillable="false"/>
              <xsd:element name="obj-code" type="xsd:int" nillable="false"/>
              <xsd:element name="gds-dis-base" type="xsd:decimal" nillable="false"/>
              <xsd:element name="gds-dis-rubl" type="xsd:decimal" nillable="false"/>
              <xsd:element name="gds-tot-base" type="xsd:decimal" nillable="false"/>
              <xsd:element name="gds-tot-rubl" type="xsd:decimal" nillable="false"/>
              <xsd:element name="num-chk" type="xsd:int" nillable="false"/>
              <xsd:element name="pay-tot-base" type="xsd:decimal" nillable="false"/>
              <xsd:element name="pay-tot-rubl" type="xsd:decimal" nillable="false"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//sale-card-doc"/>
      <xsd:field xpath="sale-doc"/>
    </xsd:unique>
    <xsd:unique name="sale-card-line_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//sale-card-line"/>
      <xsd:field xpath="sale-doc"/>
      <xsd:field xpath="d-card"/>
    </xsd:unique>
    <xsd:keyref name="doc-line" refer="pi">
      <xsd:selector xpath=".//sale-card-line"/>
      <xsd:field xpath="sale-doc"/>
    </xsd:keyref>
  </xsd:element>
</xsd:schema>
