<?xml version="1.0" encoding="windows-1251"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:element name="scales-export-01-ds" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="scales-01" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="scales-num" type="xsd:int" nillable="false"/>
              <xsd:element name="scales-type" type="xsd:string" nillable="false"/>
              <xsd:element name="scales-name" type="xsd:string" nillable="false"/>
              <xsd:element name="address" type="xsd:string" nillable="false"/>
              <xsd:element name="unit-base" type="xsd:string" nillable="false"/>
              <xsd:element name="max-gds" type="xsd:int" nillable="false"/>
              <xsd:element name="remote" type="xsd:int" nillable="false"/>
              <xsd:element name="slave-scales-01" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="scales-num" type="xsd:int" nillable="false"/>
                    <xsd:element name="scales-type" type="xsd:string" nillable="false"/>
                    <xsd:element name="scales-name" type="xsd:string" nillable="false"/>
                    <xsd:element name="address" type="xsd:string" nillable="false"/>
                    <xsd:element name="master" type="xsd:int" nillable="false"/>
                    <xsd:element name="unit-base" type="xsd:string" nillable="false"/>
                    <xsd:element name="max-gds" type="xsd:int" nillable="false"/>
                    <xsd:element name="remote" type="xsd:int" nillable="false"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="scales-gds-01" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="scales-num" type="xsd:int" nillable="false"/>
                    <xsd:element name="b-code" type="xsd:int" nillable="false"/>
                    <xsd:element name="deadline" type="xsd:int" nillable="false"/>
                    <xsd:element name="obj-type" type="xsd:string" nillable="false"/>
                    <xsd:element name="obj-code" type="xsd:int" nillable="false"/>
                    <xsd:element name="PLU-code" type="xsd:int" nillable="false"/>
                    <xsd:element name="whole-send-news" type="xsd:int" nillable="false"/>
                    <xsd:element name="wt-cart" type="xsd:decimal" nillable="false"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="scales-grp-01" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="scales-num" type="xsd:int" nillable="false"/>
                    <xsd:element name="node-code" type="xsd:int" nillable="false"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="scales-attr-01" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="scales-num" type="xsd:int" nillable="false"/>
                    <xsd:element name="attr-code" type="xsd:string" nillable="false"/>
                    <xsd:element name="attr-value" type="xsd:string" nillable="false"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//scales-01"/>
      <xsd:field xpath="scales-num"/>
    </xsd:unique>
    <xsd:unique name="slave-scales-01_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//slave-scales-01"/>
      <xsd:field xpath="scales-num"/>
    </xsd:unique>
    <xsd:unique name="scales-gds-01_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//scales-gds-01"/>
      <xsd:field xpath="scales-num"/>
      <xsd:field xpath="PLU-code"/>
    </xsd:unique>
    <xsd:unique name="scales-grp-01_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//scales-grp-01"/>
      <xsd:field xpath="scales-num"/>
      <xsd:field xpath="node-code"/>
    </xsd:unique>
    <xsd:unique name="scales-attr-01_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//scales-attr-01"/>
      <xsd:field xpath="scales-num"/>
      <xsd:field xpath="attr-code"/>
    </xsd:unique>
    <xsd:keyref name="scales-num1" refer="pi" prodata:nested="true">
      <xsd:selector xpath=".//slave-scales-01"/>
      <xsd:field xpath="master"/>
    </xsd:keyref>
    <xsd:keyref name="scales-num2" refer="pi" prodata:nested="true">
      <xsd:selector xpath=".//scales-gds-01"/>
      <xsd:field xpath="scales-num"/>
    </xsd:keyref>
    <xsd:keyref name="scales-num3" refer="pi" prodata:nested="true">
      <xsd:selector xpath=".//scales-grp-01"/>
      <xsd:field xpath="scales-num"/>
    </xsd:keyref>
    <xsd:keyref name="scales-num4" refer="pi" prodata:nested="true">
      <xsd:selector xpath=".//scales-attr-01"/>
      <xsd:field xpath="scales-num"/>
    </xsd:keyref>
  </xsd:element>
</xsd:schema>
