<?xml version="1.0" encoding="windows-1251"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:include schemaLocation="reporttypes.xsd"/>
  <xsd:element name="shift-1" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="report-header" type="reportheaderType"/>
        <xsd:element name="shift" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="obj-type" type="xsd:string" nillable="false"/>
              <xsd:element name="obj-code" type="xsd:int" nillable="false"/>
              <xsd:element name="obj-name" type="xsd:string" nillable="false"/>
              <xsd:element name="obj-address" type="xsd:string"/>
              <xsd:element name="obj-phone" type="xsd:string"/>
              <xsd:element name="db-num" type="xsd:int" nillable="false"/>
              <xsd:element name="shift-date" type="xsd:date" nillable="false"/>
              <xsd:element name="shift-num" type="xsd:int" nillable="false"/>
              <xsd:element name="shift-name" type="xsd:string" nillable="false"/>
              <xsd:element name="base-code" type="xsd:int" nillable="false"/>
              <xsd:element name="curr-abbr" type="xsd:string" nillable="false"/>
              <xsd:element name="shift-pgds" minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                  <xsd:documentation>Структура для ТОПЛИВ - общие данные на начало и конец смены, и смену в целом см постфиксом 2 - это килограммы, остальные кол-ва - литры
                  суффикс state означает ФАКТИЧЕСКОЕ кол-во
                  суффикс system - РАСЧЕТНО-КНИЖНОЕ</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="obj-type" type="xsd:string" nillable="false"/>
                    <xsd:element name="obj-code" type="xsd:int" nillable="false"/>
                    <xsd:element name="shift-date" type="xsd:date" nillable="false"/>
                    <xsd:element name="shift-num" type="xsd:int" nillable="false"/>
                    <xsd:element name="gds-code" type="xsd:int" nillable="false"/>
                    <xsd:element name="gds-name" type="xsd:string" nillable="false"/>
                    <xsd:element name="start-state-qnty" type="xsd:decimal" nillable="false"/>
                    <xsd:element name="start-system-qnty" type="xsd:decimal" nillable="false"/>
                    <xsd:element name="start-state-qnty-2" type="xsd:decimal" nillable="false"/>
                    <xsd:element name="start-system-qnty-2" type="xsd:decimal" nillable="false"/>
                    <xsd:element name="end-state-qnty" type="xsd:decimal" nillable="false"/>
                    <xsd:element name="end-system-qnty" type="xsd:decimal" nillable="false"/>
                    <xsd:element name="end-state-qnty-2" type="xsd:decimal" nillable="false"/>
                    <xsd:element name="end-system-qnty-2" type="xsd:decimal" nillable="false"/>
                    <xsd:element name="in-qnty" type="xsd:decimal" nillable="false"/>
                    <xsd:element name="in-qnty-2" type="xsd:decimal" nillable="false"/>
                    <xsd:element name="icnt-out-qnty" type="xsd:decimal" nillable="false">
                      <xsd:annotation>
                        <xsd:documentation>расход по счетчикам</xsd:documentation>
                      </xsd:annotation>
                    </xsd:element>
                    <xsd:element name="end-price-sale" type="xsd:decimal" nillable="true"/>
                    <xsd:element name="shift-pgds-out" minOccurs="0" maxOccurs="unbounded">
                      <xsd:annotation>
                        <xsd:documentation>Структура для ТОПЛИВ - расходы</xsd:documentation>
                      </xsd:annotation>
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="obj-type" type="xsd:string" nillable="false"/>
                          <xsd:element name="obj-code" type="xsd:int" nillable="false"/>
                          <xsd:element name="shift-date" type="xsd:date" nillable="false"/>
                          <xsd:element name="shift-num" type="xsd:int" nillable="false"/>
                          <xsd:element name="gds-code" type="xsd:int" nillable="false"/>
                          <xsd:element name="pay-code" type="xsd:int" nillable="false">
                            <xsd:annotation>
                              <xsd:documentation>код типа кассового платежа или иной спец код для расхода</xsd:documentation>
                            </xsd:annotation>
                          </xsd:element>
                          <xsd:element name="curr-code" type="xsd:int" nillable="false"/>
                          <xsd:element name="cp-type" type="xsd:int" nillable="false"/>
                          <xsd:element name="out-name" type="xsd:string" nillable="false">
                            <xsd:annotation>
                              <xsd:documentation>название типа касс платежа или типа расхода</xsd:documentation>
                            </xsd:annotation>
                          </xsd:element>
                          <xsd:element name="fact-qnty" type="xsd:decimal" nillable="false"/>
                          <xsd:element name="fact-qnty-2" type="xsd:decimal" nillable="false"/>
                          <xsd:element name="fact-sum" type="xsd:decimal" nillable="false"/>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="shift-pgds-in" minOccurs="0" maxOccurs="unbounded">
                      <xsd:annotation>
                        <xsd:documentation>Структура для ТОПЛИВ - приходы</xsd:documentation>
                      </xsd:annotation>
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="obj-type" type="xsd:string" nillable="false"/>
                          <xsd:element name="obj-code" type="xsd:int" nillable="false"/>
                          <xsd:element name="shift-date" type="xsd:date" nillable="false"/>
                          <xsd:element name="shift-num" type="xsd:int" nillable="false"/>
                          <xsd:element name="gds-code" type="xsd:int" nillable="false"/>
                          <xsd:element name="doc-code" type="xsd:string" nillable="false"/>
                          <xsd:element name="cli-type-code" type="xsd:string" nillable="false"/>
                          <xsd:element name="cli-name" type="xsd:string" nillable="false"/>
                          <xsd:element name="fact-qnty" type="xsd:decimal" nillable="false"/>
                          <xsd:element name="fact-qnty-2" type="xsd:decimal" nillable="false"/>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="shift-grp" minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                  <xsd:documentation>Структура для ГРУПП СТ - общие данные на начало и конец смены</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="obj-type" type="xsd:string" nillable="false"/>
                    <xsd:element name="obj-code" type="xsd:int" nillable="false"/>
                    <xsd:element name="shift-date" type="xsd:date" nillable="false"/>
                    <xsd:element name="shift-num" type="xsd:int" nillable="false"/>
                    <xsd:element name="grp-code" type="xsd:int" nillable="false"/>
                    <xsd:element name="full-grp-name" type="xsd:string" nillable="false"/>
                    <xsd:element name="start-qnty" type="xsd:decimal" nillable="false"/>
                    <xsd:element name="start-sum" type="xsd:decimal" nillable="false"/>
                    <xsd:element name="end-qnty" type="xsd:decimal" nillable="false"/>
                    <xsd:element name="end-sum" type="xsd:decimal" nillable="false"/>
                    <xsd:element name="shift-grp-out" minOccurs="0" maxOccurs="unbounded">
                      <xsd:annotation>
                        <xsd:documentation>Структура для ГРУПП СТ - расходы</xsd:documentation>
                      </xsd:annotation>
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="obj-type" type="xsd:string" nillable="false"/>
                          <xsd:element name="obj-code" type="xsd:int" nillable="false"/>
                          <xsd:element name="shift-date" type="xsd:date" nillable="false"/>
                          <xsd:element name="shift-num" type="xsd:int" nillable="false"/>
                          <xsd:element name="grp-code" type="xsd:int" nillable="false"/>
                          <xsd:element name="pay-code" type="xsd:int" nillable="false">
                            <xsd:annotation>
                              <xsd:documentation>код типа кассового платежа или иной спец код для расхода</xsd:documentation>
                            </xsd:annotation>
                          </xsd:element>
                          <xsd:element name="curr-code" type="xsd:int" nillable="false"/>
                          <xsd:element name="cp-type" type="xsd:int" nillable="false"/>
                          <xsd:element name="out-name" type="xsd:string" nillable="false">
                            <xsd:annotation>
                              <xsd:documentation>название типа касс платежа или типа расхода</xsd:documentation>
                            </xsd:annotation>
                          </xsd:element>
                          <xsd:element name="fact-qnty" type="xsd:decimal" nillable="false"/>
                          <xsd:element name="fact-sum" type="xsd:decimal" nillable="false"/>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="shift-grp-in" minOccurs="0" maxOccurs="unbounded">
                      <xsd:annotation>
                        <xsd:documentation>Структура для ГРУПП СТ - приходы</xsd:documentation>
                      </xsd:annotation>
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="obj-type" type="xsd:string" nillable="false"/>
                          <xsd:element name="obj-code" type="xsd:int" nillable="false"/>
                          <xsd:element name="shift-date" type="xsd:date" nillable="false"/>
                          <xsd:element name="shift-num" type="xsd:int" nillable="false"/>
                          <xsd:element name="grp-code" type="xsd:int" nillable="false"/>
                          <xsd:element name="doc-code" type="xsd:string" nillable="false"/>
                          <xsd:element name="cli-type-code" type="xsd:string" nillable="false"/>
                          <xsd:element name="cli-name" type="xsd:string" nillable="false"/>
                          <xsd:element name="fact-qnty" type="xsd:decimal" nillable="false"/>
                          <xsd:element name="fact-cost-sum" type="xsd:decimal" nillable="false">
                            <xsd:annotation>
                              <xsd:documentation>ЦЕНА УЧЕТНАЯ</xsd:documentation>
                            </xsd:annotation>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//shift"/>
      <xsd:field xpath="obj-type"/>
      <xsd:field xpath="obj-code"/>
      <xsd:field xpath="shift-date"/>
      <xsd:field xpath="shift-num"/>
    </xsd:unique>
    <xsd:unique name="shift-pgds_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//shift-pgds"/>
      <xsd:field xpath="obj-type"/>
      <xsd:field xpath="obj-code"/>
      <xsd:field xpath="shift-date"/>
      <xsd:field xpath="shift-num"/>
      <xsd:field xpath="gds-code"/>
    </xsd:unique>
    <xsd:unique name="shift-pgds-in_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//shift-pgds-in"/>
      <xsd:field xpath="obj-type"/>
      <xsd:field xpath="obj-code"/>
      <xsd:field xpath="shift-date"/>
      <xsd:field xpath="shift-num"/>
      <xsd:field xpath="gds-code"/>
      <xsd:field xpath="doc-code"/>
    </xsd:unique>
    <xsd:unique name="shift-pgds-out_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//shift-pgds-out"/>
      <xsd:field xpath="obj-type"/>
      <xsd:field xpath="obj-code"/>
      <xsd:field xpath="shift-date"/>
      <xsd:field xpath="shift-num"/>
      <xsd:field xpath="gds-code"/>
      <xsd:field xpath="pay-code"/>
      <xsd:field xpath="curr-code"/>
    </xsd:unique>
    <xsd:unique name="shift-grp_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//shift-grp"/>
      <xsd:field xpath="obj-type"/>
      <xsd:field xpath="obj-code"/>
      <xsd:field xpath="shift-date"/>
      <xsd:field xpath="shift-num"/>
      <xsd:field xpath="grp-code"/>
    </xsd:unique>
    <xsd:unique name="shift-grp-in_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//shift-grp-in"/>
      <xsd:field xpath="obj-type"/>
      <xsd:field xpath="obj-code"/>
      <xsd:field xpath="shift-date"/>
      <xsd:field xpath="shift-num"/>
      <xsd:field xpath="grp-code"/>
      <xsd:field xpath="doc-code"/>
    </xsd:unique>
    <xsd:unique name="shift-grp-out_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//shift-grp-out"/>
      <xsd:field xpath="obj-type"/>
      <xsd:field xpath="obj-code"/>
      <xsd:field xpath="shift-date"/>
      <xsd:field xpath="shift-num"/>
      <xsd:field xpath="grp-code"/>
      <xsd:field xpath="pay-code"/>
      <xsd:field xpath="curr-code"/>
    </xsd:unique>
    <xsd:keyref name="r1" refer="pi" prodata:nested="true">
      <xsd:selector xpath=".//shift-pgds"/>
      <xsd:field xpath="obj-type"/>
      <xsd:field xpath="obj-code"/>
      <xsd:field xpath="shift-date"/>
      <xsd:field xpath="shift-num"/>
    </xsd:keyref>
    <xsd:keyref name="r2" refer="pi" prodata:nested="true">
      <xsd:selector xpath=".//shift-grp"/>
      <xsd:field xpath="obj-type"/>
      <xsd:field xpath="obj-code"/>
      <xsd:field xpath="shift-date"/>
      <xsd:field xpath="shift-num"/>
    </xsd:keyref>
    <xsd:keyref name="r11" refer="shift-pgds_pi" prodata:nested="true">
      <xsd:selector xpath=".//shift-pgds-out"/>
      <xsd:field xpath="obj-type"/>
      <xsd:field xpath="obj-code"/>
      <xsd:field xpath="shift-date"/>
      <xsd:field xpath="shift-num"/>
      <xsd:field xpath="gds-code"/>
    </xsd:keyref>
    <xsd:keyref name="r12" refer="shift-pgds_pi" prodata:nested="true">
      <xsd:selector xpath=".//shift-pgds-in"/>
      <xsd:field xpath="obj-type"/>
      <xsd:field xpath="obj-code"/>
      <xsd:field xpath="shift-date"/>
      <xsd:field xpath="shift-num"/>
      <xsd:field xpath="gds-code"/>
    </xsd:keyref>
    <xsd:keyref name="r21" refer="shift-grp_pi" prodata:nested="true">
      <xsd:selector xpath=".//shift-grp-out"/>
      <xsd:field xpath="obj-type"/>
      <xsd:field xpath="obj-code"/>
      <xsd:field xpath="shift-date"/>
      <xsd:field xpath="shift-num"/>
      <xsd:field xpath="grp-code"/>
    </xsd:keyref>
    <xsd:keyref name="r22" refer="shift-grp_pi" prodata:nested="true">
      <xsd:selector xpath=".//shift-grp-in"/>
      <xsd:field xpath="obj-type"/>
      <xsd:field xpath="obj-code"/>
      <xsd:field xpath="shift-date"/>
      <xsd:field xpath="shift-num"/>
      <xsd:field xpath="grp-code"/>
    </xsd:keyref>
    <xsd:unique name="report-header_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//report-header"/>
      <xsd:field xpath="report-id"/>
    </xsd:unique>
    <xsd:unique name="report-parameters_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//report-parameters"/>
      <xsd:field xpath="report-id"/>
      <xsd:field xpath="parameter-name"/>
      <xsd:field xpath="parameter-index"/>
    </xsd:unique>
    <xsd:unique name="report-errors_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//report-errors"/>
      <xsd:field xpath="report-id"/>
      <xsd:field xpath="ErrNum"/>
    </xsd:unique>
    <xsd:unique name="report-destination_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//report-destination"/>
      <xsd:field xpath="report-id"/>
      <xsd:field xpath="destination-id"/>
    </xsd:unique>
    <xsd:keyref name="rh1" refer="report-header_pi" prodata:nested="true">
      <xsd:selector xpath=".//report-parameters"/>
      <xsd:field xpath="report-id"/>
    </xsd:keyref>
    <xsd:keyref name="rh2" refer="report-header_pi" prodata:nested="true">
      <xsd:selector xpath=".//report-errors"/>
      <xsd:field xpath="report-id"/>
    </xsd:keyref>
    <xsd:keyref name="rh3" refer="report-header_pi" prodata:nested="true">
      <xsd:selector xpath=".//report-destination"/>
      <xsd:field xpath="report-id"/>
    </xsd:keyref>
  </xsd:element>
</xsd:schema>