<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xs:include schemaLocation="exitetypes_0-01.xsd"/>
  <xs:element name="Status__">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Status_">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="EXiteICID" type="edi-interchange-id"/>
              <xs:element name="CustomerICID" type="numbertype"/>
              <xs:element name="From_" type="mailbox"/>
              <xs:element name="To_" type="mailbox"/>
              <xs:element name="Status_" type="statustype"/>
              <xs:element name="DateIn" type="xs:date"/>
              <xs:element name="TimeIn" type="timetype"/>
              <xs:element name="DateOut" type="xs:date" minOccurs="0"/>
              <xs:element name="TimeOut" type="timetype" minOccurs="0"/>
              <xs:element name="SizeInBytes" type="xs:int" minOccurs="0"/>
              <xs:element name="MessageClass" type="doctype"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    <xs:unique name="pi">
      <xs:selector xpath=".//Status_"/>
      <xs:field xpath="EXiteICID"/>
    </xs:unique>
  </xs:element>
</xs:schema>