<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:element name="temp-d-card-ds" prodata:proDataSet="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="temp-d-card" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="card-num" type="xsd:int" nillable="true"/>
              <xsd:element name="d-card" type="xsd:string" nillable="true"/>
              <xsd:element name="dt-code" type="xsd:int" nillable="true"/>
              <xsd:element name="first-card" type="xsd:string" nillable="true"/>
              <xsd:element name="first-main-card" type="xsd:string" nillable="true"/>
              <xsd:element name="gds-dis-base" type="xsd:decimal" nillable="true"/>
              <xsd:element name="gds-dis-rubl" type="xsd:decimal" nillable="true"/>
              <xsd:element name="gds-tot-b0" type="xsd:decimal" nillable="true"/>
              <xsd:element name="gds-tot-base" type="xsd:decimal" nillable="true"/>
              <xsd:element name="gds-tot-r0" type="xsd:decimal" nillable="true"/>
              <xsd:element name="gds-tot-rubl" type="xsd:decimal" nillable="true"/>
              <xsd:element name="host-code" type="xsd:int" nillable="true"/>
              <xsd:element name="main-card" type="xsd:string" nillable="true"/>
              <xsd:element name="num-chk" type="xsd:int" nillable="true"/>
              <xsd:element name="obj-code" type="xsd:int" nillable="true"/>
              <xsd:element name="obj-type" type="xsd:string" nillable="true"/>
              <xsd:element name="pay-tot-base" type="xsd:decimal" nillable="true"/>
              <xsd:element name="pay-tot-rubl" type="xsd:decimal" nillable="true"/>
              <xsd:element name="sum-dis-base" type="xsd:decimal" nillable="true"/>
              <xsd:element name="sum-dis-rubl" type="xsd:decimal" nillable="true"/>
              <xsd:element name="sum-tot-base" type="xsd:decimal" nillable="true"/>
              <xsd:element name="sum-tot-rubl" type="xsd:decimal" nillable="true"/>
              <xsd:element name="sum-tot-r-b" type="xsd:decimal" nillable="true"/>
              <xsd:element name="gds-tot-r-b" type="xsd:decimal" nillable="true"/>
              <xsd:element name="gds-dis-r-b" type="xsd:decimal" nillable="true"/>
              <xsd:element name="cli-type" type="xsd:string" nillable="true"/>
              <xsd:element name="cli-code" type="xsd:int" nillable="true"/>
              <xsd:element name="emitent-host-code" type="xsd:int" nillable="true"/>
              <xsd:element name="type" type="xsd:string" nillable="true"/>
              <xsd:element name="exp-imp" type="xsd:boolean" nillable="true"/>
              <xsd:element name="sale-doc" type="xsd:string" nillable="true"/>
              <xsd:element name="sale-type" type="xsd:string" nillable="true"/>
              <xsd:element name="doc-date" type="xsd:date" nillable="true"/>
              <xsd:element name="base-code" type="xsd:int" nillable="true"/>
              <xsd:element name="smart-nws-log" type="xsd:boolean" nillable="true" prodata:initial="prodata:unknown"/>
              <xsd:element name="action" type="xsd:int" nillable="true"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="vchk-pay" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="d-card" type="xsd:string" nillable="true" prodata:format="X(19)"/>
              <xsd:element name="PAY-code" type="xsd:int" nillable="true" prodata:format="99999"/>
              <xsd:element name="curr-code" type="xsd:int" nillable="true" prodata:format="999"/>
              <xsd:element name="doc-date" type="xsd:date" nillable="true"/>
              <xsd:element name="cre-pay" type="xsd:boolean" nillable="true"/>
              <xsd:element name="exch-rate" type="xsd:decimal" nillable="true"/>
              <xsd:element name="base-rate" type="xsd:decimal" nillable="true"/>
              <xsd:element name="tot-sum" type="xsd:decimal" nillable="true" prodata:format="-999,999,999.99"/>
              <xsd:element name="tot-base" type="xsd:decimal" nillable="true" prodata:format="-999,999,999.99"/>
              <xsd:element name="tot-rubl" type="xsd:decimal" nillable="true" prodata:format="-999,999,999.99"/>
              <xsd:element name="pmnt-code" type="xsd:string" nillable="true"/>
              <xsd:element name="obj-type" type="xsd:string" nillable="true"/>
              <xsd:element name="obj-code" type="xsd:int" nillable="true"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//temp-d-card"/>
      <xsd:field xpath="d-card"/>
      <xsd:field xpath="obj-type"/>
      <xsd:field xpath="obj-code"/>
    </xsd:unique>
    <xsd:unique name="PI" prodata:primaryIndex="true">
      <xsd:selector xpath=".//vchk-pay"/>
      <xsd:field xpath="d-card"/>
      <xsd:field xpath="PAY-code"/>
      <xsd:field xpath="curr-code"/>
      <xsd:field xpath="doc-date"/>
      <xsd:field xpath="cre-pay"/>
      <xsd:field xpath="exch-rate"/>
      <xsd:field xpath="base-rate"/>
    </xsd:unique>
  </xsd:element>
  <xsd:annotation>
    <xsd:appinfo>
      <prodata:index name="iobj">
        <prodata:table name="temp-d-card"/>
        <prodata:field name="obj-type"/>
        <prodata:field name="obj-code"/>
      </prodata:index>
      <prodata:index name="itype">
        <prodata:table name="temp-d-card"/>
        <prodata:field name="type"/>
        <prodata:field name="emitent-host-code"/>
      </prodata:index>
    </xsd:appinfo>
  </xsd:annotation>
</xsd:schema>