<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:element name="THheader" prodata:proTempTable="true">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="THheaderRow" minOccurs="1" maxOccurs="1">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="THfilename" type="xsd:string" nillable="false"/>
              <xsd:element name="THfilenumber" type="xsd:int" nillable="false"/>
              <xsd:element name="THformat_" type="xsd:string" nillable="false"/>
              <xsd:element name="THversion_" type="xsd:string" nillable="false"/>
              <xsd:element name="THrevision" type="xsd:string" nillable="false"/>
              <xsd:element name="THesysname" type="xsd:string" nillable="false"/>
              <xsd:element name="THcurrentDbNum" type="xsd:int" nillable="false"/>
              <xsd:element name="THpack-num" type="xsd:int" nillable="false"/>
              <xsd:element name="THschema-name" type="xsd:string" nillable="false"/>
              <xsd:element name="THexport-esys-id" type="xsd:int" nillable="false"/>
              <xsd:element name="THimport-esys-id" type="xsd:int" nillable="false"/>
              <xsd:element name="THtotal-recs" type="xsd:int" nillable="false"/>
              <xsd:element name="THprev-crc" type="xsd:string" nillable="false"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//THheaderRow"/>
      <xsd:field xpath="THfilename"/>
      <xsd:field xpath="THfilenumber"/>
    </xsd:unique>
  </xsd:element>
</xsd:schema>
