<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="" xmlns:prodata="urn:schemas-progress-com:xml-prodata:0001">
  <xsd:element name="waybill-01" prodata:proDataSet="true" prodata:datasetName="waybill-01">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="operation" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="referenceNo" type="xsd:string" nillable="true"/>
              <xsd:element name="isDel" type="xsd:boolean" nillable="true"/>
              <xsd:element name="codeOperation" type="xsd:string" nillable="true"/>
              <xsd:element name="host" type="xsd:int" nillable="true"/>
              <xsd:element name="store" type="xsd:string" nillable="true"/>
              <xsd:element name="factOrder" type="xsd:decimal" nillable="true"/>
              <xsd:element name="sysDateXml" type="xsd:date" nillable="true"/>
              <xsd:element name="sysTime" type="xsd:string" nillable="true"/>
              <xsd:element name="dateDelXml" type="xsd:date" nillable="true"/>
              <xsd:element name="dateDocXml" type="xsd:date" nillable="true"/>
              <xsd:element name="dateFactXml" type="xsd:date" nillable="true"/>
              <xsd:element name="timeFact" type="xsd:string" nillable="true"/>
              <xsd:element name="valutCode" type="xsd:int" nillable="true"/>
              <xsd:element name="valutCodeOKV" type="xsd:int" nillable="true"/>
              <xsd:element name="exchCode" type="xsd:int" nillable="true"/>
              <xsd:element name="exchRate" type="xsd:decimal" nillable="true"/>
              <xsd:element name="exchScale" type="xsd:int" nillable="true"/>
              <xsd:element name="firm" type="xsd:string" nillable="true"/>
              <xsd:element name="extNumber" type="xsd:string" nillable="true"/>
              <xsd:element name="OutNumber" type="xsd:string" nillable="true"/>
              <xsd:element name="outDateXml" type="xsd:date" nillable="true"/>
              <xsd:element name="paymentCode" type="xsd:int" nillable="true"/>
              <xsd:element name="InterFirmDocChild" type="xsd:string" nillable="true"/>
              <xsd:element name="InterFirmDocParent" type="xsd:string" nillable="true"/>
              <xsd:element name="InterFirmObjType" type="xsd:string" nillable="true"/>
              <xsd:element name="InterFirmObjCode" type="xsd:int" nillable="true"/>
              <xsd:element name="authority" type="xsd:string" nillable="true"/>
              <xsd:element name="suppInDocDateXml" type="xsd:date" nillable="true"/>
              <xsd:element name="suppInDocNo" type="xsd:string" nillable="true"/>
              <xsd:element name="contractSuppCode" type="xsd:string" nillable="true"/>
              <xsd:element name="contractSuppNo" type="xsd:string" nillable="true"/>
              <xsd:element name="contractSuppDateXml" type="xsd:date" nillable="true"/>
              <xsd:element name="contractDateXml" type="xsd:date" nillable="true"/>
              <xsd:element name="contractNo" type="xsd:string" nillable="true"/>
              <xsd:element name="sfNo" type="xsd:string" nillable="true"/>
              <xsd:element name="sfDateXml" type="xsd:date" nillable="true"/>
              <xsd:element name="doverNo" type="xsd:string" nillable="true"/>
              <xsd:element name="doverDateXml" type="xsd:date" nillable="true"/>
              <xsd:element name="reasonCode" type="xsd:int" nillable="true"/>
              <xsd:element name="outCode" type="xsd:string" nillable="true"/>
              <xsd:element name="comment" type="xsd:string" nillable="true"/>
              <xsd:element name="ordDocCode" type="xsd:string" nillable="true"/>
              <xsd:element name="ordOutDocCode" type="xsd:string" nillable="true"/>
              <xsd:element name="shiftDateXml" type="xsd:date" nillable="true"/>
              <xsd:element name="shiftNum" type="xsd:int" nillable="true"/>
              <xsd:element name="shiftName" type="xsd:string" nillable="true"/>
              <xsd:element name="dCard" type="xsd:string" nillable="true"/>
              <xsd:element name="techfuel" type="xsd:boolean" nillable="true"/>
              <xsd:element name="office" type="xsd:boolean" nillable="true"/>
              <xsd:element name="docQnty" type="xsd:decimal" nillable="true" prodata:columnLabel="Кол-во по док-ту"/>
              <xsd:element name="factQnty" type="xsd:decimal" nillable="true" prodata:columnLabel="Кол-во факт."/>
              <xsd:element name="cliQnty" type="xsd:decimal" nillable="true" prodata:columnLabel="Кол-во в ед пост - соттвет doc-qnty."/>
              <xsd:element name="totalSum" type="xsd:decimal" nillable="true" prodata:columnLabel="Сумма по док-ту"/>
              <xsd:element name="totalDsc" type="xsd:decimal" nillable="true" prodata:columnLabel="Скидка по док-ту"/>
              <xsd:element name="totalFact" type="xsd:decimal" nillable="true" prodata:columnLabel="Сумма факт"/>
              <xsd:element name="totalDscFact" type="xsd:decimal" nillable="true" prodata:columnLabel="Скидка факт"/>
              <xsd:element name="totalPayFact" type="xsd:decimal" nillable="true" prodata:columnLabel="К оплате факт"/>
              <xsd:element name="baserate" type="xsd:decimal" nillable="true" prodata:columnLabel="Курс баз.вал"/>
              <xsd:element name="vatType" type="xsd:string" nillable="true"/>
              <xsd:element name="beforeSum" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="referenceNo" type="xsd:string" nillable="true"/>
                    <xsd:element name="qnty" type="xsd:decimal" nillable="true"/>
                    <xsd:element name="saleSumBeforeSum" minOccurs="0" maxOccurs="unbounded" prodata:undo="true">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="referenceNo" type="xsd:string" nillable="true"/>
                          <xsd:element name="sumr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="VATr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="roadTaxr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="transportr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="otherr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="exciser" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="sumb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="VATb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="roadTaxb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="transportb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="otherb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="exciseb" type="xsd:decimal" nillable="true"/>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="costSumBeforeSum" minOccurs="0" maxOccurs="unbounded" prodata:undo="true">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="referenceNo" type="xsd:string" nillable="true"/>
                          <xsd:element name="sumr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="VATr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="roadTaxr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="transportr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="otherr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="exciser" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="sumb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="VATb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="roadTaxb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="transportb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="otherb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="exciseb" type="xsd:decimal" nillable="true"/>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="afterSum" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="referenceNo" type="xsd:string" nillable="true"/>
                    <xsd:element name="qnty" type="xsd:decimal" nillable="true"/>
                    <xsd:element name="saleSumAfterSum" minOccurs="0" maxOccurs="unbounded" prodata:undo="true">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="referenceNo" type="xsd:string" nillable="true"/>
                          <xsd:element name="sumr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="VATr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="roadTaxr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="transportr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="otherr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="exciser" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="sumb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="VATb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="roadTaxb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="transportb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="otherb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="exciseb" type="xsd:decimal" nillable="true"/>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="costSumAfterSum" minOccurs="0" maxOccurs="unbounded" prodata:undo="true">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="referenceNo" type="xsd:string" nillable="true"/>
                          <xsd:element name="sumr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="VATr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="roadTaxr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="transportr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="otherr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="exciser" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="sumb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="VATb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="roadTaxb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="transportb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="otherb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="exciseb" type="xsd:decimal" nillable="true"/>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="linedoc" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="referenceNo" type="xsd:string" nillable="true"/>
                    <xsd:element name="good" type="xsd:int" nillable="true"/>
                    <xsd:element name="artic" type="xsd:string" nillable="true"/>
                    <xsd:element name="prodType" type="xsd:string" nillable="true"/>
                    <xsd:element name="prodCode" type="xsd:int" nillable="true"/>
                    <xsd:element name="type" type="xsd:string" nillable="true"/>
                    <xsd:element name="unitType" type="xsd:string" nillable="true"/>
                    <xsd:element name="wait" type="xsd:decimal" nillable="true"/>
                    <xsd:element name="place" type="xsd:decimal" nillable="true"/>
                    <xsd:element name="priceCli" type="xsd:decimal" nillable="true"/>
                    <xsd:element name="cliBaseRate" type="xsd:decimal" nillable="true"/>
                    <xsd:element name="quantity" type="xsd:decimal" nillable="true"/>
                    <xsd:element name="vatPC" type="xsd:decimal" nillable="true"/>
                    <xsd:element name="petrolWeight" type="xsd:decimal" nillable="true"/>
                    <xsd:element name="petrolDensity" type="xsd:decimal" nillable="true"/>
                    <xsd:element name="petrolInvFactStk" type="xsd:decimal" nillable="true"/>
                    <xsd:element name="petrolBeforeQnty" type="xsd:decimal" nillable="true"/>
                    <xsd:element name="petrolAfterQnty" type="xsd:decimal" nillable="true"/>
                    <xsd:element name="petrolDiffQnty" type="xsd:decimal" nillable="true"/>
                    <xsd:element name="petrolAbsDiffQnty" type="xsd:decimal" nillable="true"/>
                    <xsd:element name="CSTCode" type="xsd:string" nillable="true"/>
                    <xsd:element name="cashParts" type="xsd:boolean" nillable="true"/>
                    <xsd:element name="dtl" minOccurs="0" maxOccurs="unbounded">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="referenceNo" type="xsd:string" nillable="true"/>
                          <xsd:element name="good" type="xsd:int" nillable="true"/>
                          <xsd:element name="prtCode" type="xsd:int" nillable="true"/>
                          <xsd:element name="dtlName" type="xsd:string" nillable="true"/>
                          <xsd:element name="qnty" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="sumr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="VATr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="roadTaxr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="sumb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="VATb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="roadTaxb" type="xsd:decimal" nillable="true"/>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="part" minOccurs="0" maxOccurs="unbounded">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="referenceNo" type="xsd:string" nillable="true"/>
                          <xsd:element name="good" type="xsd:int" nillable="true"/>
                          <xsd:element name="doc_ID" type="xsd:string" nillable="true"/>
                          <xsd:element name="partCode" type="xsd:string" nillable="true"/>
                          <xsd:element name="qnty" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="cst" type="xsd:string" nillable="true"/>
                          <xsd:element name="supp" type="xsd:string" nillable="true"/>
                          <xsd:element name="hostCode" type="xsd:int" nillable="true"/>
                          <xsd:element name="contractCode" type="xsd:string" nillable="true"/>
                          <xsd:element name="sumr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="VATr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="roadTaxr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="transportr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="otherr" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="exciser" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="sumb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="VATb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="roadTaxb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="transportb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="otherb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="exciseb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="contractSuppCode" type="xsd:string" nillable="true"/>
                          <xsd:element name="contractSuppNo" type="xsd:string" nillable="true"/>
                          <xsd:element name="contractSuppDateXml" type="xsd:date" nillable="true"/>
                          <xsd:element name="countryCode" type="xsd:string" nillable="true"/>
                          <xsd:element name="priceCli" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="cliBaseRate" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="vatType" type="xsd:string" nillable="true"/>
                          <xsd:element name="exchCode" type="xsd:int" nillable="true"/>
                          <xsd:element name="attrExchRate" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="attrExchScale" type="xsd:int" nillable="true"/>
                          <xsd:element name="attrUnitCli" type="xsd:string" nillable="true"/>
                          <xsd:element name="lastDate" type="xsd:date" nillable="true"/>
                          <xsd:element name="priceb" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="pricer" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="prodPrice" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="fib" type="xsd:int" nillable="true"/>
                          <xsd:element name="salePrice" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="purch-code" type="xsd:int" nillable="true"/>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="beforeSumLine" minOccurs="0" maxOccurs="unbounded">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="referenceNo" type="xsd:string" nillable="true"/>
                          <xsd:element name="good" type="xsd:int" nillable="true"/>
                          <xsd:element name="qnty" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="petrolweight" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="saleSumBeforeSumLine" minOccurs="0" maxOccurs="unbounded" prodata:undo="true">
                            <xsd:complexType>
                              <xsd:sequence>
                                <xsd:element name="referenceNo" type="xsd:string" nillable="true"/>
                                <xsd:element name="good" type="xsd:int" nillable="true"/>
                                <xsd:element name="sumr" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="VATr" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="roadTaxr" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="transportr" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="otherr" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="exciser" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="sumb" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="VATb" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="roadTaxb" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="transportb" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="otherb" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="exciseb" type="xsd:decimal" nillable="true"/>
                              </xsd:sequence>
                            </xsd:complexType>
                          </xsd:element>
                          <xsd:element name="costSumBeforeSumLine" minOccurs="0" maxOccurs="unbounded" prodata:undo="true">
                            <xsd:complexType>
                              <xsd:sequence>
                                <xsd:element name="referenceNo" type="xsd:string" nillable="true"/>
                                <xsd:element name="good" type="xsd:int" nillable="true"/>
                                <xsd:element name="sumr" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="VATr" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="roadTaxr" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="transportr" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="otherr" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="exciser" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="sumb" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="VATb" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="roadTaxb" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="transportb" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="otherb" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="exciseb" type="xsd:decimal" nillable="true"/>
                              </xsd:sequence>
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="afterSumLine" minOccurs="0" maxOccurs="unbounded">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="referenceNo" type="xsd:string" nillable="true"/>
                          <xsd:element name="good" type="xsd:int" nillable="true"/>
                          <xsd:element name="qnty" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="petrolweight" type="xsd:decimal" nillable="true"/>
                          <xsd:element name="saleSumAfterSumLine" minOccurs="0" maxOccurs="unbounded" prodata:undo="true">
                            <xsd:complexType>
                              <xsd:sequence>
                                <xsd:element name="referenceNo" type="xsd:string" nillable="true"/>
                                <xsd:element name="good" type="xsd:int" nillable="true"/>
                                <xsd:element name="sumr" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="VATr" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="roadTaxr" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="transportr" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="otherr" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="exciser" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="sumb" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="VATb" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="roadTaxb" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="transportb" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="otherb" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="exciseb" type="xsd:decimal" nillable="true"/>
                              </xsd:sequence>
                            </xsd:complexType>
                          </xsd:element>
                          <xsd:element name="costSumAfterSumLine" minOccurs="0" maxOccurs="unbounded" prodata:undo="true">
                            <xsd:complexType>
                              <xsd:sequence>
                                <xsd:element name="referenceNo" type="xsd:string" nillable="true"/>
                                <xsd:element name="good" type="xsd:int" nillable="true"/>
                                <xsd:element name="sumr" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="VATr" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="roadTaxr" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="transportr" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="otherr" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="exciser" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="sumb" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="VATb" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="roadTaxb" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="transportb" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="otherb" type="xsd:decimal" nillable="true"/>
                                <xsd:element name="exciseb" type="xsd:decimal" nillable="true"/>
                              </xsd:sequence>
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//operation"/>
      <xsd:field xpath="referenceNo"/>
    </xsd:unique>
    <xsd:unique name="beforeSum_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//beforeSum"/>
      <xsd:field xpath="referenceNo"/>
    </xsd:unique>
    <xsd:unique name="saleSumBeforeSum_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//saleSumBeforeSum"/>
      <xsd:field xpath="referenceNo"/>
    </xsd:unique>
    <xsd:unique name="costSumBeforeSum_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//costSumBeforeSum"/>
      <xsd:field xpath="referenceNo"/>
    </xsd:unique>
    <xsd:unique name="afterSum_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//afterSum"/>
      <xsd:field xpath="referenceNo"/>
    </xsd:unique>
    <xsd:unique name="saleSumAfterSum_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//saleSumAfterSum"/>
      <xsd:field xpath="referenceNo"/>
    </xsd:unique>
    <xsd:unique name="costSumAfterSum_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//costSumAfterSum"/>
      <xsd:field xpath="referenceNo"/>
    </xsd:unique>
    <xsd:unique name="linedoc_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//linedoc"/>
      <xsd:field xpath="referenceNo"/>
      <xsd:field xpath="good"/>
    </xsd:unique>
    <xsd:unique name="beforeSumLine_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//beforeSumLine"/>
      <xsd:field xpath="referenceNo"/>
    </xsd:unique>
    <xsd:unique name="saleSumBeforeSumLine_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//saleSumBeforeSumLine"/>
      <xsd:field xpath="referenceNo"/>
      <xsd:field xpath="good"/>
    </xsd:unique>
    <xsd:unique name="costSumBeforeSumLine_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//costSumBeforeSumLine"/>
      <xsd:field xpath="referenceNo"/>
      <xsd:field xpath="good"/>
    </xsd:unique>
    <xsd:unique name="afterSumLine_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//afterSumLine"/>
      <xsd:field xpath="referenceNo"/>
    </xsd:unique>
    <xsd:unique name="saleSumAfterSumLine_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//saleSumAfterSumLine"/>
      <xsd:field xpath="referenceNo"/>
      <xsd:field xpath="good"/>
    </xsd:unique>
    <xsd:unique name="costSumAfterSumLine_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//costSumAfterSumLine"/>
      <xsd:field xpath="referenceNo"/>
      <xsd:field xpath="good"/>
    </xsd:unique>
    <xsd:unique name="dtl_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//dtl"/>
      <xsd:field xpath="referenceNo"/>
      <xsd:field xpath="good"/>
      <xsd:field xpath="prtCode"/>
    </xsd:unique>
    <xsd:unique name="part_pi" prodata:primaryIndex="true">
      <xsd:selector xpath=".//part"/>
      <xsd:field xpath="referenceNo"/>
      <xsd:field xpath="good"/>
      <xsd:field xpath="doc_ID"/>
      <xsd:field xpath="partCode"/>
    </xsd:unique>
    <xsd:keyref name="operation-beforesum" refer="pi" prodata:nested="true">
      <xsd:selector xpath=".//beforeSum"/>
      <xsd:field xpath="referenceNo"/>
    </xsd:keyref>
    <xsd:keyref name="beforesum-salesumbeforesum" refer="beforeSum_pi" prodata:nested="true">
      <xsd:selector xpath=".//saleSumBeforeSum"/>
      <xsd:field xpath="referenceNo"/>
    </xsd:keyref>
    <xsd:keyref name="beforesum-costsumbeforesum" refer="beforeSum_pi" prodata:nested="true">
      <xsd:selector xpath=".//costSumBeforeSum"/>
      <xsd:field xpath="referenceNo"/>
    </xsd:keyref>
    <xsd:keyref name="operation-aftersum" refer="pi" prodata:nested="true">
      <xsd:selector xpath=".//afterSum"/>
      <xsd:field xpath="referenceNo"/>
    </xsd:keyref>
    <xsd:keyref name="aftersum-salesumaftersum" refer="afterSum_pi" prodata:nested="true">
      <xsd:selector xpath=".//saleSumAfterSum"/>
      <xsd:field xpath="referenceNo"/>
    </xsd:keyref>
    <xsd:keyref name="aftersum-costsumaftersum" refer="afterSum_pi" prodata:nested="true">
      <xsd:selector xpath=".//costSumAfterSum"/>
      <xsd:field xpath="referenceNo"/>
    </xsd:keyref>
    <xsd:keyref name="operation-linedoc" refer="pi" prodata:nested="true">
      <xsd:selector xpath=".//linedoc"/>
      <xsd:field xpath="referenceNo"/>
    </xsd:keyref>
    <xsd:keyref name="linedoc-dtl" refer="linedoc_pi" prodata:nested="true">
      <xsd:selector xpath=".//dtl"/>
      <xsd:field xpath="referenceNo"/>
      <xsd:field xpath="good"/>
    </xsd:keyref>
    <xsd:keyref name="linedoc-part" refer="linedoc_pi" prodata:nested="true">
      <xsd:selector xpath=".//part"/>
      <xsd:field xpath="referenceNo"/>
      <xsd:field xpath="good"/>
    </xsd:keyref>
    <xsd:keyref name="linedoc-beforesumLine" refer="linedoc_pi" prodata:nested="true">
      <xsd:selector xpath=".//beforeSumLine"/>
      <xsd:field xpath="referenceNo"/>
      <xsd:field xpath="good"/>
    </xsd:keyref>
    <xsd:keyref name="linedoc-aftersumLine" refer="linedoc_pi" prodata:nested="true">
      <xsd:selector xpath=".//afterSumLine"/>
      <xsd:field xpath="referenceNo"/>
      <xsd:field xpath="good"/>
    </xsd:keyref>
  </xsd:element>
  <xsd:annotation>
    <xsd:appinfo>
      <prodata:relation name="beforesum-salesumbeforesumLine" prodata:nested="true" prodata:parent="beforeSumLine" prodata:child="saleSumBeforeSumLine" prodata:relationFields="referenceNo,referenceNo,good,good"/>
      <prodata:relation name="beforesum-costsumbeforesumLine" prodata:nested="true" prodata:parent="beforeSumLine" prodata:child="costSumBeforeSumLine" prodata:relationFields="referenceNo,referenceNo,good,good"/>
      <prodata:relation name="aftersum-salesumaftersumLine" prodata:nested="true" prodata:parent="afterSumLine" prodata:child="saleSumAfterSumLine" prodata:relationFields="referenceNo,referenceNo,good,good"/>
      <prodata:relation name="aftersum-costsumaftersumLine" prodata:nested="true" prodata:parent="afterSumLine" prodata:child="costSumAfterSumLine" prodata:relationFields="referenceNo,referenceNo,good,good"/>
    </xsd:appinfo>
  </xsd:annotation>
</xsd:schema>
