&ANALYZE-SUSPEND _VERSION-NUMBER UIB_v8r12 GUI
&ANALYZE-RESUME
&Scoped-define WINDOW-NAME CURRENT-WINDOW
&Scoped-define FRAME-NAME Dialog-Frame
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CUSTOM _DEFINITIONS Dialog-Frame
/*

$Revision$
$Author$
$Date$
$Workfile$
$Archive$

Выбор колонок для отчета "Детализированная оборотная ведомость"

Автор: Чернова Светлана Александровна
Дата создания: 02/11/10
Author: Svetlana Chernova
Creation date: 02/11/10

Автор1: Кочетков Михаил Юрьевич
Дата создания: 09/16/05

*/

/* ***************************  Definitions  ************************** */

/* Parameters Definitions ---                                           */
define input  parameter       p-type   as integer   no-undo . /* 0 - детал, 1 -дет с призн , 3 c партиями */
define input-output parameter prod-zen as logical no-undo .
define output parameter       print-o  as character no-undo .


/* Local Variable Definitions ---                                       */

define variable vss-revision    as character no-undo init "$Revision$":U .
define variable vss-author      as character no-undo init "$Author$":U .
define variable vss-date        as character no-undo init "$Date$":U .
define variable vss-workfile    as character no-undo init "$Workfile$":U .
define variable vss-archive     as character no-undo init "$Archive$":U .
define variable vss-description as character no-undo init "Поля для расширенной оборотки".
{ cmp/vssrevis.i }
{ cmp/str-glbl.i }
{ cmp/r-page1.i }
{ rep/rep-bt.i }

define variable parparentproc     as widget-handle no-undo.
assign parparentproc =  my-handle .

define variable g#userid as character no-undo .
run get-userid  in parparentproc ( output g#userid ).

&scop max-col 120
&Scop List-2-t TOG-1,  TOG-2,  TOG-3 , TOG-4,  TOG-5,  TOG-6,  TOG-7,  TOG-8,  TOG-9,  TOG-10, ~
TOG-11, TOG-12, TOG-13 ,TOG-14, TOG-15, TOG-16, TOG-17, TOG-18, TOG-19, TOG-20, ~
TOG-21, TOG-22, TOG-23 ,TOG-24, TOG-25, TOG-26, TOG-27, TOG-28, TOG-29, TOG-30, ~
TOG-31, TOG-32, TOG-33 ,TOG-34, TOG-35, TOG-36, TOG-37, TOG-38, TOG-39, TOG-40, ~
TOG-41, TOG-42, TOG-43 ,TOG-44, TOG-45, TOG-46, TOG-47, TOG-48, TOG-49, TOG-50, ~
TOG-51, TOG-52, TOG-53 ,TOG-54, TOG-55, TOG-56, TOG-57, TOG-58, TOG-59, TOG-60, ~
TOG-61, TOG-62, TOG-63 ,TOG-64, TOG-65, TOG-66, TOG-67, TOG-68, TOG-69, TOG-70, ~
TOG-71, TOG-72, TOG-73 ,TOG-74, TOG-75, TOG-76, TOG-77, TOG-78, TOG-79, TOG-80, ~
TOG-81, TOG-82, TOG-83 ,TOG-84, TOG-85, TOG-86, TOG-87, TOG-88

define variable col-size as integer no-undo .
define variable s-column  as integer EXTENT   {&max-col}  no-undo .

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-PREPROCESSOR-BLOCK

/* ********************  Preprocessor Definitions  ******************** */

&Scoped-define PROCEDURE-TYPE DIALOG-BOX
&Scoped-define DB-AWARE no

/* Name of designated FRAME-NAME and/or first browse and/or first query */
&Scoped-define FRAME-NAME Dialog-Frame

/* Standard List Definitions                                            */
&Scoped-Define ENABLED-OBJECTS B-quit B-exit B-mark B-unmark B-help RECT-21 ~
RECT-18 RECT-19 RECT-20 TOG-1 TOG-12 TOG-31 TOG-50 TOG-2 TOG-13 TOG-51 ~
TOG-32 TOG-3 TOG-89 TOG-90 TOG-91 TOG-4 TOG-92 TOG-93 TOG-94 TOG-95 TOG-96 ~
TOG-5 TOG-6 TOG-14 TOG-33 RADIO-SET-2 TOG-15 TOG-34 TOG-7 TOG-16 TOG-35 ~
TOG-52 TOG-68 TOG-77 TOG-8 TOG-17 TOG-36 TOG-53 TOG-69 TOG-78 TOG-9 TOG-18 ~
TOG-37 TOG-54 TOG-70 TOG-79 TOG-10 TOG-19 TOG-55 TOG-71 TOG-80 TOG-38 ~
TOG-11 TOG-20 TOG-56 TOG-72 TOG-82 TOG-39 TOG-73 TOG-21 TOG-40 TOG-57 ~
TOG-81 TOG-58 TOG-74 TOG-83 TOG-22 TOG-41 TOG-42 TOG-59 TOG-75 TOG-84 ~
TOG-23 TOG-24 TOG-60 TOG-76 TOG-85 TOG-43 TOG-25 TOG-61 TOG-44 TOG-26 ~
TOG-45 TOG-62 TOG-46 TOG-27 TOG-63 TOG-47 TOG-28 TOG-64 TOG-48 TOG-29 ~
TOG-65 TOG-30 TOG-66 TOG-49 only-text-exel TOG-86 TOG-87 TOG-88 TOG-67 A-3 ~
FILL-IN-40 FILL-IN-43 FILL-IN-44 FILL-IN-39 FILL-IN-47 FILL-IN-41 ~
FILL-IN-42 FILL-IN-45 FILL-IN-46 FILL-IN-2 FILL-IN-25 FILL-IN-3 FILL-IN-26 ~
FILL-IN-4 FILL-IN-27 FILL-IN-52 FILL-IN-28 FILL-IN-53 FILL-IN-32 FILL-IN-5 ~
FILL-IN-48 FILL-IN-6 FILL-IN-7 FILL-IN-50 FILL-IN-8 FILL-IN-29 FILL-IN-9 ~
FILL-IN-49 FILL-IN-10 FILL-IN-30 FILL-IN-11 FILL-IN-31 FILL-IN-12 ~
FILL-IN-13 FILL-IN-14 FILL-IN-15 FILL-IN-16 FILL-IN-17 FILL-IN-18 ~
FILL-IN-19 FILL-IN-20 FILL-IN-21 FILL-IN-51 F-col-size FILL-IN-22 ~
FILL-IN-23 a3 A4-port a4-lansc only-file FILL-IN-24
&Scoped-Define DISPLAYED-OBJECTS TOG-1 TOG-12 TOG-31 TOG-50 TOG-2 TOG-13 ~
TOG-51 TOG-32 TOG-3 TOG-89 TOG-90 TOG-91 TOG-4 TOG-92 TOG-93 TOG-94 TOG-95 ~
TOG-96 TOG-5 TOG-6 TOG-14 TOG-33 RADIO-SET-2 TOG-15 TOG-34 TOG-7 TOG-16 ~
TOG-35 TOG-52 TOG-68 TOG-77 TOG-8 TOG-17 TOG-36 TOG-53 TOG-69 TOG-78 TOG-9 ~
TOG-18 TOG-37 TOG-54 TOG-70 TOG-79 TOG-10 TOG-19 TOG-55 TOG-71 TOG-80 ~
TOG-38 TOG-11 TOG-20 TOG-56 TOG-72 TOG-82 TOG-39 TOG-73 TOG-21 TOG-40 ~
TOG-57 TOG-81 TOG-58 TOG-74 TOG-83 TOG-22 TOG-41 TOG-42 TOG-59 TOG-75 ~
TOG-84 TOG-23 TOG-24 TOG-60 TOG-76 TOG-85 TOG-43 TOG-25 TOG-61 TOG-44 ~
TOG-26 TOG-45 TOG-62 TOG-46 TOG-27 TOG-63 TOG-47 TOG-28 TOG-64 TOG-48 ~
TOG-29 TOG-65 TOG-30 TOG-66 TOG-49 only-text-exel TOG-86 TOG-87 TOG-88 ~
TOG-67 FILL-IN-40 FILL-IN-43 FILL-IN-44 FILL-IN-39 FILL-IN-47 FILL-IN-41 ~
FILL-IN-42 FILL-IN-45 FILL-IN-46 FILL-IN-2 FILL-IN-25 FILL-IN-3 FILL-IN-26 ~
FILL-IN-4 FILL-IN-27 FILL-IN-52 FILL-IN-28 FILL-IN-53 FILL-IN-32 FILL-IN-5 ~
FILL-IN-48 FILL-IN-6 FILL-IN-7 FILL-IN-50 FILL-IN-8 FILL-IN-29 FILL-IN-9 ~
FILL-IN-49 FILL-IN-10 FILL-IN-30 FILL-IN-11 FILL-IN-31 FILL-IN-12 ~
FILL-IN-13 FILL-IN-14 FILL-IN-15 FILL-IN-16 FILL-IN-17 FILL-IN-18 ~
FILL-IN-19 FILL-IN-20 FILL-IN-21 FILL-IN-51 F-col-size FILL-IN-22 ~
FILL-IN-23 a3 A4-port a4-lansc only-file FILL-IN-24

/* Custom List Definitions                                              */
/* List-1,List-2,List-3,List-4,List-5,List-6                            */
&Scoped-define List-1 FILL-IN-40 FILL-IN-43 FILL-IN-44 FILL-IN-39 ~
FILL-IN-47 FILL-IN-41 FILL-IN-42 FILL-IN-45 FILL-IN-46 FILL-IN-2 FILL-IN-3 ~
FILL-IN-4 FILL-IN-52 FILL-IN-28 FILL-IN-53 FILL-IN-32 FILL-IN-5 FILL-IN-48 ~
FILL-IN-6 FILL-IN-7 FILL-IN-50 FILL-IN-8 FILL-IN-29 FILL-IN-9 FILL-IN-49 ~
FILL-IN-10 FILL-IN-11 FILL-IN-12 FILL-IN-13 FILL-IN-14 FILL-IN-15 ~
FILL-IN-16 FILL-IN-17 FILL-IN-18 FILL-IN-19 FILL-IN-20 FILL-IN-21 ~
FILL-IN-22
&Scoped-define List-2 TOG-1 TOG-12 TOG-31 TOG-50 TOG-2 TOG-13 TOG-51 TOG-32 ~
TOG-3 TOG-89 TOG-90 TOG-91 TOG-4 TOG-92 TOG-93 TOG-94 TOG-95 TOG-96 TOG-5 ~
TOG-6 TOG-14 TOG-33 TOG-15 TOG-34 TOG-7 TOG-16 TOG-35 TOG-52 TOG-68 TOG-77 ~
TOG-8 TOG-17 TOG-36 TOG-53 TOG-69 TOG-78 TOG-9 TOG-18 TOG-37 TOG-54 TOG-70 ~
TOG-79 TOG-10 TOG-19 TOG-55 TOG-71 TOG-80 TOG-38 TOG-11 TOG-20 TOG-56 ~
TOG-72 TOG-82 TOG-39 TOG-73 TOG-21 TOG-40 TOG-57 TOG-81 TOG-58 TOG-74 ~
TOG-83 TOG-22 TOG-41 TOG-42 TOG-59 TOG-75 TOG-84 TOG-23 TOG-24 TOG-60 ~
TOG-76 TOG-85 TOG-43 TOG-25 TOG-61 TOG-44 TOG-26 TOG-45 TOG-62 TOG-46 ~
TOG-27 TOG-63 TOG-47 TOG-28 TOG-64 TOG-48 TOG-29 TOG-65 TOG-30 TOG-66 ~
TOG-49 TOG-86 TOG-87 TOG-88 TOG-67
&Scoped-define List-4 A4-port
&Scoped-define List-5 a4-lansc
&Scoped-define List-6 a3

/* _UIB-PREPROCESSOR-BLOCK-END */
&ANALYZE-RESUME



/* ***********************  Control Definitions  ********************** */

/* Define a dialog box                                                  */

/* Definitions of the field level widgets                               */
DEFINE BUTTON A-3
     LABEL "A3"
     SIZE 4.25 BY 1.13.

DEFINE BUTTON B-exit AUTO-GO
     LABEL "Ввод"
     SIZE 12 BY 1
     BGCOLOR 8 .

DEFINE BUTTON B-help
     LABEL "Помощь"
     SIZE 10.38 BY 1
     BGCOLOR 8 .

DEFINE BUTTON B-mark
     LABEL "Отметить *"
     SIZE 12 BY 1
     BGCOLOR 8 .

DEFINE BUTTON B-quit AUTO-END-KEY
     LABEL "Отмена"
     SIZE 12 BY 1
     BGCOLOR 8 .

DEFINE BUTTON B-unmark
     LABEL "Снять *"
     SIZE 12 BY 1
     BGCOLOR 8 .

DEFINE VARIABLE only-text-exel AS CHARACTER INITIAL "На экране возможно отобразить ограниченное число символов. Полная информация возможна при выводе в Excel"
     VIEW-AS EDITOR NO-BOX
     SIZE 27.38 BY 2.83
     FGCOLOR 12 FONT 4 NO-UNDO.

DEFINE VARIABLE a3 AS CHARACTER FORMAT "X(256)":C6 INITIAL "A3"
      VIEW-AS TEXT
     SIZE 8.13 BY 1.58
     BGCOLOR 15 FGCOLOR 9 FONT 4 NO-UNDO.

DEFINE VARIABLE a4-lansc AS CHARACTER FORMAT "X(256)" INITIAL "A4"
      VIEW-AS TEXT
     SIZE 5.38 BY .96
     BGCOLOR 15 FGCOLOR 9 FONT 4 NO-UNDO.

DEFINE VARIABLE A4-port AS CHARACTER FORMAT "X(256)" INITIAL "A4"
      VIEW-AS TEXT
     SIZE 3.13 BY 1.46
     BGCOLOR 15 FGCOLOR 9 FONT 4 NO-UNDO.

DEFINE VARIABLE F-col-size AS CHARACTER FORMAT "X(256)":U
      VIEW-AS TEXT
     SIZE 7 BY .67
     FGCOLOR 4  NO-UNDO.

DEFINE VARIABLE FILL-IN-10 AS CHARACTER FORMAT "X(256)":U INITIAL "Расход - Возврат"
      VIEW-AS TEXT
     SIZE 25 BY 1 NO-UNDO.

DEFINE VARIABLE FILL-IN-11 AS CHARACTER FORMAT "X(256)":U INITIAL "Касса продажа"
      VIEW-AS TEXT
     SIZE 25.38 BY 1 NO-UNDO.

DEFINE VARIABLE FILL-IN-12 AS CHARACTER FORMAT "X(256)":U INITIAL "Касса возврат"
      VIEW-AS TEXT
     SIZE 25.38 BY 1 NO-UNDO.

DEFINE VARIABLE FILL-IN-13 AS CHARACTER FORMAT "X(256)":U INITIAL "Касса продажа - возврат"
      VIEW-AS TEXT
     SIZE 25.13 BY 1 NO-UNDO.

DEFINE VARIABLE FILL-IN-14 AS CHARACTER FORMAT "X(256)":U INITIAL "Всего расход внеш."
      VIEW-AS TEXT
     SIZE 25 BY 1 NO-UNDO.

DEFINE VARIABLE FILL-IN-15 AS CHARACTER FORMAT "X(256)":U INITIAL "Всего возврат внеш."
      VIEW-AS TEXT
     SIZE 24.63 BY 1 NO-UNDO.

DEFINE VARIABLE FILL-IN-16 AS CHARACTER FORMAT "X(256)":U INITIAL "Всего расх.-возвр. внеш."
      VIEW-AS TEXT
     SIZE 24.13 BY 1 NO-UNDO.

DEFINE VARIABLE FILL-IN-17 AS CHARACTER FORMAT "X(256)":U INITIAL "Инвентаризация"
      VIEW-AS TEXT
     SIZE 23.75 BY 1 NO-UNDO.

DEFINE VARIABLE FILL-IN-18 AS CHARACTER FORMAT "X(256)":U INITIAL "Списание"
      VIEW-AS TEXT
     SIZE 23.63 BY 1 NO-UNDO.

DEFINE VARIABLE FILL-IN-19 AS CHARACTER FORMAT "X(256)":U INITIAL "Приход перемещение"
      VIEW-AS TEXT
     SIZE 23.75 BY 1 NO-UNDO.

DEFINE VARIABLE FILL-IN-2 AS CHARACTER FORMAT "X(256)":U INITIAL "Остатки"
      VIEW-AS TEXT
     SIZE 13 BY .67
     FGCOLOR 4  NO-UNDO.

DEFINE VARIABLE FILL-IN-20 AS CHARACTER FORMAT "X(256)":U INITIAL "Расход перемещение"
      VIEW-AS TEXT
     SIZE 23.75 BY 1 NO-UNDO.

DEFINE VARIABLE FILL-IN-21 AS CHARACTER FORMAT "X(256)":U INITIAL "Возврат перемещение"
      VIEW-AS TEXT
     SIZE 24.13 BY 1 NO-UNDO.

DEFINE VARIABLE FILL-IN-22 AS CHARACTER FORMAT "X(256)":U INITIAL "Приход производство"
      VIEW-AS TEXT
     SIZE 24.38 BY 1 NO-UNDO.

DEFINE VARIABLE FILL-IN-23 AS CHARACTER FORMAT "X(256)":U INITIAL "Расход производство"
      VIEW-AS TEXT
     SIZE 23.88 BY 1 NO-UNDO.

DEFINE VARIABLE FILL-IN-24 AS CHARACTER FORMAT "X(256)":U INITIAL "Переоценка"
      VIEW-AS TEXT
     SIZE 24.5 BY 1 NO-UNDO.

DEFINE VARIABLE FILL-IN-25 AS CHARACTER FORMAT "X(256)":U INITIAL "Код"
      VIEW-AS TEXT
     SIZE 29 BY .67 NO-UNDO.

DEFINE VARIABLE FILL-IN-26 AS CHARACTER FORMAT "X(256)":U INITIAL "Артикул"
      VIEW-AS TEXT
     SIZE 29 BY .67 NO-UNDO.

DEFINE VARIABLE FILL-IN-27 AS CHARACTER FORMAT "X(256)":U INITIAL "Название товара"
      VIEW-AS TEXT
     SIZE 29 BY .67 NO-UNDO.

DEFINE VARIABLE FILL-IN-28 AS CHARACTER FORMAT "X(256)":U INITIAL "Ед.изм"
      VIEW-AS TEXT
     SIZE 29 BY .67 NO-UNDO.

DEFINE VARIABLE FILL-IN-29 AS CHARACTER FORMAT "X(256)":U INITIAL "Дата последней переоценки"
      VIEW-AS TEXT
     SIZE 29 BY .67 NO-UNDO.

DEFINE VARIABLE FILL-IN-3 AS CHARACTER FORMAT "X(256)":U INITIAL "Остаток на начало"
      VIEW-AS TEXT
     SIZE 23.5 BY 1 NO-UNDO.

DEFINE VARIABLE FILL-IN-30 AS CHARACTER FORMAT "X(256)":U INITIAL "Эффективность"
      VIEW-AS TEXT
     SIZE 24.63 BY .67 NO-UNDO.

DEFINE VARIABLE FILL-IN-31 AS CHARACTER FORMAT "X(256)":U INITIAL "Фактический % наценки"
      VIEW-AS TEXT
     SIZE 24.75 BY .67 NO-UNDO.

DEFINE VARIABLE FILL-IN-32 AS CHARACTER FORMAT "X(256)":U INITIAL "Учетная цена"
      VIEW-AS TEXT
     SIZE 29 BY .67 NO-UNDO.

DEFINE VARIABLE FILL-IN-39 AS CHARACTER FORMAT "X(256)":U INITIAL "Кол-во"
      VIEW-AS TEXT
     SIZE 7.38 BY .67
     FGCOLOR 4  NO-UNDO.

DEFINE VARIABLE FILL-IN-4 AS CHARACTER FORMAT "X(256)":U INITIAL "Остаток на конец"
      VIEW-AS TEXT
     SIZE 23.88 BY 1 NO-UNDO.

DEFINE VARIABLE FILL-IN-40 AS CHARACTER FORMAT "X(256)":U INITIAL "Сумма"
      VIEW-AS TEXT
     SIZE 6.38 BY .63
     FGCOLOR 4  NO-UNDO.

DEFINE VARIABLE FILL-IN-41 AS CHARACTER FORMAT "X(256)":U INITIAL "учет. цен"
      VIEW-AS TEXT
     SIZE 9.63 BY .63
     FGCOLOR 4  NO-UNDO.

DEFINE VARIABLE FILL-IN-42 AS CHARACTER FORMAT "X(256)":U INITIAL "прод. цен"
      VIEW-AS TEXT
     SIZE 9.25 BY .63
     FGCOLOR 4  NO-UNDO.

DEFINE VARIABLE FILL-IN-43 AS CHARACTER FORMAT "X(256)":U INITIAL "Сумма"
      VIEW-AS TEXT
     SIZE 6.38 BY .63
     FGCOLOR 4  NO-UNDO.

DEFINE VARIABLE FILL-IN-44 AS CHARACTER FORMAT "X(256)":U INITIAL "Сумма"
      VIEW-AS TEXT
     SIZE 6.38 BY .63
     FGCOLOR 4  NO-UNDO.

DEFINE VARIABLE FILL-IN-45 AS CHARACTER FORMAT "X(256)":U INITIAL "скидок"
      VIEW-AS TEXT
     SIZE 6.38 BY .63
     FGCOLOR 4  NO-UNDO.

DEFINE VARIABLE FILL-IN-46 AS CHARACTER FORMAT "X(256)":U INITIAL "скидок"
      VIEW-AS TEXT
     SIZE 6.38 BY .63
     FGCOLOR 4  NO-UNDO.

DEFINE VARIABLE FILL-IN-47 AS CHARACTER FORMAT "X(256)":U INITIAL "%"
      VIEW-AS TEXT
     SIZE 3.25 BY .63
     FGCOLOR 4  NO-UNDO.

DEFINE VARIABLE FILL-IN-48 AS CHARACTER FORMAT "X(256)":U INITIAL "Продажная цена"
      VIEW-AS TEXT
     SIZE 25.5 BY .67 NO-UNDO.

DEFINE VARIABLE FILL-IN-49 AS CHARACTER FORMAT "X(256)":U INITIAL "Номер последней переоценки"
      VIEW-AS TEXT
     SIZE 29 BY .67 NO-UNDO.

DEFINE VARIABLE FILL-IN-5 AS CHARACTER FORMAT "X(256)":U INITIAL "Оборот"
      VIEW-AS TEXT
     SIZE 13 BY .67
     FGCOLOR 4  NO-UNDO.

DEFINE VARIABLE FILL-IN-50 AS CHARACTER FORMAT "X(256)":U INITIAL "Наценка на конец периода"
      VIEW-AS TEXT
     SIZE 29 BY .67 NO-UNDO.

DEFINE VARIABLE FILL-IN-51 AS CHARACTER FORMAT "X(256)" INITIAL "  Формат вывода на печать  "
      VIEW-AS TEXT
     SIZE 25.88 BY .67
     FGCOLOR 4  NO-UNDO.

DEFINE VARIABLE FILL-IN-52 AS CHARACTER FORMAT "X(256)":U INITIAL "Свободно на конец"
      VIEW-AS TEXT
     SIZE 23.88 BY .71 NO-UNDO.

DEFINE VARIABLE FILL-IN-53 AS CHARACTER FORMAT "X(256)":U INITIAL "Зарезервировано на конец"
      VIEW-AS TEXT
     SIZE 25 BY .67 NO-UNDO.

DEFINE VARIABLE FILL-IN-6 AS CHARACTER FORMAT "X(256)":U INITIAL "Приход внешний"
      VIEW-AS TEXT
     SIZE 23.88 BY 1 NO-UNDO.

DEFINE VARIABLE FILL-IN-7 AS CHARACTER FORMAT "X(256)":U INITIAL "Возврат поставщику"
      VIEW-AS TEXT
     SIZE 24.13 BY 1 NO-UNDO.

DEFINE VARIABLE FILL-IN-8 AS CHARACTER FORMAT "X(256)":U INITIAL "Расход внешний"
      VIEW-AS TEXT
     SIZE 24.75 BY 1 NO-UNDO.

DEFINE VARIABLE FILL-IN-9 AS CHARACTER FORMAT "X(256)":U INITIAL "Возврат внешний"
      VIEW-AS TEXT
     SIZE 25 BY 1 NO-UNDO.

DEFINE VARIABLE only-file AS CHARACTER FORMAT "X(256)" INITIAL "  вывод в файл  "
      VIEW-AS TEXT
     SIZE 16 BY .67
     BGCOLOR 15 FGCOLOR 9  NO-UNDO.

DEFINE VARIABLE RADIO-SET-2 AS INTEGER
     VIEW-AS RADIO-SET VERTICAL
     RADIO-BUTTONS
          "Средняя за период", 1,
"Последняя за период", 2
     SIZE 28.13 BY 1.29 NO-UNDO.

DEFINE RECTANGLE RECT-18
     EDGE-PIXELS 2 GRAPHIC-EDGE  NO-FILL
     SIZE 66 BY 17.33.

DEFINE RECTANGLE RECT-19
     EDGE-PIXELS 2 GRAPHIC-EDGE  NO-FILL
     SIZE 65.88 BY 3.75.

DEFINE RECTANGLE RECT-20
     EDGE-PIXELS 2 GRAPHIC-EDGE  NO-FILL
     SIZE 29.38 BY 2.

DEFINE RECTANGLE RECT-21
     EDGE-PIXELS 2 GRAPHIC-EDGE  NO-FILL
     SIZE 36.38 BY 17.25.

DEFINE VARIABLE TOG-1 AS LOGICAL INITIAL yes
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .67 NO-UNDO.

DEFINE VARIABLE TOG-10 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .67 NO-UNDO.

DEFINE VARIABLE TOG-11 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .67 NO-UNDO.

DEFINE VARIABLE TOG-12 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .88 NO-UNDO.

DEFINE VARIABLE TOG-13 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .88 NO-UNDO.

DEFINE VARIABLE TOG-14 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .88 NO-UNDO.

DEFINE VARIABLE TOG-15 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .88 NO-UNDO.

DEFINE VARIABLE TOG-16 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .88 NO-UNDO.

DEFINE VARIABLE TOG-17 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-18 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-19 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-2 AS LOGICAL INITIAL yes
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .67 NO-UNDO.

DEFINE VARIABLE TOG-20 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-21 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-22 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .75 NO-UNDO.

DEFINE VARIABLE TOG-23 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-24 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-25 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-26 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-27 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-28 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-29 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-3 AS LOGICAL INITIAL yes
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .67 NO-UNDO.

DEFINE VARIABLE TOG-30 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-31 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-32 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-33 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-34 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-35 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-36 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-37 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-38 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-39 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-4 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .67 NO-UNDO.

DEFINE VARIABLE TOG-40 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-41 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-42 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-43 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .71 NO-UNDO.

DEFINE VARIABLE TOG-44 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-45 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-46 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-47 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-48 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-49 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-5 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .67 NO-UNDO.

DEFINE VARIABLE TOG-50 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .75 NO-UNDO.

DEFINE VARIABLE TOG-51 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-52 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-53 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-54 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-55 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-56 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-57 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-58 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-59 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-6 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .67 NO-UNDO.

DEFINE VARIABLE TOG-60 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-61 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-62 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-63 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-64 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-65 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-66 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-67 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-68 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-69 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-7 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .67 NO-UNDO.

DEFINE VARIABLE TOG-70 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-71 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-72 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-73 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-74 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-75 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-76 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-77 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-78 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-79 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-8 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .67 NO-UNDO.

DEFINE VARIABLE TOG-80 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-81 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-82 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-83 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-84 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-85 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-86 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.38 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-87 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-88 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.13 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-89 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .88 NO-UNDO.

DEFINE VARIABLE TOG-9 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .67 NO-UNDO.

DEFINE VARIABLE TOG-90 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-91 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-92 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .88 NO-UNDO.

DEFINE VARIABLE TOG-93 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-94 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-95 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.

DEFINE VARIABLE TOG-96 AS LOGICAL INITIAL no
     LABEL ""
     VIEW-AS TOGGLE-BOX
     SIZE 2.5 BY .83 NO-UNDO.


/* ************************  Frame Definitions  *********************** */

DEFINE FRAME Dialog-Frame
     B-quit AT ROW 1 COL 2.25
     B-exit AT ROW 1 COL 14.25
     B-mark AT ROW 1 COL 26.25
     B-unmark AT ROW 1 COL 38.13
     B-help AT ROW 1 COL 50.25
     TOG-1 AT ROW 2.92 COL 35.5 RIGHT-ALIGNED
     TOG-12 AT ROW 3.04 COL 67.75 RIGHT-ALIGNED
     TOG-31 AT ROW 3.04 COL 76.25 RIGHT-ALIGNED
     TOG-50 AT ROW 3.08 COL 84.75 RIGHT-ALIGNED
     TOG-2 AT ROW 3.79 COL 35.5 RIGHT-ALIGNED
     TOG-13 AT ROW 3.88 COL 67.75 RIGHT-ALIGNED
     TOG-51 AT ROW 3.88 COL 84.75 RIGHT-ALIGNED
     TOG-32 AT ROW 3.92 COL 76.38 RIGHT-ALIGNED
     TOG-3 AT ROW 4.67 COL 35.5 RIGHT-ALIGNED
     TOG-89 AT ROW 4.79 COL 67.75 RIGHT-ALIGNED
     TOG-90 AT ROW 4.79 COL 76.25 RIGHT-ALIGNED
     TOG-91 AT ROW 4.79 COL 84.75 RIGHT-ALIGNED
     TOG-4 AT ROW 5.54 COL 35.5 RIGHT-ALIGNED
     TOG-92 AT ROW 5.67 COL 67.75 RIGHT-ALIGNED
     TOG-93 AT ROW 5.67 COL 76.25 RIGHT-ALIGNED
     TOG-94 AT ROW 5.67 COL 84.75 RIGHT-ALIGNED
     TOG-95 AT ROW 5.71 COL 96.38 RIGHT-ALIGNED
     TOG-96 AT ROW 5.71 COL 102.63 RIGHT-ALIGNED
     TOG-5 AT ROW 6.33 COL 35.5 RIGHT-ALIGNED
     TOG-6 AT ROW 7.08 COL 35.5 RIGHT-ALIGNED
     TOG-14 AT ROW 7.17 COL 67.75 RIGHT-ALIGNED
     TOG-33 AT ROW 7.17 COL 76.38 RIGHT-ALIGNED
     RADIO-SET-2 AT ROW 7.67 COL 2.88 NO-LABEL
     TOG-15 AT ROW 7.96 COL 67.75 RIGHT-ALIGNED
     TOG-34 AT ROW 8.08 COL 76.38 RIGHT-ALIGNED
     TOG-7 AT ROW 9 COL 35.5 RIGHT-ALIGNED
     TOG-16 AT ROW 9.04 COL 67.75 RIGHT-ALIGNED
     TOG-35 AT ROW 9.04 COL 76.38 RIGHT-ALIGNED
     TOG-52 AT ROW 9.04 COL 84.75 RIGHT-ALIGNED
     TOG-68 AT ROW 9.04 COL 96.38 RIGHT-ALIGNED
     TOG-77 AT ROW 9.04 COL 102.63 RIGHT-ALIGNED
     TOG-8 AT ROW 9.75 COL 35.5 RIGHT-ALIGNED
     TOG-17 AT ROW 9.88 COL 67.75 RIGHT-ALIGNED
     TOG-36 AT ROW 9.88 COL 76.38 RIGHT-ALIGNED
     TOG-53 AT ROW 9.88 COL 84.75 RIGHT-ALIGNED
     TOG-69 AT ROW 9.88 COL 96.38 RIGHT-ALIGNED
     TOG-78 AT ROW 9.88 COL 102.63 RIGHT-ALIGNED
     TOG-9 AT ROW 10.46 COL 35.5 RIGHT-ALIGNED
     TOG-18 AT ROW 10.71 COL 67.75 RIGHT-ALIGNED
     TOG-37 AT ROW 10.71 COL 76.38 RIGHT-ALIGNED
     TOG-54 AT ROW 10.71 COL 84.75 RIGHT-ALIGNED
     TOG-70 AT ROW 10.71 COL 96.38 RIGHT-ALIGNED
     TOG-79 AT ROW 10.71 COL 102.63 RIGHT-ALIGNED
     TOG-10 AT ROW 11.21 COL 35.5 RIGHT-ALIGNED
     TOG-19 AT ROW 11.58 COL 67.75 RIGHT-ALIGNED
     TOG-55 AT ROW 11.58 COL 84.75 RIGHT-ALIGNED
     TOG-71 AT ROW 11.58 COL 96.38 RIGHT-ALIGNED
     TOG-80 AT ROW 11.58 COL 102.63 RIGHT-ALIGNED
     TOG-38 AT ROW 11.63 COL 76.38 RIGHT-ALIGNED
     TOG-11 AT ROW 12 COL 35.5 RIGHT-ALIGNED WIDGET-ID 24
     TOG-20 AT ROW 12.42 COL 67.75 RIGHT-ALIGNED
     TOG-56 AT ROW 12.42 COL 84.75 RIGHT-ALIGNED
     TOG-72 AT ROW 12.42 COL 96.38 RIGHT-ALIGNED
     TOG-82 AT ROW 12.42 COL 102.63 RIGHT-ALIGNED
     TOG-39 AT ROW 12.5 COL 76.38 RIGHT-ALIGNED
     TOG-73 AT ROW 13.08 COL 96.38 RIGHT-ALIGNED
     TOG-21 AT ROW 13.25 COL 67.75 RIGHT-ALIGNED
     TOG-40 AT ROW 13.25 COL 76.38 RIGHT-ALIGNED
     TOG-57 AT ROW 13.25 COL 84.75 RIGHT-ALIGNED
     TOG-81 AT ROW 13.29 COL 102.63 RIGHT-ALIGNED
     TOG-58 AT ROW 14.25 COL 84.75 RIGHT-ALIGNED
     TOG-74 AT ROW 14.25 COL 96.38 RIGHT-ALIGNED
     TOG-83 AT ROW 14.25 COL 102.63 RIGHT-ALIGNED
     TOG-22 AT ROW 14.29 COL 67.75 RIGHT-ALIGNED
    WITH VIEW-AS DIALOG-BOX KEEP-TAB-ORDER
         SIDE-LABELS NO-UNDERLINE THREE-D  SCROLLABLE
         DEFAULT-BUTTON B-exit CANCEL-BUTTON B-quit.

/* DEFINE FRAME statement is approaching 4K Bytes.  Breaking it up   */
DEFINE FRAME Dialog-Frame
     TOG-41 AT ROW 14.29 COL 76.38 RIGHT-ALIGNED
     TOG-42 AT ROW 15.08 COL 76.38 RIGHT-ALIGNED
     TOG-59 AT ROW 15.08 COL 84.63 RIGHT-ALIGNED
     TOG-75 AT ROW 15.08 COL 96.38 RIGHT-ALIGNED
     TOG-84 AT ROW 15.08 COL 102.63 RIGHT-ALIGNED
     TOG-23 AT ROW 15.17 COL 67.75 RIGHT-ALIGNED
     TOG-24 AT ROW 15.88 COL 67.75 RIGHT-ALIGNED
     TOG-60 AT ROW 15.92 COL 84.75 RIGHT-ALIGNED
     TOG-76 AT ROW 15.92 COL 96.38 RIGHT-ALIGNED
     TOG-85 AT ROW 15.92 COL 102.63 RIGHT-ALIGNED
     TOG-43 AT ROW 15.96 COL 76.38 RIGHT-ALIGNED
     TOG-25 AT ROW 16.96 COL 67.88 RIGHT-ALIGNED
     TOG-61 AT ROW 16.96 COL 84.75 RIGHT-ALIGNED
     TOG-44 AT ROW 17 COL 76.38 RIGHT-ALIGNED
     TOG-26 AT ROW 17.75 COL 67.88 RIGHT-ALIGNED
     TOG-45 AT ROW 17.75 COL 76.38 RIGHT-ALIGNED
     TOG-62 AT ROW 17.75 COL 84.75 RIGHT-ALIGNED
     TOG-46 AT ROW 18.63 COL 76.38 RIGHT-ALIGNED
     TOG-27 AT ROW 18.71 COL 67.88 RIGHT-ALIGNED
     TOG-63 AT ROW 18.71 COL 84.75 RIGHT-ALIGNED
     TOG-47 AT ROW 19.42 COL 76.38 RIGHT-ALIGNED
     TOG-28 AT ROW 19.46 COL 67.88 RIGHT-ALIGNED
     TOG-64 AT ROW 19.46 COL 84.75 RIGHT-ALIGNED
     TOG-48 AT ROW 20.21 COL 76.38 RIGHT-ALIGNED
     TOG-29 AT ROW 20.33 COL 67.88 RIGHT-ALIGNED
     TOG-65 AT ROW 20.33 COL 84.75 RIGHT-ALIGNED
     TOG-30 AT ROW 21.29 COL 67.88 RIGHT-ALIGNED
     TOG-66 AT ROW 21.29 COL 84.75 RIGHT-ALIGNED
     TOG-49 AT ROW 21.33 COL 76.38 RIGHT-ALIGNED
     only-text-exel AT ROW 21.42 COL 4.38 NO-LABEL
     TOG-86 AT ROW 22.13 COL 66.38
     TOG-87 AT ROW 22.13 COL 75
     TOG-88 AT ROW 22.13 COL 83.38
     TOG-67 AT ROW 23 COL 84.75 RIGHT-ALIGNED
     A-3 AT ROW 23.04 COL 26.88
     FILL-IN-40 AT ROW 1.33 COL 72.5 NO-LABEL
     FILL-IN-43 AT ROW 1.33 COL 82 NO-LABEL
     FILL-IN-44 AT ROW 1.33 COL 91.5 NO-LABEL
     FILL-IN-39 AT ROW 1.38 COL 63.75 NO-LABEL
     FILL-IN-47 AT ROW 1.38 COL 99.25 NO-LABEL
     FILL-IN-41 AT ROW 1.92 COL 70.88 NO-LABEL
     FILL-IN-42 AT ROW 1.96 COL 80.88 NO-LABEL
     FILL-IN-45 AT ROW 1.96 COL 91.13 NO-LABEL
     FILL-IN-46 AT ROW 1.96 COL 98.25 NO-LABEL
     FILL-IN-2 AT ROW 2.46 COL 43 NO-LABEL
     FILL-IN-25 AT ROW 3 COL 2.38 NO-LABEL
     FILL-IN-3 AT ROW 3.04 COL 41 NO-LABEL
     FILL-IN-26 AT ROW 3.75 COL 2.38 NO-LABEL
     FILL-IN-4 AT ROW 3.92 COL 41 NO-LABEL
     FILL-IN-27 AT ROW 4.63 COL 2.38 NO-LABEL
     FILL-IN-52 AT ROW 4.83 COL 41 NO-LABEL
     FILL-IN-28 AT ROW 5.46 COL 2.38 NO-LABEL
     FILL-IN-53 AT ROW 5.67 COL 41 NO-LABEL
     FILL-IN-32 AT ROW 6.25 COL 2.38 NO-LABEL
     FILL-IN-5 AT ROW 6.58 COL 43 NO-LABEL
     FILL-IN-48 AT ROW 7.08 COL 2.13 NO-LABEL
     FILL-IN-6 AT ROW 7.25 COL 41 NO-LABEL
     FILL-IN-7 AT ROW 8.04 COL 41 NO-LABEL
     FILL-IN-50 AT ROW 9 COL 2.38 NO-LABEL
     FILL-IN-8 AT ROW 9.04 COL 41 NO-LABEL
     FILL-IN-29 AT ROW 9.75 COL 2.38 NO-LABEL
     FILL-IN-9 AT ROW 9.83 COL 41 NO-LABEL
     FILL-IN-49 AT ROW 10.46 COL 2.38 NO-LABEL
     FILL-IN-10 AT ROW 10.63 COL 41 NO-LABEL
     FILL-IN-30 AT ROW 11.21 COL 2.5 NO-LABEL
    WITH VIEW-AS DIALOG-BOX KEEP-TAB-ORDER
         SIDE-LABELS NO-UNDERLINE THREE-D  SCROLLABLE
         DEFAULT-BUTTON B-exit CANCEL-BUTTON B-quit.

/* DEFINE FRAME statement is approaching 4K Bytes.  Breaking it up   */
DEFINE FRAME Dialog-Frame
     FILL-IN-11 AT ROW 11.63 COL 41 NO-LABEL
     FILL-IN-31 AT ROW 12 COL 2.5 NO-LABEL WIDGET-ID 22
     FILL-IN-12 AT ROW 12.46 COL 41 NO-LABEL
     FILL-IN-13 AT ROW 13.25 COL 41 NO-LABEL
     FILL-IN-14 AT ROW 14.25 COL 41 NO-LABEL
     FILL-IN-15 AT ROW 15.04 COL 41 NO-LABEL
     FILL-IN-16 AT ROW 15.83 COL 41 NO-LABEL
     FILL-IN-17 AT ROW 16.83 COL 41 NO-LABEL
     FILL-IN-18 AT ROW 17.63 COL 41 NO-LABEL
     FILL-IN-19 AT ROW 18.63 COL 41 NO-LABEL
     FILL-IN-20 AT ROW 19.46 COL 41 NO-LABEL
     FILL-IN-21 AT ROW 20.25 COL 41 NO-LABEL
     FILL-IN-51 AT ROW 20.5 COL 4 NO-LABEL
     F-col-size AT ROW 20.5 COL 29 COLON-ALIGNED NO-LABEL
     FILL-IN-22 AT ROW 21.25 COL 41 NO-LABEL
     FILL-IN-23 AT ROW 21.96 COL 39 COLON-ALIGNED NO-LABEL
     a3 AT ROW 22.08 COL 12.5 COLON-ALIGNED NO-LABEL
     A4-port AT ROW 22.25 COL 15.38 COLON-ALIGNED NO-LABEL
     a4-lansc AT ROW 22.42 COL 13.88 COLON-ALIGNED NO-LABEL
     only-file AT ROW 22.5 COL 7.25 COLON-ALIGNED NO-LABEL
     FILL-IN-24 AT ROW 23.21 COL 39 COLON-ALIGNED NO-LABEL
     "(-скидки)" VIEW-AS TEXT
          SIZE 8.75 BY .67 AT ROW 15.92 COL 85.5
     "(-скидки)" VIEW-AS TEXT
          SIZE 8.75 BY .67 AT ROW 13.38 COL 85.38
     "Колонки":C28 VIEW-AS TEXT
          SIZE 27.38 BY .67 AT ROW 2.08 COL 2.25
          FGCOLOR 4
     "Показать":C8 VIEW-AS TEXT
          SIZE 8.88 BY .67 AT ROW 2.08 COL 31.38
          FGCOLOR 4
     "(-скидки)" VIEW-AS TEXT
          SIZE 8.75 BY .67 AT ROW 10.83 COL 85.5
     "(-скидки)" VIEW-AS TEXT
          SIZE 8.75 BY .67 AT ROW 5.79 COL 85.5
     RECT-21 AT ROW 7.25 COL 70.5
     RECT-18 AT ROW 6.96 COL 40.5
     RECT-19 AT ROW 2.83 COL 40.5
     RECT-20 AT ROW 7.04 COL 1.75
     SPACE(75.99) SKIP(15.49)
    WITH VIEW-AS DIALOG-BOX KEEP-TAB-ORDER
         SIDE-LABELS NO-UNDERLINE THREE-D  SCROLLABLE
         TITLE "Выбор колонок для печати"
         DEFAULT-BUTTON B-exit CANCEL-BUTTON B-quit.


/* *********************** Procedure Settings ************************ */

&ANALYZE-SUSPEND _PROCEDURE-SETTINGS
/* Settings for THIS-PROCEDURE
   Type: DIALOG-BOX
   Allow: Basic,Browse,DB-Fields,Query
 */
&ANALYZE-RESUME _END-PROCEDURE-SETTINGS



/* ***********  Runtime Attributes and AppBuilder Settings  *********** */

&ANALYZE-SUSPEND _RUN-TIME-ATTRIBUTES
/* SETTINGS FOR DIALOG-BOX Dialog-Frame
   FRAME-NAME                                                           */
ASSIGN
       FRAME Dialog-Frame:SCROLLABLE       = FALSE
       FRAME Dialog-Frame:HIDDEN           = TRUE.

ASSIGN
       A-3:HIDDEN IN FRAME Dialog-Frame           = TRUE.

/* SETTINGS FOR FILL-IN a3 IN FRAME Dialog-Frame
   6                                                                    */
/* SETTINGS FOR FILL-IN a4-lansc IN FRAME Dialog-Frame
   5                                                                    */
/* SETTINGS FOR FILL-IN A4-port IN FRAME Dialog-Frame
   4                                                                    */
ASSIGN
       B-help:HIDDEN IN FRAME Dialog-Frame           = TRUE.

ASSIGN
       B-unmark:HIDDEN IN FRAME Dialog-Frame           = TRUE.

/* SETTINGS FOR FILL-IN FILL-IN-10 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-11 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-12 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-13 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-14 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-15 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-16 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-17 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-18 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-19 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-2 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-20 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-21 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-22 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-25 IN FRAME Dialog-Frame
   ALIGN-L                                                              */
/* SETTINGS FOR FILL-IN FILL-IN-26 IN FRAME Dialog-Frame
   ALIGN-L                                                              */
/* SETTINGS FOR FILL-IN FILL-IN-27 IN FRAME Dialog-Frame
   ALIGN-L                                                              */
/* SETTINGS FOR FILL-IN FILL-IN-28 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-29 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-3 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-30 IN FRAME Dialog-Frame
   ALIGN-L                                                              */
/* SETTINGS FOR FILL-IN FILL-IN-31 IN FRAME Dialog-Frame
   ALIGN-L                                                              */
/* SETTINGS FOR FILL-IN FILL-IN-32 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-39 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-4 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-40 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-41 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-42 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-43 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-44 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-45 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-46 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-47 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-48 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-49 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-5 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-50 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-51 IN FRAME Dialog-Frame
   ALIGN-L                                                              */
/* SETTINGS FOR FILL-IN FILL-IN-52 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-53 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-6 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-7 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-8 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
/* SETTINGS FOR FILL-IN FILL-IN-9 IN FRAME Dialog-Frame
   ALIGN-L 1                                                            */
ASSIGN
       only-text-exel:READ-ONLY IN FRAME Dialog-Frame        = TRUE.

/* SETTINGS FOR TOGGLE-BOX TOG-1 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-10 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-11 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-12 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-13 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-14 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-15 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-16 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-17 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-18 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-19 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-2 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-20 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-21 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-22 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-23 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-24 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-25 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-26 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-27 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-28 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-29 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-3 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-30 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-31 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-32 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-33 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-34 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-35 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-36 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-37 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-38 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-39 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-4 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-40 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-41 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-42 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-43 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-44 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-45 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-46 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-47 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-48 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-49 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-5 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-50 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-51 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-52 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-53 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-54 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-55 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-56 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-57 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-58 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-59 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-6 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-60 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-61 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-62 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-63 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-64 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-65 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-66 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-67 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-68 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-69 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-7 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-70 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-71 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-72 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-73 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-74 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-75 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-76 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-77 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-78 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-79 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-8 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-80 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-81 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-82 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-83 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-84 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-85 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-86 IN FRAME Dialog-Frame
   2                                                                    */
/* SETTINGS FOR TOGGLE-BOX TOG-87 IN FRAME Dialog-Frame
   2                                                                    */
/* SETTINGS FOR TOGGLE-BOX TOG-88 IN FRAME Dialog-Frame
   2                                                                    */
/* SETTINGS FOR TOGGLE-BOX TOG-89 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-9 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-90 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-91 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-92 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-93 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-94 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-95 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* SETTINGS FOR TOGGLE-BOX TOG-96 IN FRAME Dialog-Frame
   ALIGN-R 2                                                            */
/* _RUN-TIME-ATTRIBUTES-END */
&ANALYZE-RESUME





/* ************************  Control Triggers  ************************ */

&Scoped-define SELF-NAME Dialog-Frame
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL Dialog-Frame Dialog-Frame
ON WINDOW-CLOSE OF FRAME Dialog-Frame /* Выбор колонок для печати */
DO:
  APPLY "END-ERROR":U TO SELF.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME A-3
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL A-3 Dialog-Frame
ON CHOOSE OF A-3 IN FRAME Dialog-Frame /* A3 */
DO:
  Display {&list-6}  with frame {&frame-name}.
  Hide  {&list-4}  {&list-5}  only-file  in frame {&frame-name}.
  print-o = "A3-lansc":U.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME B-exit
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL B-exit Dialog-Frame
ON CHOOSE OF B-exit IN FRAME Dialog-Frame /* Ввод */
DO:
  define variable l-ind as integer no-undo .
  run eq-frame.

 find first ubflt.usr-flt share-lock
   where ubflt.usr-flt.user-name  = g#userid
     and ubflt.usr-flt.call-point = "e-obort1":U
   no-error .
 if NOT avail ubflt.usr-flt then  create ubflt.usr-flt.
 Assign
   ubflt.usr-flt.user-name = g#userid
   ubflt.usr-flt.call-point   = "e-obort1":U
   ubflt.usr-flt.list_ = "" .
   repeat l-ind = 1 to {&max-col} :
     if   use-column[ l-ind ] =  true then ubflt.usr-flt.list_ = ubflt.usr-flt.list_  + string( l-ind ) + "," .
   End.
   ubflt.usr-flt.list_ = ubflt.usr-flt.list_  + string( "print-o=" + print-o ) + ",prod-zen=" + string( prod-zen ) + "," .
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME B-mark
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL B-mark Dialog-Frame
ON CHOOSE OF B-mark IN FRAME Dialog-Frame /* Отметить * */
DO:
  Assign
   TOG-1:screen-value  in frame {&frame-name} = string( true  )
   TOG-2:screen-value  in frame {&frame-name} = string( true  )
   TOG-3:screen-value  in frame {&frame-name} = string( true  )
   TOG-4:screen-value  in frame {&frame-name} = string( true  )
   TOG-5:screen-value  in frame {&frame-name} = string( true  )
   TOG-6:screen-value  in frame {&frame-name} = string( true  )
   TOG-7:screen-value  in frame {&frame-name} = string( true  )
   TOG-8:screen-value  in frame {&frame-name} = string( true  )
   TOG-9:screen-value  in frame {&frame-name} = string( true  )
   TOG-10:screen-value in frame {&frame-name} = string( true  )
   TOG-11:screen-value in frame {&frame-name} = string( true  )
   TOG-12:screen-value in frame {&frame-name} = string( true  )
   TOG-13:screen-value in frame {&frame-name} = string( true  )
   TOG-14:screen-value in frame {&frame-name} = string( true  )
   TOG-15:screen-value in frame {&frame-name} = string( true  )
   TOG-16:screen-value in frame {&frame-name} = string( true  )
   TOG-17:screen-value in frame {&frame-name} = string( true  )
   TOG-18:screen-value in frame {&frame-name} = string( true  )
   TOG-19:screen-value in frame {&frame-name} = string( true  )
   TOG-20:screen-value in frame {&frame-name} = string( true  )
   TOG-21:screen-value in frame {&frame-name} = string( true )
   TOG-22:screen-value in frame {&frame-name} = string( true )
   TOG-23:screen-value in frame {&frame-name} = string( true )
   TOG-24:screen-value in frame {&frame-name} = string( true )
   TOG-25:screen-value in frame {&frame-name} = string( true )
   TOG-26:screen-value in frame {&frame-name} = string( true )
   TOG-27:screen-value in frame {&frame-name} = string( true )
   TOG-28:screen-value in frame {&frame-name} = string( true )
   TOG-29:screen-value in frame {&frame-name} = string( true )
   TOG-30:screen-value in frame {&frame-name} = string( true )
   TOG-31:screen-value  in frame {&frame-name} = string( true )
   TOG-32:screen-value  in frame {&frame-name} = string( true )
   TOG-33:screen-value  in frame {&frame-name} = string( true )
   TOG-34:screen-value  in frame {&frame-name} = string( true )
   TOG-35:screen-value  in frame {&frame-name} = string( true )
   TOG-36:screen-value  in frame {&frame-name} = string( true )
   TOG-37:screen-value  in frame {&frame-name} = string( true )
   TOG-38:screen-value  in frame {&frame-name} = string( true )
   TOG-39:screen-value  in frame {&frame-name} = string( true )
   TOG-40:screen-value  in frame {&frame-name} = string( true )
   TOG-41:screen-value  in frame {&frame-name} = string( true )
   TOG-42:screen-value  in frame {&frame-name} = string( true )
   TOG-43:screen-value  in frame {&frame-name} = string( true )
   TOG-44:screen-value  in frame {&frame-name} = string( true )
   TOG-45:screen-value  in frame {&frame-name} = string( true )
   TOG-46:screen-value  in frame {&frame-name} = string( true )
   TOG-47:screen-value  in frame {&frame-name} = string( true )
   TOG-48:screen-value  in frame {&frame-name} = string( true )
   TOG-49:screen-value  in frame {&frame-name} = string( true )
   TOG-50:screen-value  in frame {&frame-name} = string( true )
   TOG-51:screen-value  in frame {&frame-name} = string( true )
   TOG-52:screen-value  in frame {&frame-name} = string( true )
   TOG-53:screen-value  in frame {&frame-name} = string( true )
   TOG-54:screen-value  in frame {&frame-name} = string( true )
   TOG-55:screen-value  in frame {&frame-name} = string( true )
   TOG-56:screen-value  in frame {&frame-name} = string( true )
   TOG-57:screen-value  in frame {&frame-name} = string( true )
   TOG-58:screen-value  in frame {&frame-name} = string( true )
   TOG-59:screen-value  in frame {&frame-name} = string( true )
   TOG-60:screen-value  in frame {&frame-name} = string( true )
   TOG-61:screen-value  in frame {&frame-name} = string( true )
   TOG-62:screen-value  in frame {&frame-name} = string( true )
   TOG-63:screen-value  in frame {&frame-name} = string( true )
   TOG-64:screen-value  in frame {&frame-name} = string( true )
   TOG-65:screen-value  in frame {&frame-name} = string( true )
   TOG-66:screen-value  in frame {&frame-name} = string( true )
   TOG-67:screen-value  in frame {&frame-name} = string( true )
   TOG-68:screen-value  in frame {&frame-name} = string( true )
   TOG-69:screen-value  in frame {&frame-name} = string( true )
   TOG-70:screen-value  in frame {&frame-name} = string( true )
   TOG-71:screen-value  in frame {&frame-name} = string( true )
   TOG-72:screen-value  in frame {&frame-name} = string( true )
   TOG-73:screen-value  in frame {&frame-name} = string( true )
   TOG-74:screen-value  in frame {&frame-name} = string( true )
   TOG-75:screen-value  in frame {&frame-name} = string( true )
   TOG-76:screen-value  in frame {&frame-name} = string( true )
   TOG-77:screen-value  in frame {&frame-name} = string( true )
   TOG-78:screen-value  in frame {&frame-name} = string( true )
   TOG-79:screen-value  in frame {&frame-name} = string( true )
   TOG-80:screen-value  in frame {&frame-name} = string( true )
   TOG-81:screen-value  in frame {&frame-name} = string( true )
   TOG-82:screen-value  in frame {&frame-name} = string( true )
   TOG-83:screen-value  in frame {&frame-name} = string( true )
   TOG-84:screen-value  in frame {&frame-name} = string( true )
   TOG-85:screen-value  in frame {&frame-name} = string( true )
   TOG-86:screen-value  in frame {&frame-name} = string( true )
   TOG-87:screen-value  in frame {&frame-name} = string( true )
   TOG-88:screen-value  in frame {&frame-name} = string( true )
   TOG-89:screen-value  in frame {&frame-name} = string( true )
   TOG-90:screen-value  in frame {&frame-name} = string( true )
   TOG-91:screen-value  in frame {&frame-name} = string( true )
   TOG-92:screen-value  in frame {&frame-name} = string( true )
   TOG-93:screen-value  in frame {&frame-name} = string( true )
   TOG-94:screen-value  in frame {&frame-name} = string( true )
   TOG-95:screen-value  in frame {&frame-name} = string( true )
   TOG-96:screen-value  in frame {&frame-name} = string( true )

  .

  Display
     only-text-exel
     with frame {&frame-name}.
  Hide
  only-file
  a-3
  {&list-4}
  {&list-5}
  {&list-6}
  in frame {&frame-name}.
  print-o = "to-file":U.

END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME B-unmark
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL B-unmark Dialog-Frame
ON CHOOSE OF B-unmark IN FRAME Dialog-Frame /* Снять * */
DO:
  Assign
   TOG-1:screen-value  in frame {&frame-name} = string( false  )
   TOG-2:screen-value  in frame {&frame-name} = string( false  )
   TOG-3:screen-value  in frame {&frame-name} = string( false  )
   TOG-4:screen-value  in frame {&frame-name} = string( false  )
   TOG-5:screen-value  in frame {&frame-name} = string( false  )
   TOG-6:screen-value  in frame {&frame-name} = string( false  )
   TOG-7:screen-value  in frame {&frame-name} = string( false  )
   TOG-8:screen-value  in frame {&frame-name} = string( false  )
   TOG-9:screen-value  in frame {&frame-name} = string( false  )
   TOG-10:screen-value in frame {&frame-name} = string( false  )
   TOG-11:screen-value in frame {&frame-name} = string( false  )
   TOG-12:screen-value in frame {&frame-name} = string( false  )
   TOG-13:screen-value in frame {&frame-name} = string( false  )
   TOG-14:screen-value in frame {&frame-name} = string( false  )
   TOG-15:screen-value in frame {&frame-name} = string( false  )
   TOG-16:screen-value in frame {&frame-name} = string( false  )
   TOG-17:screen-value in frame {&frame-name} = string( false  )
   TOG-18:screen-value in frame {&frame-name} = string( false  )
   TOG-19:screen-value in frame {&frame-name} = string( false  )
   TOG-20:screen-value in frame {&frame-name} = string( false  )
   TOG-21:screen-value in frame {&frame-name} = string( false  )
   TOG-22:screen-value in frame {&frame-name} = string( false  )
   TOG-23:screen-value in frame {&frame-name} = string( false  )
   TOG-24:screen-value in frame {&frame-name} = string( false  )
   TOG-25:screen-value in frame {&frame-name} = string( false  )
   TOG-26:screen-value in frame {&frame-name} = string( false  )
   TOG-27:screen-value in frame {&frame-name} = string( false  )
   TOG-28:screen-value in frame {&frame-name} = string( false  )
   TOG-29:screen-value in frame {&frame-name} = string( false  )
   TOG-30:screen-value in frame {&frame-name} = string( false  )
   TOG-31:screen-value  in frame {&frame-name} = string( false  )
   TOG-32:screen-value  in frame {&frame-name} = string( false  )
   TOG-33:screen-value  in frame {&frame-name} = string( false  )
   TOG-34:screen-value  in frame {&frame-name} = string( false  )
   TOG-35:screen-value  in frame {&frame-name} = string( false  )
   TOG-36:screen-value  in frame {&frame-name} = string( false  )
   TOG-37:screen-value  in frame {&frame-name} = string( false  )
   TOG-38:screen-value  in frame {&frame-name} = string( false  )
   TOG-39:screen-value  in frame {&frame-name} = string( false  )
   TOG-40:screen-value in frame {&frame-name} = string( false  )
   TOG-41:screen-value  in frame {&frame-name} = string( false  )
   TOG-42:screen-value  in frame {&frame-name} = string( false  )
   TOG-43:screen-value  in frame {&frame-name} = string( false  )
   TOG-44:screen-value  in frame {&frame-name} = string( false  )
   TOG-45:screen-value  in frame {&frame-name} = string( false  )
   TOG-46:screen-value  in frame {&frame-name} = string( false  )
   TOG-47:screen-value  in frame {&frame-name} = string( false  )
   TOG-48:screen-value  in frame {&frame-name} = string( false  )
   TOG-49:screen-value  in frame {&frame-name} = string( false  )
   TOG-50:screen-value in frame {&frame-name} = string( false  )
   TOG-51:screen-value  in frame {&frame-name} = string( false  )
   TOG-52:screen-value  in frame {&frame-name} = string( false  )
   TOG-53:screen-value  in frame {&frame-name} = string( false  )
   TOG-54:screen-value  in frame {&frame-name} = string( false  )
   TOG-55:screen-value  in frame {&frame-name} = string( false  )
   TOG-56:screen-value  in frame {&frame-name} = string( false  )
   TOG-57:screen-value  in frame {&frame-name} = string( false  )
   TOG-58:screen-value  in frame {&frame-name} = string( false  )
   TOG-59:screen-value  in frame {&frame-name} = string( false  )
   TOG-60:screen-value in frame {&frame-name} = string( false  )
   TOG-61:screen-value  in frame {&frame-name} = string( false  )
   TOG-62:screen-value  in frame {&frame-name} = string( false  )
   TOG-63:screen-value  in frame {&frame-name} = string( false  )
   TOG-64:screen-value  in frame {&frame-name} = string( false  )
   TOG-65:screen-value  in frame {&frame-name} = string( false  )
   TOG-66:screen-value  in frame {&frame-name} = string( false  )
   TOG-67:screen-value  in frame {&frame-name} = string( false  )
   TOG-68:screen-value  in frame {&frame-name} = string( false  )
   TOG-69:screen-value  in frame {&frame-name} = string( false  )
   TOG-70:screen-value in frame {&frame-name} = string( false  )
   TOG-71:screen-value  in frame {&frame-name} = string( false  )
   TOG-72:screen-value  in frame {&frame-name} = string( false  )
   TOG-73:screen-value  in frame {&frame-name} = string( false  )
   TOG-74:screen-value  in frame {&frame-name} = string( false  )
   TOG-75:screen-value  in frame {&frame-name} = string( false  )
   TOG-76:screen-value  in frame {&frame-name} = string( false  )
   TOG-77:screen-value  in frame {&frame-name} = string( false  )
   TOG-78:screen-value  in frame {&frame-name} = string( false  )
   TOG-79:screen-value  in frame {&frame-name} = string( false  )
   TOG-80:screen-value in frame {&frame-name} = string( false  )
   TOG-81:screen-value  in frame {&frame-name} = string( false  )
   TOG-82:screen-value  in frame {&frame-name} = string( false  )
   TOG-83:screen-value  in frame {&frame-name} = string( false  )
   TOG-84:screen-value  in frame {&frame-name} = string( false  )
   TOG-85:screen-value  in frame {&frame-name} = string( false  )
   TOG-86:screen-value  in frame {&frame-name} = string( false  )
   TOG-87:screen-value  in frame {&frame-name} = string( false  )
   TOG-88:screen-value  in frame {&frame-name} = string( false  )
   TOG-89:screen-value  in frame {&frame-name} = string( false  )
   TOG-90:screen-value  in frame {&frame-name} = string( false  )
   TOG-91:screen-value  in frame {&frame-name} = string( false  )
   TOG-92:screen-value  in frame {&frame-name} = string( false  )
   TOG-93:screen-value  in frame {&frame-name} = string( false  )
   TOG-94:screen-value  in frame {&frame-name} = string( false  )
   TOG-95:screen-value  in frame {&frame-name} = string( false  )
   TOG-96:screen-value  in frame {&frame-name} = string( false  )
  .
  Display
  {&list-4}
  with frame {&frame-name}.

  hide
  only-text-exel
  only-file
  {&list-5}
  {&list-6}
  in frame {&frame-name}.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME RECT-18
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL RECT-18 Dialog-Frame
ON MOUSE-SELECT-CLICK OF RECT-18 IN FRAME Dialog-Frame
DO:

END.

ON VALUE-CHANGED OF {&List-2-t}
    IN FRAME Dialog-Frame
DO:
  RUN Show-format.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME RECT-19
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL RECT-19 Dialog-Frame
ON MOUSE-SELECT-CLICK OF RECT-19 IN FRAME Dialog-Frame
DO:

END.

ON VALUE-CHANGED OF {&List-2-t}
    IN FRAME Dialog-Frame
DO:
  RUN Show-format.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&Scoped-define SELF-NAME RECT-21
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CONTROL RECT-21 Dialog-Frame
ON MOUSE-SELECT-CLICK OF RECT-21 IN FRAME Dialog-Frame
DO:

END.

ON VALUE-CHANGED OF {&List-2-t}
    IN FRAME Dialog-Frame
DO:
  RUN Show-format.
END.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&UNDEFINE SELF-NAME

&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CUSTOM _MAIN-BLOCK Dialog-Frame


/* ***************************  Main Block  *************************** */
{ gbl/app_help.i }
IF VALID-HANDLE(ACTIVE-WINDOW) AND FRAME {&FRAME-NAME}:PARENT eq ?
THEN FRAME {&FRAME-NAME}:PARENT = ACTIVE-WINDOW.
define variable  all-empty  as integer no-undo init 0 .
define variable  ii  as integer no-undo init 0 .

if prod-zen = no then RADIO-SET-2 = 2 .
else RADIO-SET-2 = 1 .

repeat ii = 1 to {&max-col} :
  if use-column[ii ] then all-empty  = all-empty + 1 .
End.
 if all-empty =0 then
    apply "CHOOSE" TO B-mark IN FRAME Dialog-Frame.
 Else
 Assign
    TOG-1  = use-column[1 ]
    TOG-2  = use-column[2 ]
    TOG-3  = use-column[3 ]
    TOG-4  = use-column[4 ]
    TOG-5  = use-column[5 ]
    TOG-6  = use-column[6 ]
    TOG-7  = use-column[7 ]
    TOG-8  = use-column[8 ]
    TOG-9  = use-column[9 ]
    TOG-10 = use-column[10]
    TOG-11 = use-column[11]
    TOG-12 = use-column[12]
    TOG-13 = use-column[13]
    TOG-14 = use-column[14]
    TOG-15 = use-column[15]
    TOG-16 = use-column[16]
    TOG-17 = use-column[17]
    TOG-18 = use-column[18]
    TOG-19 = use-column[19]
    TOG-20 = use-column[20]
    TOG-21 = use-column[21]
    TOG-22 = use-column[22]
    TOG-23 = use-column[23]
    TOG-24 = use-column[24]
    TOG-25 = use-column[25]
    TOG-26 = use-column[26]
    TOG-27 = use-column[27]
    TOG-28 = use-column[28]
    TOG-29 = use-column[29]
    TOG-30 = use-column[30]
    TOG-31 = use-column[31]
    TOG-32 = use-column[32]
    TOG-33 = use-column[33]
    TOG-34 = use-column[34]
    TOG-35 = use-column[35]
    TOG-36 = use-column[36]
    TOG-37 = use-column[37]
    TOG-38 = use-column[38]
    TOG-39 = use-column[39]
    TOG-40 = use-column[40]
    TOG-41 = use-column[41]
    TOG-42 = use-column[42]
    TOG-43 = use-column[43]
    TOG-44 = use-column[44]
    TOG-45 = use-column[45]
    TOG-46 = use-column[46]
    TOG-47 = use-column[47]
    TOG-48 = use-column[48]
    TOG-49 = use-column[49]
    TOG-50 = use-column[50]
    TOG-51 = use-column[51]
    TOG-52 = use-column[52]
    TOG-53 = use-column[53]
    TOG-54 = use-column[54]
    TOG-55 = use-column[55]
    TOG-56 = use-column[56]
    TOG-57 = use-column[57]
    TOG-58 = use-column[58]
    TOG-59 = use-column[59]
    TOG-60 = use-column[60]
    TOG-61 = use-column[61]
    TOG-62 = use-column[62]
    TOG-63 = use-column[63]
    TOG-64 = use-column[64]
    TOG-65 = use-column[65]
    TOG-66 = use-column[66]
    TOG-67 = use-column[67]
    TOG-68 = use-column[68]
    TOG-69 = use-column[69]
    TOG-70 = use-column[70]
    TOG-71 = use-column[71]
    TOG-72 = use-column[72]
    TOG-73 = use-column[73]
    TOG-74 = use-column[74]
    TOG-75 = use-column[75]
    TOG-76 = use-column[76]
    TOG-77 = use-column[77]
    TOG-78 = use-column[78]
    TOG-79 = use-column[79]
    TOG-80 = use-column[80]
    TOG-81 = use-column[81]
    TOG-82 = use-column[82]
    TOG-83 = use-column[83]
    TOG-84 = use-column[84]
    TOG-85 = use-column[85]
    TOG-86 = use-column[86]
    TOG-87 = use-column[87]
    TOG-88 = use-column[88]
    TOG-89 = use-column[89]
    TOG-90 = use-column[90]
    TOG-91 = use-column[91]
    TOG-92 = use-column[92]
    TOG-93 = use-column[93]
    TOG-94 = use-column[94]
    TOG-95 = use-column[95]
    TOG-96 = use-column[96]

  .

  Assign
  s-column[1 ] =  9
  s-column[2 ] =  16
  s-column[3 ] =  38
  s-column[4 ] =  3
  s-column[5 ] =  10
  s-column[6 ] =  10
  s-column[7 ] =  10
  s-column[8 ] =  10
  s-column[9 ] =  10
  s-column[10] =  14
  s-column[11] =  10
  s-column[12] =  14
  s-column[13] =  14
  s-column[14] =  14
  s-column[15] =  14
  s-column[16] =  14
  s-column[17] =  14
  s-column[18] =  14
  s-column[19] =  14
  s-column[20] =  14
  s-column[21] =  14
  s-column[22] =  14
  s-column[23] =  14
  s-column[24] =  14
  s-column[25] =  14
  s-column[26] =  14
  s-column[27] =  14
  s-column[28] =  14
  s-column[29] =  14
  s-column[30] =  14
  s-column[31] =  14
  s-column[32] =  14
  s-column[33] =  14
  s-column[34] =  14
  s-column[35] =  14
  s-column[36] =  14
  s-column[37] =  14
  s-column[38] =  14
  s-column[39] =  14
  s-column[40] =  14
  s-column[41] =  14
  s-column[42] =  14
  s-column[43] =  14
  s-column[44] =  14
  s-column[45] =  14
  s-column[46] =  14
  s-column[47] =  14
  s-column[48] =  14
  s-column[49] =  14
  s-column[50] =  14
  s-column[51] =  14
  s-column[52] =  14
  s-column[53] =  14
  s-column[54] =  14
  s-column[55] =  14
  s-column[56] =  14
  s-column[57] =  14
  s-column[58] =  14
  s-column[59] =  14
  s-column[60] =  14
  s-column[61] =  14
  s-column[62] =  14
  s-column[63] =  14
  s-column[64] =  14
  s-column[65] =  14
  s-column[66] =  14
  s-column[67] =  14
  s-column[68] =  14
  s-column[69] =  14
  s-column[70] =  14
  s-column[71] =  14
  s-column[72] =  14
  s-column[73] =  14
  s-column[74] =  14
  s-column[75] =  14
  s-column[76] =  14
  s-column[77] =  14
  s-column[78] =  14
  s-column[79] =  14
  s-column[80] =  14
  s-column[81] =  14
  s-column[82] =  14
  s-column[83] =  14
  s-column[84] =  14
  s-column[85] =  14
  s-column[86] =  14
  s-column[87] =  14
  s-column[88] =  14
  s-column[89] =  14
  s-column[90] =  14
  s-column[91] =  14
  s-column[92] =  14
  s-column[93] =  14
  s-column[94] =  14
  s-column[95] =  14
  s-column[96] =  14
  s-column[97] =  14
  s-column[98] =  14
  s-column[99] =  14
  s-column[100] =  14
    s-column[101] =  14
    s-column[102] =  14
    s-column[103] =  14
    s-column[104] =  14
    s-column[105] =  14
    s-column[106] =  14
    s-column[107] =  14
    s-column[108] =  14
    s-column[109] =  14
    s-column[110] =  14
    s-column[111] =  14
    s-column[112] =  14
    s-column[113] =  14
    s-column[114] =  14
    s-column[115] =  14
    s-column[116] =  14
    s-column[117] =  14
    s-column[118] =  14
    s-column[119] =  14
    s-column[120] =  14

  .

/* Now enable the interface and wait for the exit condition.            */
/* (NOTE: handle ERROR and END-KEY so cleanup code will always fire.    */
MAIN-BLOCK:
DO ON ERROR   UNDO MAIN-BLOCK, LEAVE MAIN-BLOCK
   ON END-KEY UNDO MAIN-BLOCK, LEAVE MAIN-BLOCK:
  RUN enable_UI.

  define variable Log-Res1 as logical   no-undo .
  define variable Log-Res2 as logical   no-undo .
  { gbl/chk-actg.i
    v-cntxt-db-num
    v-cntxt-userid
    {&action-head-code-main}
    'actn_reports_lookup-cost':U
    {&cntxt-object}
    v-cntxt-host-code-obj
    v-cntxt-obj-type
    v-cntxt-obj-code
    0
    0
    0
    yes
    Log-Res1
  }
  if not Log-Res1 then do:
    DISABLE
      TOG-31 TOG-32 TOG-33 TOG-34 TOG-35 TOG-36 TOG-37 TOG-38 TOG-39 TOG-40 TOG-41
      TOG-42 TOG-43 TOG-44 TOG-45 TOG-46 TOG-47 TOG-48 TOG-49 TOG-87 TOG-90 TOG-93
      TOG-68 TOG-69 TOG-70 TOG-71 TOG-72 TOG-73 TOG-74 TOG-75 TOG-76 TOG-77 TOG-78 TOG-79
      TOG-80 TOG-81 TOG-82 TOG-83 TOG-84 TOG-85 TOG-95 TOG-96
    WITH FRAME {&FRAME-NAME}.
  end.

/*    'actn_document-reports-sale_print':U*/

  { gbl/chk-actg.i
    v-cntxt-db-num
    v-cntxt-userid
    {&action-head-code-main}
    'actn_reports_lookup-crsa':U
    {&cntxt-object}
    v-cntxt-host-code-obj
    v-cntxt-obj-type
    v-cntxt-obj-code
    0
    0
    0
    yes
    Log-Res2
  }
  if not Log-Res2 then do:
    DISABLE
      TOG-31 TOG-32 TOG-33 TOG-34 TOG-35 TOG-36 TOG-37 TOG-38 TOG-39 TOG-40 TOG-41
      TOG-42 TOG-43 TOG-44 TOG-45 TOG-46 TOG-47 TOG-48 TOG-49 TOG-87 TOG-90 TOG-93
      TOG-68 TOG-69 TOG-70 TOG-71 TOG-72 TOG-73 TOG-74 TOG-75 TOG-76 TOG-77 TOG-78 TOG-79
      TOG-80 TOG-81 TOG-82 TOG-83 TOG-84 TOG-85 TOG-95 TOG-96
    WITH FRAME {&FRAME-NAME}.
  end.



  if p-type = 1 then do: /* по признакам */
     disable tog-89 tog-90 tog-91 tog-92 tog-93 tog-94 tog-95 tog-96 with frame {&frame-name}.
  end.
  if p-type = 3  then do: /* по партиям */
     disable tog-89 tog-90 tog-91 tog-92 tog-93 tog-94 tog-95 tog-96 radio-set-2 with frame {&frame-name}.
  end.

  RUN Show-format.
  WAIT-FOR GO OF FRAME {&FRAME-NAME}.
END.
RUN disable_UI.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


/* **********************  Internal Procedures  *********************** */

&ANALYZE-SUSPEND _UIB-CODE-BLOCK _PROCEDURE disable_UI Dialog-Frame  _DEFAULT-DISABLE
PROCEDURE disable_UI :
/*------------------------------------------------------------------------------
  Purpose:     DISABLE the User Interface
  Parameters:  <none>
  Notes:       Here we clean-up the user-interface by deleting
               dynamic widgets we have created and/or hide
               frames.  This procedure is usually called when
               we are ready to "clean-up" after running.
------------------------------------------------------------------------------*/
  /* Hide all frames. */
  HIDE FRAME Dialog-Frame.
END PROCEDURE.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME

&ANALYZE-SUSPEND _UIB-CODE-BLOCK _PROCEDURE enable_UI Dialog-Frame  _DEFAULT-ENABLE
PROCEDURE enable_UI :
/*------------------------------------------------------------------------------
  Purpose:     ENABLE the User Interface
  Parameters:  <none>
  Notes:       Here we display/view/enable the widgets in the
               user-interface.  In addition, OPEN all queries
               associated with each FRAME and BROWSE.
               These statements here are based on the "Other
               Settings" section of the widget Property Sheets.
------------------------------------------------------------------------------*/
  DISPLAY TOG-1 TOG-12 TOG-31 TOG-50 TOG-2 TOG-13 TOG-51 TOG-32 TOG-3 TOG-89
          TOG-90 TOG-91 TOG-4 TOG-92 TOG-93 TOG-94 TOG-95 TOG-96 TOG-5 TOG-6
          TOG-14 TOG-33 RADIO-SET-2 TOG-15 TOG-34 TOG-7 TOG-16 TOG-35 TOG-52
          TOG-68 TOG-77 TOG-8 TOG-17 TOG-36 TOG-53 TOG-69 TOG-78 TOG-9 TOG-18
          TOG-37 TOG-54 TOG-70 TOG-79 TOG-10 TOG-19 TOG-55 TOG-71 TOG-80 TOG-38
          TOG-11 TOG-20 TOG-56 TOG-72 TOG-82 TOG-39 TOG-73 TOG-21 TOG-40 TOG-57
          TOG-81 TOG-58 TOG-74 TOG-83 TOG-22 TOG-41 TOG-42 TOG-59 TOG-75 TOG-84
          TOG-23 TOG-24 TOG-60 TOG-76 TOG-85 TOG-43 TOG-25 TOG-61 TOG-44 TOG-26
          TOG-45 TOG-62 TOG-46 TOG-27 TOG-63 TOG-47 TOG-28 TOG-64 TOG-48 TOG-29
          TOG-65 TOG-30 TOG-66 TOG-49 only-text-exel TOG-86 TOG-87 TOG-88 TOG-67
          FILL-IN-40 FILL-IN-43 FILL-IN-44 FILL-IN-39 FILL-IN-47 FILL-IN-41
          FILL-IN-42 FILL-IN-45 FILL-IN-46 FILL-IN-2 FILL-IN-25 FILL-IN-3
          FILL-IN-26 FILL-IN-4 FILL-IN-27 FILL-IN-52 FILL-IN-28 FILL-IN-53
          FILL-IN-32 FILL-IN-5 FILL-IN-48 FILL-IN-6 FILL-IN-7 FILL-IN-50
          FILL-IN-8 FILL-IN-29 FILL-IN-9 FILL-IN-49 FILL-IN-10 FILL-IN-30
          FILL-IN-11 FILL-IN-31 FILL-IN-12 FILL-IN-13 FILL-IN-14 FILL-IN-15
          FILL-IN-16 FILL-IN-17 FILL-IN-18 FILL-IN-19 FILL-IN-20 FILL-IN-21
          FILL-IN-51 F-col-size FILL-IN-22 FILL-IN-23 a3 A4-port a4-lansc
          only-file FILL-IN-24
      WITH FRAME Dialog-Frame.
  ENABLE B-quit B-exit B-mark B-unmark B-help RECT-21 RECT-18 RECT-19 RECT-20
         TOG-1 TOG-12 TOG-31 TOG-50 TOG-2 TOG-13 TOG-51 TOG-32 TOG-3 TOG-89
         TOG-90 TOG-91 TOG-4 TOG-92 TOG-93 TOG-94 TOG-95 TOG-96 TOG-5 TOG-6
         TOG-14 TOG-33 RADIO-SET-2 TOG-15 TOG-34 TOG-7 TOG-16 TOG-35 TOG-52
         TOG-68 TOG-77 TOG-8 TOG-17 TOG-36 TOG-53 TOG-69 TOG-78 TOG-9 TOG-18
         TOG-37 TOG-54 TOG-70 TOG-79 TOG-10 TOG-19 TOG-55 TOG-71 TOG-80 TOG-38
         TOG-11 TOG-20 TOG-56 TOG-72 TOG-82 TOG-39 TOG-73 TOG-21 TOG-40 TOG-57
         TOG-81 TOG-58 TOG-74 TOG-83 TOG-22 TOG-41 TOG-42 TOG-59 TOG-75 TOG-84
         TOG-23 TOG-24 TOG-60 TOG-76 TOG-85 TOG-43 TOG-25 TOG-61 TOG-44 TOG-26
         TOG-45 TOG-62 TOG-46 TOG-27 TOG-63 TOG-47 TOG-28 TOG-64 TOG-48 TOG-29
         TOG-65 TOG-30 TOG-66 TOG-49 only-text-exel TOG-86 TOG-87 TOG-88 TOG-67
         A-3 FILL-IN-40 FILL-IN-43 FILL-IN-44 FILL-IN-39 FILL-IN-47 FILL-IN-41
         FILL-IN-42 FILL-IN-45 FILL-IN-46 FILL-IN-2 FILL-IN-25 FILL-IN-3
         FILL-IN-26 FILL-IN-4 FILL-IN-27 FILL-IN-52 FILL-IN-28 FILL-IN-53
         FILL-IN-32 FILL-IN-5 FILL-IN-48 FILL-IN-6 FILL-IN-7 FILL-IN-50
         FILL-IN-8 FILL-IN-29 FILL-IN-9 FILL-IN-49 FILL-IN-10 FILL-IN-30
         FILL-IN-11 FILL-IN-31 FILL-IN-12 FILL-IN-13 FILL-IN-14 FILL-IN-15
         FILL-IN-16 FILL-IN-17 FILL-IN-18 FILL-IN-19 FILL-IN-20 FILL-IN-21
         FILL-IN-51 F-col-size FILL-IN-22 FILL-IN-23 a3 A4-port a4-lansc
         only-file FILL-IN-24
      WITH FRAME Dialog-Frame.
  VIEW FRAME Dialog-Frame.
  {&OPEN-BROWSERS-IN-QUERY-Dialog-Frame}
END PROCEDURE.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME

&ANALYZE-SUSPEND _UIB-CODE-BLOCK _PROCEDURE Show-format Dialog-Frame
PROCEDURE Show-format :
define variable ij as integer no-undo .
  run eq-frame.
  col-size = 0.

  repeat ij = 1 to {&max-col} :
    if use-column[ij] then col-size = col-size + s-column[ij] + 1 .
  End.

  F-col-size:screen-value in frame {&frame-name} = string( col-size).
  F-col-size = string(col-size).
  Display F-col-size with frame {&frame-name}.

  If col-size >= 1 and col-size <= 136 Then DO:
    Display {&list-4} a-3  with frame {&frame-name}.
    Hide {&list-5} {&list-6} only-file only-text-exel in frame {&frame-name}.
    print-o = "A4-port":U.
  End.

  If col-size > 136 and col-size <= 198 Then DO:
    Display  {&list-5} a-3  with frame {&frame-name}.
    Hide {&list-4} {&list-6} only-file only-text-exel in frame {&frame-name}.
    print-o = "A4-lansc":U.
  End.

  If col-size > 198 and col-size <= 235 Then DO:
    Display {&list-6} a-3  with frame {&frame-name}.
    Hide {&list-4} {&list-5} only-text-exel  only-file in frame {&frame-name}.
    print-o = "A3-lansc":U.
  End.

  If col-size > 235 Then DO:
    Display only-file a-3 with frame {&frame-name}.
    Hide {&list-4} {&list-5} {&list-6} only-text-exel in frame {&frame-name}.
    print-o = "to-file":U.
  End.

  If col-size > 550 Then DO:
    Display  only-text-exel  with frame {&frame-name}.
    Hide only-file a-3 {&list-4} {&list-5} {&list-6} in frame {&frame-name}.
    print-o = "to-file":U.
  End.

END PROCEDURE.

procedure eq-frame:
  Assign frame {&frame-name}  {&list-2} .
  Assign RADIO-SET-2.

  if RADIO-SET-2 = 1 then prod-zen = yes .
  else prod-zen = no .

  Assign
  use-column[1 ] =  TOG-1
  use-column[2 ] =  TOG-2
  use-column[3 ] =  TOG-3
  use-column[4 ] =  TOG-4
  use-column[5 ] =  TOG-5
  use-column[6 ] =  TOG-6
  use-column[7 ] =  TOG-7
  use-column[8 ] =  TOG-8
  use-column[9 ] =  TOG-9
  use-column[10] =  TOG-10
  use-column[11] =  TOG-11
  use-column[12] =  TOG-12
  use-column[13] =  TOG-13
  use-column[14] =  TOG-14
  use-column[15] =  TOG-15
  use-column[16] =  TOG-16
  use-column[17] =  TOG-17
  use-column[18] =  TOG-18
  use-column[19] =  TOG-19
  use-column[20] =  TOG-20
  use-column[21] =  TOG-21
  use-column[22] =  TOG-22
  use-column[23] =  TOG-23
  use-column[24] =  TOG-24
  use-column[25] =  TOG-25
  use-column[26] =  TOG-26
  use-column[27] =  TOG-27
  use-column[28] =  TOG-28
  use-column[29] =  TOG-29
  use-column[30] =  TOG-30
  use-column[31] =  TOG-31
  use-column[32] =  TOG-32
  use-column[33] =  TOG-33
  use-column[34] =  TOG-34
  use-column[35] =  TOG-35
  use-column[36] =  TOG-36
  use-column[37] =  TOG-37
  use-column[38] =  TOG-38
  use-column[39] =  TOG-39
  use-column[40] =  TOG-40
  use-column[41] =  TOG-41
  use-column[42] =  TOG-42
  use-column[43] =  TOG-43
  use-column[44] =  TOG-44
  use-column[45] =  TOG-45
  use-column[46] =  TOG-46
  use-column[47] =  TOG-47
  use-column[48] =  TOG-48
  use-column[49] =  TOG-49
  use-column[50] =  TOG-50
  use-column[51] =  TOG-51
  use-column[52] =  TOG-52
  use-column[53] =  TOG-53
  use-column[54] =  TOG-54
  use-column[55] =  TOG-55
  use-column[56] =  TOG-56
  use-column[57] =  TOG-57
  use-column[58] =  TOG-58
  use-column[59] =  TOG-59
  use-column[60] =  TOG-60
  use-column[61] =  TOG-61
  use-column[62] =  TOG-62
  use-column[63] =  TOG-63
  use-column[64] =  TOG-64
  use-column[65] =  TOG-65
  use-column[66] =  TOG-66
  use-column[67] =  TOG-67
  use-column[68] =  TOG-68
  use-column[69] =  TOG-69
  use-column[70] =  TOG-70
  use-column[71] =  TOG-71
  use-column[72] =  TOG-72
  use-column[73] =  TOG-73
  use-column[74] =  TOG-74
  use-column[75] =  TOG-75
  use-column[76] =  TOG-76
  use-column[77] =  TOG-77
  use-column[78] =  TOG-78
  use-column[79] =  TOG-79
  use-column[80] =  TOG-80
  use-column[81] =  TOG-81
  use-column[82] =  TOG-82
  use-column[83] =  TOG-83
  use-column[84] =  TOG-84
  use-column[85] =  TOG-85
  use-column[86] =  TOG-86
  use-column[87] =  TOG-87
  use-column[88] =  TOG-88
  use-column[89] =  TOG-89
  use-column[90] =  TOG-90
  use-column[91] =  TOG-91
  use-column[92] =  TOG-92
  use-column[93] =  TOG-93
  use-column[94] =  TOG-94
  use-column[95] =  TOG-95
  use-column[96] =  TOG-96

  .
end procedure.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME
