/*

$Revision: 992a74a9441b, 3581, rls $
$Author: VSpiridonov $
$Date: 2023/12/14 13:36:13 $
$Workfile: load-doc.i $
$Archive: rep/load-doc.i $

Список форм печати

Автор: Демин Алексей Сергеевич
Дата создания: 03/20/06
Author: Alexey Demin
Creation date: 03/20/06

Required:

*/

&scoped-define vssseq {&sequence}
define variable vss-include-info{&vssseq} as character format "X(65)" no-undo
initial "@(#)$Workfile: load-doc.i $ $Revision: 992a74a9441b, 3581, rls $".
/*
1 типы документов type-doc      * -это все
2 Статусы документов Status_    * -это все
3 Internal документов           * -это все
4 Flag документов               * -это все

5 Уникальный !!! номер отчета    int ! ! !
6 Номер следования в меню      int
7 Название в меню              char
8 строка в которой указана каким бывает документ    char
9 Вызов программы              char
10 Дополнительные параметры вызова процедуры помимо recid(trn-doc)
11 список syskey ('' и  'IBS' - виден)
12 формат страницы
     'A3port'
     'A3lans'
     'A4port'
     'A4lans' - по умолчанию
     self - своя печать
     EXCEL - вывод в excel

  типы цен   cost  - учетная;
             sale  - документа;
             crsa  - продажная;
   типы валют    rubl
                 base
 Пример  "'cost,sale,rubl,base,scale'"
13 список syskey, для которых НЕ нужно печатать форму
*/

define variable is-ptrl  as character no-undo .
define variable is-jwlr  as character no-undo .
define variable par-type as character no-undo .
run gbl/conf-rd.p ("is-ptrl", "", "", 0, "", "", "", no, output is-ptrl, output par-type) no-error.
if error-status :error
  or par-type <> "l"
  or is-ptrl  <> "yes"
then do:
  assign is-ptrl = "no".
end.
run gbl/conf-rd.p ("is-jwlr", "", "", 0, "", "", "", no, output is-jwlr, output par-type) no-error.
if error-status :error
  or par-type <> "l"
  or is-jwlr  <> "yes"
then do:
  assign is-jwlr = "no".
end.


/*-РАСХОДЫ-----------------------------------------------------------------------------------------------------------------------------------------------------------------*/
/*1-29 */
{ rep/menu-doc.i {&expense_return} "'*'" "'*'" "'*'"                                            "'Расходная накладная (с упаковками)'"                          "'cost,sale,rubl,base'"   "'rep/r-outretu.p'"  "'no'"                          "'-++++++-'"  "''"               "'A4port'"  "''"                   ? }
{ rep/menu-doc.i {&expense_return} "'*'" "'yes'" "'*'"                                          "'Накладная расхода (короткая форма)'"                          "'cost,sale,rubl,base'"   "'rep/r-outret.p'"   "'no,no'"                          "'-++++++-'"  "''"               "'A4port'"  "''"                   ? }
{ rep/menu-doc.i {&expense_return} "'*'" "'yes'" "'*'"                                          "'Накладная расхода (Аптека)'"                                  "'cost,sale,rubl,base'"   "'rep/r-outrta.p'"   "'no'"                          "'-++++++-'"  "'ODIS'"           "'A4port'"  "''"                   ? }
{ rep/menu-doc.i {&expense_return} "'*'" "'yes'" "'*'"                                          "'Накладная ТАМОЖНЯ (короткая форма)'"                          "'cost,sale,rubl,base'"   "'rep/r-outrec.p'"   "'no'"                          "'-++++++-'"  "''"               "''"        "''"                   ? }
{ rep/menu-doc.i {&expense} {&permitted} "'*'" "'*'"                                            "'Список на отгрузку'"                                          "'cost,sale,rubl,base'"   "'rep/load-lst.w'"   "''"                            "'--------'"  "''"               "''"        "''"                   ? }
{ rep/menu-doc.i {&expense} "'*'" "'*'" "'*'"                                                   "'Возвратная накладная Румыния'"                                "'cost,sale,rubl,base'"   in-docprvalue        "''"                            "'--------'"  "''"               "''"        "''"                   ? }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'*'" "'*'"              "'ТН Приложение № 4 (Бизнес-Букет)'"                            "'cost,sale,rubl,base'"   "'rep/r-f_t1.p'"     "'no,TopAukc,no'"               "'---+----'"  "'TopAukc'"        "''"        "''"                                  ? }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'*'" "'*'"              "'ТН Приложение № 4'"                                           "'cost,sale,rubl,base'"   "'rep/r-f_t1.p'"     "'no,all,no'"                   "'-+-+----'"  "''"               "''"        "'mag,Mari,iab,ng,Rosneft-Moscow'"    ? }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'*'" "'*'"              "'Типовая межотраслевая форма № 1-Т (Бизнес-Букет)'"            "'cost,sale,rubl,base'"   "'rep/r-ft1old.p'"   "'no,TopAukc,no-round,no,no'"   "'---+----'"  "'TopAukc'"        "''"        "''"                                  ? }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'*'" "'*'"              "'Типовая межотраслевая форма № 1-Т'"                           "'cost,sale,rubl,base'"   "'rep/r-ft1old.p'"   "'no,all,no-round,no,no'"       "'-++++++-'"  "''"               "''"        "'mag,Mari,iab,ng,Rosneft-Moscow'"    ? }
{ rep/menu-doc.i {&expense} "'*'" "'*'" "'*'"                                                   "'Документ ТОРГ12 (Бизнес-Букет)'"                              "'cost,sale,rubl,base'"   "'rep/torg-12.p'"    "'no,TopAukc;Vnesh_art,no-round,no,no'"   "'-++++++-'"  "'TopAukc'"        "''"        "''"                   ? }
{ rep/menu-doc.i {&expense} "'*'" "'*'" "'*'"                                                   "'Документ ТОРГ12 ГТД (Бизнес-Букет)'"                          "'cost,sale,rubl,base'"   "'rep/torg-12.p'"    "'no,TopAukc;GTD,no-round,no,no'"  "'-+-++++-'"  "'TopAukc'"     "''"        "''"                                  ? }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'*'" "'*'"              "'Документ ТОРГ12'"                                             "'cost,sale,rubl,base'"   "'rep/torg-12.p'"    "'no,all,no-round,no,no'"       "'-++++++-'"  "''"               "''"        "'mag,Mari,iab,ng,Rosneft-Moscow'"    ? }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'*'" "'*'"              "'Документ ТОРГ12'"                                             "'cost,sale,rubl,base'"   "'rep/torg-12.p'"    "'no,KEDR,no-round,no,no'"      "'-++++++-'"  "'Rosneft-Moscow'" "''"        "''"                                  ? }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'*'" "'*'"              "'Документ ТОРГ12 обратная'"                                    "'cost,sale,rubl,base'"   "'rep/torg-12.p'"    "'no,all,no-round,no,yes'"      "'-++++++-'"  "''"               "''"        "'mag,Mari,iab,ng'"   ? }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'no'" "'*'"             "'Топливная накладная'"                                         "'cost,sale,rubl,base'"   "'rep/torg-12p.p'"   "''"                            "'---+++--'"  "''"               "''"        "''"                   "is-ptrl = 'yes'" }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'no'" "'*'"             "'Документ ТОРГ12'"                                             "'cost,sale,rubl,base'"   "'rep/torg-12.p'"    "'no,mag,no-round,no,no'"       "'-++++++-'"  "'mag'"            "''"        "''"                  ? }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'no'" "'*'"             "'Документ ТОРГ12'"                                             "'cost,sale,rubl,base'"   "'rep/torg-12.p'"    "'no,Mari,no-round,no,no'"      "'-++++++-'"  "'Mari'"           "''"        "''"                  ? }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'*'" "'*'"              "'Документ ТОРГ12'"                                             "'cost,sale,rubl,base'"   "'rep/torg-12.p'"    "'no,iab,no-round,no,no'"       "'-++++++-'"  "'IAB'"            "''"        "''"                  ? }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'no'" "'*'"             "'Документ ТОРГ12'"                                             "'cost,sale,rubl,base'"   "'rep/torg-12.p'"    "'no,ng,no-round,no,no'"        "'-++++++-'"  "'NG'"             "''"        "''"                  ? }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'no'" "'*'"             "'Документ ТОРГ12 по чекам'"                                    "'cost,sale,rubl,base'"   "'rep/torg-12.p'"    "'no,all,no-round,yes,no'"      "'-++++++-'"  "''"               "''"        "''"                  ? }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'no'" "'*'"             "'Документ ТОРГ12 по складским местам'"                         "'cost,sale,rubl,base'"   "'rep/torg12pl.p'"   "'all'"                         "'-+-+----'"  "'IBS'"            "''"        "'mag'"               ? }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'no'" "'*'"             "'Документ ТОРГ12 по складским местам'"                         "'cost,sale,rubl,base'"   "'rep/torg12pl.p'"   "'mag'"                         "'-+-+----'"  "'IBSmag'"         "''"        "''"                  ? }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'no'" "'*'"             "'Документ ТОРГ12 с округлением'"                               "'cost,sale,rubl,base'"   "'rep/torg-12.p'"    "'no,all,round,no,no'"          "'-++++++-'"  "''"               "''"        "'mag,Mari'"          ? }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'no'" "'*'"             "'Документ ТОРГ12 с округлением'"                               "'cost,sale,rubl,base'"   "'rep/torg-12.p'"    "'no,mag,round,no,no'"          "'-++++++-'"  "'mag'"            "''"        "''"                  ? }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'no'" "'*'"             "'Документ ТОРГ12 с округлением'"                               "'cost,sale,rubl,base'"   "'rep/torg-12.p'"    "'no,Mari,round,no,no'"         "'-++++++-'"  "'Mari'"           "''"        "''"                  ? }
{ rep/menu-doc.i {&expense} "'*'" "'*'" "'*'"                                                   "'Упаковочный лист поставщика'"                                 "'cost,sale,rubl,base'"   "'rep/pack-list.p'"  "''"                            "'--------'"  "''"                 "'EXCEL'"   "''"                           	   ? }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'no'" "'*'"             "'Накладная с артикулом поставщика'"                            "'cost,sale,rubl,base'"   "'rep/t12-art.p'"    "''"                            "'-+++++--'"  "''"               "''"        "''"                  ? }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'*'" "'*'"              "'Список сертификатов к накладной'"                             "'cost,sale,rubl,base'"   "'rep/r-sert.p'"     "''"                            "'--------'"  "''"               "''"        "''"                  ? }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'*'" "'*'"              "'Список сертификатов к накладной (расширенный)'"               "'cost,sale,rubl,base'"   "'rep/r-sert1.p'"    "''"                            "'--------'"  "''"               "''"        "''"                  ? }
{ rep/menu-doc.i {&expense_return} "'*'" "'yes'" "'*'"                                          "'Документ ТОРГ13'"                                             "'cost,sale,rubl,base'"   "'rep/torg-13.p'"    "'no,no,no'"                    "'++++++++'"  "''"               "''"        "'zum'"               ? }
{ rep/menu-doc.i {&expense_return} "'*'" "'yes'" "'*'"                                          "'Документ внутреннего перемещения'"                            "'cost,sale,rubl,base'"   "'rep/torg-13x.p'"   "'no,no,no'"                    "'-+++++--'"  "'iab,NG,Statir'"  "'HTML'"  "''"                  ? }
{ rep/menu-doc.i {&expense_return} "'*'" "'yes'" "'*'"                                          "'Документ внутреннего перемещения с фото товара'"              "'cost,sale,rubl,base'"   "'rep/torg-13x-foto.p'"   "'no,no,no'"               "'-+++++--'"  "''"                 "'HTML'"  "''"                  ? }
{ rep/menu-doc.i {&expense_return} "'*'" "'yes'" "'*'"                                          "'Документ  ТОРГ13'"                                            "'cost,sale,rubl,base'"   "'rep/torg-13.p'"    "'no,yes,no'"                   "'++++++++'"  "'zum'"            "''"        "''"                  ? }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'yes'" "'*'"            "'Документ ТОРГ13 для ювелирных изделий'"                       "'cost,sale,rubl,base'"   "'rep/torg-13.p'"    "'yes,yes,yes'"                 "'++++++--'"  "'zum'"            "''"        "''"                  ? }
{ rep/menu-doc.i {&write-off} "'*'" "'no'" "'*'"                                                "'Документ Списания ТОРГ16'"                                    "'cost,sale,rubl,base'"   "'rep/torg-16.p'"    "''"                            "'-+++--++'"  "''"               "''"        "''"                  ? }
{ rep/menu-doc.i {&write-off} {&fact} "'no'" "'*'"                                              "'Документ Списания ТОРГ15'"                                    "'cost,rubl,base'"        "'rep/torg-15.p'"    "''"                            "'-------'"  "''"                 "'HTML'"    "''"                                  ? }
{ rep/menu-doc.i {&write-off} {&fact} "'no'" "'*'"                                              "'АКТ учета НП при выполнении ремонтных работ'"                 "'cost,rubl,base'"        "'rep/akt-np-make.p'"    "''"                            "'-------'"  "''"                 "'HTML'"    "''"                                  ? }
{ rep/menu-doc.i {&expense_write-off_return} {&fact_permitted_wayb_manufactured} "'*'" "'*'"    "'Спецификация по партиям к документу'"                         "'cost,sale,rubl,base'"   "'rep/r-specif.p'"   "'no'"                          "'--------'"  "''"               "''"        "'world'"             ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'*'" "'*'"                     "'Счет-фактура (формат 2011г.)'"                                "'cost,sale,rubl,base'"   "'rep/r-sf-old.p'"   "'no,all,no-round,no,no'"       "'-+++--+-'"  "''"               "''"        "'GreenL,zum'"        ? }
{ rep/menu-doc.i {&expense_return} {&fact}                      "'*'" "'*'"                     "'Корректировочный счет-фактура в ред. от 19.08.2017'"          "'cost,sale,rubl,base'"   "'rep/r-factur.p'"   "'no,corr,no-round,no,no'"      "'-+++--+-'"  "''"               "''"        "''"                  ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'*'" "'*'"                     "'Счет-фактура в ред. от 19.08.2017'"                           "'cost,sale,rubl,base'"   "'rep/r-factur.p'"   "'no,all,no-round,no,no'"       "'-+++--+-'"  "''"               "''"        "'GreenL,zum'"        ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'no'" "'*'"                    "'Счет-фактура обратная в ред. от 19.08.2017'"                  "'cost,sale,rubl,base'"   "'rep/r-factur.p'"   "'no,all,no-round,no,yes'"      "'-+++--+-'"  "''"               "''"        "'GreenL,zum'"        ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'no'" "'*'"                    "'Счет-фактура в ред. от 19.08.2017'"                           "'cost,sale,rubl,base'"   "'rep/r-factur.p'"   "'no,zum,no-round,no,no'"       "'-+++--+-'"  "'zum'"            "''"        "''"                  ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'no'" "'*'"                    "'Счет-фактура в ред. от 19.08.2017'"                           "'cost,sale,rubl,base'"   "'rep/r-factur.p'"   "'no,GreenL,no-round,no,no'"    "'-+++--+-'"  "'GreenL'"         "''"        "''"                  ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'no'" "'*'"                    "'Счет-фактура (Бизнес-Букет) в ред. от 19.08.2017'"            "'cost,sale,rubl,base'"   "'rep/r-factur.p'"   "'no,TopAukc,no-round,no,no'"   "'-+++--+-'"  "'TopAukc'"        "''"        "''"                  ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'no'" "'*'"                    "'Счет-фактура на услуги в ред. от 19.08.2017'"                 "'cost,sale,rubl,base'"   "'rep/r-factur.p'"   "'no,serv,no-round,no,no'"      "'-+++--+-'"  "''"               "''"        "'GreenL,zum'"        ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'no'" "'*'"                    "'Счет-фактура с округлением в ред. от 19.08.2017'"             "'cost,sale,rubl,base'"   "'rep/r-factur.p'"   "'no,all,round,no,no'"          "'-+++--+-'"  "''"               "''"        "'zum'"               ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'no'" "'*'"                    "'Счет-фактура с округлением в ред. от 19.08.2017'"             "'cost,sale,rubl,base'"   "'rep/r-factur.p'"   "'no,zum,round,no,no'"          "'-+++--+-'"  "'zum'"            "''"        "''"                  ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'no'" "'*'"                    "'Счет-фактура старая (без НП) в ред. от 19.08.2017'"           "'cost,sale,rubl,base'"   "'rep/r-factur.p'"   "'no,all,no-round,yes,no'"      "'-+++--+-'"  "''"               "''"        "'GreenL,zum'"        ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'no'" "'*'"                    "'Счет-фактура старая (без НП) в ред. от 19.08.2017'"           "'cost,sale,rubl,base'"   "'rep/r-factur.p'"   "'no,zum,no-round,yes,no'"      "'-+++--+-'"  "'zum'"            "''"        "''"                  ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'no'" "'*'"                    "'Счет-фактура старая (без НП) в ред. от 19.08.2017'"           "'cost,sale,rubl,base'"   "'rep/r-factur.p'"   "'no,GreenL,no-round,yes,no'"   "'-+++--+-'"  "'GreenL'"         "''"        "''"                  ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'no'" "'*'"                     "'Счет-фактура (в редакции от 02.04.2021)'"                           "'cost,sale,rubl,base'"   "'rep/r-factur-2021.p'" "'no,all,no-round,no,no'"   "'-+++----'"  "''"                 "'HTML'"        "'GreenL,zum'"                        ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'no'" "'*'"                    "'Счет-фактура старая с округлением (без НП) в ред. от 19.08.2017'" "'cost,sale,rubl,base'"   "'rep/r-factur.p'"   "'no,all,round,yes,no'"         "'-+++--+-'"  "''"               "''"        "'zum'"               ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'no'" "'*'"                    "'Счет-фактура старая с округлением (без НП) в ред. от 19.08.2017'" "'cost,sale,rubl,base'"   "'rep/r-factur.p'"   "'no,zum,round,yes,no'"         "'-+++--+-'"  "'zum'"            "''"        "''"                  ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'*'"  "'*'"                    "'Счёт-фактура с итогами по НДС в ред. от 19.08.2017'"          "'cost,sale,rubl,base'"   "'rep/factur.p'"     "'no,no,vat-itog,no-round,yes'" "'-++++-+-'"  "''"               "''"        "''"                  ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'no'" "'*'"                    "'Счет-фактура (без НП) в ред. от 19.08.2017'"                  "'cost,sale,rubl,base'"   "'rep/factur.p'"     "'no,no,all,no-round,yes'"      "'-+++--+-'"  "''"               "''"        "'GreenL,zum'"        ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'no'" "'*'"                    "'Счет-фактура (без НП) в ред. от 19.08.2017'"                  "'cost,sale,rubl,base'"   "'rep/factur.p'"     "'no,no,zum,no-round,yes'"      "'-+++--+-'"  "'zum'"            "''"        "''"                  ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'no'" "'*'"                    "'Счет-фактура (без НП) в ред. от 19.08.2017'"                  "'cost,sale,rubl,base'"   "'rep/factur.p'"     "'no,no,GreenL,no-round,yes'"   "'-+++--+-'"  "'GreenL'"         "''"        "''"                  ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'no'" "'*'"                    "'Счёт-фактура до 10-го знака в ред. от 19.08.2017'"            "'cost,sale,rubl,base'"   "'rep/factur.p'"     "'no,no,dec10,no-round,yes'"    "'-++++-+-'"  "''"               "''"        "''"                  ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'no'" "'*'"                    "'Счет-фактура с округлением (без НП) в ред. от 19.08.2017'"    "'cost,sale,rubl,base'"   "'rep/factur.p'"     "'no,no,all,round,yes'"         "'-+++--+-'"  "''"               "''"        "'zum'"               ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'no'" "'*'"                    "'Счет-фактура с округлением (без НП) в ред. от 19.08.2017'"    "'cost,sale,rubl,base'"   "'rep/factur.p'"     "'no,no,zum,round,yes'"         "'-+++--+-'"  "'zum'"            "''"        "''"                  ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured}  "'*'" "'*'"                    "'Рахунок-фактура'"                                             "'cost,sale,rubl,base'"   "'rep/r-sf-ukr.p'"   "'s-f'"                         "'-+-+----'"  "''"               "'A4port'"  "''"                  ? }
{ rep/menu-doc.i {&expense} {&wayb}                             "'*'" "'yes'"                   "'Рахунок'"                                                     "'cost,sale,rubl,base'"   "'rep/r-sf-ukr.p'"   "'rahunok'"                     "'-+-+----'"  "''"               "'A4port'"  "''"                  ? }
{ rep/menu-doc.i {&expense} "{&fact} + {&comma-char} + {&permitted}" "'*'" "'*'"                "'Рахунок'"                                                     "'cost,sale,rubl,base'"   "'rep/r-sf-ukr.p'"   "'rahunok'"                     "'-+-+----'"  "''"               "'A4port'"  "''"                  ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured}  "'*'" "'*'"                    "'Витратна накладная'"                                          "'cost,sale,rubl,base'"   "'rep/r-sf-ukr.p'"   "'vit-nakl'"                    "'-+-+----'"  "''"               "'A4port'"  "''"                  ? }
{ rep/menu-doc.i {&expense} {&fact} "'*'" "'no'"                                                "'Акт несоответствия'"                                          "'cost,sale,rubl,base'"   "'rep/r-nesoot.p'"   "'1'"                           "'-+------'"  "''"               "''"        "''"                  ? }
{ rep/menu-doc.i {&expense} {&fact} "'*'" "'no'"                                                "'Акт несоответствия с округлением'"                            "'cost,sale,rubl,base'"   "'rep/r-nest2.p'"    "'1,'"                          "'--------'"  "''"               "''"        "''"                  ? }
{ rep/menu-doc.i {&expense_return} "'*'" "'*'" "'*'"                                            "'Акт автоматической переоценки'"                               "'crsa,sale,rubl,base'"   "'rep/avt-akt0.p'"   "'all'"                         "'--------'"  "''"               "''"        "'ParCom'"            ? }
{ rep/menu-doc.i {&expense_return} "'*'" "'*'" "'*'"                                            "'Акт автоматической переоценки'"                               "'crsa,sale,rubl,base'"   "'rep/avt-akt0.p'"   "'ParCom'"                      "'--------'"  "'ParCom'"         "''"        "''"                  ? }
{ rep/menu-doc.i {&expense_return} "'*'" "'*'" "'*'"                                            "'Акт автоматической переоценки топлива (весовой учет)'"        "'crsa,sale,rubl,base'"   "'rep/autoact0.p'"   "'all'"                         "'--------'"  "''"               "''"        "''"                  "is-ptrl = 'yes'" }
{ rep/menu-doc.i {&expense_return} {&fact} "'no'" "'*'"                                            "'Справка А-Б'"                                                 "'sale,rubl,base'"        "'rep/formA-B.p'"    "''"                            "'--------'"  "''"                 "'HTML'"    "''"                                  ? }
{ rep/menu-doc.i {&expense} {&fact} "'yes'" "'*'"                                                   "'Справка Б'"                                                 "'sale,rubl,base'"        "'rep/formA-B.p'"    "''"                      "'--------'"  "''"                 "'HTML'"    "''"                                  ? }
{ rep/menu-doc.i {&expense} "'*'" "'*'" "'*'"                                                   "'Акт формирования продажной цены  (текущие продажные цены)'"   "'sale,rubl,base'"        "'rep/avt-akt.p'"    "'yes,no'"                      "'----+---'"  "''"                 "''"        "'Basis'"                             ? }
{ rep/menu-doc.i {&expense} "'*'" "'*'" "'*'"                                                   "'Акт формирования продажной цены  (цены на момент закрытия)'"  "'sale,rubl,base'"        "'rep/avt-akt.p'"    "'no,no'"                       "'----+---'"  "''"                 "''"        "'Basis,'"                            ? }
{ rep/menu-doc.i {&expense} "'*'" "'*'" "'*'"                                                   "'Акт формирования продажной цены  (текущие продажные цены)'"   "'sale,rubl,base'"        "'rep/avt-akt1.p'"   "'yes'"                         "'--------'"  "'Basis'"          "''"        "''"                  ? }
{ rep/menu-doc.i {&expense} "'*'" "'*'" "'*'"                                                   "'Акт формирования продажной цены  (цены на момент закрытия)'"  "'sale,rubl,base'"        "'rep/avt-akt1.p'"   "'no'"                          "'--------'"  "'Basis'"          "''"        "''"                  ? }
{ rep/menu-doc.i {&expense} "'*'" "'*'" "'*'"                                                   "'Протокол согласования отпускных цен'"                         "'sale,rubl,base'"        "'rep/r-protcl.p'"   "'1,no'"                        "'--------'"  "''"               "''"        "''"                  ? }
{ rep/menu-doc.i {&expense} "'*'" "'*'" "'*'"                                                   "'Протокол согласования отпускных цен c округлением'"           "'sale,rubl,base'"        "'rep/r-avprtc.p'"   "'1,no'"                        "'--++----'"  "''"               "''"        "''"                  ? }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'no'" "'*'"                    "'Документ для ювелирных изделий'"                              "'cost,sale,rubl,base'"   "'rep/torg-12z.p'"   "'no'"                          "'-+-+-+--'"  "''"               "''"        "''"                  "is-jwlr = 'yes'" }
{ rep/menu-doc.i {&expense} {&fact_permitted_wayb_manufactured} "'*'" "'*'"                     "'Ценники (этикетки)         '"                                 "'cost,sale,rubl,base'"   "'rep/tick-doc.p'"   "'trn,1,no,no'"                 "'--------'"  "''"               "'self'"    "''"                  ? }
{ rep/menu-doc.i {&expense_write-off} {&fact_permitted_wayb_manufactured} "'yes'" "'*'"         "'Документ ОП-4 накладная производства'"                        "'cost,sale,rubl,base'"   "'rep/op-4.p'"       "''"                            "'---+----'"  "''"               "''"        "''"                  ? }
{ rep/menu-doc.i {&expense_write-off_return} {&fact_permitted_wayb_manufactured} "'*'" "'*'"    "'Спецификация по партиям'"                                     "'cost,sale,rubl,base'"   "'rep/r-specif.p'"   "'yes'"                         "'---+----'"  "'world,SportC'"   "''"        "''"                  ? }
{ rep/menu-doc.i {&expense} "'{&bef-permitted},{&bef-fact},{&bef-wayb}'"        "'*'" "'*'"    "'Счет с разбивкой по НДС'"                                      "'cost,sale,rubl,base'"   "'rep/r-schflr.p'"   "''"                            "'---+----'"  "''"               "'A4port'"  "''"                  ? }
{ rep/menu-doc.i {&expense} {&fact}                             "'no'" "'*'"                   "'Счет'"                                                         "'cost,sale,rubl,base'"   "'rep/r-schet1.p'"   "''"                            "'-+++++--'"  "''"               "''"        "'mag'"               ? }
{ rep/menu-doc.i {&expense} {&wayb}                             "'no'" "'*'"                   "'Счет'"                                                         "'cost,sale,rubl,base'"   "'rep/r-schet1.p'"   "''"                            "'-+++++--'"  "''"               "''"        "'mag'"               ? }
{ rep/menu-doc.i {&expense} {&wayb}                             "'no'" "'yes'"                 "'Счет'"                                                         "'cost,sale,rubl,base'"   "'rep/r-schet.p'"    "'mag'"                         "'--++----'"  "'mag'"            "''"        "''"                  ? }
{ rep/menu-doc.i {&expense} {&inquiry}                          "'no'" "'yes'"                 "'Счет'"                                                         "'cost,sale,rubl,base'"   "'rep/r-schet1.p'"   "''"                            "'-+++++--'"  "''"               "''"        "'mag'"               ? }
{ rep/menu-doc.i {&expense} {&inquiry}                          "'no'" "'yes'"                 "'Запрос'"                                                       "'cost,sale,rubl,base'"   "'rep/r-schet.p'"    "'mag'"                         "'---+----'"  "'mag'"            "''"        "''"                  ? }
{ rep/menu-doc.i {&expense_return} {&inquiry}                   "'no'" "'*'"                   "'Запрос'"                                                       "'cost,sale,rubl,base'"   "'rep/r-schet.p'"    "'all'"                         "'---+----'"  "''"               "''"        "'mag'"               ? }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'no'" "'*'"            "'Накладная расхода (короткая форма)'"                           "'cost,sale,rubl,base'"   "'rep/r-outret.p'"   "'no,no'"                       "'-++++++-'"  "''"               "'A4port'"  "''"                  ? }
{ rep/menu-doc.i {&expense_return} {&fact_permitted_wayb_manufactured} "'no'" "'*'"            "'Накладная расхода (короткая форма) Аптека'"                    "'cost,sale,rubl,base'"   "'rep/r-outrta.p'"   "'no'"                          "'-++++++-'"  "'ODIS'"           "'A4port'"  "''"                  ? }
{ rep/menu-doc.i {&write-off} "'*'" "'no'" "'*'"                                               "'Накладная списания (короткая форма)'"                          "'cost,sale,rubl,base'"   "'rep/r-outret.p'"   "'no,no'"                          "'-++++++-'"  "''"               "'A4port'"  "''"                  ? }

{ rep/menu-doc.i {&write-off} "'*'" "'no'" "'*'"                                               "'Накладная списания (короткая форма.Spar)'"                     "'cost,sale,rubl,base'"   "'rep/r-outret.p'"   "'no,SPAR'"                     "'-++++++-'"  "'SPAR'"                 "'A4port'"  "''"                                  ? }

{ rep/menu-doc.i {&write-off} "'*'" "'no'" "'*'"                                               "'Служебная записка (Роснефть)'"                                 "'cost,sale,rubl,base'"   "'rep/r-wofrosneft.p'"    "'no,no'"                  "'--------'"  "'yukos,ibs,Rosneft-*'"                 "'self'"  "''"                                  ? }

{ rep/menu-doc.i {&expense} "'*'" "'no'" "'*'"                                                 "'Выгрузка товарной накладной'"                                  "'cost,sale,rubl,base'"   "'rep/r-unlway.p'"   "''"                            "'-+-+----'"  "'Can_Ru'"         "'EXCEL'"   "''"                  ? }
{ rep/menu-doc.i {&write-off} "'*'" "'no'" "'*'"                                               "'Акт о списании материалов'"                                    "'cost,sale,rubl,base'"   "'rep/torg-16a.p'"   "''"                            "'--++----'"  "'zum'"            "''"        "''"                  ? }
{ rep/menu-doc.i {&expense} "'{&bef-inquiry},{&bef-ready}'"       "'*'" "'*'"                  "'Заказ флористов - бланк № 1'"                                  "'cost,sale,rubl,base'"   "'rep/r-flor1.p'"    "''"                            "'---+----'"  "''"               "'self'"    "''"                  ? }
{ rep/menu-doc.i {&expense} "'{&bef-permitted},{&bef-fact},{&bef-wayb}'"   "'*'" "'*'"         "'Заказ флористов - бланк № 2'"                                  "'cost,sale,rubl,base'"   "'rep/r-flor2.p'"    "''"                            "'---+----'"  "''"               "'self'"    "''"                  ? }
{ rep/menu-doc.i {&expense} "'{&bef-permitted},{&bef-fact},{&bef-wayb}'"   "'*'" "'*'"         "'Заказ флористов - бланк № 2(TRADE)'"                           "'cost,sale,rubl,base'"   "'rep/r-flor4.p'"    "''"                            "'---+----'"  "''"               "'self'"    "''"                  ? }
{ rep/menu-doc.i {&expense} "'*'" "'*'" "'*'"                                                  "'Эффективность движения товара'"                                "'cost,sale,rubl,base'"   "'rep/eff-move.p'"   "''"                            "'---+++--'"  "''"               "''"        "''"                  ? }
{ rep/menu-doc.i {&expense} "'*'" "'no'" "'*'"                                                 "'Товарный чек'"                                                 "'cost,sale,rubl,base'"   "'rep/r-outret.p'"   "'yes,no'"                      "'-++++++-'"  "''"               "'A4port'"  "''"                  ? }
{ rep/menu-doc.i {&expense} "'*'" "'*'" "'*'"                                                  "'Распоряжение на склад'"                                        "'cost,sale,rubl,base'"   "'rep/r-alkout.p'"   "''"                            "'--------'"  "''"               "'A4port'"  "''"                  ? }
{ rep/menu-doc.i {&expense} "'*'" "'*'" "'*'"                                                  "'АКТ (ТОРГ-2)'"                                                 "'cost,sale,rubl,base'"   "'rep/r-torg2.p'"    "''"                            "'----++--'"  "''"               "'A4port'"  "''"                  "v-menu-doc-ext-doc-type = {&TDEDT_Ras_Vnesh_VP} " }
{ rep/menu-doc.i {&expense} "'*'" "'*'" "'*'"                                                  "'Претензия'"                                                    "'cost,sale,rubl,base'"   "'rep/r-pret.p'"     "''"                            "'--------'"  "''"               "'A4port'"  "''"                  "v-menu-doc-ext-doc-type = {&TDEDT_Ras_Vnesh_VP} " }
{ rep/menu-doc.i {&expense} "'*'" "'*'" "'*'"                                                  "'Маршрутный лист - по выделенным накладным'"                    "'other,no-print-many'"   "'rep/mar-list.p'"   "''"                            "'--------'"  "''"               "'EXCEL'"   "''"                  ? }
{ rep/menu-doc.i {&expense} "'*'" "'*'" "'*'"                                                  "'Лист журнала фасовочных работ'"                                "'cost,sale,rubl,base'"   "'rep/r-fasov.p'"    "''"                            "'---+++--'"  "''"               "'A4lans'"  "''"                  ? }
{ rep/menu-doc.i {&expense} "'*'" "'*'" "'*'"                                                  "'Стеллажная карта'"                                             "'cost,sale,rubl,base'"   "'rep/r-stkard.p'"   "''"                            "'--------'"  "''"               "'self'"    "''"                  ? }
/*-ПРИХОДЫ--------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
/*30 - 59 */
{ rep/menu-doc.i {&income} "'*'" "'*'" "'*'"       "'Документ приход Румыния'"                                       "'cost,sale,rubl,base'" in-docprvalue       "''"                            "'--------'"  "''"        "''"          "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'*'" "'*'"       "'Накладная прихода (короткая форма)'"                            "'cost,sale,rubl,base'" "'rep/r-inp.p'"     "''"                            "'-+++++--'"  "''"        "'A4port'"    "'zum,UKR'"       ? }
{ rep/menu-doc.i {&income} "'*'" "'*'" "'*'"       "'Накладная прихода (короткая форма)'"                            "'cost,sale,rubl,base'" "'rep/r-inp-uk.p'"  "''"                            "'-+++++--'"  "'UKR'"     "'A4port'"    "''"              ? }
{ rep/menu-doc.i {&income} {&fact} "'yes'" "'*'"   "'Накладная прихода (Аптека)'"                                    "'cost,sale,rubl,base'" "'rep/r-outrta.p'"   "'no'"                         "'-++++++-'"  "'ODIS'"    "'A4port'"    "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'no'" "'*'"      "'Документ ТОРГ12'"                                               "'cost,sale,rubl,base'" "'rep/torg-12.p'"   "'no,all,no-round,no,no'"       "'-++++++-'"  "''"        "''"          "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'no'" "'*'"      "'Накладная с артикулом поставщика'"                              "'cost,sale,rubl,base'" "'rep/t12-art.p'"   "''"                            "'-+++++--'"  "''"        "''"          "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'yes'" "'*'"     "'Документ ТОРГ13'"                                               "'cost,sale,rubl,base'" "'rep/torg-13.p'"   "'no,no,no'"                    "'++++++-+'"  "''"        "''"          "'zum'"           ? }
{ rep/menu-doc.i {&income} "'*'" "'yes'" "'*'"     "'Документ внутреннего перемещения'"                              "'cost,sale,rubl,base'" "'rep/torg-13x.p'"  "'no,no,no'"                    "'-+++++--'"  "'iab,NG'"  "'HTML'"    "''"              ? }
{ rep/menu-doc.i {&income}  "'*'" "'yes'" "'*'"    "'Документ внутреннего перемещения с фото товара'"                "'cost,sale,rubl,base'"   "'rep/torg-13x-foto.p'"   "'no,no,no'"                    "'-+++++--'"  "''"                 "'HTML'"  "''"                                  ? }
{ rep/menu-doc.i {&income} "'*'" "'yes'" "'*'"     "'Документ  ТОРГ13'"                                              "'cost,sale,rubl,base'" "'rep/torg-13.p'"   "'no,yes,no'"                   "'++++++--'"  "'zum'"     "''"          "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'yes'" "'*'"     "'Документ ТОРГ13 для ювелирных изделий'"                         "'cost,sale,rubl,base'" "'rep/torg-13.p'"   "'yes,yes,yes'"                 "'++++++--'"  "'zum'"     "''"          "''"              ? }
{ rep/menu-doc.i {&income} {&inquiry} "'*'" "'*'"  "'Заказ ТОРГ26'"                                                  "'cost,sale,rubl,base'" "'rep/order2.p'"    "''"                            "'-+++-+--'"  "''"        "''"          "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'*'" "'*'"       "'Спецификация к документу'"                                      "'cost,sale,rubl,base'" "'rep/r-specsr.p'"  "{&income}"                     "'--------'"  "''"        "''"          "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'*'" "'*'"       "'Спецификация по срокам годности'"                               "'cost,sale,rubl,base'" "'rep/r-specsg.p'"  "''"                            "'---+++--'"  "''"        "'A4port'"    "''"              ? }
{ rep/menu-doc.i {&income} {&fact} "'*'" "'no'"    "'Акт несоответствия'"                                            "'cost,sale,rubl,base'" "'rep/r-nesoot.p '" "'1'"                           "'--------'"  "''"        "''"          "''"              ? }
{ rep/menu-doc.i {&income} {&fact} "'*'" "'*'"     "'Акт несоответствия поставке'"                                   "'cost,sale,rubl,base'" "'rep/r-nesonn.p'"  "''"                            "'-+-+----'"  "'SPAR'"    "''"          "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Акт автоматической переоценки'"                                 "'cost,sale,rubl,base'" "'rep/avt-akt0.p'"  "'all'"                         "'--------'"  "''"        "''"          "'ParCom'"        ? }
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Акт автоматической переоценки'"                                 "'cost,sale,rubl,base'" "'rep/avt-akt0.p'"  "'ParCom'"                      "'--------'"  "'ParCom'"  "''"          "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Акт автоматической переоценки топлива (весовой учет)'"          "'cost,sale,rubl,base'" "'rep/autoact0.p'"  "'all'"                         "'--------'"  "''"        "''"          "''"              "is-ptrl = 'yes'" }
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Акт формирования продажной цены (текущие продажные цены)'"      "'cost,sale,rubl,base'" "'rep/avt-akt.p'"   "'yes,no'"                       "'----+---'"  "''"                  "''"          "'Basis,Pskov'"   ? }
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Акт формирования продажной цены (текущие продажные цены)'"      "'cost,sale,rubl,base'" "'rep/avt-akt.p'"   "'yes,yes'"                      "'----+---'"  "'Pskov'"             "''"          "'Basis'"         ? }
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Акт формирования продажной цены (текущие продажные цены)'"      "'cost,sale,rubl,base'" "'rep/avt-akt1.p'"  "'yes'"                         "'--------'"  "'Basis'"   "''"          "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Акт приемки-передачи товаров народного потребления'"            "'cost,sale,rubl,base'" "'rep/orl-aktn.p'"  "'yes'"                          "'--------'"  "'yukos,ibs,Rosneft-*'"   "''"          "''"              ? }
/* { rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Акт приемки-передачи топливных товаров (весовой учет)'"         "'cost,sale,rubl,base'" "'rep/orl-actn.p'"  "'yes'"                       "'-------'"     "'yukos,ibs,Rosneft-*'"  "''"          "''"              "is-ptrl = 'yes'" } */
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Акт формирования продажной цены (цены на момент закрытия)'"     "'cost,sale,rubl,base'" "'rep/avt-akt.p'"   "'no,no'"                        "'--------'"  "''"                  "''"          "'Basis,Pskov'"   ? }
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Акт формирования продажной цены (цены на момент закрытия)'"     "'cost,sale,rubl,base'" "'rep/avt-akt.p'"   "'no,yes'"                       "'--------'"  "'Pskov'"             "''"          "'Basis'"         ? }
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Акт формирования продажной цены (цены на момент закрытия)'"     "'cost,sale,rubl,base'" "'rep/avt-akt1.p'"  "'no'"                          "'--------'"  "'Basis'"   "''"          "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Ценники (этикетки)         '"                                   "'cost,sale,rubl,base'" "'rep/tick-doc.p'"  "'trn,1,no,no'"                 "'--------'"  "''"        "'self'"      "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Расходная накладная (для поставщика)'"                          "'cost,sale,rubl,base'" "'rep/torg-12.p'"   "'yes,all,no-round,no,no'"      "'---++++-'"  "''"        "''"          "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'no'"  "'*'"     "'Счет-фактура для поставщика (формат 2011г.)'"                   "'cost,sale,rubl,base'" "'rep/r-sf-old.p'"  "'yes,all,no-round,no,no'"      "'-+-+--+-'"  "''"        "''"          "'GreenL,zum'"    ? }
{ rep/menu-doc.i {&income} "'*'" "'no'"  "'*'"     "'Счет-фактура (для поставщика) в ред. от 19.08.2017'"            "'cost,sale,rubl,base'" "'rep/r-factur.p'"  "'yes,all,no-round,no,no'"      "'-+-+--+-'"  "''"        "''"          "'GreenL,zum'"    ? }
{ rep/menu-doc.i {&income} "'*'" "'no'"  "'*'"     "'Счет-фактура (для поставщика) в ред. от 19.08.2017'"            "'cost,sale,rubl,base'" "'rep/r-factur.p'"  "'yes,zum,no-round,no,no'"      "'-+-+--+-'"  "'zum'"     "''"          "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'no'"  "'*'"     "'Счет-фактура (для поставщика) в ред. от 19.08.2017'"            "'cost,sale,rubl,base'" "'rep/r-factur.p'"  "'yes,GreenL,no-round,no,no'"   "'-+-+--+-'"  "'GreenL'"  "''"          "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'no'"  "'*'"     "'Счет-фактура старая (для поставщика) (без НП) в ред. от 19.08.2017'" "'cost,sale,rubl,base'" "'rep/r-factur.p'"  "'yes,all,no-round,yes,no'"     "'-+-+--+-'"  "''"        "''"          "'GreenL,zum'"    ? }
{ rep/menu-doc.i {&income} "'*'" "'no'"  "'*'"     "'Счет-фактура (в редакции от 02.04.2021)'"                       "'cost,sale,rubl,base'"   "'rep/r-factur-2021.p'" "'no,all,no-round,no,no'"   "'-+++----'"  "''"                 "'HTML'"        "'GreenL,zum'"                        ? }
{ rep/menu-doc.i {&income} "'*'" "'no'"  "'*'"     "'Счет-фактура старая (для поставщика) (без НП) в ред. от 19.08.2017'" "'cost,sale,rubl,base'" "'rep/r-factur.p'"  "'yes,zum,no-round,yes,no'"     "'-+-+--+-'"  "'zum'"     "''"          "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'no'"  "'*'"     "'Счет-фактура старая (для поставщика) (без НП) в ред. от 19.08.2017'" "'cost,sale,rubl,base'" "'rep/r-factur.p'"  "'yes,GreenL,no-round,yes,no'"  "'-+-+--+-'"  "'GreenL'"  "''"          "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'no'"  "'*'"     "'Счёт-фактура (для поставщика) с итогами по НДС в ред. от 19.08.2017'" "'cost,sale,rubl,base'" "'rep/factur.p'"    "'no,yes,vat-itog,no-round,yes'" "'-+-++--+'" "''"        "''"          "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'no'"  "'*'"     "'Счет-фактура (для поставщика) (без НП) в ред. от 19.08.2017'"   "'cost,sale,rubl,base'" "'rep/factur.p'"    "'no,yes,all,no-round,yes'"     "'-+-+--+-'"  "''"        "''"          "'GreenL,zum'"    ? }
{ rep/menu-doc.i {&income} "'*'" "'no'"  "'*'"     "'Счет-фактура (для поставщика) (без НП) в ред. от 19.08.2017'"   "'cost,sale,rubl,base'" "'rep/factur.p'"    "'no,yes,zum,no-round,yes'"     "'-+-+--+-'"  "'zum'"     "''"          "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'no'"  "'*'"     "'Счет-фактура (для поставщика) (без НП) в ред. от 19.08.2017'"   "'cost,sale,rubl,base'" "'rep/factur.p'"    "'no,yes,GreenL,no-round,yes'"  "'-+-+--+-'"  "'GreenL'"  "''"          "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'no'"  "'*'"     "'Счёт-фактура (для поставщика) до 10-го знака в ред. от 19.08.2017'" "'cost,sale,rubl,base'" "'rep/factur.p'"    "'no,yes,dec10,no-round,yes'"   "'-+-++-+-'"  "''"        "''"          "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Топливная накладная'"                                           "'cost,sale,rubl,base'" "'rep/r-inrvs.p'"   "''"                            "'--------'"  "''"        "''"          "''"              "is-ptrl = 'yes'" }
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Протокол цен - (Excel)'"                                        "'cost,sale,rubl,base'" "'rep/xl-prtcl.p'"  "''"                            "'-+------'"  "''"        "'EXCEL'"     "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'no'"  "'*'"     "'Накладная для ювелирных изделий'"                               "'cost,sale,rubl,base'" "'rep/torg-12z.p'"  "'no'"                          "'-+-+-+--'"  "''"        "''"          "''"              "is-jwlr = 'yes'" }
{ rep/menu-doc.i {&income} "'*'" "'no'"  "'*'"     "'Расходная накладная (для поставщка юв.изделий)'"                "'cost,sale,rubl,base'" "'rep/torg-12z.p'"  "'yes'"                         "'-----+--'"  "''"        "''"          "''"              "is-jwlr = 'yes'" }
{ rep/menu-doc.i {&income} "'*'" "'no'"  "'*'"     "'Документ ТОРГ1 - АКТ о приемке товаров'"                        "'cost,sale,rubl,base'" "'rep/torg-1.p'"    "'no'"                          "'---+----'"  "''"        "'A4port'"    "''"              ? }
{ rep/menu-doc.i {&income} {&fact} "'no'"  "'*'"     "'Документ ТОРГ1 - АКТ о приемке товаров (HTML)'"                 "'cost,sale,rubl,base'" "'rep/torg-1a.p'"   "'no'"                           "'--------'"  "'SPAR'"              "'self'"      "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Акт о приемке товаров, ТОРГ-8.4'"                               "'cost,sale,rubl,base'" "'rep/r-torg84.p'"  "'no'"                          "'---+----'"  "'yukos,ibs,Rosneft-*'"   "'A4port'"    "''"    ? }
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Акт о расхождениях при приемке товара, ТОРГ-8.3'"               "'cost,sale,rubl,base'" "'rep/r-torg83.p'"  "'no'"                          "'--------'"  "'yukos,ibs,Rosneft-*'"   "'A4port'"    "''"    ? }
/*{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Акт несоответствия по топливной накладной (без печати воды)'"   "'cost,sale,rubl,base'" "'rep/akt-topl.p'"  "'no'"                          "'-------'"  "''"        "'A4port'"    "''"              "is-ptrl = 'yes'" }*/
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Акт несоответствия по топливной накладной'"                     "'cost,sale,rubl,base'" "'rep/akt-topl.p'"  "'yes'"                         "'--------'"  "''"        "'A4port'"    "''"              "is-ptrl = 'yes'" }
/*{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Акт приемки-передачи нефтепродуктов'"                           "'cost,sale,rubl,base'" "'rep/orl-aktp.p'"  "''"                            "'-------'"  "'yukos,ibs,Rosneft-*'"   "'A4port'"    "''"              "is-ptrl = 'yes'" }*/
/*{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Акт приемки-передачи нефтепродуктов (весовой учет)'"            "'cost,sale,rubl,base'" "'rep/orl-actp.p'"  "''"                            "'-------'"  "'yukos,ibs,Rosneft-*'"   "'A4port'"    "''"              "is-ptrl = 'yes'" }*/
/*{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Акт приема нефтепродуктов по количеству'"                       "'cost,sale,rubl,base'" "'rep/sib-actp.p'"  "''"                            "'-------'"  "'Siboil'"  "''"          "''"              "is-ptrl = 'yes'" }*/
{ rep/menu-doc.i {&income} "'*'" "'yes'" "'*'"     "'Документ ОП-4 накладная производства'"                          "'cost,sale,rubl,base'" "'rep/op-4.p'"      "''"                            "'---+----'"  "''"        "''"          "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Накладная прихода (короткая форма)'"                            "'cost,sale,rubl,base'" "'rep/r-inpzum.p'"  "''"                            "'-+++++--'"  "'zum'"     "'A4port'"    "''"              ? }
{ rep/menu-doc.i {&income} {&fact} "'no'" "'*'"    "'Справка'"                                                       "'cost,sale,rubl,base'" "'rep/r-sprav.p'"   "''"                            "'---+----'"  "''"        "'A4port'"    "''"              ? }
{ rep/menu-doc.i {&income} {&fact} "'no'" "'*'"    "'Справка по менеджерам'"                                         "'cost,sale,rubl,base'" "'rep/r-spravm.p'"  "''"                            "'---+----'"  "'Basis'"   "'A4port'"    "''"              ? }
{ rep/menu-doc.i "{&expense} + {&comma-char} + {&income}" "'*'" "'*'" "'*'"  "'Товарная накладная'"                  "'cost,sale,rubl,base'" "'rep/torg-tov.p'"  "''"                            "'--+-++--'"  "''"        "'A4port'"    "''"              ? }
{ rep/menu-doc.i "{&write-off} + {&comma-char} + {&expense} + {&comma-char} + {&return} + {&comma-char} + {&income}" "'*'" "'*'" "'*'"   "'Приложение к документам перемещения товаров'"       "'cost,sale,rubl,base'" "'rep/torg-0.p'"   "''"   "'-+-+++--'" "''"  "''" "''" ? }
{ rep/menu-doc.i "{&write-off} + {&comma-char} + {&expense} + {&comma-char} + {&return} + {&comma-char} + {&income}" "'*'" "'*'" "'*'"   "'Качественное удостоверение на мясные полуфабрикаты'" "'cost,sale,rubl,base'" "'rep/r-cert.p'"  "''"   "'--------'" "''"  "''" "''" ? }
{ rep/menu-doc.i "{&write-off} + {&comma-char} + {&expense} + {&comma-char} + {&return} + {&comma-char} + {&income}" "'*'" "'*'" "'*'"   "'Накладная с баркодами производителя'"                "'cost,sale,rubl,base'" "'rep/r-bcod-p.p'" "''"   "'-+-++++-'" "''"  "''" "''" ? }
{ rep/menu-doc.i "{&write-off} + {&comma-char} + {&expense} + {&comma-char} + {&return} + {&comma-char} + {&income}" "'*'" "'*'" "'*'"   "'Требование в кладовую'"                             "'cost,sale,rubl,base'" "'rep/r-trkl.p'"   "''"   "'--------'" "''"  "'self'" "''" ? }
{ rep/menu-doc.i {&income} "'*'"   "'no'"  "'*'"    "'Акт отклонения цен накладной от цен спецификации к договору с поставщиком'"      "'cost,sale,rubl,base'" "'rep/r-spccnt.p'"  "''"          "'----++--'"  "''"        "''"          "''"              ? }
{ rep/menu-doc.i {&income} {&fact} "'no'" "'*'"    "'Документ ТОРГ-2'"                                               "'cost,sale,rubl,base'" "'rep/torg-2.p'"    "''"                            "'----++--'"  "''"        "'A4port'"    "''"              ? }
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"     "'Лист журнала фасовочных работ'"                                 "'cost,sale,rubl,base'" "'rep/r-fasov.p'"   "''"                            "'---+++--'"  "''"        "'A4lans'"    "''"              ? }
{ rep/menu-doc.i {&income} {&fact} "'yes'" "'*'"   "'Документ ОП-12'"                                                "'cost,sale,rubl,base'" "'rep/op-12.p'"     "''"                            "'---+----'"  "''"        "''"          "''"              "v-menu-doc-ext-doc-type = {&TDEDT_Pri_Prvo}" }
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"   "'Акт приема и недовоза нефтепродуктов'"                          "'cost,sale,rubl,base'" "'rep/apn-ptrl.p'"  "''"                            "'--------'"  "'yukos,ibs,Rosneft-*'"   "'A4port'"     "''"              "is-ptrl = 'yes'" }
{ rep/menu-doc.i {&income} "'*'"   "'*'"   "'*'"   "'Стеллажная карта'"                                              "'cost,sale,rubl,base'" "'rep/r-stkard.p'"  "''"                            "'--------'"  "''"                  "'self'"       "''"               ? }
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"   "'Акт приемки нефтепродуктов по количеству'"                      "'cost,sale,rubl,base'" "'rep/akt-petrl-qnty.p'"  "''"                       "'--------'"  "'Pskov'"             "'A4port'"     "''"              "is-ptrl = 'yes'" }
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"   "'Этикетка проб'"                                                 "'cost,sale,rubl,base'" "'rep/ticket-prob.p'"  "''"                       "'--------'"  "'yukos,ibs,Rosneft-*'"                   "'HTML'"     "''"              "is-ptrl = 'yes'" }
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"   "'Акт отбора проб'"                                                 "'cost,sale,rubl,base'" "'rep/akt-prob.p'"  "''"                       "'--------'"  "'yukos,ibs,Rosneft-*'"                   "'HTML'"     "''"              "is-ptrl = 'yes'" }
{ rep/menu-doc.i {&income} "'*'" "'*'"   "'*'"   "'Акт приема нефтепродуктов'"                                                 "'cost,sale,rubl,base'" "'rep/akt-petrol.p'"  "''"                       "'--------'"  "'yukos,ibs,Rosneft-*'"                   "'HTML'"     "''"              "is-ptrl = 'yes'" }
{ rep/menu-doc.i {&income} {&fact} "'*'"   "'*'"   "'Акт приема СУГ'"                                                 "'cost,sale,rubl,base'" "'rep/akt-sug.p'"  "''"                       "'--------'"  "'yukos,ibs,Rosneft-*'"                   "'HTML'"     "''"              "is-ptrl = 'yes'" }
{ rep/menu-doc.i {&income} {&fact} "'*'"   "'*'"   "'Акт приема СУГ (Расчет тех. потерь)'"                            "'cost,sale,rubl,base'" "'rep/akt-sug-ras.p'"  "''"                       "'--------'"  "'yukos,ibs,Rosneft-*'"                   "'HTML'"     "''"              "is-ptrl = 'yes'" }
{ rep/menu-doc.i {&income} {&fact} "'*'"   "'*'"   "'Акт приема СУГ (корректировка)'"                                                 "'cost,sale,rubl,base'" "'rep/akt-sug-corr.p'"  "''"                       "'--------'"  "'yukos,ibs,Rosneft-*'"                   "'HTML'"     "''"              "is-ptrl = 'yes'" }
/* $Workfile: load-doc.i $   E n d */