/*

$Revision$
$Author$
$Date$
$Workfile$
$Archive$

Форма для ввода часов в почасовых отчетах - определени

Автор: Чернова Светлана Александровна
Дата создания: 03/06/06
Author: Svetlana Chernova
Creation date: 03/06/06

Created: 16/10/00
*/

/*
&IF DEFINED(UIB_is_Running) NE 0 &THEN
&MESSAGE UIB_is_Running "{1}"
&else
&MESSAGE UIB_is_NOT_Running "{1}"
&endif
*/

&IF "{1}" = "NEW" or "{1}" = "NEW GLOBAL" &then
    &IF DEFINED(UIB_is_Running) NE 0 &THEN
    { cmp/obj-list.i "{1}" }
    &else
    /*
    { cmp/obj-list.i }*/
    &endif
&else
{ cmp/obj-list.i }
&endif

DEFINE {1} SHARED VARIABLE loc#log as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE loc#db-num as integer NO-UNDO.
DEFINE {1} SHARED VARIABLE loc#host-code as integer NO-UNDO.
DEFINE {1} SHARED VARIABLE loc#store-code as integer NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-0 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-1 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-2 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-3 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-4 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-5 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-6 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-7 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-8 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-9 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-10 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-11 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-12 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-13 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-14 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-15 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-16 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-17 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-18 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-19 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-20 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-21 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-22 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vH-23 as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE vXL    as LOGICAL NO-UNDO.
DEFINE {1} SHARED VARIABLE WH-start as CHARACTER NO-UNDO.
DEFINE {1} SHARED VARIABLE WH-end  as CHARACTER NO-UNDO.